### ISSUE TITLE
[Hacktoberfest] Improve swagger documentation about 

### ISSUE THREAD

**Issue by strokyl** [linagora/james-project#1019]
Hello dear HocktoberFester, and thanks for considering helping us!

The goal of this issue is to contribute to https://github.com/apache/james-project (yes, an **Apache project!**) but for technical reasons, we could not open tickets on that repository...

You can gather a bit more information on what is James and why it's an awesome project [on our website](http://james.apache.org/).

-------------------------------------------------------

**Here are the more specific task details**

Jira issue: https://issues.apache.org/jira/browse/JAMES-2174.

James provide a REST API to administrate James server. This documentation is documented using [Swagger](https://swagger.io/), with the help of annotation in our code the documentation is generated.
Unfortunately the documentation about quota could be more precise:

Here is the current state of the documentation for GET /quota of the webadmin API.

```
    @GET
    @ApiOperation(value = "Reading count and size at the same time")
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = QuotaDTO.class),
            @ApiResponse(code = 500, message = "Internal server error - Something went bad on the server side.")
    })
    public void defineGetQuota() {
```

in `org.apache.james.webadmin.routes.GlobalQuotaRoutes.`

This current documentation is not precise enough on what the server reply if there is no limitation for "count" and/or "size".
The documentation should specify that if there is no limitation the returned value will be -1.

------------------------------------------------------------------------

![giphy](https://user-images.githubusercontent.com/6928740/30963301-2cd87a62-a477-11e7-8dca-dcd3dc43b681.gif)

**Comment by omarmjhd** [comment]
Just opened a PR!
