### ISSUE TITLE
[Hactoberfest] CLI: add commands to manage MailRepository and mail reprocessing

### ISSUE THREAD

**Issue by strokyl** [linagora/james-project#1050]
Hello dear HocktoberFester, and thanks for considering helping us!

The goal of this issue is to contribute to https://github.com/apache/james-project (yes, an **Apache project!**) but for technical reasons, we could not open tickets on that repository...

You can gather a bit more information on what is James and why it's an awesome project [on our website](http://james.apache.org/).

Specific task details
================

Jira issue: https://issues.apache.org/jira/browse/JAMES-2191

Explanation of James mail reprocessing workflow
--------------------------------------------------------------

When James receive an email, firstly it's get queue into the mail queue that handle all received SMTP mail. Then it go to the mailet pipeline after that either it processing worked (mailbox, resent to remote, etc...) either it failed. When the processing of a mail failed, it can bounce (SMTP send a error message to the source) or it get stocked in a mail repository waiting to be deleted or to get re-queue for retry:

![james_workflow](https://user-images.githubusercontent.com/173588/31713359-3c99765c-b428-11e7-96e2-7e9865a8ee4c.png)

Explanation of the issue
------------------------------

On James 2 because file was the only implementation available for the mail queue and the mail repository, it was possible for the user to reprocess failed email by copying them from the mail repository folder into the mail queue folder. But this was a bad practice because it is linked to the file system implementation of the mail queue and the mail repository.

Now that James 3 have multiple implementations, there is no way (except the experimental `FromRepository` mailet) to reprocess failed mails.

We should therefore add some commands to our CLI interface. Here is an overview of the minimum sets of commands that should be done:

* `ReprocessAllMails <repositoryPath>`:  it will take all the mails from the repository designed by the given path and move them to the message queue

* `ReprocessMail <repositoryPath> <emailKey>`:  it will look for the email having the given key in the repository designed by the repository path and move it to the message queue

* `ListMailRepository` list (by giving paths) all the message repositories

* `ListMailsInRepository <repositoryPath>` list all mails present in a mail repository

* `GetMailInRepository <repositoryPath> <emailKey>`

* `DeleteMailInRepository <repositoryPath> <emailKey>`

* `DeleteMailsInRepository <repositoryPath>`: delete all the mail in the given repository

Some hint for the PR
---------------------------

The code about the CI is located into **server/cli** maven project.

Those command will be added into CmdType.

You will modify ServerCmd#executeCommand to route command to the correct method of your new JmxProbe.

We then need to let James expose these functionnality threw CLI. For that:
 - We need to create a **MailReprocessingManagementMBean** API
 - We will implement it: **MailReprocessingManagement**. The implementation will directly use *MailRepositoryStore* and *MailQueueFactory*.
 - You will introduce a **JMXMailReprocessingProbe** in `/server/container/cli/src/main/java/org/apache/james/cli/probe/impl` and rely on it for **ServerCmd** command handling. The probe will call **MailReprocessingManagementMBean** API.
 - You will need Spring and Guice registration. For spring add the mapping in `server/container/spring/src/main/resources/META-INF/org/apache/james/spring-server.xml` . For guice `server/container/guice/jmx/src/main/java/org/apache/james/modules/server/JMXServerModule.java` needs additional bindings.

**Comment by ilkerceng** [comment]
If this is issue is still available, can i work on it?

**Comment by chibenwa** [comment]
Sure, you can give it a try ;-)

**Comment by ilkerceng** [comment]
I have just wanted to start from simplest command, ListMailRepository. It is defined as "list (by giving paths) all the message repositories". Does it need any parameters? I think the command ListMailRepository should executed without any parameters. Doesn't it?

**Comment by chibenwa** [comment]
> I think the command ListMailRepository should executed without any parameters. Doesn't it?

You are right :-)

**Comment by ilkerceng** [comment]
Hi @chibenwa, i have just finished ListMailRepository, could you review it please? [here](https://github.com/ilkerceng/james-project) is the forked james-repo.

**Comment by ilkerceng** [comment]
Thank you @chibenwa . I will create it just now.

**Comment by ilkerceng** [comment]
Hi @chibenwa . There are two MailQueue objects when i call `this.mailQueueFactory.listCreatedMailQueues()` named "outgoing" and "spool". Should i send the mail/s to spool mailqueue for reprocessing?

**Comment by ilkerceng** [comment]
Hi @chibenwa
Is that issue is still active? I have seen [MailRepositoryStoreService](https://github.com/linagora/james-project/blob/master/server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/service/MailRepositoryStoreService.java) and [ReprocessingService](https://github.com/linagora/james-project/blob/master/server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/service/ReprocessingService.java) are implemented. I have started it about one year ago, but i couldn't maintain it, but now if it is still active i want to fix the remaining parts in my code.

**Comment by chibenwa** [comment]
Hi @ilkerceng 

Well to be fairly honnest, the CLI is based on JMX protocol, which have proven to be deeply insecured. (Think Java deserialization issues, and random port used by the JMX protocol) The long term plan would be ultimately to:

 - Implement all of the features of the CLI with webAdmin REST API
 - Then make webAdmin available for Spring users (at least for the subset of features of the CLI)
 - Eventually port the CLI to rely on the webAdmin REST API
 - Finally drop JMX related code

Note that JMX server can (should?) be disabled using Guice products (managing Spring binding is more painful, and I must admit not having invested time in this.

For the time being, I would not do huge changes in the CLI code base. If your work is in a good status, then yes for sure we should be merging it - (as what I described above might be a long running process).

----------------------------------------------

Regarding your (old) question:
 - `spool` is the queue consumed by mailet processing and ultimately mail delivery
 - `outgoing` act as a buffer (and manages delays) foroutbound mail delivery (think RemoteDelivery)

The reprocessing should target the `spool` mail queue. Additionally it should allow to reset the `state` of the mail (defaults to `root`) to allow to target the processor you want within themailet pipelines.

Cheers

**Comment by ilkerceng** [comment]
Hi @chibenwa 
I am sorry for the latency, due to my own job. 

Yes i have implemented all the features defined in this task, just i need to add the tests for  each queue operation. I don't know if it will be usefull for your long term plan. I may add unit tests and create a merge request. Or i can start to another issue to work on. You know better :)

Thanks.
