### ISSUE TITLE
Populate gitignore

### ISSUE THREAD

**Issue by blackheaven** [linagora/james-project#1470]
The current `.gitignore` is pretty empty, is there anything that prevent us to add some lines for the popular IDEs (Eclipse, IntelliJ)?

It'd reduce the on-boarding phase.

PS: I already use `.git/info/exclude`, but it's tedious.

**Comment by rouazana** [comment]
For this I have this section in my .gitconfig:
```
[core]
	excludesfile = /home/raphael/.gitignore_global
```
And all the files I want to ignore for several projects are in.

For files I won't to ignore for particular project, I put then in exclude.

**Comment by blackheaven** [comment]
Thanks.

**Comment by blackheaven** [comment]
Thanks.
