### ISSUE TITLE
Return Streams instead of Collections

### ISSUE THREAD

**Issue by blackheaven** [linagora/james-project#1471]
As far as i know functional-style (mainly via immutability and `Stream`s) is widely established in the code base. Despite of that it's mostly confined to the body of methods, so that most of the methods follow the same pattern:

* Take a collection
* Convert it to stream
* Do some stuff
* Collect it

The issue I see is that we tend to take this new `Collection` and give it to another function following this pattern, while we could just re-use/continue the `Stream`.

I propose to stop dealing with `Collection`s until we absolutely need it:

* IO (Dto, representations)
* External API

**Comment by chibenwa** [comment]
Sounds like a good idea to me.

IMO we should update the APIs introduced in this Sprint ASAP, and plan (in the FR summer for VN @rouazana ?) to do it for the others API's.

I'll update https://github.com/linagora/james-project/pull/1465 & https://github.com/linagora/james-project/pull/1468

**Comment by rouazana** [comment]
As discussed, the issue is that streams are mutable. So we can eventually use it as return value (the caller being responsible of using it once) while we cannot use it as a parameter.
