### ISSUE TITLE
[Webadmin] API paths are not consistent

### ISSUE THREAD

**Issue by heroandtn3** [linagora/james-project#1473]
I got `mailRepositories` in mailrepository APIs but `domain_mappings` in domain mappings management APIs.

Expected: the API paths must have consistent format, either camelCase or snake_case (the internet perfer the later one)

**Comment by chibenwa** [comment]
Sorry I do not understand that one. Can you descibe more precisely your issue?

**Comment by heroandtn3** [comment]
@chibenwa description updated, sorry for that.

**Comment by chibenwa** [comment]
Sorry, but we have, to the extent of my knowledge as well as from the inspections of my IDE allow me to see, no `domain_mappings`routes.

**Comment by heroandtn3** [comment]
I added it during a barcamp in VN: https://github.com/linagora/james-admin-client/blob/master/src/api/domain_mappings.js. But the API might be removed. 

Where is the API to manage domain mapping?

**Comment by chibenwa** [comment]
That is not merged in James, thus not usable.

We do have a contribution for adding it here (but the syntax might differ: you might have to update your client...) https://github.com/apache/james-project/pull/119

**Comment by chibenwa** [comment]
May we close this issue?

**Comment by heroandtn3** [comment]
Yes, I made a note in the lib.
