### ISSUE TITLE
[Webadmin] Listing mails in a mail repository does not respond correctly data

### ISSUE THREAD

**Issue by heroandtn3** [linagora/james-project#1474]
In https://james.apache.org/server/manage-webadmin.html#Administrating_mail_repositories, section __Listing mails contained in a mail repository__

The expected response specified by the documentation:

```
[
    "mail-key-1",
    "mail-key-2",
    "mail-key-3"
]
```
Actually response:

```
[{
  "mailKey": "381bde50-6e11-11e8-bc7a-af84a10f8322-!1604061"
}, {
  "mailKey": "381bde50-6e11-11e8-bc7a-af84a10f8322"
}]
```

**Comment by chibenwa** [comment]
Good point. We might update the API to match the specification.

**Comment by chibenwa** [comment]
Solved
