### ISSUE TITLE
JAMES-2325 Allow to exclude some matcher/mailet from documentation

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#1833]
Hello dear HocktoberFester, and thanks for considering helping us!

The goal of this issue is to contribute to https://github.com/apache/james-project (yes, an **Apache project!**) but for technical reasons, we could not open tickets on that repository...

You can gather a bit more information on what is James and why it's an awesome project [on our website](http://james.apache.org/).

-------------------------------------------------------

**Here are the more specific task details:**

Link to JIRA: https://issues.apache.org/jira/browse/JAMES-2325

Apache James uses the `mailetdocs-maven-plugin` in order to build the mailet/matcher documentation.

This plugin scans the sources, finds mailet and matcher, then generates the documentation entry from its javadoc.

Nowadays all mailet and matchers are included.

This is a problem because we have some test specifics mailets/matcher that are not usable as part of James but still are reported as part of the documentation. 

(Examples includes james-project/server/container/guice/custom-mailets/src/main/java/org/apache/james/transport/mailets/CustomMailet.java and the like, used to generate a separate library containing custom mailets/matchers in order to test custom mailets/matchers instanciation)

The goal of this ticket is to add a `@ExcludeFromDocumentation` annotation as part of the mailet-api. The plugin would skip such annotated mailets/matcher.

In order to to this:
 - Create a new  `@ExcludeFromDocumentation`  in the mailet API
 - Annotate with it classes in `james-project/server/container/guice/custom-mailets`
 - Modify james-project/mailet/mailetdocs-maven-plugin/src/main/java/org/apache/james/mailet/DefaultDescriptorsExtractor.java in order to skip classes annotated as excluded.
 - Add a test in james-project/mailet/mailetdocs-maven-plugin/src/test/java/org/apache/james/mailet/DefaultDescriptorsExtractorTest.java showing excluded mailets are not listed (add an excluded mailet in that package, then assert in a new test that it is not reported).

As always we stay at your disposal to answer any question on the chat! https://gitter.im/apache/james-project

------------------------------------------------------------------------

![giphy](https://user-images.githubusercontent.com/6928740/30963301-2cd87a62-a477-11e7-8dca-dcd3dc43b681.gif)

**Comment by mschnitzler** [comment]
I created pull request #1845 . Please review.

**Comment by chibenwa** [comment]
It looks really nice to me.

Thank you.

**Comment by chibenwa** [comment]
Many thanks for your involvement!
