### ISSUE TITLE
JAMES-2516 Create a SenderDomainId && RecipeintDomainIs matchers

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#1834]
Hello dear HocktoberFester, and thanks for considering helping us!

The goal of this issue is to contribute to https://github.com/apache/james-project (yes, an **Apache project!**) but for technical reasons, we could not open tickets on that repository...

You can gather a bit more information on what is James and why it's an awesome project [on our website](http://james.apache.org/).

-------------------------------------------------------

**Here are the more specific task details:**

Link to JIRA: https://issues.apache.org/jira/browse/JAMES-2516

Nowadays users needs tricks with RecipientIsRegex & SenderIsRegex for handling users of specific domains in a customized way in mailet processing. We need to provide utilities for avoiding such a hack.

In `mailet/standard` create two matchers (and their unit tests):

 - *SenderDomainIs* will look at the envelope sender's domain. If equal to configured value, then all recipients will be returned. Overwise an empty list will be returned.

 - *RecipientDomainIs* will return recipients mathcing a configured domain.

Please note that a valid domain needs to be configured, according to James core Domain model.

**Comment by athulyaraj** [comment]
I created a pull request for this
https://github.com/apache/james-project/pull/139

**Comment by chibenwa** [comment]
Yes ^^ You will find my comments on the Linagora pull request.

Cheers!

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project/pull/1839 solved this issue
