### ISSUE TITLE
JAMES-2574 Listing Healthchecks

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#1847]
Hello dear HocktoberFester, and thanks for considering helping us!

The goal of this issue is to contribute to https://github.com/apache/james-project (yes, an **Apache project!**) but for technical reasons, we could not open tickets on that repository...

You can gather a bit more information on what is James and why it's an awesome project [on our website](http://james.apache.org/).

-------------------------------------------------------

**Here are the more specific task details:**

Link to JIRA: https://issues.apache.org/jira/browse/JAMES-2574

Currently, JAMES-2563 proposes additional healthchecks.

Thus we will need, using the webAdmin API to list enabled healthchecks.

Here is the corresponding user story:

```
As an admin,
Using the webadmin protocol
I can see the checks enabled on the server
```

Here is the route we proposes to add to the current endpoints:

```
GET /healthcheck/checks
```

will return 

```
[
    {
      "componentName": "Cassandra Backend",
      "escapedComponentName": "Cassandra%40Backend"
    },
    ...
]
```

Here is a few implementation details. In webadmin-core maven project:

 - Create a HeathCheckDTO including above fields
 - Implement the route in HealthCheckRoutes and test it in HealthCheckRoutesTest
 - Document in with swagger annotations and in src/site/markdown/server/manage-webadmin.md

If you do have any questions, reach us on gitter: https://gitter.im/apache/james-project

------------------------------------------------------------------------

![giphy](https://user-images.githubusercontent.com/6928740/30963301-2cd87a62-a477-11e7-8dca-dcd3dc43b681.gif)

**Comment by chibenwa** [comment]
No, this proposed API will not be executing the health checks.

With such a proposal this endpoint would be redundant with the aggregation health check #1849 .

Here the idea is more to list the available checks in order to execute just a single check in #1848 .

If that API sounds strange to you, feel free to propose changes ;-)

**Comment by lpegoraro** [comment]
I am just considering the gain of listing the checks without the information of it's status.

Usually, health checks in my experience, they would only have two endpoints,

1 - Simple health check, for the entire service like this: 
GET {.../health}
- healthy - (everything is ok), 
- degraded (somethings that we can live without are missing), 
- unhealthy (some required checks returned unhealthy)

And one other endpoint, with that list I asked about
GET {.../health/dependencies
```
[ 
    ...
    {
      "componentName": "Cassandra Backend",
      "escapedComponentName": "Cassandra%40Backend",
      "health" : "healthy"
    },
   ...
]
```
How does that sound?

**Comment by chibenwa** [comment]
Well to be honest:

 - Because we need to execute the dependencies to get system status, then we can easily display the status of each dependency in the response.

This is what I proposed as part of the #1849 ticket.

The endpoint being described here will IMO just be helpful for API discovery (and know which healthcheck to execute - see #1848 )

My original concerns is that in the face of a degraded/failing component we might need to wait some timeouts and thus executing the aggregation health check might take a long time.

Also, technicaly, health checks execution are side effects. Thus it seems fair to be able to list heath checks without executing them.

**Comment by lpegoraro** [comment]
I did not see it like that, I agree.

**Comment by kratostaine** [comment]
Hi @chibenwa. I would like to help you with this.

**Comment by chibenwa** [comment]
Hi @kratostaine.

Please feel free!

**Comment by chibenwa** [comment]
Solved by @kratostaine in https://github.com/linagora/james-project/pull/1872
