### ISSUE TITLE
JAMES-2600 Implement an ObjectStorage healthcheck

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#1928]
**Here are the more specific task details:**

Link to JIRA: https://issues.apache.org/jira/browse/JAMES-2600

Add a `long countBlob()` public method to the ObjectStorageBlobsDAO class.

In your ObjectStoragetHealthCheck call this method:

 - If a count is returned then swift is healthy
 - If an exception is encountered then swift is unhealthy.

Write tests on top of a `pausable` swift container in `server/blob/blob-objectstorage`.

Bind this health check in `server/container/guice/blob-objectstorage-guice/src/main/java/org/apache/james/modules/objectstorage/ObjectStorageBlobStoreModule.java`

Don't hesitate to ask for help on the Gitter chat : https://gitter.im/apache/james-project

------------------------------------------------------------------------

![giphy](https://user-images.githubusercontent.com/6928740/30963301-2cd87a62-a477-11e7-8dca-dcd3dc43b681.gif)

**Comment by chibenwa** [comment]
We can also use the newly added `listBuckets` method

**Comment by hungphan227** [comment]
I have created PR https://github.com/apache/james-project/pull/1637
Please review
