### ISSUE TITLE
JAMES-2643 Optimize listing mapping by destination on top of JPA

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#2106]
In `JPARecipientRewriteTable` implement the listSources method defined in JAMES-2596 : map it to an SQL query

Tests should still pass.

**Comment by trantienduchn** [comment]
Currently, the structure of the `JAMES_RECIPIENT_REWRITE`:

| USER_NAME | DOMAIN_NAME | TARGET_ADDRESS |
|-|-|-|
| source | domain.tld | `destination1@anotherdomain.tld; destination2@anotherdomain.tld`

`JPARecipientRewriteTable.listSources(Mapping mapping)` can be optimized by using the query 
```
SELECT * from JAMES_RECIPIENT_REWRITE where TARGET_ADDRESS like '%inputMapping%'
``` 
where the `inputMapping` is generated from `mapping.asString()`.

**Comment by remk** [comment]
Are the TARGET_ADDRESS separated by a semicolon separator ?
If so  do an sql query like this : 

```
SELECT * from JAMES_RECIPIENT_REWRITE where TARGET_ADDRESS like 'inputMapping' 
OR  TARGET_ADDRESS like '%;inputMapping' 
OR  TARGET_ADDRESS like 'inputMapping;%'
OR  TARGET_ADDRESS like '%;inputMapping;%'
```
otherwise you will have some false positive
