### ISSUE TITLE
Can't dnd an email into my prefered folder

### ISSUE THREAD

**Issue by MichaelBailly** [linagora/james-project#254]
Hi, this is a bug report.

I created a heart folder (❤, U+2764, see http://www.fileformat.info/info/unicode/char/2764/browsertest.htm). I then try to dnd an email from my inbox into my heart folder. Looking at the JMAP response sent by james, I got a "notUpdated" object, with the title "invalidProperties" and description "mailboxIds: Can not deserialize instance of java.util.Optional out of START_ARRAY token at [Source: {"mailboxIds":["b7fb3640-2672-11e6-a6b3-0b2672b3443d"]}; line: 1, column: 2](through reference chain: org.apache.james.jmap.model.Builder["mailboxIds"])"

Can you make my heart folder work ? It would be... lovely

**Comment by MichaelBailly** [comment]
Well, it seems that it also happen with my "yolo" folder... with the same error message received from the server. I can't move messages in yolo nor in ❤.

**Comment by Laura-Royet** [comment]
The first part of this problem is to improve the handling of error message which is technical instead of being a business one. See the following issue : https://issues.apache.org/jira/browse/JAMES-1756

**Comment by Laura-Royet** [comment]
The second part is to implement the fact that a message can be moved from a mailbox to another mailbox.
See : https://issues.apache.org/jira/browse/JAMES-1785

**Comment by StephaneColson** [comment]
https://issues.apache.org/jira/browse/JAMES-1756 & https://issues.apache.org/jira/browse/JAMES-1785 are closed, maybe this one should be also closed. WDYT?

**Comment by chibenwa** [comment]
Yes you are right.

Solved
