### ISSUE TITLE
Add Content-Disposition header when downloading attachments

### ISSUE THREAD

**Issue by ddolcimascolo** [linagora/james-project#320]
Hey James team,

In relation to https://ci.open-paas.org/jira/browse/INBOX-392 and more generally as we're completing attachments downloads in OpenPaas, I think we lack `Content-Disposition` header on the download endpoint. This header helps the browser to force a file download, which is what we want when downloading attachments.
The expected value would be `Content-Disposition: attachment; filename="attachment_filename"`

I'm however opened to doing this at the frontal level, but I assume this is an added value to do it in James directly, considering that you know the filenames, etc. already.

David

**Comment by Laura-Royet** [comment]
This issue is fixed in the ticket : https://issues.apache.org/jira/browse/JAMES-1809
