### ISSUE TITLE
EOL dependencies

### ISSUE THREAD

**Issue by tommyhp2** [linagora/james-project#3231]
Hi,

Has anyone looked at EOL for the James' dependencies?  I know [log4j](https://github.com/linagora/james-project/pull/3214) was recently.  What about [springframework](https://spring.io/blog/2015/06/15/spring-framework-3-2-x-eol-on-dec-31-2016)?  There are probably others too.

Thanks,
Tommy

**Comment by chibenwa** [comment]
Hello @tommyhp2,

We have a long term plan for removing spring support, yes, but it might not happen in the short run. The end users are still missing some feature with guice implementation so far: being able to add jars on the classpath (ie for a JPA driver) is one of them. And this migration cannot be done overnight.

Does it answer your question regarding Spring support?

Also, that's quitte a long time we had not been doing a dependency upgrade.

If it is something you are willing contributing on, that would be very welcome.

**Comment by tommyhp2** [comment]
Hi @chibenwa ,

The springframework caught my eye quickly because I was experimenting with Spring's MVC framework when it was 5.0 at that time.  Given how long ago it was and there's 2 major version difference, I had a hunched that it's at EOL.

As for contributing to upgrade it, when I was experimenting it for a little bit, I didn't like it because of how configurations are made and, IMO, sluggish due to reflections.  I never got deeper into the framework beyond the Web MVC which I don't see James server using from what I could tell so far.

**Comment by chibenwa** [comment]
:+1: That makes a really strong point of promoting guice products over the Spring one.
