### ISSUE TITLE
Dots are not supported in folder names

### ISSUE THREAD

**Issue by StephaneColson** [linagora/james-project#324]
When creating a folder name with dots, example ".test" it fails with this jmap response:
`[["mailboxesSet",{"created":{},"updated":[],"destroyed":[],"notCreated":{"1468240580914":{"type":"invalidArguments","description":"The mailbox '.test' contains an illegal character: '.'","properties":null}},"notUpdated":{},"notDestroyed":{}},"#0"]]`

**Comment by chibenwa** [comment]
It is besause James uses the '.' character as a delimiter for mailbox folders. "INBOX.any" means folder "any" in mailbox "INBOX".

To allow some names like this, we should add some escaping mechanisms in mailbox names. It's quitte costly. Should we invest in it ?

**Comment by rouazana** [comment]
I don't think so, as it is stated in IMAP RFC that delimiters could be forbidden in mailbox name:

> 4)    Usually, a character (determined by the server implementation)
>          is reserved to delimit levels of hierarchy.
> 

As the error message is pretty clear, I don't think we have anything to handle on this issue.

**Comment by chibenwa** [comment]
Right. Thanks Raphael for clarification.

**Comment by MichaelBailly** [comment]
This is indeed a problem... Lots of users, working on websites, will use the url name as a folder name (e.g. "linagora.com" ). I see 2 possibilities:

1/ the clean one
Support character escaping, maybe following Cyrus escape strategy (not at the beginning of the name, not 2 times the espace char in a row).

2/ the ugly one
make this a configuration settings, to allow the netnews and not netnews separators. We'll then use '/' for most of our installations.

**Comment by chibenwa** [comment]
#465 on our board https://aduprat.framaboard.org/?controller=BoardViewController&action=show&project_id=6

```
We need to encode decode mailboxes names between the store layer and the JMAP layer to escape dot.

You can have a look to Guava char escaper. I propose the folowing escape code : 

// -> /
\\ -> \
\/ -> .

You will write the following tests : 
 - Unit test your escaping mechanism
 - Integration tests : 
   - GetMailboxes : create a mailbox with all escaped char directly via probe and retrieve it.
   - SetMailboxes creation : Create a mailbox with all escapable character
   - SetMailboxesUpdate : Rename a mailbox with a name made of escapable characters. Rename a normal mailbox name to a mailbox name with escapable characters.
```

**Comment by rouazana** [comment]
Hi,
We tried to handle this at the JMAP level (see #662) but then this fails at the IMAP level.
The user won't be able to see the same naming via IMAP and she will see escape characters.

A known hint could have be to use UTF-7 encoding to allow mailers to encode/decode correctly the value, but James is handling correctly UTF-7 (see #667), so we won't change it's good behaviour on this.

So the only fine way we propose to handle dots in JMAP mailboxes names is to change the default hierarchical separator to an other value. / (slash) seems to be recommended in other implementations.

**Comment by chibenwa** [comment]
If we do so, we should provide migration task + see where it is hard coded...
