### ISSUE TITLE
"org.apache.james.mailbox.exception.MailboxNotFoundException: null" when deleting a folder

### ISSUE THREAD

**Issue by StephaneColson** [linagora/james-project#326]
To reproduce, simply delete a folder, it is deleted except that we get an error in the esn logs. Here are the several jmap request and responses

jmap request 1

> [["setMailboxes",{"destroy":["fe4041d0-4801-11e6-bf3b-2b97d605aec1"]},"#0"]]

Response 1

> [["mailboxesSet",{"created":{},"updated":[],"destroyed":["fe4041d0-4801-11e6-bf3b-2b97d605aec1"],"notCreated":{},"notUpdated":{},"notDestroyed":{}},"#0"]]

jmap request 2

> [["getMailboxes",{},"#0"]]

Response 2

> [["mailboxes",{"accountId":null,"state":null,"list":[{"id":"16e78110-4782-11e6-bd05-2b97d605aec1","name":"INBOX","parentId":null,"role":"inbox","sortOrder":10,"mustBeOnlyMailbox":false,"mayReadItems":false,"mayAddItems":false,"mayRemoveItems":false,"mayCreateChild":false,"mayRename":false,"mayDelete":false,"totalMessages":0,"unreadMessages":0,"totalThreads":0,"unreadThreads":0},{"id":"16ee10c0-4782-11e6-bd05-2b97d605aec1","name":"Outbox","parentId":null,"role":"outbox","sortOrder":40,"mustBeOnlyMailbox":false,"mayReadItems":false,"mayAddItems":false,"mayRemoveItems":false,"mayCreateChild":false,"mayRename":false,"mayDelete":false,"totalMessages":0,"unreadMessages":0,"totalThreads":0,"unreadThreads":0},{"id":"16f081c0-4782-11e6-bd05-2b97d605aec1","name":"Sent","parentId":null,"role":"sent","sortOrder":50,"mustBeOnlyMailbox":false,"mayReadItems":false,"mayAddItems":false,"mayRemoveItems":false,"mayCreateChild":false,"mayRename":false,"mayDelete":false,"totalMessages":0,"unreadMessages":0,"totalThreads":0,"unreadThreads":0}],"notFound":null},"#0"]]

jmap request 3

> [["getMessageList",{"filter":{"inMailboxes":["16e78110-4782-11e6-bd05-2b97d605aec1"]},"sort":["date desc"],"collapseThreads":false,"fetchMessages":false,"position":0,"limit":200},"#0"]]

Response 3

> [["messageList",{"accountId":null,"filter":null,"sort":
> [],"collapseThreads":false,"state":null,"canCalculateUpdates":false,"position":0,"total":0,"threadIds":[],"messageIds":[]},"#0"]]

jmap request 4

> [["getMessages",{"properties":["id","threadId","subject","to","cc","bcc","from","preview","date","isUnread","isFlagged","isDraft","hasAttachment","mailboxIds"],"ids":[]},"#0"]]

Response 4

> [["messages",{"notFound":[],"list":[]},"#0"]]

Error in esn logs

> esn_james       | 07:28:42.304 [INFO ] o.a.j.j.JWTAuthenticationStrategy - deleteMailbox #private:user6@open-paas.org:FolderTest
> esn_james       | 07:28:42.422 [WARN ] o.a.j.j.u.MailboxUtils - Cannot find mailbox for :FolderTest
> esn_james       | org.apache.james.mailbox.exception.MailboxNotFoundException: null
> esn_james       |     at org.apache.james.mailbox.cassandra.mail.CassandraMailboxMapper.findMailboxByPath(CassandraMailboxMapper.java:88)
> esn_james       |     at org.apache.james.mailbox.store.StoreMailboxManager.getMailbox(StoreMailboxManager.java:394)
> esn_james       |     at org.apache.james.jmap.utils.MailboxUtils.getMailboxMetaData(MailboxUtils.java:89)
> esn_james       |     at org.apache.james.jmap.utils.MailboxUtils.mailboxFromMailboxPath(MailboxUtils.java:64)
> esn_james       |     at org.apache.james.jmap.methods.GetMailboxesMethod.lambda$getMailboxesResponse$0(GetMailboxesMethod.java:94)
> esn_james       |     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> esn_james       |     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> esn_james       |     at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
> esn_james       |     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> esn_james       |     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> esn_james       |     at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> esn_james       |     at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> esn_james       |     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> esn_james       |     at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> esn_james       |     at org.apache.james.jmap.methods.GetMailboxesMethod.getMailboxesResponse(GetMailboxesMethod.java:99)
> esn_james       |     at org.apache.james.jmap.methods.GetMailboxesMethod.process(GetMailboxesMethod.java:78)
> esn_james       |     at org.apache.james.jmap.methods.RequestHandler.lambda$extractAndProcess$1(RequestHandler.java:67)
> esn_james       |     at java.util.Optional.map(Optional.java:215)
> esn_james       |     at org.apache.james.jmap.methods.RequestHandler.handle(RequestHandler.java:57)
> esn_james       |     at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
> esn_james       |     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> esn_james       |     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> esn_james       |     at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
> esn_james       |     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> esn_james       |     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> esn_james       |     at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
> esn_james       |     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> esn_james       |     at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
> esn_james       |     at org.apache.james.jmap.JMAPServlet.doPost(JMAPServlet.java:71)
> esn_james       |     at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
> esn_james       |     at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> esn_james       |     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
> esn_james       |     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
> esn_james       |     at org.apache.james.jmap.FirstUserConnectionFilter.doFilter(FirstUserConnectionFilter.java:71)
> esn_james       |     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
> esn_james       |     at org.apache.james.jmap.AuthenticationFilter.doFilter(AuthenticationFilter.java:75)
> esn_james       |     at org.apache.james.jmap.BypassAuthOnRequestMethod.tryAuth(BypassAuthOnRequestMethod.java:115)
> esn_james       |     at org.apache.james.jmap.BypassAuthOnRequestMethod.doFilter(BypassAuthOnRequestMethod.java:97)
> esn_james       |     at org.apache.james.jmap.AllowAllCrossOriginRequests.doFilter(AllowAllCrossOriginRequests.java:46)
> esn_james       |     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
> esn_james       |     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
> esn_james       |     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
> esn_james       |     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> esn_james       |     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
> esn_james       |     at org.eclipse.jetty.server.Server.handle(Server.java:517)
> esn_james       |     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
> esn_james       |     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
> esn_james       |     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
> esn_james       |     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
> esn_james       |     at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
> esn_james       |     at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
> esn_james       |     at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
> esn_james       |     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
> esn_james       |     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
> esn_james       |     at java.lang.Thread.run(Thread.java:745)

**Comment by chibenwa** [comment]
I still observe this issue after JMAP refactoring for avoiding mappers.

Question to INBOX team : does they wait the result of the delete before performing  a read ?

On James side, we do something like : 

```
retrieveUserMailboxes(mailboxSession) // a search on mailboxes. Deleted mailboxes is still present
                .stream()
                .map(MailboxMetaData::getPath)
                .map(mailboxPath -> mailboxFactory.fromMailboxPath(mailboxPath, mailboxSession)) // reads the specific mailbox for getting it's path
 // Here the deleted mailbox do not exist anymore
                .filter(Optional::isPresent)
```

Are both requests issued concurently ? It might lead to unpredictable behaviour...

**Comment by chibenwa** [comment]
After exchanges with @ddolcimascolo, INBOX team is doing a GetMailboxList while deleting.

Hence the folder is removed during GetMailboxList request, giving this log.

They then delete the folder from the UI when receiving answer from the Delete.

We should keep a warning here, but maybe stacktrace is overkill.

**Comment by chibenwa** [comment]
Will be corrected by https://issues.apache.org/jira/browse/JAMES-1874
