### ISSUE TITLE
The content of a .txt attachment is displayed as a preview and body of an email

### ISSUE THREAD

**Issue by StephaneColson** [linagora/james-project#331]
Send an email with a subject, no body and add a .txt file (this file contains for example "This is content of test.txt file")

The email received have the content of the attached file ("This is content of test.txt file") as the body of the email.

Request payload
> [["getMessages",{"properties":["id","threadId","subject","to","cc","bcc","from","preview","date","isUnread","isFlagged","isDraft","hasAttachment","mailboxIds"],"ids":["user6@open-paas.org|INBOX|1"]},"#0"]]

Response

> [["messages",{"notFound":[],"list":[{"id":"user6@open-paas.org|INBOX|1","threadId":"user6@open-paas.org|INBOX|1","mailboxIds":["9d694860-48fc-11e6-9948-2b97d605aec1"],"isUnread":true,"isFlagged":false,"isDraft":false,"hasAttachment":true,"from":{"name":"user2@open-paas.org","email":"user2@open-paas.org"},"to":[{"name":"John6 Doe6","email":"user6@open-paas.org"}],"cc":[],"bcc":[],"subject":"Subject","date":"2016-07-13T13:45:20.928Z","preview":"This is content of test.txt\n"}]},"#0"]]

![selection_637](https://cloud.githubusercontent.com/assets/1481595/16805600/3afa3648-4911-11e6-896a-222ebf85370a.png)

**Comment by rouazana** [comment]
Should be fixed by #414
