### ISSUE TITLE
Shouldn't raise an error but a usual logs when an attachment is canceled before upload ended

### ISSUE THREAD

**Issue by StephaneColson** [linagora/james-project#340]
When an upload of a file is started with OpenPaaS Unified Inbox, not finished, then cancel before it's finished, the following error is raised

> Unable to find source-code formatter for language: title james logs. Available languages are: actionscript, html, java, javascript, none, sql, xhtml, xml
> esn_james       | 14:15:46.952 [ERROR] o.a.j.j.UploadServlet - Error while uploading content
> esn_james       | org.eclipse.jetty.io.EofException: Early EOF
> esn_james       |   at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:791)
> esn_james       |   at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:157)
> esn_james       |   at java.io.InputStream.read(InputStream.java:101)
> esn_james       |   at com.google.common.io.ByteStreams.copy(ByteStreams.java:70)
> esn_james       |   at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:115)
> esn_james       |   at org.apache.james.jmap.UploadHandler.uploadContent(UploadHandler.java:59)
> esn_james       |   at org.apache.james.jmap.UploadHandler.handle(UploadHandler.java:51)
> esn_james       |   at org.apache.james.jmap.UploadServlet.doPost(UploadServlet.java:55)
> esn_james       |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
> esn_james       |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> esn_james       |   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
> esn_james       |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
> esn_james       |   at org.apache.james.jmap.AuthenticationFilter.doFilter(AuthenticationFilter.java:75)
> esn_james       |   at org.apache.james.jmap.BypassAuthOnRequestMethod.tryAuth(BypassAuthOnRequestMethod.java:115)
> esn_james       |   at org.apache.james.jmap.BypassAuthOnRequestMethod.doFilter(BypassAuthOnRequestMethod.java:97)
> esn_james       |   at org.apache.james.jmap.AllowAllCrossOriginRequests.doFilter(AllowAllCrossOriginRequests.java:46)
> esn_james       |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
> esn_james       |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
> esn_james       |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
> esn_james       |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> esn_james       |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)

This should not be an error but a normal log "An upload has been canceled before the end" or something like that.

**Comment by chibenwa** [comment]
I created an issue : https://issues.apache.org/jira/browse/JAMES-1871

**Comment by quynhn** [comment]
It's done and merged. Please check the related jira ticket
