### ISSUE TITLE
Filename http encoding (non-latin) not handled

### ISSUE THREAD

**Issue by StephaneColson** [linagora/james-project#344]
Attachments with cyrillic, arabic or chinese (perhaps non-exhaustive list) are not well retrieved (tested this with OpenPaaS/Unifid Inbox sending these attachments in emails).

Here's the jmap Response I can retrieve when sending the email:

> 
[["messagesSet",{"accountId":null,"oldState":null,"newState":null,"created":{"1469191919092":{"id":"user0@open-paas.org|Outbox|3","blobId":"3","threadId":"user0@open-paas.org|Outbox|3","mailboxIds":["0f3d4130-5005-11e6-8e34-2b97d605aec1"],"inReplyToMessageId":null,"isUnread":false,"isFlagged":false,"isAnswered":false,"isDraft":false,"hasAttachment":true,"headers":{"mime-version":"1.0","date":"Fri, 22 Jul 2016 12:51:59 +0000","sender":"user0@open-paas.org","subject":"test","message-id":"1469191919092","content-type":"multipart/mixed; boundary=\"-=Part.2.761d7be53df6bc21.15612a9972c.f4c37f57c999a9de=-\"","from":"user0@open-paas.org","to":"John1 Doe1 <user1@open-paas.org>"},"from":{"name":"user0@open-paas.org","email":"user0@open-paas.org"},"to":[{"name":"John1 Doe1","email":"user1@open-paas.org"}],"cc":[],"bcc":[],"replyTo":[],"subject":"test","date":"2016-07-22T12:51:59.247Z","size":528192,"preview":"(Empty)","textBody":null,"htmlBody":null,"attachments":[{"blobId":"64503ed4e71ecd9a668f131d6e63fd76fbc143bb","type":"image/png","name":"تتطور أم لا.png","size":181973,"cid":null,"isInline":false,"width":null,"height":null},{"blobId":"9eeb86bb873b77a04de589fdf53dff1e5610e3e5","type":"image/png","name":"эволюционировать.png","size":86289,"cid":null,"isInline":false,"width":null,"height":null},{"blobId":"12b6d65de37b0631060d57d54fb17bec3b352122","type":"image/png","name":"进化还是不.png","size":117062,"cid":null,"isInline":false,"width":null,"height":null}],"attachedMessages":{}}},"updated":[],"destroyed":[],"notCreated":{},"notUpdated":{},"notDestroyed":{}},"#0"]]

The name of files  seem ok in the blobId line

![sent](https://cloud.githubusercontent.com/assets/1481595/17058776/36d954e6-5022-11e6-8204-780684067991.png)

Then as the recipient here's the jpam Response when opening the received email

> [["messages",{"notFound":[],"list":[{"id":"user1@open-paas.org|INBOX|5","threadId":"user1@open-paas.org|INBOX|5","mailboxIds":["3552b490-5005-11e6-8e34-2b97d605aec1"],"isUnread":false,"isFlagged":false,"isDraft":false,"hasAttachment":true,"from":{"name":"user0@open-paas.org","email":"user0@open-paas.org"},"to":[{"name":"John1 Doe1","email":"user1@open-paas.org"}],"cc":[],"bcc":[],"replyTo":[],"subject":"test","date":"2016-07-22T12:51:59.683Z","preview":"(Empty)","textBody":null,"htmlBody":null,"attachments":[{"blobId":"64503ed4e71ecd9a668f131d6e63fd76fbc143bb","type":"image/png","name":"**7H1 #E D'.png","size":181973,"cid":null,"isInline":false,"width":null,"height":null},{"blobId":"9eeb86bb873b77a04de589fdf53dff1e5610e3e5","type":"image/png","name":"M2>;NF8>=8@>20BL.png","size":86289,"cid":null,"isInline":false,"width":null,"height":null},{"blobId":"12b6d65de37b0631060d57d54fb17bec3b352122","type":"image/png","name":"Û\u0016Ø/.png","size":117062,"cid":null,"isInline":false,"width":null,"height":null}]}]},"#0"]]

Filenames are now altered.

![received](https://cloud.githubusercontent.com/assets/1481595/17058771/31cd8490-5022-11e6-80b5-b684b267febc.png)

Some files cannot be downloaded.

**Comment by Laura-Royet** [comment]
This issue is currently being treated in : https://issues.apache.org/jira/browse/JAMES-1814

**Comment by Laura-Royet** [comment]
Tested on Firefox Desktop with an email containing 3 attachments with non ASCII Filename : ديناصور.png, 进化还是不.png and эволюционировать.png
To be tested :
 on other browsers on desktop and also on mobile (Chrome, IE, Safari).

**Comment by Laura-Royet** [comment]
Tested on Firefox Desktop with an email containing 3 attachments with non ASCII Filename : ديناصور.png, 进化还是不.png and эволюционировать.png
To be tested :
  - on other browsers on desktop and also on mobile (Chrome, IE, Safari)
 - with a lot of non ASCII filenames attachments 
 - with all cases with sending and receiving emails containing non ASCII filenames attachments
