### ISSUE TITLE
Cannot have twice the same inline image "Broken pipe" exception while downloading

### ISSUE THREAD

**Issue by StephaneColson** [linagora/james-project#345]
Send an email with 2 inline images that are the same (same file, same name...). Open the email, the first inline image is displayed not the second one, we can only see a throbber

![selection_668](https://cloud.githubusercontent.com/assets/1481595/17061113/445a358a-502d-11e6-9ed2-79a2d865f8fc.png)

In James logs

> 14:20:36.921 [INFO ] o.a.j.m.p.SMTPServerModule - Id='408062262' User='' Connection established from 10.69.0.163
> 14:20:37.115 [INFO ] o.a.j.m.p.SMTPServerModule - Id='408062262' User='' Successfully spooled mail Mail1469197237073-acb9b25a-1df9-4de9-8000-361be1301182 from user0@open-paas.org on sco-lyon.lyon.lan/10.69.0.163 for [user1@open-paas.org]
> 14:20:37.156 [INFO ] o.a.j.m.p.SMTPServerModule - Id='408062262' User='' Connection closed for 10.69.0.163
> 14:20:37.518 [INFO ] o.a.j.m.i.JamesMailetContext - Local delivered mail Mail1469197237073-acb9b25a-1df9-4de9-8000-361be1301182 sucessfully from user0@open-paas.org to user1@open-paas.org in folder INBOX
> 14:20:46.743 [ERROR] o.a.j.j.DownloadServlet - Error while downloading
> java.io.IOException: Broken pipe
>     at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
>     at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
>     at sun.nio.ch.IOUtil.write(IOUtil.java:148)
>     at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
>     at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:177)
>     ... 41 common frames omitted
> Wrapped by: org.eclipse.jetty.io.EofException: null
>     at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:197)
>     at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:419)
>     at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:313)
>     at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:141)
>     at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:746)
>     at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
>     at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
>     at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:511)
>     at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:653)
>     at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:702)
>     at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:177)
>     at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:163)
>     at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:413)
>     at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1793)
>     at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
>     at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
>     at org.apache.james.jmap.DownloadServlet.download(DownloadServlet.java:119)
>     at org.apache.james.jmap.DownloadServlet.doGet(DownloadServlet.java:105)
>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
>     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
>     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
>     at org.apache.james.jmap.AuthenticationFilter.doFilter(AuthenticationFilter.java:75)
>     at org.apache.james.jmap.BypassAuthOnRequestMethod.tryAuth(BypassAuthOnRequestMethod.java:115)
>     at org.apache.james.jmap.BypassAuthOnRequestMethod.doFilter(BypassAuthOnRequestMethod.java:97)
>     at org.apache.james.jmap.AllowAllCrossOriginRequests.doFilter(AllowAllCrossOriginRequests.java:46)
>     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
>     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
>     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
>     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
>     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
>     at org.eclipse.jetty.server.Server.handle(Server.java:517)
>     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
>     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
>     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
>     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
>     at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
>     at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
>     at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
>     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
>     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
>     at java.lang.Thread.run(Thread.java:745)

There is only one blobId in the Jmap response

> [["messages",{"notFound":[],"list":[{"id":"user1@open-paas.org|INBOX|13","threadId":"user1@open-paas.org|INBOX|13","mailboxIds":["3552b490-5005-11e6-8e34-2b97d605aec1"],"isUnread":false,"isFlagged":false,"isDraft":false,"hasAttachment":true,"from":{"name":"user0","email":"user0@open-paas.org"},"to":[{"name":"user1@open-paas.org","email":"user1@open-paas.org"}],"cc":[],"bcc":[],"replyTo":[],"subject":"2 inline identiques","date":"2016-07-22T14:20:37.326Z","preview":"\n    1\n\n    \n\n    \n\n    \n\n    2\n\n    \n\n    \n\n    \n\n    \n\n    \n\n  ","textBody":"1\r\n\r\n\r\n2\r\n\r\n\r\n\r\n","htmlBody":"<html>\r\n  <head>\r\n\r\n    <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\">\r\n  </head>\r\n  <body bgcolor=\"#FFFFFF\" text=\"#000000\">\r\n    <p>1</p>\r\n    <p><img src=\"cid:part1.35E677AB.7B78BBB4@open-paas.org\" alt=\"\"></p>\r\n    <p><br>\r\n    </p>\r\n    <p>2</p>\r\n    <p><br>\r\n    </p>\r\n    <p><img src=\"cid:part1.35E677AB.7B78BBB4@open-paas.org\" alt=\"\"></p>\r\n    <p><br>\r\n    </p>\r\n  </body>\r\n</html>\r\n","attachments":[{"blobId":"01bd11d28fb2aa46ebe4b74884f734c2e282378b","type":"image/jpeg","name":"pkamleemneafipii.jpeg","size":121234,"cid":"part1.35E677AB.7B78BBB4@open-paas.org","isInline":true,"width":null,"height":null}]}]},"#0"]]

**Comment by chibenwa** [comment]
I believe it is normal that there is only one blobId in the James response, as there is only one attachment to the message.

Why transfer the same attachment twice ? Displaying an image twice is IMO an INBOX concern.

For the message logged, 

```
java.io.IOException: Broken pipe
at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
at sun.nio.ch.IOUtil.write(IOUtil.java:148)
at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:177
```

I think socket channel was closed, thus copy could not occur. (INBOX exception ?)

Anyway, we will add integration test for this.

https://issues.apache.org/jira/browse/JAMES-1872

**Comment by ddolcimascolo** [comment]
I can't test right now because of #544, but I tend to agree it's probably a bug on Inbox' side.
Will confirm later.

**Comment by chibenwa** [comment]
We added tests for this and it was green...

I just merged it as part of https://github.com/linagora/james-project/pull/539
