### ISSUE TITLE
RabbitMQ MailQueue do not survive restart

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3485]
GITLAB-1802

## Why

Incident thread: https://chat.linagora.com/openpaas/pl/fg4rz381ufgwtggjfs9qm4c19y

Over 37k messages are stuck in RMQ

![Image_Pasted_at_2020-6-19_15-25.png.jpg](https://images.zenhubusercontent.com/5ef2aee69879df3417738ce4/32d0243c-94b9-4bfe-8956-f78ca243bc63)

> it seems not dequeuing, is there any node connected to this queue ?

> No consumer indeed 

![Image_Pasted_at_2020-6-19_15-31.png.jpg](https://images.zenhubusercontent.com/5ef2aee69879df3417738ce4/3969b05e-269d-4330-884f-fe2af5680858)

Restarting the node solves the issue

> There is a consumer now 

![Image_Pasted_at_2020-6-19_15-36.png.jpg](https://images.zenhubusercontent.com/5ef2aee69879df3417738ce4/6c249676-8e01-4039-9af0-9db78a65edb1)

![Image_Pasted_at_2020-6-19_16-11.png.jpg](https://images.zenhubusercontent.com/5ef2aee69879df3417738ce4/648636b7-da3f-4cf4-8b6f-010953af5e44)

## How ?

https://chat.linagora.com/openpaas/pl/qesjymi5dfb9uby8nmda6jct7e

> it seems that we need resilient channels @Benoît TELLIER 

## Definition of done

Full RabbitMQ restart should not threaten MailQueue delivery. James is resilient to RabbitMQ errors.

**Comment by blackheaven** [comment]
JIRA:

 * https://issues.apache.org/jira/browse/JAMES-3288 (wrongly diagnosed)
 * https://issues.apache.org/jira/browse/JAMES-3290

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project/pull/3532 

I actually found out that we do not handle nack when we fail to load a mail.

In case many errors are faced, this means that the maximum number of unacknowledged message is reached, resulting in no longer dequeueing taking place.

We need to :

-  Discard messages referencing blobs that no longer exist (as queuing them is doomed anyway)
-   Requeue and retry messages that failed to for instance to resource over-usage.

See https://github.com/linagora/james-project/pull/3532

**Comment by chibenwa** [comment]
Connex issue: https://github.com/linagora/james-project/pull/3534

JAMES-3291 Badly formatted mailqueue causes RabbitMQMailQueue to crash

No clear solution yet...
