### ISSUE TITLE
Distributed James: Disable ElasticSearch

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3490]
GITLAB-1781

For use cases not using IMAP/JMAP, it makes no sense to pay for mail indexation on top of an ElasticSearch cluster.

We should offer a way to start DistributedJames on top of scanning search for such usages.

We will leverage module choosing to do so.

**DOD** Integration test starting distributed james without ElasticSearch. Smoke test about mail delivery + pop3 will be provided for it.

PR https://github.com/linagora/james-project/pull/3425

We just need to polish this.

**Comment by mbaechler** [comment]
Could we also try what happens on usages that are not supported by scanning-search?
Also, can ensure a very long search times out to prevent hours of cluster pain in case of a mistake? (AFAIK there's no way to stop a given user request for an admin).

**Comment by rouazana** [comment]
> Could we also try what happens on usages that are not supported by scanning-search?
> Also, can ensure a very long search times out to prevent hours of cluster pain in case of a mistake? (AFAIK there's no way to stop a given user request for an admin).

We should just document the risks of using this option.
