### ISSUE TITLE
MessageFastView health check should be using "moving averages"

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3493]
GITLAB-1728

It currently relies on total count since last reboot.

It thus don't correctly latest server state especially for a long running server instance.

A 5 minute moving average enabled by dropwizard should be more helpful here.

JIRA: https://issues.apache.org/jira/browse/JAMES-3269

**Comment by Arsnael** [comment]
https://github.com/linagora/james-project/pull/3439 fixed this
