### ISSUE TITLE
Make S3 blobstore implementation perform well

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3497]
Spent 0d

GITLAB-1794

We have a S3 implementation using amazon sdk 2.x pending for some times here : https://github.com/linagora/james-project/pull/3430

We have a list of steps to pass before we consider merging it:

* [ ] making it pass CI tests
* [ ] run stress tests against OVH latest Swift-over-S3 implementation
* [ ] compare results to existing S3 implementation against the same infrastructure
* [ ] compare results to existing Swift implementation against the same infrastructure
* [ ] document changelog and migration steps

**Comment by blackheaven** [comment]
After thinking a bit: deployment tests are failing due to the CI which is built to run Swift, which support is dropped in this PR.

I'll change the CI.

**Comment by mbaechler** [comment]
> After thinking a bit: deployment tests are failing due to the CI which is built to run Swift, which support is dropped in this PR.

This one is funny. Good finding.

**Comment by blackheaven** [comment]
PR: https://github.com/linagora/james-jenkins/pull/192

**Comment by blackheaven** [comment]
>  compare results to existing Swift implementation against the same infrastructure

since we drop Swift, I do not get it.

**Comment by mbaechler** [comment]
> > compare results to existing Swift implementation against the same infrastructure
> 
> since we drop Swift, I do not get it.

I guess it's with previous implementation
