### ISSUE TITLE
NoClassDefFoundError: org/apache/jempbox/xmp/XMPMetadata with some files

### ISSUE THREAD

**Issue by StephaneColson** [linagora/james-project#350]
The following error is raised when sending the attached file as an attachment or an inline image (see 5Mb.jpg)

> 12:14:15.278 [ERROR] o.a.j.m.i.JamesMailetContext - Error while processing listener org.apache.james.mailbox.elasticsearch.events.ElasticSearchListeningMessageSearchIndex for org.apache.james.mailbox.store.event.EventFactory.AddedImpl args=[]
> java.lang.NoClassDefFoundError: org/apache/jempbox/xmp/XMPMetadata
>   at org.apache.tika.parser.image.xmp.JempboxExtractor.parse(JempboxExtractor.java:57)
>   at org.apache.tika.parser.jpeg.JpegParser.parse(JpegParser.java:59)
>   at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
>   at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
>   at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120)
>   at org.apache.james.mailbox.tika.extractor.TikaTextExtractor.extractContent(TikaTextExtractor.java:70)
>   at org.apache.james.mailbox.elasticsearch.json.MimePart$Builder.parseContent(MimePart.java:145)
>   at org.apache.james.mailbox.elasticsearch.json.MimePart$Builder.build(MimePart.java:119)
>   at org.apache.james.mailbox.elasticsearch.json.MimePartParser.closeMimePart(MimePartParser.java:99)
>   at org.apache.james.mailbox.elasticsearch.json.MimePartParser.processMimePart(MimePartParser.java:77)
>   at org.apache.james.mailbox.elasticsearch.json.MimePartParser.parse(MimePartParser.java:58)
>   at org.apache.james.mailbox.elasticsearch.json.IndexableMessage.from(IndexableMessage.java:48)
>   at org.apache.james.mailbox.elasticsearch.json.MessageToElasticSearchJson.convertToJson(MessageToElasticSearchJson.java:57)
>   at org.apache.james.mailbox.elasticsearch.events.ElasticSearchListeningMessageSearchIndex.add(ElasticSearchListeningMessageSearchIndex.java:77)
>   at org.apache.james.mailbox.store.search.ListeningMessageSearchIndex.event(ListeningMessageSearchIndex.java:83)
>   at org.apache.james.mailbox.store.event.SynchronousEventDelivery.deliver(SynchronousEventDelivery.java:29)
>   at org.apache.james.mailbox.store.event.DefaultDelegatingMailboxListener.deliverEventToGlobalListeners(DefaultDelegatingMailboxListener.java:106)
>   at org.apache.james.mailbox.store.event.DefaultDelegatingMailboxListener.event(DefaultDelegatingMailboxListener.java:95)
>   at org.apache.james.mailbox.store.event.MailboxEventDispatcher.added(MailboxEventDispatcher.java:55)
>   at org.apache.james.mailbox.store.StoreMessageManager$1.execute(StoreMessageManager.java:399)
>   at org.apache.james.mailbox.store.StoreMessageManager$1.execute(StoreMessageManager.java:391)
>   at org.apache.james.mailbox.store.AbstractMailboxPathLocker.executeWithLock(AbstractMailboxPathLocker.java:38)
>   at org.apache.james.mailbox.store.StoreMessageManager.appendMessage(StoreMessageManager.java:391)
>   at org.apache.james.transport.mailets.SieveMailet.post(SieveMailet.java:194)
>   at org.apache.jsieve.mailet.SieveMailboxMailet.storeMessageInbox(SieveMailboxMailet.java:381)
>   at org.apache.jsieve.mailet.SieveMailboxMailet.sieveMessage(SieveMailboxMailet.java:351)
>   at org.apache.jsieve.mailet.SieveMailboxMailet.storeMail(SieveMailboxMailet.java:334)
>   at org.apache.james.transport.mailets.SieveMailet.storeMail(SieveMailet.java:98)
>   at org.apache.jsieve.mailet.SieveMailboxMailet.service(SieveMailboxMailet.java:268)
>   at org.apache.james.transport.mailets.LocalDelivery.service(LocalDelivery.java:92)
>   at org.apache.james.mailetcontainer.impl.camel.CamelProcessor.process(CamelProcessor.java:64)
>   at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
>   at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:416)
>   at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
>   at org.apache.camel.processor.ChoiceProcessor.process(ChoiceProcessor.java:111)
>   at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:416)
>   at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
>   at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
>   at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
>   at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:416)
>   at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
>   at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:570)
>   at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:503)
>   at org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:215)
>   at org.apache.camel.processor.Splitter.process(Splitter.java:98)
>   at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:416)
>   at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
>   at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
>   at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
>   at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
>   at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:51)
>   at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
>   at org.apache.camel.processor.UnitOfWorkProducer.process(UnitOfWorkProducer.java:73)
>   at org.apache.camel.impl.ProducerCache$2.doInProducer(ProducerCache.java:375)
>   at org.apache.camel.impl.ProducerCache$2.doInProducer(ProducerCache.java:343)
>   at org.apache.camel.impl.ProducerCache.doInProducer(ProducerCache.java:233)
>   at org.apache.camel.impl.ProducerCache.sendExchange(ProducerCache.java:343)
>   at org.apache.camel.impl.ProducerCache.send(ProducerCache.java:184)
>   at org.apache.camel.impl.DefaultProducerTemplate.send(DefaultProducerTemplate.java:124)
>   at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:137)
>   at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:144)
>   at org.apache.james.mailetcontainer.impl.camel.CamelMailetProcessor.service(CamelMailetProcessor.java:66)
>   at org.apache.james.mailetcontainer.lib.AbstractStateCompositeProcessor.service(AbstractStateCompositeProcessor.java:98)
>   at org.apache.james.mailetcontainer.lib.AbstractStateMailetProcessor.toProcessor(AbstractStateMailetProcessor.java:165)
>   at org.apache.james.mailetcontainer.impl.camel.CamelMailetProcessor.access$1000(CamelMailetProcessor.java:51)
>   at org.apache.james.mailetcontainer.impl.camel.CamelMailetProcessor$MailetContainerRouteBuilder$StateChangedProcessor.process(CamelMailetProcessor.java:216)
>   at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
>   at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:416)
>   at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
>   at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
>   at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
>   at org.apache.camel.processor.ChoiceProcessor.process(ChoiceProcessor.java:111)
>   at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:416)
>   at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
>   at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
>   at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
>   at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:416)
>   at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
>   at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:570)
>   at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:503)
>   at org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:215)
>   at org.apache.camel.processor.Splitter.process(Splitter.java:98)
>   at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:416)
>   at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
>   at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
>   at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
>   at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
>   at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:51)
>   at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
>   at org.apache.camel.processor.UnitOfWorkProducer.process(UnitOfWorkProducer.java:73)
>   at org.apache.camel.impl.ProducerCache$2.doInProducer(ProducerCache.java:375)
>   at org.apache.camel.impl.ProducerCache$2.doInProducer(ProducerCache.java:343)
>   at org.apache.camel.impl.ProducerCache.doInProducer(ProducerCache.java:233)
>   at org.apache.camel.impl.ProducerCache.sendExchange(ProducerCache.java:343)
>   at org.apache.camel.impl.ProducerCache.send(ProducerCache.java:184)
>   at org.apache.camel.impl.DefaultProducerTemplate.send(DefaultProducerTemplate.java:124)
>   at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:137)
>   at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:144)
>   at org.apache.james.mailetcontainer.impl.camel.CamelMailetProcessor.service(CamelMailetProcessor.java:66)
>   at org.apache.james.mailetcontainer.lib.AbstractStateCompositeProcessor.service(AbstractStateCompositeProcessor.java:98)
>   at org.apache.james.mailetcontainer.impl.JamesMailSpooler$1.run(JamesMailSpooler.java:167)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at java.lang.Thread.run(Thread.java:745)
> 12:14:15.410 [INFO ] o.a.j.m.i.JamesMailetContext - Local delivered mail user1@open-paas.org|Outbox|1 sucessfully from user1@open-paas.org to user1@open-paas.org in folder INBOX
> 12:14:16.020 [ERROR] o.a.j.j.s.PostDequeueDecorator - Error while processing listener org.apache.james.mailbox.elasticsearch.events.ElasticSearchListeningMessageSearchIndex for org.apache.james.mailbox.store.event.EventFactory.AddedImpl
> java.lang.NoClassDefFoundError: org/apache/jempbox/xmp/XMPMetadata
>   at org.apache.tika.parser.image.xmp.JempboxExtractor.parse(JempboxExtractor.java:57)
>   at org.apache.tika.parser.jpeg.JpegParser.parse(JpegParser.java:59)
>   at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
>   at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
>   at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120)
>   at org.apache.james.mailbox.tika.extractor.TikaTextExtractor.extractContent(TikaTextExtractor.java:70)
>   at org.apache.james.mailbox.elasticsearch.json.MimePart$Builder.parseContent(MimePart.java:145)
>   at org.apache.james.mailbox.elasticsearch.json.MimePart$Builder.build(MimePart.java:119)
>   at org.apache.james.mailbox.elasticsearch.json.MimePartParser.closeMimePart(MimePartParser.java:99)
>   at org.apache.james.mailbox.elasticsearch.json.MimePartParser.processMimePart(MimePartParser.java:77)
>   at org.apache.james.mailbox.elasticsearch.json.MimePartParser.parse(MimePartParser.java:58)
>   at org.apache.james.mailbox.elasticsearch.json.IndexableMessage.from(IndexableMessage.java:48)
>   at org.apache.james.mailbox.elasticsearch.json.MessageToElasticSearchJson.convertToJson(MessageToElasticSearchJson.java:57)
>   at org.apache.james.mailbox.elasticsearch.events.ElasticSearchListeningMessageSearchIndex.add(ElasticSearchListeningMessageSearchIndex.java:77)
>   at org.apache.james.mailbox.store.search.ListeningMessageSearchIndex.event(ListeningMessageSearchIndex.java:83)
>   at org.apache.james.mailbox.store.event.SynchronousEventDelivery.deliver(SynchronousEventDelivery.java:29)
>   at org.apache.james.mailbox.store.event.DefaultDelegatingMailboxListener.deliverEventToGlobalListeners(DefaultDelegatingMailboxListener.java:106)
>   at org.apache.james.mailbox.store.event.DefaultDelegatingMailboxListener.event(DefaultDelegatingMailboxListener.java:95)
>   at org.apache.james.mailbox.store.event.MailboxEventDispatcher.added(MailboxEventDispatcher.java:55)
>   at org.apache.james.mailbox.store.StoreMessageManager$4.execute(StoreMessageManager.java:628)
>   at org.apache.james.mailbox.store.StoreMessageManager$4.execute(StoreMessageManager.java:623)
>   at org.apache.james.mailbox.store.AbstractMailboxPathLocker.executeWithLock(AbstractMailboxPathLocker.java:38)
>   at org.apache.james.mailbox.store.StoreMessageManager.moveTo(StoreMessageManager.java:623)
>   at org.apache.james.mailbox.store.StoreMailboxManager$5.execute(StoreMailboxManager.java:547)
>   at org.apache.james.mailbox.store.MessageBatcher.batchMessages(MessageBatcher.java:52)
>   at org.apache.james.mailbox.store.StoreMailboxManager.moveMessages(StoreMailboxManager.java:545)
>   at org.apache.james.jmap.send.PostDequeueDecorator.moveFromOutboxToSent(PostDequeueDecorator.java:129)
>   at org.apache.james.jmap.send.PostDequeueDecorator.done(PostDequeueDecorator.java:80)
>   at org.apache.james.mailetcontainer.impl.JamesMailSpooler$1.run(JamesMailSpooler.java:168)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at java.lang.Thread.run(Thread.java:745)

![5mb](https://cloud.githubusercontent.com/assets/1481595/17101000/3b888b90-5272-11e6-9217-c1134cc632f1.jpg)

**Comment by chibenwa** [comment]
It's a tika related error.

It's a duplicate from https://github.com/linagora/james-project/issues/333
