### ISSUE TITLE
[Specification] Write down James JMAP extensions

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3502]
Spend 0d

GITLAB-1648

We need to write RFC-like specification for the extensions being specific to James.

**DOD**: an ASCII DOC file per extension, commited as part of `server/protocols/jmap-rfc-8620` folder.

---------------------------------------------------

Here are the extensions being specific to James:

 - [x] `urn:apache:james:params:jmap:mail:quota` : 
   - `quotas` field on the mailbox object.

 - [x] `urn:apache:james:params:jmap:mail:shares` : 
   - `rights` field on the mailbox object.
   - `namespace` field on the mailbox object.
   - Including objects accross accounts for `/get`, `/set`, `/query` commands.

 - [x] `urn:apache:james:params:jmap:mail:filters` :
   - `Filter` object, `Filter/get` + `Filter/set` methods

**Comment by Arsnael** [comment]
@chibenwa : writing on urn:apache:james:params:jmap:mail:shares
@Arsnael : writing on urn:apache:james:params:jmap:mail:quota

**Comment by Arsnael** [comment]
JIRA: https://issues.apache.org/jira/browse/JAMES-3353

**Comment by chibenwa** [comment]
Done JMAP filters for the new spec are documented as part of TMail
