### ISSUE TITLE
[Documentation] Website doc update and annotated RFCs

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3503]
Spend 0d

GITLAB-1649

You will need to update the apache documentation on how to configure and use the new `jmap` implementation: https://james.apache.org/server/config-jmap.html

You might need to create a new page, as we should keep the old doc for the versions of James implementing `jmap-draft`. You should as well redirect to proper JMAP RFCs (https://tools.ietf.org/html/rfc8620 and https://tools.ietf.org/html/rfc8621) and add annotated RFCs as part of `server/protocols/jmap-rfc-8621` folder.

JIRA: https://issues.apache.org/jira/browse/JAMES-3099

**Comment by Arsnael** [comment]
Technically the configuration is still the same right? What is different is the header that you need to specify to use draft or the new jmap (that should be documented of course)

**Comment by rouazana** [comment]
The extensions that we are adding and that still are not a draft should also be documented (or be a draft ^^)

**Comment by Arsnael** [comment]
@rouazana : Are you talking of unofficial James extensions that we use? Which should be covered by this ticket https://app.zenhub.com/workspaces/team-james-5873652b2a0b13cc0b8bbe63/issues/linagora/james-project/3502 

Or something else?

**Comment by rouazana** [comment]
> @rouazana : Are you talking of unofficial James extensions that we use? Which should be covered by this ticket https://app.zenhub.com/workspaces/team-james-5873652b2a0b13cc0b8bbe63/issues/linagora/james-project/3502
> 
> Or something else?

Oh yes sorry, I mixed the tickets.
