### ISSUE TITLE
Configure session hardcoded prefixes

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3508]
Spend: 0d

GITLAB-1731

## WHY 

In `SessionSupplier.scala`: 

```
        apiUrl = new URL(s"$HARD_CODED_URL_PREFIX/jmap"),
        downloadUrl = new URL(s"$HARD_CODED_URL_PREFIX/download"),
        uploadUrl = new URL(s"$HARD_CODED_URL_PREFIX/upload"),
        eventSourceUrl = new URL(s"$HARD_CODED_URL_PREFIX/eventSource")))
```

We hard coded with a costant the URL prefix for JMAP service endpoint advertised via the session object.

This of course should be adapted to the running server domain/URL

## How

We should be able to parse and configure this prefix reading `jmap.properties`

**DOD** We should be able to get HARD_CODED_URL_PREFIX from JMAP server configuration. 

Write (or adapt) an integration test where the session route relies on the configured parameters.

**Comment by nvduc91** [comment]
https://issues.apache.org/jira/browse/JAMES-3316
