### ISSUE TITLE
RabbitMQ EventBus deserialization error handling

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3541]
## Why ?

https://github.com/linagora/james-project/issues/3485 proved a non deserializable message caused the entire MailQueue processing to crash.

https://github.com/linagora/james-project/pull/3532 solved this by doing an explicit nack on such messages, relying on RabbitMQ dead-letter exchanges to not loose data. The messqge is thus effectively ignored.

Following this, we need to further investigate RabbitMQ related code and evaluate if there is similar issues.

A quick study proved the EventBus is subject to the same class of bugs.

## Acceptance criteria

 - If a message cannot be deserialized, following legitimate events can still be processed.
 - Discarded messages are stored in a dead-letter queue and not lost
 
Note that both group registration and key registration needs to be tested: Regarding key registration, dropping events is OK.

## Definition of done

 - Write tests to reproduce the issue and the expected behaviour
 - Implement the fix leveraging dead-letter and nack

**Comment by Arsnael** [comment]
JIRA: https://issues.apache.org/jira/browse/JAMES-3305

**Comment by Arsnael** [comment]
PR: https://github.com/linagora/james-project/pull/3567
