### ISSUE TITLE
RabbitMQ deserialization error handling for the Distributed Task Manager

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3542]
## Why ?

https://github.com/linagora/james-project/issues/3485 proved a non deserializable message caused the entire MailQueue processing to crash.

https://github.com/linagora/james-project/pull/3532 solved this by doing an explicit nack on such messages, relying on RabbitMQ dead-letter exchanges to not loose data. The messqge is thus effectively ignored.

Following this, we need to further investigate RabbitMQ related code and evaluate if there is similar issues.

We need to evaluate the impact on the RabbitMQ code for the distributed task manager.

## Acceptance criteria

 - If a message cannot be deserialized, following legitimate events can still be processed.
 - Discarded messages are stored in a dead-letter queue and not lost
 - Both job submission and cancellation needs to be tested

## Definition of done

 - Write tests to reproduce the issue and the expected behaviour
 - Implement the fix leveraging dead-letter and nack

**Comment by nvduc91** [comment]
https://issues.apache.org/jira/browse/JAMES-3308
