### ISSUE TITLE
Extract DumbBlobStore for Object storage

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3590]
## DOD 

ObjectStorage blobStore should only call a DumbBlobStore

Running performance tests you should get equivalent performances.

**Comment by blackheaven** [comment]
Why running performance tests for a refactoring?

**Comment by rouazana** [comment]
> Why running performance tests for a refactoring?

I"m not sure we can really consider this as a refactoring, as the DumbBlobStore is pretty different from the original implementation.

**Comment by blackheaven** [comment]
In my understanding, we split the id generation from the storing.

**Comment by chibenwa** [comment]
Not only, we enforce the use of temporary files in order to generate ids instead of the previous write-then-copy mechanism.
