### ISSUE TITLE
JAMES-3314 Implement a PassThroughBlobStore

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3592]
## Why

 - Deduplication adds complexity eg by requiring garbage collection for deduplication
 - Garbage collection is still a work in progress

## Goal 

Provide an alternative BlobStore without deduplication, that can delete mails directly.

## DOD

 - Implement a PassThrough blobStore
     - Two identical blobs needs to be stored two times
 - Using memory dumbBlobStore pass the BlobStore contract

https://issues.apache.org/jira/browse/JAMES-3314

**Comment by blackheaven** [comment]
GPG payloads will benefit from it if there are many recipients

**Comment by chibenwa** [comment]
No. Each recipient get a separated message being written with a differnet GPG key by design.

**Comment by blackheaven** [comment]
Nope, by design, when the message is sent to multiple recipients, the content is symmetrically ciphered and the symmetric key is public-key ciphered with each recipients' public key in GPG headers. so the message is the same.

**Comment by chibenwa** [comment]
My bad, you are right. Sorry for being such a GPG noob. Shame on me.
