### ISSUE TITLE
PassThroughBlobStore: effective blob Deletion (mailbox/cassandra)

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3593]
Right now `BlobStore::delete` is never called given that Deduplicating blobStore do not handle dereference/gc yet.

We need to rework the BlobStore API in order to allow the distinction between a "force delete" and a "dereference".

## DOD 

Modify the `DeleteMessageListener` to call "BlobStore::delete".

**Comment by rouazana** [comment]
I don't see why we should have to very different delete methods. For me we should have one interface, with one delete (or dereference ?) method. Depending on the implementation, delete/dereference will effectively delete or just dereference.

As the naming seems hard, I initially thought the we should have a DeduplicatingBlobStore with a dereference method. And a BlobStore with a delete method. The DeduplicatingBlobStore would use the BlobStore to effectively store things.

**Comment by chibenwa** [comment]
> I don't see why we should have to very different delete methods. For me we should have one interface, with one delete (or dereference ?) method. Depending on the implementation, delete/dereference will effectively delete or just dereference.

That's driven by the feature need of the Deleted Message vault. That expects delete to actually delete all the messages having the same content.

Also, we want the delete to be immediate in that case, not to wait for a GC to happen.

Hence, the need for two different deletes.

An alternative could be to rewritte DeletedMessageVault on top of the DumbBlobStore. But we wont benefit from BlobStore services (metrics?).

**Comment by chibenwa** [comment]
We agreed on adding a ticket to have deletedMessageVault deleteMessage relying explicitly on `DumbBlobStore::delete` as a separated ticket.

The Delete operation for the Deduplication blob store can then be a noop.
