### ISSUE TITLE
Configuration option: choosing between PassThroughBlobStore & DeDuplicatingBlobStore

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3595]
As an operator, I want to be able to choose between the PassThrough blob Store and de deduplicating one.

## DOD

I am able to start a Distributed server with a PassThrough blob store.

IMAP APPENDing 2 time the same mail to "bob" on top of such a server should result in the body being stored 2 times (so 4 objects in the blobStore).

## How

Add a `duplication.enable` option within `blobstore.properties` (default to false)

BlobStoreConfiguration will allow a `duplicationEnabled()` method call.

BlobStoreModulesChooser need bind either PassThroughBlobStore or DeDuplicatingBlobStore depending on `duplicationEnabled()` result.

**Comment by blackheaven** [comment]
deduplication should be enabled by default, as currently

**Comment by blackheaven** [comment]
`BlobStoreConfiguration` should also have a `deduplicationDisabled()` and we should enforce the selection

**Comment by chibenwa** [comment]
> deduplication should be enabled by default, as currently

Deduplication can not be disabled. Enabling it by default leaves the room open to disasters, hence the proposal to disable it by default. Safety first.

**Comment by blackheaven** [comment]
so, current deployments will not start anymore.

**Comment by Arsnael** [comment]
> so, current deployments will not start anymore.

Not an issue: upgrade instructions, and no destrructive changes

**Comment by remk** [comment]
https://issues.apache.org/jira/browse/JAMES-3317
