### ISSUE TITLE
Deletion of Distributed MailQueue referenced blobs

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3597]
## DOD of done

Dequeued/deleted emails blobs are eventually deleted/dereferenced

## How

Piggy back blob dereference on Mail Queue delete/dequeue operation.

Write a test ensuring that after a delete the mail queue content is well deleted.

**Comment by blackheaven** [comment]
when should it happen? on the dequeue or the deletion?

**Comment by chibenwa** [comment]
On both, as deleted mails are not dequeued.

**Comment by blackheaven** [comment]
why should we remove them twice?

**Comment by chibenwa** [comment]
That depends at which level you do it. 

I agree to only enforce deletion once, after rabbitMQ message consumption.

**Comment by blackheaven** [comment]
no, Iagree with the ticket, I did not remembered that the MQ messages were not the same as the mailbox messages.
