### ISSUE TITLE
Expose supported private extension in Session object

### ISSUE THREAD

**Issue by rouazana** [linagora/james-project#3609]
The session object shows the extensions supported by the server.

Even if they are not officially normalized, James customized extensions should be exposed into the session object.

See https://github.com/linagora/james-project/issues/3502 for the list of extension, knowing that for the moment only `urn:apache:james:params:jmap:mail:quota` and `urn:apache:james:params:jmap:mail:shares` are implemented.

DoD:
When a user get a session object, `urn:apache:james:params:jmap:mail:quota` and `urn:apache:james:params:jmap:mail:shares` shoud appear next to `urn:ietf:params:jmap:core` and `urn:ietf:params:jmap:mail`

**Comment by nvduc91** [comment]
https://issues.apache.org/jira/browse/JAMES-3320

**Comment by rouazana** [comment]
This will be solved by https://github.com/linagora/james-project/pull/3594
