### ISSUE TITLE
Issue about webadimn,for help！

### ISSUE THREAD

**Issue by huangyqhw** [linagora/james-project#3649]
[root@host-10-33-207-49 bin]# curl -X GET  -v http://10.33.207.49:4190/domains/xinuoxi.com
* About to connect() to 10.33.207.49 port 4190 (#0)
*   Trying 10.33.207.49...
* Connected to 10.33.207.49 (10.33.207.49) port 4190 (#0)
> GET /domains/xinuoxi.com HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.33.207.49:4190
> Accept: */*
> 
"STARTTLS"
"SIEVE" "log fileinto reject vacation i;ascii-numeric envelope body"
"VERSION" "1.0"
"SASL" "PLAIN"
"IMPLEMENTATION" "Apache ManageSieve v1.0"
///
[root@host-10-33-207-49 bin]# james-cli.sh -h 10.33.207.49 -p 9999 ListDomains
host-10-33-207-49
ss.com
xinuoxi.com
10.33.207.49
194.105.56.170
ListDomains command executed sucessfully in 3304 ms.
///
I try to get a exist domain,but  it seems that there is not response like below：
Response codes:
204: The domain exists
404: The domain does not exist
Could you give me some guide pls?

**Comment by huangyqhw** [comment]
and other logs like this:

[root@host-10-33-207-49 ~]# curl -XGET  -v http://10.33.207.49:4190/domains/xinuoxi.com
* About to connect() to 10.33.207.49 port 4190 (#0)
*   Trying 10.33.207.49...
* Connected to 10.33.207.49 (10.33.207.49) port 4190 (#0)
> GET /domains/xinuoxi.com HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.33.207.49:4190
> Accept: */*
> 
"STARTTLS"
"SIEVE" "log fileinto reject vacation i;ascii-numeric envelope body"
"VERSION" "1.0"
"SASL" "PLAIN"
"IMPLEMENTATION" "Apache ManageSieve v1.0"
NO unknown GET command
NO unknown User-Agent: command
NO unknown Host: command
NO unknown Accept: command
NO unknown  command

**Comment by huangyqhw** [comment]
whether we can not use it when using James with Spring？

**Comment by Arsnael** [comment]
Hi @huangyqhw ! As stated here: https://james.apache.org/server/manage.html , the webadmin interface is not available in Spring. You should use the command line client instead?
