### ISSUE TITLE
Mailbox Trash not available - Cannot delete an email

### ISSUE THREAD

**Issue by StephaneColson** [linagora/james-project#367]
When trying to delete an email with OpenPaaS Inbox, then the deletion fails with the error "Move of message "Mails" to trash failed" and "angular.js:11706 Error: Cannot find a mailbox with role trash" in the browser console.

![selection_699](https://cloud.githubusercontent.com/assets/1481595/17894163/b9417712-6948-11e6-833f-553a093b52cb.png)

**Comment by chibenwa** [comment]
I guess we should ensure JMAP related folder exists upon JMAP connection.

https://issues.apache.org/jira/browse/JAMES-1873

**Comment by rouazana** [comment]
done
