### ISSUE TITLE
Grooming JMAP RFC-8621: reading emails

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3690]
Here is a list of topics with some beginning of ticket split...

 - Email/query implementation (raphael / remi)
     - Allow listing emails (no filters)
     - Implement (and test) filters - we can split operator & combinators into two tickets?
     - Implement (and test) sorts
     - share extension managements: searched mailboxes depends on it!

 - Email/get - metadata ( Lan/ Benoit)
     - Support only answering the following properties: id, mailboxIds, keywords, size, receivedAt
     - Partial reads (sealed traits for EmailRepresentation)
     - Support headers
     - Support preview
     - Body parts + bodyProperties handling
     - fetchTextBodyValues, fetchHTMLBodyValues, fetchAllBodyValues handling
     - maxBodyValueBytes handling (body parts truncation)

 - Downloads... (rene/ duc)
    - Downloading a message MIME
    - Downloading an attachment
    - Downloading another mime part (needed?)

**Comment by chibenwa** [comment]
Wrote tickets the entire morning!!!

Here are the results for reading email bodies with THE new spec (tickets are ordered):

 - https://github.com/linagora/james-project/issues/3705 `Email/get 14. bodyStructure property`
 - https://github.com/linagora/james-project/issues/3699 `Email/get 8. preview / hasAttachment support`
 - https://github.com/linagora/james-project/issues/3700 `Email/get 9. textBody + htmlBody property (mime structure)`
 - https://github.com/linagora/james-project/issues/3701 `Email/get 10. bodyProperties: EmailBodyPart filtering`
 - https://github.com/linagora/james-project/issues/3703 `Email/get 12. bodyValues`
 - https://github.com/linagora/james-project/issues/3702 `Email/get 11. attachments property`
 - https://github.com/linagora/james-project/issues/3704 `Email/get 13. maxBodyValueBytes property (body truncation)` (low priority ?)
 - https://github.com/linagora/james-project/issues/3707 `Email/get 15. EmailBodyPart individual headers` (low priority ?)

**Comment by Arsnael** [comment]
Tickets regarding the download JMAP part:

* https://github.com/linagora/james-project/issues/3708 `Download 1. Port DownloadRoutes from draft to RFC-8621`
* https://github.com/linagora/james-project/issues/3709 `Download 2. Download part of a MIME message`
* https://github.com/linagora/james-project/issues/3710 `Download 3. Setting cache control headers`
