### ISSUE TITLE
Email/get 11.  attachments property

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3702]
## What?

Mime structure description for attachments.

## The spec

```
attachments: EmailBodyPart[] (immutable) A list, traversing depth-first, of all parts in bodyStructure that satisfy either of the following conditions:

    not of type multipart/* and not included in textBody or htmlBody
    of type image/*, audio/*, or video/* and not in both textBody and htmlBody

None of these parts include subParts, including message/* types. Attached messages may be fetched using the Email/parse method and the blobId.

Note that a text/html body part HTML may reference image parts in attachments by using cid: links to reference the Content-Id, as defined in [@!RFC2392], or by referencing the Content-Location.
```

## DOD

Given an email with an attachment, as a client, I am able to retrieve the blobId to download it.

## Notes

 - The **blobId** of an attachment should be its attachmentId.
 - We will rely on accessing attachments as currently stored by James. Any storage modification is out of scope.
 - In order to fully comply, and given that mailbox stored implementation don't include all headers, we will need to find a way to corellate the MIME4J parsing with the stored attachments.

## Example

Executing the following request

```
{
  "using": [
    "urn:ietf:params:jmap:core",
    "urn:ietf:params:jmap:mail"],
  "methodCalls": [[
    "Email/get",
    {
      "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
      "ids": ["3647"],
      "properties": ["attachments"]
    },
    "c1"]]
}
```

Will return:

```
{
  "sessionState": "75128aab4b1b",
  "methodResponses": [[
    "Email/get",
    {
      "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
      "state": "000001",
      "list": [
        {
          "id": "3647",
          "attachments": [
               {
                   "partId": "partId3",
                    "type": "image/png",
                    "blobId": "3647/partId3",
                    "size":12566,
                    "charset":"UTF-8",
                     "cid": null
                     "disposition" : null,
                     "language": "en, fr",
                     "location": "fiction1/fiction2",
                     "subParts": null,
                     "headers" : [
                            {"name": "Content/type", "value":"text/plain; charset=UTF-8"},
                            ...
                     ]
                }
             ]
        }
      ],
      "notFound": []
    },
    "c1"]]
}
```

**Comment by rouazana** [comment]
> Given an email with an attachment,

You miss to define what is an email with an attachment

**Comment by chibenwa** [comment]
Given an email with an attachment, **as per James already existing, implemented and battle tested heuristic**, ...

**Comment by rouazana** [comment]
Ok my question was more: did the definition change between the draft we implemented and the RFC?

**Comment by chibenwa** [comment]
The attachment object have more property than in the draft...

**Comment by rouazana** [comment]
I was not wondering about additional properties, but about a change in the definition of was is an attachment. When we implemented the draft the definition was not clear and we made our own heuristic on this. Does it match the definition of the RFC?

**Comment by chibenwa** [comment]
>  but about a change in the definition of was is an attachment

 - hasAttachment relies on a server heuristic thus current implementation status is fine
 - The new definition `not textBody and htmlBody & not multipart`

Our current definition is 

 - not a multipart
 - not in textBody/htmlBody
 - is an attachment or inline (disposition) OR has a CID OR is matching a contentType we consider as an attachment

So the transgression to the new spec is minimal.

That being said, we could very well rely on the parsing result of the bodyStructure, and correlate with the `attachmentId` stored on the backend, in order to have the corresponding blobId - if present.
