### ISSUE TITLE
Email/query Allow listing email

### ISSUE THREAD

**Issue by remk** [linagora/james-project#3706]
Simple implementation without filters/sorting/pagination
### Why

With the new specification, I should be able to list my emails:
```
[[ "Email/query",{
  "accountId": "ue150411c"
}, "0" ]]
```

Should return :

```
[[ "Email/query", {
  "accountId": "ue150411c",
  "queryState": "09aa9a075588-780599:0",
  "canCalculateChanges": false,
  "position": 0,
  "ids": [ "Ma783e5cdf5f2deffbc97930a",
    "M9bd17497e2a99cb345fc1d0a", ... ]
}, "0" ]]
```

### HOW

1. Implement a method for Email/query
2. Write dedicated integration tests for it.

### Notes

Even without sorting the order of the elements should be stable between two calls to the method.
The default sorting order will be the default used by james i.e by ascending order of message uids

### DOD

Write memory integration tests for Email/query

**Comment by chibenwa** [comment]
Is there a limitation of the Email ids count returned to the client?

How does the client discovers this limitation?

Maybe we can detail which sort / query is implicitly used as well.

**Comment by remk** [comment]
Yes, it will be part of another ticket.
This is only the first basic ticket

**Comment by remk** [comment]
JIRA : https://issues.apache.org/jira/browse/JAMES-3371
