### ISSUE TITLE
Download 1. Port DownloadRoutes from draft to RFC-8621

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#3708]
Regarding the JMAP specifications concerning downloading blobs : https://jmap.io/spec-core.html#downloading-binary-data 

The JMAP draft version already manages the download of attachments and full messages, thus: 

* Port download route from JMAP draft version.
* Make sure it works for full message and attachment
* Handle error:
  + Failed to Authenticate
  + No right to download
  + Resources not found
  + Parameters missing or wrong format

We need as well to propose an URL including the following parameters:

* **accountId**: The id of the account to which the record with the blobId belongs
* **blobId**: The blobId representing the data of the file to download
* **type**: The type for the server to set in the Content-Type header of the response; the blobId only represents the binary data and does not have a content-type innately associated with it
* **name**: The name for the file; the server MUST return this as the filename if it sets a Content-Disposition header

A proposed URL would be: `/download/$accountId/$blobId/?type=$type&name=$name`

DOD:
- Make sure it work for download full message or attachment
- Write integration test
- Update the session object with the new download URL

**Comment by chibenwa** [comment]
Can you provide an example URL scheme, and maybe also details the headers of the response?

**Comment by Arsnael** [comment]
I think for the URl I'm not so sure, it should be opened to discussion... 

Maybe something like `/download/$accountId/$blobId/$name?type=$type` ?

But couple of things I am not sure:
* regarding `accountId` it's something we don't really use for the moment. Should it be in the URL path or as a query param?
* `name` is optional as well right? Should it be a query param or like ind raft, you have two routes => `$blobId` and `$blobId/$name`?

**Comment by chibenwa** [comment]
I think name is an attribute of the resource and not an identifier.

I would suggest moving it as a parameter.

So `/download/$accountId/$blobId/?type=$type&name=$name`

Please mention in the DOD that the Session object will need to be updated.
