### ISSUE TITLE
Download 2. Download part of a MIME message

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#3709]
Following the porting work on https://app.zenhub.com/workspaces/team-james-5873652b2a0b13cc0b8bbe63/issues/linagora/james-project/3708

We need to be able to download as well mime parts of a message, represented in JMAP as an `EmailBodyPart` as described in https://app.zenhub.com/workspaces/team-james-5873652b2a0b13cc0b8bbe63/issues/linagora/james-project/3705

The `blobId` would be the serialization result of `emailId_partId`. 

We need to implement a new method in `BlobManager` that would allow us to retrieve a part of a message following above requirements.

**DoD**
Write integration tests where we can successfully download parts of a message

**Comment by Arsnael** [comment]
Would this be related to the bodyStructure as explained here? https://github.com/linagora/james-project/issues/3705

**Comment by chibenwa** [comment]
Yes. We have to share a common scheme for representing mime parts blobId.

I propose "emailId/partId" where partId is an integer.

**Comment by Arsnael** [comment]
But partId is a String in the specs no?

**Comment by chibenwa** [comment]
"365" is a string too :-p

**Comment by rouazana** [comment]
> I propose "emailId/partId" where partId is an integer.

I don't think `/` is a good separator for that, as it has a specific meaning in URI, and so can change the download format. But I agree with the general idea.

**Comment by Arsnael** [comment]
Very good remark thanks! I changed it to a `-` instead?

**Comment by chibenwa** [comment]
Not that good when the EmailId is UUIDish :-)

**Comment by Arsnael** [comment]
How about `:`?

**Comment by rouazana** [comment]
> How about `:`?

It's used to separate the port section. I see `_` as a good candidate.
