### ISSUE TITLE
Download 3. Setting cache control headers

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#3710]
As the data for a particular blobId is immutable, and thus the response in the generated download URL is too, implementors are recommended to set long cache times and use the “immutable” Cache-Control extension [@?RFC8246] for successful responses, 
for example: `Cache-Control: private, immutable, max-age=31536000`

DOD: with integration test showing that we return the blob with a correct `Cache-Control` header

**Comment by chibenwa** [comment]
I think you mean "setting cache control headers". We might want to better understand the impact of such cache within the scope of OpenPaaS INBOX product.

**Comment by Arsnael** [comment]
Not sure to fully get it yet but I think this task is not a priority one either?
