### ISSUE TITLE
Email/query Allow filtering by mailbox

### ISSUE THREAD

**Issue by remk** [linagora/james-project#3714]
First ticket to implement the filtering when querying emails.
The handling of shared mailbox will be done later in another issues

### Why

As an user i want to be able to select the mail in a mailbox like this : 
```
[[ "Email/query",{
  "accountId": "ue150411c",
  "filter":  {
     "inMailbox": "myMailboxID"
}
}, "0" ]]
```
I also want to be able to select emails NOT in a set of mailboxes
```
[[ "Email/query",{
  "accountId": "ue150411c",
  "filter":  {
     "inMailboxOtherThan": ["myMailboxID1", ""myMailboxID2"]
}
}, "0" ]]
```
### HOW
- accept a simple FilterCondition with an optional 'inMailbox' field
- accept a simple FilterCondition with an optional 'inMailboxOtherThan' field
- filter the query with the provided mailboxId

### Still to groom
- error when mailbox not found or empty result ?

### DOD

- write integration demonstrating that a user can filter the email of one of its mailbox.
- write integration demonstrating that a user can filter the email  not in some of its mailboxes.

- write integration demonstrating that a user can filter the email  by both those filters. The expected result is the intersection of the results of both filters.

**Comment by chibenwa** [comment]
`error when mailbox not found or empty result ?` => empty result. Error if the mailboxId is invalid...
