### ISSUE TITLE
Email/Query Allow filter by size

### ISSUE THREAD

**Issue by remk** [linagora/james-project#3718]
As an user i want to be able to select messages by size using the 'minSize' and 'maxSize' filters.

### Why

As an user i want to be able to select the mail in a mailbox like this : 
```
[[ "Email/query",{
  "accountId": "ue150411c",
  "filter":  {
     "minSize":  512
}
}, "0" ]]
```

### HOW
- accept the filters 'minSize' and 'maxSize' in the filter condition from the request
- filter the query with the provided size
### DOD

- write integration demonstrating that a user can filter its emails by size

**Comment by rouazana** [comment]
worth to say that minSize is inclusive while maxSize is exclusive
```
minSize: UnsignedInt The size property of the Email must be equal to or greater than this number to match the condition.
maxSize: UnsignedInt The size property of the Email must be less than this number to match the condition.
```
