### ISSUE TITLE
Email/Query filter by keywords

### ISSUE THREAD

**Issue by remk** [linagora/james-project#3719]
As an user i want to be able to select messages by their keywords using the 'hasKeyword' and 'notKeyword' filters.
The following system flags are handled
```
"$Draft"
"$Seen"
"$Flagged"
"$Answered"
"$Forwarded"
```
user keywords should be handled too

Please not that 
> The IMAP \Recent keyword is not exposed via JMAP. The IMAP \Deleted keyword is also not present: IMAP uses a delete+expunge model, which JMAP does not. Any message with the \Deleted keyword MUST NOT be visible via JMAP (and so are not counted in the “totalEmails”, “unreadEmails”, “totalThreads”, and “unreadThreads” Mailbox properties).

### Why

As an user i want to be able to select the mail in a mailbox like this : 
```
[[ "Email/query",{
  "accountId": "ue150411c",
  "filter":  {
     "hasKeyword":  "$Flagged"
}
}, "0" ]]
```

### HOW
- accept the filters 'hasKeyword' and 'notKeyword' in the filter condition from the request
- filter the query with the provided keywords
### DOD

- write integration demonstrating that a user can filter its emails by supported system keyword
- write integration demonstrating that a user can filter its emails with valid user keyword
- write an integration test verifying that a message with a deleted flags is never returned in jmap

**Comment by chibenwa** [comment]
`Any message with the \Deleted keyword MUST NOT be visible via JMAP (and so are not counted in the “totalEmails”, “unreadEmails”, “totalThreads”, and “unreadThreads” Mailbox properties).` => should be another ticket IMO

We might want to further discuss how to enforce this.

Would explicitly rejecting \\Deleted messages from backend search be enough to be spec compliant? Maybe Email/get also need to return 'not found' on deleted messages (and thus that's yet another ticket)

**Comment by remk** [comment]
The more i think about it, the more i think it as not its place on this ticket. 
It is a part of the jmap specification that i put as a reminder in several ticket. 
It should be handled on its own it think
