### ISSUE TITLE
Email/Query filter hasAttachments

### ISSUE THREAD

**Issue by remk** [linagora/james-project#3721]
As an user i want to be able to select messages by their 'hasAttachments' property.

### Why

As an user i want to be able to select the mail in a mailbox like this : 
```
[[ "Email/query",{
  "accountId": "ue150411c",
  "filter":  {
     "hasAttachments":  true
}
}, "0" ]]
```

### HOW
- accept the filters 'hasAttachments' in the filter condition from the request
- filter the query with the hasAttachments property
### DOD

- write integration demonstrating that a user can filter its emails by their 'hasAttachments' property

**Comment by rouazana** [comment]
```
hasAttachment: Boolean (immutable; server-set) This is true if there are one or more parts in the message that a client UI should offer as downloadable. A server SHOULD set hasAttachment to true if the attachments list contains at least one item that does not have Content-Disposition: inline. The server MAY ignore parts in this list that are processed automatically in some way or are referenced as embedded images in one of the text/html parts of the message.

The server MAY set hasAttachment based on implementation-defined or site-configurable heuristics.
```

**Comment by chibenwa** [comment]
> The server MAY set hasAttachment based on implementation-defined or site-configurable heuristics.

Looks 100% compatible with what we are currently doing ^^
