### ISSUE TITLE
Email/Query support combination of filters with the FilterOperator (AND, OR, NOT)

### ISSUE THREAD

**Issue by remk** [linagora/james-project#3725]
### WHY
As an user i want to be able to build complex query using the FilterOperators (AND, OR, NOT)

```
[[ "Email/query",{
  "accountId": "ue150411c",
  "filter":  {
      "operator": "OR",
      "conditions": [
      { "inMailbox":  "mailbox1"}, {"inMailbox":  "mailbox2"}   
]
}
}, "0" ]]
```

###HOW
- in the request accept the filter with an 'operator' field and distinguish it from the simple Condition.
  This should be handled in the Json reads. And build a tree which have nodes being FilterOperator and leaf being FilterConditions. 
- translate those elastic search query

### DOD

- write an integration test demonstrating the support of one level of Operator (like in the previous example)
- write an integration test demonstrating the support of an arbitrary level of nesting Operators.
- run those tests against the distributed version of james.

**Comment by chibenwa** [comment]
How this combines with inMailboxes, notInMailboxes filters? What do we actually allow here?

**Comment by rouazana** [comment]
> How this combines with inMailboxes, notInMailboxes filters? What do we actually allow here?

I don't see any issue regarding this, do you have specific examples?

**Comment by rouazana** [comment]
Is implicit AND handled in this ticket?

for example
```
[[ "Email/query",{
  "accountId": "ue150411c",
  "filter":  { "inMailbox":  "mailbox1", "inMailboxOtherThan":  "mailbox2"}   
}, "0" ]]
```

**Comment by rouazana** [comment]
> > How this combines with inMailboxes, notInMailboxes filters? What do we actually allow here?
> 
> I don't see any issue regarding this, do you have specific examples?

The worst example I see regarding this is:
```
[[ "Email/query",{
  "accountId": "ue150411c",
  "filter":  { "inMailbox":  "mailbox1", "inMailboxOtherThan":  "mailbox1"}   
}, "0" ]]
```

If message1 is in mailbox1 and mailbox2, I guess this filter should return message1 as it is in mailbox1, and it is also in a mailbox other than mailbox1.

**Comment by chibenwa** [comment]
(I think it should be handled here, and I also think your example is misleading as no email will match both of these contraint. We will likely forbid to specify inMailbox & inMailboxOtherThan at the same time)

**Comment by rouazana** [comment]
> (I think it should be handled here, and I also think your example is misleading as no email will match both of these contraint. We will likely forbid to specify inMailbox & inMailboxOtherThan at the same time)

My example is perfectly valid, don't forget that "inMailboxOtherThan" is different of "notInMailbox". It's not the same meaning. In this case
```
[[ "Email/query",{
  "accountId": "ue150411c",
  "filter":  { "inMailbox":  "mailbox1", "inMailboxOtherThan":  "mailbox2"}   
}, "0" ]]
```
would simple return all emails that are at least present in mailbox1. In this specific case "inMailboxOtherThan" is useless but think of it as a way to exclude trash/spam folder for some search.

**Comment by rouazana** [comment]
implicit AND is handled into #3714

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/JAMES-3390
