### ISSUE TITLE
Email/Query Allow filter by date

### ISSUE THREAD

**Issue by remk** [linagora/james-project#3727]
As an user i want to be able to select messages by reception date using the 'before' and 'after' filters.

### Why

As an user i want to be able to select the mail in a mailbox like this : 
```
[[ "Email/query",{
  "accountId": "ue150411c",
  "filter":  {
     "before":  "1994-11-05T13:15:30Z "
}
}, "0" ]]
```

### HOW
- accept the filters 'before' and 'after' in the filter condition from the request
- filter the query with the provided date
### DOD

- write integration demonstrating that a user can filter its emails by reception date

**Comment by rouazana** [comment]
Here also be careful of the limits:
```
before: UTCDate The receivedAt date-time of the Email must be before this date-time to match the condition.
after: UTCDate The receivedAt date-time of the Email must be the same or after this date-time to match the condition.
```
before is exclusive, while after is inclusive.
