### ISSUE TITLE
Email/Query expose allowed sort in accountCapabilities

### ISSUE THREAD

**Issue by remk** [linagora/james-project#3728]
### WHY
As a client i need to know what sort filters are supported by the server.
the list of field supported will be returned as an array of string in the emailQuerySortOption field of the capabilities(a field inside MailCapability) in the session object.

`emailQuerySortOptions: String[] A list of all the values the server supports for the “property” field of the Comparator object in an Email/query sort (see Section 4.4.2). This MAY include properties the client does not recognise (for example, custom properties specified in a vendor extension). Clients MUST ignore any unknown properties in the list.`

The list of supported filters in this first implementation are :
```
receivedAt
size
from
to
subject
sentAt
hasKeyword
```

the following fields are not supported at the moment :
allInThreadHaveKeyword, someInThreadHaveKeyword
Because we don't support thread yet.

### HOW
- add the emailQuerySortOption fields to the supported capabilites

### DOD
- write an integration test validating that all the filter in the previous list appears in the capabilities in the session object

**Comment by nvduc91** [comment]
https://issues.apache.org/jira/browse/JAMES-3383

**Comment by nvduc91** [comment]
it is already done in code?

**Comment by nvduc91** [comment]
Those emailQuerySortOption: `"from", "to", "subject", "size","hasKeyword"` are not supported yet so will be only:
`"receivedAt", "sentAt"` for now.
