### ISSUE TITLE
Email/Query Pagination 3 - handle pagination with position and limit clause

### ISSUE THREAD

**Issue by remk** [linagora/james-project#3733]
### WHY

As a client I want to be able to get a long list of results in several operations.
As a client i want to be able to fetch a page of result with a given position (position) and a page size (limit)

```

    position: Int (default: 0) The zero-based index of the first id in the full list of results to return.

    If a negative value is given, it is an offset from the end of the list. Specifically, the negative value MUST be added to the total number of results given the filter, and if still negative, it’s clamped to 0. This is now the zero-based index of the first id to return.

    If the index is greater than or equal to the total number of objects in the results list, then the ids array in the response will be empty, but this is not an error.
```

    request

```
    [[ "Email/query",{
      "accountId": "ue150411c",
      "position": 5,
      "limit": 20
    }, "0" ]]
```

### DOD

- write an integration test demonstrating that when the client provide a position parameter and a limit clause, only the results since this position are returned in the response and only the number of element corresponding to the limit are fetched.

- write the same test with a negative position **(Rejected in current implementation)**

- write an integration test demonstrating that if the client provide a position parameter bigger than the total number of results then the response is empty and there is no error.

- run the tests against the distributed version of the contract

**Comment by rouazana** [comment]
do you miss a limit in your request to match this ticket?
