### ISSUE TITLE
Email/query Allow filtering by from/to/bcc/cc/subject

### ISSUE THREAD

**Issue by remk** [linagora/james-project#3734]
As a user i want to be able to search by from/to/bcc/cc/subject

```
from: String Looks for the text in the From header field of the message.
to: String Looks for the text in the To header field of the message.
cc: String Looks for the text in the Cc header field of the message.
bcc: String Looks for the text in the Bcc header field of the message.
subject: String Looks for the text in the Subject header field of the message.
```

### Why

As an user i want to be able to select the mail by searching for a text in those headers like this : 
```
[[ "Email/query",{
  "accountId": "ue150411c",
  "filter":  {
     "from": "@james.org"
}
}, "0" ]]
```

should return the emails from all the address containing '@james.org'

### HOW
- accept a simple FilterCondition with an optional 'from' field
- accept a simple FilterCondition with an optional 'to' field
- accept a simple FilterCondition with an optional 'bcc' field
- accept a simple FilterCondition with an optional 'cc' field
- filter the query with those parameters. It don't need to be an exact match. For the result to appear the field should contains the value : .*value.*

```
The exact semantics for matching String fields is deliberately not defined to allow for flexibility in indexing implementation, subject to the following:

    Any syntactically correct encoded sections [@!RFC2047] of header fields with a known encoding SHOULD be decoded before attempting to match text.

    Text SHOULD be matched in a case-insensitive manner.

    Text contained in either (but matched) single (‘) or double (“) quotes SHOULD be treated as a phrase search; that is, a match is required for that exact word or sequence of words, excluding the surrounding quotation marks.
```

### DOD

- write integration demonstrating that a user can filter the email with an exact value from those fields
- write integration demonstrating that a user can filter the email  with a value contained in one of those fields

**Comment by chibenwa** [comment]
Sould we only match the address or should we conduct a match on the name as well?
