### ISSUE TITLE
Email/Query handle unsupported parameters

### ISSUE THREAD

**Issue by remk** [linagora/james-project#3738]
### Why
The following properties, mainly related to thread handling are not supported.
The user shoud receive an appropriate error message.
filters: allInThreadHaveKeyword/someInThreadHaveKeyword/noneInThreadHaveKeyword
sorting: allInThreadHaveKeyword/someInThreadHaveKeyword
collapseThreads
(and more generically any other unsupported value)

### HOW 

In case of an unsupported sort the response should be a method level error of type : 
`unsupportedSort: The sort is syntactically valid, but it includes a property the server does not support sorting on or a collation method it does not recognise.`

In case of an unsupported filter the response should be a method level error of type : 
unsupportedFilter: The filter is syntactically valid, but the server cannot process it. If the filter was the result of a user’s search input, the client SHOULD suggest that the user simplify their search.

### TO GROOM
Do we handle  Anchor / AnchorOffset or do we reject those properties ?

how to handle collapseThreads, do we accept but ignore the property has each mails have its own thread at the moment.
Or do we send an error response ?

### DOD
- write an integration test demonstrating that when using the filters allInThreadHaveKeyword and noneInThreadHaveKeyword, the client receive  an unsupportedFilter error. Generalize it to any none recognized/handled property
- write an integration test demonstrating that when using the sorts allInThreadHaveKeyword and someInThreadHaveKeyword, the client receive  an unsupportedSort error. Generalize it to any none recognized/handled property
- write an integration showing Anchor and AnchorOffSet are rejected
- write an integration test showing collapseThreads results in a noop

**Comment by Arsnael** [comment]
JIRA: https://issues.apache.org/jira/browse/JAMES-3384
