### ISSUE TITLE
Add capability mandatory checks regarding jmap core and mail 

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#3745]
It seems we are not checking that base mandatory capabilities are present in the request when processing the methods :

* urn:ietf:params:jmap:core
* urn:ietf:params:jmap:mail

We need to make sure we reject requests in our apis missing those (mailbox/get, mailbox/set, vacationresponse/get, vacationresponse/set... even core/echo with core capability?)

It would be ideal to handle this in a generic fashion: the methods declare which capabilities they need and the API routes ensure these capabilities are there before calling the methods themselves.

**DoD**
* Add integration tests showing that requests with missing mandatory capabilities are being rejected in our existing APIs

JIRA: https://issues.apache.org/jira/browse/JAMES-3367

**Comment by chibenwa** [comment]
I would like to have this handled in a generic fashion: the methods declares which capabilities they need and the API routes ensure these capabilities are there before calling the methods themselves.

This way we won't need to worry about this every time we write a new method.

Cc @LanKhuat

**Comment by Arsnael** [comment]
Interesting, I agree :)
