### ISSUE TITLE
a issue about mailbox-cassandra keyspace, for help pls.

### ISSUE THREAD

**Issue by huangyaoqing** [linagora/james-project#3751]
We are going to use cassandra to store mail.

**1 configure  mailbox.xml   provider as "cassandra" like this:**

**2 and add config file :\james-project-james-project-3.4.0\mailbox\cassandra\src\main\resources\cassandra.properties**
mailbox.max.retry.acl=1
mailbox.max.retry.modseq=2
mailbox.max.retry.uid=3
mailbox.max.retry.message.flags.update=4
mailbox.max.retry.message.id.flags.update=5
fetch.advance.row.count=6
chunk.size.message.read=7
chunk.size.expunge=8
mailbox.blob.part.size=9
attachment.v2.migration.read.timeout=10
message.attachmentids.read.timeout=11
cassandra.username=cassandra
cassandra.password=cassandra
cassandra.host=10.33.207.49
cassandra.port=9042

**3 james-project-james-project-3.4.0\mailbox\spring\src\main\resources\META-INF\spring\spring-mailbox.xml**
in this file, add this:
    import resource="classpath:META-INF/spring/mailbox-cassandra.xml"
META-INF/spring/mailbox-cassandra.xml"
in this file, add this:
    bean class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer“
        property name="ignoreUnresolvablePlaceholders" value="true"
        property name="location" value="classpath:cassandra.properties"

**4 At cassandra side, i also create  keyspace.table: mai.messagecounter.**

cqlsh:mail> describe mail
CREATE KEYSPACE mail WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
CREATE TABLE mail.messagecounter (
    mailboxid text PRIMARY KEY,
    nextuid text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
==========

The error point is at here
    @Inject
    public CassandraUidProvider(Session session, CassandraConfiguration cassandraConfiguration) {
        this.executor = new CassandraAsyncExecutor(session);
        this.maxUidRetries = cassandraConfiguration.getUidMaxRetry();
        this.selectStatement = **prepareSelect(session);   //error point**
        this.updateStatement = prepareUpdate(session);
        this.insertStatement = prepareInsert(session);
    }

**** 5 The error log is as below：**** 
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandra-mailboxmanager' defined in class path resource [META-INF/spring/mailbox-cassandra.xml]: Cannot resolve reference to bean 'mapperFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mapperFactory' defined in class path resource [META-INF/spring/mailbox-cassandra.xml]: Cannot resolve reference to bean 'cassandra-uidprovider' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandra-uidprovider' defined in class path resource [META-INF/spring/mailbox-cassandra.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.apache.james.mailbox.cassandra.mail.CassandraUidProvider]: Constructor threw exception; nested exception is com.datastax.driver.core.exceptions.InvalidQueryException: No keyspace has been specified. USE a keyspace, or explicitly specify keyspace.tablename

**6 then I add keyspace , the error is same.**
public interface CassandraMessageUidTable {
    **String TABLE_NAME = "mail.messageCounter"; //modify TABLE_NAME,add keyspace mail**
    String MAILBOX_ID = "mailboxId";
    String NEXT_UID = "nextUid";
}

I donot know how to analysis the issue, could you give me some guide, or if you have any demo or example available, share me pls.
Thank you very much.

**Comment by Arsnael** [comment]
Hi,

It seems you are using the Spring version of James. However, Cassandra is only supported in Guice Cassandra product and distributed version. Note that the version 3.5 went out not too long ago as well.

James Cassandra: https://james.apache.org/server/install/guice-cassandra.html
James Distributed: https://james.apache.org/server/install/guice-cassandra-rabbitmq-swift.html

Hope this can help you :)

**Comment by huangyaoqing** [comment]
Hi,Arsnael 
    Thanks for your help.
    
    I want to use james with cassandra in spring framework.I find JPAMailboxMapper and CassandraMailboxMapper are extened from MailboxMapper，JPAMessageManager and CassandraMessageManager are extended from StoreMessageManager
    In StoreMessageManager.appendMessageToStore, messageMapper.add() is called, 
    the add api is implemented in both JPAMailboxMapper and CassandraMailboxMapper.
    It seems that cassandra can also work well in spring framework.
	
    But when i configure as above, i encountered the above issue.
    could you give some guide, how to apply it?
    and if there are script about to create keyspace and table in cassandra, share me pls!

**Comment by Arsnael** [comment]
> It seems that cassandra can also work well in spring framework.

You are jumping a bit fast in conclusion here... There is nothing so far with Spring supporting Cassandra. I will be probably honest by saying the devs here now have very little knowledge regarding Spring. We try to maintain it for now but the goal would be eventually to remove it when JPA for Guice gets complete enough to replace it. I myself don't know much how Spring works TBH. 

Why do you want to use Spring with Cassandra btw, while Cassandra with Guice is being actively developed and tested? However regarding Guice, well we do have a cassandra.properties file, for example:
* https://github.com/apache/james-project/blob/master/dockerfiles/run/guice/cassandra/destination/conf/cassandra.properties
* https://james.apache.org/server/config-cassandra.html

The keyspace is created (if needs to) during the start of the server, within all the Guice wirings:
* `CassandraSessionModule` (where we get as well conf from the `cassandra.properties` file): https://github.com/apache/james-project/blob/master/server/container/guice/cassandra-guice/src/main/java/org/apache/james/modules/mailbox/CassandraSessionModule.java#L184
* `KeyspaceFactory`: https://github.com/apache/james-project/blob/master/backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/init/KeyspaceFactory.java

I still don't get why you want to use Cassandra with Spring, any particular reason? You might get more chances of support using Cassandra with Guice than with Spring, with reasons mentioned above

**Comment by huangyaoqing** [comment]
hi, Arsnel
Thanks!

Because our team members understand few about guice, but spring available.
as far as I know guice need run in docker，and  we will not use docker.
So we select spring.

And I found that the default package of james is for spring.
I don't know how to change to guice package,and generate it.

**Comment by Arsnael** [comment]
No you can run the Guice version without Docker too. Maybe this could help you? https://james.apache.org/server/quick-start-cassandra.html

**Comment by huangyaoqing** [comment]
Thanks,Arsnael.
	Do you ever make any evaluation about the max record capacities of cassandra and Derby?
	And another question is that, wether mailbox and user account repository can be set seperately?
	like this, user account is stored in derby, and mail is in cassandra.

**Comment by Arsnael** [comment]
> Thanks,Arsnael.
You're welcome

> Do you ever make any evaluation about the max record capacities of cassandra and Derby?
I'm not sure but I don't think so

> And another question is that, wether mailbox and user account repository can be set seperately?
> like this, user account is stored in derby, and mail is in cassandra.
No the distribution are not mixing dbs together. It is derby or cassandra, not both. I'm not sure I would understand the use for this, and it would be very complex to achieve IMO (and James is complex enough I believe^^)
