### ISSUE TITLE
Allow "relaxed" mailbox creation

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3759]
Mailbox creation comes with constraints and the IMAP specification discourages the use of some characters `&` for instance.

As such James currently rejects IMAP mailbox creation with & in their name.

However, this makes existing data migration into a new James server painful: with our current Linagora tool (namely imapSync) we have currently no viable strategy for migrating mailboxes of the previous system having & in their name.

We could allow a relaxed mailbox name mode via the configuration, that we would use during the initial migration. Once migrated, administrators could then choose to re-enable the strict mode - if they whish to.

**Comment by remk** [comment]
I don't understand why we should handle that in james. It should be done in when calling the migration tool.
In fact imapsync allow to rename mailboxes using regex : https://imapsync.lamiral.info/FAQ.d/FAQ.Folders_Mapping.txt

**Comment by MichaelBailly** [comment]
My 2 cent:

I don't know if James should do this. On one side, Cyrus allows some "relaxed" chars in the mailbox names, like **&**. On another side, moving away from RFC is always a dangerous option. I'd be curious to know if Gsuite/o365 allows this kind of chars.

**Comment by rouazana** [comment]
do we support / need to support imaputf7?

**Comment by remk** [comment]
> My 2 cent:
> 
> I don't know if James should do this. On one side, Cyrus allows some "relaxed" chars in the mailbox names, like **&**. On another side, moving away from RFC is always a dangerous option. I'd be curious to know if Gsuite/o365 allows this kind of chars.

seems supported in gmail

**Comment by chibenwa** [comment]
https://james.apache.org/protocols/apidocs/org/apache/james/imap/api/display/CharsetUtil.html

`Utility class which can be used to get a list of supported Charset's Beside this it has some methods included which helps to encode/decode modified UTF7`

Sounds like we do.

**Comment by rouazana** [comment]
let's do that then!

**Comment by chibenwa** [comment]
Okay!
