### ISSUE TITLE
Java.spark issue in UserRoutes with character ';'

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#3767]
After the rebase with S3, we had to downgrade the httpclient dependency from 5.10 to 5.9, to align with the one used by aws-sdk and more stability. But then a problem arise in a test in UserRoutesTest : `putShouldReturnBadRequestWhenUsernameContainsSemicolonCharacter` (disabled test)

After debugging it looks like after the downgrade, when passing a `;` in the REST request, spark.java can't extract fully the username parameter from the URL if it contains a `;`. It seems to drop everything from the `;`

For example if you send `{webadmin}/users/user;name@domain`, instead of getting from the request parameter `user;name@domain`, you only get `user`.

**DoD**:
Fix the issue and re-enable the test

**Comment by chibenwa** [comment]
What is the JIRA issue associated to this?

**Comment by Arsnael** [comment]
Didn't create yet. Waiting to see if we really need this or not before creating the JIRA. If downgrading httpclient doesn't really solve the flaky test, there is no point of keeping the downgrade and that issue

**Comment by Arsnael** [comment]
Closing, as downgrading httpclient doesn't solve the S3 flaky tests so we won't be concerned by this bug
