### ISSUE TITLE
Bug > Able to create a mailbox using only spaces in the name

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3799]
# Actual Result
It is able to create a mailbox with `name` contains only spaces

![screenshot_15](https://user-images.githubusercontent.com/69950655/93844646-20130e80-fcc8-11ea-9c57-b90e919c8632.png)

# Expected Result
It should avoid creating a mailbox name with only spaces

# Environment 
DEV environment

**Comment by chibenwa** [comment]
We need to reject blank space in `MailboxPath::assertValid`, this should be enough to solve this issue.

We should not forget to write an integration test (new spec, but also old spec)

**Comment by tlle14** [comment]
Retest pass

![image](https://user-images.githubusercontent.com/69950655/94673824-7e339780-0341-11eb-99ff-fcd95049a755.png)
