### ISSUE TITLE
Bug > Able to update a mailbox to be the child of itself

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3806]
# Actual Result
It returns a successful result when update a mailbox to be a child of itself
But then we cannot get the mailbox
![screenshot_17](https://user-images.githubusercontent.com/69950655/93958275-5b711400-fd80-11ea-9dac-2ea01ed24c89.png)
![screenshot_18](https://user-images.githubusercontent.com/69950655/93958293-6330b880-fd80-11ea-8fa7-d788968dd36f.png)

# Expected Result
It should avoid creating a mailbox to be a child of itself. This is a kind of loop 
![image](https://user-images.githubusercontent.com/69950655/93958259-544a0600-fd80-11ea-98e6-8787dfa8ca05.png)

# Environment
DEV environment

**Comment by chibenwa** [comment]
Looks funny ;-)

**Comment by tlle14** [comment]
Thank @chibenwa 

Retest pass on DEV platform

![image](https://user-images.githubusercontent.com/69950655/94670920-5f330680-033d-11eb-99b5-ff7761f71d14.png)
