### ISSUE TITLE
[Bug] Invalid mailbox filters don't return error in new JMAP

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#3821]
When I send an invalid unknown filter through my JMAP Email/query or Mailbox/query request, it should return an invalidArguments method error.

However, for now it is just being ignored and the request is being processed as normal.

DoD: integration tests showing an invalid filter is being properly rejected by the server for email/query and mailbox/query

**Comment by nvduc91** [comment]
https://issues.apache.org/jira/browse/JAMES-3401
