### ISSUE TITLE
Bug > Search function should return the most relevant result on the top 

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3824]
# Actual Result
When searching emails in the past, it displays a lot of matching results sorted by date. 
The most relevant email displays somewhere in the middle instead of the top.

# Expect result
The most relevant result should display on the top. 
The result should be sorted by the most relevant priority instead of by date

**Comment by chibenwa** [comment]
I would say this is an INBOX bug

(in the way they query James)

IE INBOX should NOT set any sort when doing text search

cc @MichaelBailly

**Comment by tlle14** [comment]
Close this issue as it belongs to INBOX module
