### ISSUE TITLE
Email/set update mailboxIds 1. Reset

### ISSUE THREAD

**Issue by LanKhuat** [linagora/james-project#3828]
### Objective

As an user i want to move messages from mailbox to mailbox.

### How

Updating the mailboxIds field of one or more messages by sending an Email/set request, replacing the entire set of mailboxIds of the messages.

### Request
```
[[ "Email/set", {
  "accountId": "ue150411c",
  "update": {
    "messageId1": {
      "mailboxIds": {
        "mailboxId1": true,
        "mailboxId2": true,
        "mailboxId3": false
      }
    }
  }
}, "0" ]]
```

### Response
```
{
  "sessionState": "75128aab4b1b",
  "methodResponses": [
    ["Email/set", {
      "updated": {
        "messageId1": {
          mailboxIds: {
            "mailboxId1": true,
            "mailboxId2": true,
            "mailboxId3": false
          }
        }
      }
    }, "0"]
  ]
}
```
### DOD

Write integration tests to show that user can update mailboxIds for one/many messages in the same request.

**Comment by chibenwa** [comment]
Can we have 2 tickets: One for reset, one for partial update?

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/JAMES-3413
