### ISSUE TITLE
Email/set update mailboxIds 2. Partial update

### ISSUE THREAD

**Issue by LanKhuat** [linagora/james-project#3829]
### Objective

As an user i want to move messages from mailbox to mailbox.

### How

Updating several mailboxIds of one or more messages by sending an Email/set request using JSON pointer syntax. 

### Request
```
[[ "Email/set", {
  "accountId": "ue150411c",
  "update": {
    "messageId1": {
      "mailboxIds/mailboxId3": false
    }
  }
}, "0" ]]
```

### Response
```
{
  "sessionState": "75128aab4b1b",
  "methodResponses": [
    ["Email/set", {
      "updated": {
        "messageId1": {
          mailboxIds: {
            "mailboxId1": true,
            "mailboxId2": true,
            "mailboxId3": false
          }
        }
      }
    }, "0"]
  ]
}
```
### DOD

- Write integration tests to show that user can update mailboxIds for one/many messages in the same request.
- Partial update should not affect other mailboxIds of the same message.

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/JAMES-3414
