### ISSUE TITLE
[Bug] Missing the bucket handling after S3 rebase API

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#3847]
The bucket prefix and the resolution of the bucket name with the prefix has been completely forgotten during the rebase with S3 API, breaking existing James running with the bucket prefix when upgrading. It seems the namespace is not really handled too. We need to add it back

**DoD**
Bucket name handling and proper tests restored

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project/pull/3848 scope: default bocket

@Arsnael will apply another PR for "prefix" application with the (removed) BucketNameResolver

**Comment by Arsnael** [comment]
https://github.com/linagora/james-project/pull/3860 -> JAMES-3028 Bucket name resolver S3 blob store
