### ISSUE TITLE
IMAP Fetch: UidMSNConverter :: get MSN is slow

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3861]
# What?

Following openpaas-1.7.15-rc2 deployment, and the use of VAVR immutable datastructures in UidMsnConverter, I notice some offending slow FETCH requests.

![Capture d’écran de 2020-10-05 09-11-55.png](https://images.zenhubusercontent.com/5ef2aee69879df3417738ce4/505e82aa-621d-4603-97b5-2c0b5a971358)

A closer look shows Cassandra is not to blame here

![Capture d’écran de 2020-10-05 09-10-00.png](https://images.zenhubusercontent.com/5ef2aee69879df3417738ce4/c5fa4dc3-789f-487c-8c0f-2f40e6c43c2a)

Flame graphs correlate the analysis

![Capture d’écran de 2020-10-05 09-10-05.png](https://images.zenhubusercontent.com/5ef2aee69879df3417738ce4/b6d2c450-5dc7-48e1-9100-eeed3023c64b)

Micro - benchmarks show breakage in performance from 8.000.000 mails locally.

# Short term reaction

 - Should we revert the use of VAVR in UidMsnConverter?

**Comment by Arsnael** [comment]
Let's revert for now if it's an issue yes, and monitor that part again :)

**Comment by chibenwa** [comment]
N (for each message) * Log(N) access in a RedBlack tree

VS

N (for each message) * O(1) access in an array

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/JAMES-3403
