### ISSUE TITLE
Email/query incorrect address matching in distributed James

### ISSUE THREAD

**Issue by LanKhuat** [linagora/james-project#3863]
### Description

Message has many fields in which can contain email address, (From, To, Cc...). When querying for messages based on these fields, distributed James currently returns incorrect results.

### Example

Message1 is sent to the address user@domain.tld
Message2 is sent to the address other@domain.tld

When querying message with the condition {to: "user@domain.tld"}, distributed James returns both Message1 and Message2. 
When querying message with the condition {to: "domain.tld"}, distributed James returns 0 result.

### Why

ElasticSearch is configured to index address field with a custom analyzer, storing email address as a whole string as well as the tokenized version of it. For example with an email address: user@domain.tld, the splited terms we want should look like: 
```
[user, domain.tld, user@domain.tld]
```

However it seems that this configuration is not working correctly, leading to the issue.

### The fix

Investigate ElasticSearch current indexing configurations.

### DoD

- Write integration test to show that ElasticSearch returns only the correct address when full address is provided in the query.
- Write integration test to show that ElasticSearch returns all matched addresses when a part of the email is provided in the query. 
- All currently disabled tests related to address matching in DistributedEmailQueryMethodTest should pass.

**Comment by chibenwa** [comment]
Maybe a fix would be to remove the domain from the terms?
