### ISSUE TITLE
Email/set update mailboxIds 3. Update optimization

### ISSUE THREAD

**Issue by LanKhuat** [linagora/james-project#3864]
### Objective

JMAP Email/set supports update mailboxId for multiple messages in the same request. When the number of message is high, relying on the messageIdManager for updating each message individually, one at a time may have performance issues.

### How

- We should have different mechanisms for updating message, one when the messages count is low and one for high. The former should leverage messageIdManager like normal update when . The latter should leverage mailboxManager for better performance.
- We will define a certain threshold to determine which mechanism should be used when calling update.

### DoD

- Define a threshold for messages count.
- Modify the EmailSetMethod so that when the messages count is higher than the threshold, server will use the mailboxManager to update the messages. (if all the messages are in the same mailbox and if all the target mailboxes are the same single mailbox)
- Integration test to show that the mechanism switching works.
- Performance test to show that this approach does bring performance gains for Email/set update.

**Comment by chibenwa** [comment]
Also implement a MailboxId version of move
