### ISSUE TITLE
Bug > User is able to search email on Trash mailbox by using Global search

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3887]
# Actual Result

When using a global search, it returns the result including the message in the Trash mailbox
![image](https://user-images.githubusercontent.com/69950655/95704898-8d3d1280-0c7c-11eb-85f8-353ce5e80da0.png)

![Peek 2020-10-12 11-15](https://user-images.githubusercontent.com/69950655/95704903-929a5d00-0c7c-11eb-8866-4753a0c74733.gif)

# Expected Result
It shouldn't return messages in the Trash mailbox when using a global search

# Environment

DEV environment

**Comment by chibenwa** [comment]
It's an INBOX bug: they need to specify a "not in mailbox" filter on there search.

Can you move the ticket there @tlle14 ?

**Comment by tlle14** [comment]
> It's an INBOX bug: they need to specify a "not in mailbox" filter on there search.
> 
> Can you move the ticket there @tlle14 ?

Sure, thank @chibenwa

**Comment by chibenwa** [comment]
See https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/206
