### ISSUE TITLE
james-cli Get the list of domains command

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#3891]
## Why?

This task allows to get used to Feign library, then implement Get list domains command for james-cli.

## How?

* Write subcommand ***domain*** and its subcommand ***list*** in Picocli - which call a Feign interface

* Write a Feign interface which has a method request ***GET list domains*** from James server

## Definition of Done

- [x] This ```./james-cli --url "anURL" domain list``` shows the domains list

- [x] Unit test for domain list command

**Comment by chibenwa** [comment]
I believe the command should be `./james-cli domain list` only first

We will add the --url and --port options later, in the meantime we can live with hard coded url and ports

BTW default webadmin port is 8000

**Comment by quantranhong1999** [comment]
> We will add the --url and --port options later, in the meantime we can live with hard coded url and ports
I think i can handle that two options simply. Should i do it now (in this task)?

**Comment by chibenwa** [comment]
> I think i can handle that two options simply. Should i do it now (in this task)?

If you want ;-)
