### ISSUE TITLE
Bug > Attached image is lossy on the recipient's side

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3896]
# Precondition
Attachment is the images captured by the phone.

# Actual Result
Sending 2 images as attachments on Mobile, on the recipient's side, one of them displays lossy.
![screenshot_38](https://user-images.githubusercontent.com/69950655/95813838-fab37680-0d42-11eb-86f0-deda33f5c13c.png)

.eml file: [Mobile(1).zip](https://github.com/linagora/james-project/files/5368899/Mobile.1.zip)

# Expected Result
Please investigate. The cause might be the way we decode the attachment file. 

# Environment
DEV environment
iPhone X - ios 14

**Comment by chibenwa** [comment]
Please share:

 - The EML of the message you sent
 - The EML of the message you received

Describe clearly which clients you used.

**Comment by tlle14** [comment]
@chibenwa 

**Sender side:** 
iPhone X - Safari
[sent_email.zip](https://github.com/linagora/james-project/files/5370923/sent_email.zip)

**Receiver side**
Desktop Ubuntu - Gmail, OpenPaas
[receive_email.zip](https://github.com/linagora/james-project/files/5370927/receive_email.zip)

**Comment by chibenwa** [comment]
Why are the file names different in the 2 EMLs?

**Comment by tlle14** [comment]
> Why are the file names different in the 2 EMLs?

Don't worry, I changed the name

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/370 likely fixes this.

**Comment by tlle14** [comment]
> [apache#370](https://github.com/apache/james-project/pull/370) likely fixes this.

Bravo, did you merge it? Tell me if this issue is ready to be tested.

**Comment by chibenwa** [comment]
> Bravo, did you merge it? 

Not yet, it might have impacts...

> Tell me if this issue is ready to be tested.

:+1: of course, I will put the QA needed label.

Also according to the tests I run locally this happens 1/100 for 10MB+ attachments. (Good luck with testing!)

**Comment by chibenwa** [comment]
Can we retest?

**Comment by tlle14** [comment]
> Can we retest?

Sureeeeeee. In which environment? @chibenwa

**Comment by chibenwa** [comment]
Prod?

**Comment by tlle14** [comment]
Retest pass on Linagora Production.
Thank @chibenwa 
![image](https://user-images.githubusercontent.com/69950655/141431181-bd5d0e71-5d62-4089-94b1-f6ea2192afea.png)
