### ISSUE TITLE
A problem after performance test,could you help me?

### ISSUE THREAD

**Issue by panglei1984** [linagora/james-project#3898]
When I finish a performance test, I found that after running the performance, a small number of e-mails (dozens of them) could not be sent out. 
After positioning, it is found that in the JamesMailSpooler class, no messages enter the handleOnQueueItem method subscribed to by Flux, and the messages files are all overstocked in the var/store/ActiveMQ/blob-transfer directory.When I send more emails, the backlog of message files will be consumed and the corresponding email will be received. 
But there is always a backlog in the var/store/ActiveMQ/blob-transfer directory.
james-server-app-3.4.0/var/store/activemq/#  find ./ -name 'ID_host*' | wc -l
311
Could you tell me what's the problem,how to solve it? I'm using James Version 3.4.0.
Thank you very much

**Comment by chibenwa** [comment]
Hello,

Which version of James are you running?

Anything suspicious in the logs?

**Comment by panglei1984** [comment]
Version 3.4.0.I did not find suspicious.(log level is warn)

**Comment by chibenwa** [comment]
Have you tried with 3.5.0? (I would recommend the upgrade!)

**Comment by panglei1984** [comment]
OK,I will try it later.
in 3.4.0 ,the run method in JamesMailSpooler class is 
`private void run() {
        LOGGER.info("Queue={}", queue);

        disposable = Flux.from(queue.deQueue())
                .publishOn(spooler)
                .flatMap(this::handleOnQueueItem)
                .onErrorContinue((throwable, item) -> LOGGER.error("Exception processing mail while spooling {}", item, throwable))
                .subscribeOn(Schedulers.elastic(),false)
                .subscribe();
    }
`
I found that in 3.5.0,the method change to 
`private void run() {
        LOGGER.info("Queue={}", queue);
        disposable = Flux.from(queue.deQueue())
            .flatMap(item -> handleOnQueueItem(item).subscribeOn(spooler), parallelismLevel)
            .onErrorContinue((throwable, item) -> LOGGER.error("Exception processing mail while spooling {}", item, throwable))
            .subscribeOn(spooler)
            .subscribe();
    }`
queue.deQueue() and handleOnQueueItem use the sam threadpool.
whether you find some problem whit it?

**Comment by chibenwa** [comment]
You did not answer my question: Do you encounter the same issue on 3.5.0 ?

On master branch, I have:

```
    private reactor.core.Disposable run(MailQueue queue) {
        return Flux.from(queue.deQueue())
            .flatMap(item -> handleOnQueueItem(item).subscribeOn(Schedulers.elastic()), concurrencyLevel)
            .onErrorContinue((throwable, item) -> LOGGER.error("Exception processing mail while spooling {}", item, throwable))
            .subscribeOn(Schedulers.elastic())
            .subscribe();
    }
```

With a commit message being:

```
JAMES-3041 Change the way we control resources for Spooler mail processing  

For now, we controlled resources using a bounded threadpool for mail processing. 

However, it makes the concurrency of the dequeuing harder to achieve and doesn't leverage modern tools Reactor brings like explicit control over concurrency for a given Flux.  

With this commit we start using elastic Scheduler everywhere and control resources by specifying concurrency parameter.
```

(the spooler had been murdered!)

Do you encounter the same issue on master?

**Comment by panglei1984** [comment]
You did not answer my question: Do you encounter the same issue on 3.5.0 ?
I will try 3.5.0 version later.then tell you the result..

**Comment by chibenwa** [comment]
Thanks :-)

**Comment by panglei1984** [comment]
> Thanks :-)

I tried 3.5.0 version.It seems no problem.
but JamesMailSpooler consume mail file is slower than product,leading mail files block in path var/store/activemq/blob-transfer.at last out of disk space

**Comment by chibenwa** [comment]
> but JamesMailSpooler consume mail file is slower than product,leading mail files block in path var/store/activemq/blob-transfer.at last out of disk space

I don't understand this sentence...

**Comment by chibenwa** [comment]
> I tried 3.5.0 version.It seems no problem.

I'm glad to hear that!

**Comment by panglei1984** [comment]
> > but JamesMailSpooler consume mail file is slower than product,leading mail files block in path var/store/activemq/blob-transfer.at last out of disk space
> 
> I don't understand this sentence...

When smtp message received,it will be saved in var/store/activemq/blob-transfer by activemq,and then activemq will consume it(flux in JamesMailSpooler class ). In the 3.5.0 version,the rate of consuming is slower than saving.
Do you know how to solved it? I will try to modify thread number in mailetcontainer.xml

**Comment by chibenwa** [comment]
What rates are we speaking of (numbers?)?

**Comment by panglei1984** [comment]
smtp message,numbers of emails

**Comment by chibenwa** [comment]
What are those numbers? (can you share them here in mail/second)
