### ISSUE TITLE
Outbox keeps loading after sending 22 thousand emails by API

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3901]
# Actual Result

I was using Postman to send 22 thousand emails by API. 
Now when I access the Outbox of the Sender, the Outbox keeps loading. 

While sending 22 thousand emails, it got 2 errors from Postman related to the internet connection. 

![image](https://user-images.githubusercontent.com/69950655/95975512-76dfb400-0e40-11eb-825b-fdc5d54b3e6b.png)

# Expected Result
Please investigate if the cause is from our server-side. 

# Environment
DEV environment
Test account: userd on DEV

**Comment by chibenwa** [comment]
Thank you Loan!

That's a GREAT example prooving ElasticSearch is terrible at doing listing ;-)

**Comment by tlle14** [comment]
Hi @chibenwa 
I'm using a new JMAP to query Outbox mailbox, then I see a lot of emails (143 emails) in there. 
Is that the reason why the outbox keeps loading?

**Comment by chibenwa** [comment]
You mean: new JMAP works but old JMAP is brooken ?

**Comment by Arsnael** [comment]
> You mean: new JMAP works but old JMAP is brooken ?

That would be funny :smile:

**Comment by tlle14** [comment]
I mean:
1. Which cause makes 143 emails cannot be sent? While other mails with the same content can.
2. Outbox cannot load 143 emails, is it related to Elastic search? 

I just add more information for you in case it's helpful. @chibenwa

**Comment by chibenwa** [comment]
But there is 22.000 emails that had been deleted. This likely has an impact on ElasticSearch.

`Which cause makes 143 emails cannot be sent?`

 -> We need to go and see DEV logs here. @Arsnael can you plan 5 minutes with Loan to retrieve such logs?

**Comment by tlle14** [comment]
@Arsnael could you take a look at this issue. It still happens on James 16-rc1

**Comment by Arsnael** [comment]
@tlle14 you mean can't load a mailbox with imap when you have 22k mails?

**Comment by chibenwa** [comment]
Can you re-test?

**Comment by chibenwa** [comment]
Linked to the `null` messageId, this had been solved within the openpaas-1.10.0 release
