### ISSUE TITLE
Saving draft: specify html body

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3910]
## Why 

As a user, I want to be able to add a html body to my draft email

## How

Implement the html body part of  [`Email/set create` ](https://jmap.io/spec-mail.html#emailset)

```
[[ "Email/set", {
  "accountId": "ue150411c",
  "create": {
    "k192": {
      "mailboxIds": {
        "2ea1ca41b38e": true
      },
      "keywords": {
        "$seen": true,
        "$draft": true
      },
      "from": [{
        "name": "Joe Bloggs",
        "email": "joe@example.com"
      }],
      "subject": "World domination",
      "receivedAt": "2018-07-10T01:03:11Z",
      "sentAt": "2018-07-10T11:03:11+10:00",
      "htmlBody": [
        {
          "partId": "a49d",
          "type": "text/html"
        }
      ],
      "bodyValues": {
        "a49d": {
          "value": "<!DOCTYPE html><html><head><title></title>
            <style type=\"text/css\">div{font-size:16px}</style></head>
            <body><div>I have the most <b>brilliant</b> plan. Let me
            tell you all about it. What we do is, we</div></body>
            </html>",
          "isTruncated": false
        }
      }
    }
  }
}, "0" ]]
```

Note: 
* we don't implement the body text for now, only the html part
* `bodyStructure` is too complex, we only implement with `htmlBody` for now

Restrictions:
* htmlBody MUST contain exactly one body part and it MUST be of type text/html.
* Within an EmailBodyPart:
   * The charset property MUST be omitted if a partId is given (the part’s content is included in bodyValues, and the server may choose any appropriate encoding).
   * The size property MUST be omitted if a partId is given. 
   * A Content-Transfer-Encoding header field MUST NOT be given.
* Within an EmailBodyValue object, isEncodingProblem and isTruncated MUST be either false or omitted.

## Definition of Done 

Write integration tests about email creation with html body and error handlings

**Comment by chibenwa** [comment]
:-1:  don't specify bodyStructure, it is too complex.

Let's support `htmlBody` (single body) instead.

Can you rework the ticket accordingly?

**Comment by Arsnael** [comment]
Done

**Comment by chibenwa** [comment]
`htmlBody: EmailBodyPart[]` -> you got the wrong type.

We need to handle the following EmailBodyPart properties:

 - **charset** => overwize we will have encoding issues.

**Comment by chibenwa** [comment]
Say that we for now not support passing more than one EmailBodyPart in the htmlBody ?

**Comment by Arsnael** [comment]
> Say that we for now not support passing more than one EmailBodyPart in the htmlBody ?

that's in the specs, the thing I added in restrictions is directly copied from them:
`htmlBody MUST contain exactly one body part and it MUST be of type text/html.`

**Comment by Arsnael** [comment]
>     * **charset** => overwize we will have encoding issues.

From the specs too, copied:
```
The charset property MUST be omitted if a partId is given (the part’s content is included in bodyValues, and the server may choose any appropriate encoding).
```
