### ISSUE TITLE
Implement MDN/send

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3913]
### Objective

Message Disposition Notifications (MDNs) are used as "read receipts", "acknowledgements", or "receipt notifications". When receiving an email message, an MDN can be sent to the sender via the MDN/send method.

### How

The MDN/send method uses an MDN object defined in https://tools.ietf.org/html/draft-ietf-jmap-mdn-15.
When calling this method the "using" property of the Request object MUST contain the capabilities `urn:ietf:params:jmap:mdn` and 
`urn:ietf:params:jmap:mail`

### Example

**Request**
```
[[ "MDN/send", {
  "accountId": "ue150411c",
  "identityId": "I64588216",
  "send": {
    "k1546": {
      "forEmailId": "Md45b47b4877521042cec0938",
      "subject": "Read receipt for: World domination",
      "textBody": "This receipt shows that the email has been displayed on your recipient's computer. ",
      "reportingUA": "joes-pc.cs.example.com; Foomail 97.1",
      "disposition": {
        "actionMode": "manual-action",
        "sendingMode": "mdn-sent-manually",
        "type": "displayed"
      },
      "extension": {
        "X-EXTENSION-EXAMPLE": "example.com"
      }
    }
  },
  "onSuccessUpdateEmail": {
    "#k1546": {
      "keywords/$mdnsent": true
    }
  }
}, "0" ]]
```
**Response**
```
[[ "MDN/send", {
  "accountId": "ue150411c",
  "sent": {
    "k1546": {
      "finalRecipient": "rfc822; john@example.com",
      "originalMessageId": "<199509192301.23456@example.org>"
    }
  }
}, "0" ],
[ "Email/set", {
  "accountId": "ue150411c",
  "oldState": "23",
  "newState": "42",
  "updated": {
    "Md45b47b4877521042cec0938": {}
  }
}, "0" ]]
```

### DoD

Write integration test to show that a request to MDN/Send method will update the corresponding email object.
Write integration test to show that request without the `urn:ietf:params:jmap:mdn` capability is rejected.
Write integration test to show that a MDN request to update an email which has the `mdnsent` keyword already set will return an `mdnAlreadySent` error.

Specification https://www.rfc-editor.org/info/rfc9007

**Comment by chibenwa** [comment]
```
   o  originalRecipient: "String|null" (server-set) Original recipient
      address as specified by the sender of the message for which the
      MDN is being issued.
```

The spec needs to tell message ids are specified without `<...>` just like in the regular JMAP spec, no?

cc @rouazana 

```
   o  sent: "Id[MDN]|null" A map of creation id to MDN containing any
      properties that were not set by the client.  This includes any
      properties that were omitted by the client and thus set to a
      default by the server.
```

Can we clearly details which field is optional ? Server set?

Can we mandate all of the properties not being `| Null` ?

As such I don't believe **finalRecipient** should be server-set

**Comment by chibenwa** [comment]
> Write integration test to show that a MDN request to update an email which has the mdnsent keyword already set will return an mdnAlreadySent error.

I'm unsure about this one.

Maybe that's a client responsibility, no?

**Comment by rouazana** [comment]
> As such I don't believe finalRecipient should be server-set

See this discussion for the reason: https://mailarchive.ietf.org/arch/msg/jmap/HqHHzYEU4APymjehgVKXE3eIAg4/

**Comment by chibenwa** [comment]
JIRA ticket https://issues.apache.org/jira/browse/JAMES-3520

**Comment by vttranlina** [comment]
I don't see a define of `PatchObject` property `(onSuccessUpdateEmail: Id[PatchObject])` in RFC 9007. 
How can I find it?

**Comment by chibenwa** [comment]
I think we can handle `onSuccessUpdateEmail` in a following pull request.

Also, we have very similar logic for `EmailSubmission/set create` you should have a look there to get a better understanding.
