### ISSUE TITLE
Download: Attachment

### ISSUE THREAD

**Issue by nvduc91** [linagora/james-project#3923]
### Why?
User want to download his attachment.

### How?
**Request**
To download a file, the client makes an authenticated GET request to the download URL - MUST contain variables called `accountId`, `blobId`, `type`, and `name` -  with the appropriate variables substituted in:

-     accountId: The id of the account to which the record with the blobId belongs.
-     blobId: The blobId representing the data of the file to download.
-     type: The type for the server to set in the Content-Type header of the response; the blobId only represents the binary data and does not have a content-type innately associated with it.
-     name: The name for the file; the server MUST return this as the filename if it sets a Content-Disposition header.

Sample: `http://jmap.example.com/download/{accountId}/{blobId}/?type={type}&name={name}

**Response**
As the data for a particular blobId is immutable, and thus the response in the generated download URL is too, implementors are recommended to set long cache times and use the “immutable” Cache-Control extension **[@?RFC8246]** for successful responses
For example: **Cache-Control: private, immutable, max-age=31536000**

When an HTTP error response is returned to the client, the server SHOULD return a JSON “problem details” object as the response body, as per [@!RFC7807].

### DOD
```
Given bob already uploaded files on his account.
Then bob can download the same file within a timely manner (`max-age=31536000`).
```
Also write integration test for it.

**Comment by chibenwa** [comment]
This is already implemented or covered as part of https://github.com/linagora/james-project/issues/3923 . 

Shall we close this?

**Comment by nvduc91** [comment]
I agree
