### ISSUE TITLE
Lucene Index file synchronization problem while using cluster servers

### ISSUE THREAD

**Issue by gallyj** [linagora/james-project#3924]
when  I use IMAP client on a cellphone,I find that  the client will send SEARCH command , then  server  will find mail data in database using lucene index file.
But I am using  a cluster servers system. The mail may send to one server from client and generate local lucene index file in this server . When I want to fetch mail  at  IMAP client , it may fetch from another server and there not exits that local lucene index file .Therefore I can't get all mail  at  IMAP client .

Besides, when I  open the socketTLS smtp services at server, the port 25 can't normally work.  The server can‘t connect to NO SSL client and receive mail from other mail server . 

I wonder How to solve the two problems.
Thanks.

**Comment by chibenwa** [comment]
Can you share your smtpserver.xml file?

**Comment by gallyj** [comment]
Thanks for your reply.
I  studied the ElasticSearch backend but I see the ElasticSearch doesn't suit our spring frame。
I wonder if  i can use JPA to fetch mail  with mailbox_id and uid_id from database directly .It seems will take more time compared with using lucene backend. 

Besides , I upload my smtpserver.xml as an attatchment.  I am gradeful for helping to check if there are errors.
Thanks.

[smtpserver.zip](https://github.com/linagora/james-project/files/5415455/smtpserver.zip)

**Comment by chibenwa** [comment]
You cannot use lucene in a multi-james set up.

You need to rely on the Distributed Server designed to solve these issues, it is not an easy problem. And yes you need extra databases.

I will have a look to your smtpserver.xml tomorrow (cant open zips on my phone)

**Comment by chibenwa** [comment]
Use 2 smtpServer block, mandate SSL usage on port 465, but do not mandate it on port 25.
