### ISSUE TITLE
Cannot query the specified email by minSize

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3929]
# Actual Result

On DEV platform, I cannot query the specified email using Filter (inMailbox, before, after, minSize, maxSize)
There're 9 emails that should be returned but the query only returns 8. 

Body:
```
{
    "using": [
        "urn:ietf:params:jmap:core",
        "urn:ietf:params:jmap:mail",
        "urn:apache:james:params:jmap:mail:shares"
    ],
    "methodCalls": [
        [
            "Email/query",
            {
                "accountId": "{{accountId}}",
                "position": 0,
                "limit": null,
                "calculateTotal": true,
                "filter":{
                    "inMailbox":"fb91e0b0-f99b-11ea-a22e-c3be5d3f6311",
                    "before": "2020-10-21T00:00:00Z",
                    "after": "2020-09-09T00:00:00Z",
                    "minSize": 1200,
                    "maxSize": 1400
                }
            },
            "c1"
        ]
    ]
}
```

The missing email: 
[Fwd_ Re_ with local copy.zip](https://github.com/linagora/james-project/files/5407056/Fwd_.Re_.with.local.copy.zip)

# Expected Result
The query should return all the emails matching the condition.

# Environment
- DEV platform: userd
- The missing email id: 28becfc0-0c76-11eb-9ca0-0fd9c18bb02b

**Comment by chibenwa** [comment]
Can you post the result of an `Email/get` on the missing email?

**Comment by chibenwa** [comment]
Opening  the file on my computer and looking at file properties: 1,2 ko (1 193 octets)

It's expected not to be returned :-)

**Comment by tlle14** [comment]
Thank you. So this is not an issue.
