### ISSUE TITLE
Bug> JMAP is applying keywords has the first character in uppercase ($Flagged vs. $flagged)

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3931]
# Actual Result
Our JMAP allows filter by keyword to have the first character capitalized instead of the all-lowercase keyword.

![image](https://user-images.githubusercontent.com/69950655/96670678-24475000-138a-11eb-9794-0a03b577585e.png)
![image](https://user-images.githubusercontent.com/69950655/96670693-332e0280-138a-11eb-8e75-73b25401a667.png)

# Expected Result
Let's discuss this.
We should make our keyword to be the lowercase keywords.
![image](https://user-images.githubusercontent.com/69950655/96686051-3801af00-13a8-11eb-86e7-cec2a29421f2.png)

# Environment
DEV environment

**Comment by Arsnael** [comment]
You are right on this, thanks for the report :)
