### ISSUE TITLE
Filters: support wildcards

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#3937]
As a user, I want to tell my filter to match:

* Any mail from a domain ( *@acme.com )
* Any mail from a sender (notifications@*)
* Any mail that matches part of a sender (notif*@*)

**DoD**

Write integration tests on filters with wilcards

Reference: https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/133

**Comment by chibenwa** [comment]
:-1: for wildcard (REGEX) support.

James offers a CONTAINS operator fitting that use case.

It is not implemented in INBOX frontend. I suggest we rather use that. cc @MichaelBailly 

BTW you miss the reference to the original INBOX ticket.

**Comment by Arsnael** [comment]
If we have a contains operator then yes sure no need to reimplement the wheel
