### ISSUE TITLE
JMAP Filters: support multiple addresses on one filter

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#3938]
As a user, when I create a new filter, I want to set more than one email address in a filter

**DoD**

Write an integration with the use of multiple email addresses in a filter

Reference: https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/134

**Comment by chibenwa** [comment]
Can you please provide sample JMAP requests for this?

**Comment by chibenwa** [comment]
You expect a logical OR  right?

What prevents today the frontend to display a selector with several addresses create several rules, each one for one address?

Is it worth a change of format? 

Cc @MichaelBailly 

BTW you miss a reference to the upstream ticket.

**Comment by fabienmoyon** [comment]
@chibenwa yes a OR condition

> What prevents today the frontend to display a selector with several addresses create several rules, each one for one address?

In [jmap-client filters](https://github.com/linagora/jmap-client/commit/85e801090a44fcc8c5688d86a65c759436217933#diff-698e4a86a5df593dec1d6f6bf5634f8581921b0b0dab05702d2bf250ae57e3daR25) value is a string so in the backend what do you support ? Do we need to split value by a `,` or value must be a table ?

**Comment by chibenwa** [comment]
I mean the behaviour you want can be done by creating one filter per address.

Though I understand this might not be convenient and you would prefer something that looks like a JSON array.

**Comment by fabienmoyon** [comment]
Yes exactly of course but the able to add multiple address for the same condition is a better UX

**Comment by chibenwa** [comment]
Agree and coma separated also means we can easily have a retro-compatible format...

**Comment by chibenwa** [comment]
See EPIC https://github.com/linagora/james-project/issues/4568
