### ISSUE TITLE
Add a warmup for the stress tests

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#3962]
Gatling performance tests are being not accurate when you start them on a fresh James deployment, as Cassandra takes some time to warm up.

It is necessary to add some warm up in the stress test file before launching the real simulation.

A solution could be to add a warm up section in the stress test file and play the same performance test, on a shorter duration. An environment parameter for duration of a scenario could be added, that would be set up for the warm up (like 5 minutes), and omitted for the real simulation (to keep the one by default)

**DoD**
Performance tests on the bench with valid visible warm up before the actual scenario, leading to better results on the real run

**Comment by chibenwa** [comment]
![Capture d’écran de 2020-10-27 11-54-25](https://user-images.githubusercontent.com/6928740/97258572-3e31d880-184b-11eb-8ff8-5050d28a4dc8.png)

This screenshot illustrate the issue
