### ISSUE TITLE
Bug > Thunderbird > cannot save draft with emails has attachments

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3965]
# Actual Result
Cannot save drafts on Thunderbird when the email has attachments 

![image](https://user-images.githubusercontent.com/69950655/97269300-e2257f00-185f-11eb-885c-0b13d9283f34.png)

# Expected Result
It should be able to save drafts for email has attachments

# Environment
DEV platform
James openpaas-1.7.16-rc1

**Comment by chibenwa** [comment]
Do we have logs regarding this?

**Comment by chibenwa** [comment]
(cc @Arsnael  ? )

@tlle14 does it happen on PROD too?

**Comment by chibenwa** [comment]
@tlle14 we made some configuration changes (same as prod). Can you re-test this?

**Comment by tlle14** [comment]
The same issue happens after fix @chibenwa

**Comment by chibenwa** [comment]
Misconfiguration from René: He modified IMAP 993 but not IMAP 143.

Correcting the conf. Stay tuned.

**Comment by tlle14** [comment]
This configuration issue has been fixed:
![image](https://user-images.githubusercontent.com/69950655/97549873-83990600-1a03-11eb-87c4-4bfab3a377d7.png)
