### ISSUE TITLE
Bug > Thunderbird > The mailbox created on Thunderbird has incorrect order on OpenPaas

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3966]
# Precondition
A new folder has been created on Thunderbird

# Actual Result
After synchronizing to OpenPaas, the mailbox is at the incorrect order.
![image](https://user-images.githubusercontent.com/69950655/97272107-071bf100-1864-11eb-983a-8a874d5ec4ac.png)

# Expected Result
The mailboxes have the same sortOrder should be sorted by alphabetical order

**Comment by chibenwa** [comment]
That looks more like an INBOX issue, no?

**Comment by chibenwa** [comment]
Does a ctrl+f5 solves this?

**Comment by tlle14** [comment]
> That looks more like an INBOX issue, no?

@MichaelBailly could you please confirm? If yes, I should move it to Inbox board. 

@chibenwa I've refreshed the inbox.

**Comment by chibenwa** [comment]
James have no sortOrder storage, there should be no differences between IMAP creating a mailbox and JMAP...

**Comment by tlle14** [comment]
@chibenwa you're right. This should be a frontend's issue.

**Comment by chibenwa** [comment]
Wooohooo :-)
