### ISSUE TITLE
Bug > The mailbox created on Thunderbird has incorrect order on OpenPaas

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3967]
# Precondition
A new folder has been created on Thunderbird

# Actual Result
After synchronizing to OpenPaas, the mailbox is at the incorrect order.
![image](https://user-images.githubusercontent.com/69950655/97272107-071bf100-1864-11eb-983a-8a874d5ec4ac.png)

# Expected Result
The mailboxes have the same sortOrder should be sorted by alphabetical order

# Environment
DEV environment
openpaas-1.7.16-rc1

**Comment by chibenwa** [comment]
how does it differ from https://github.com/linagora/james-project/issues/3966 ?

**Comment by tlle14** [comment]
> how does it differ from #3966 ?

This is duplicated when I was creating the issue on Github. Closed!
