### ISSUE TITLE
Bug > Thunderbird > Sending email with attachments is quite slow 

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3968]
# Actual Result
This seems a performance issue. When sending an email with attachments (<10Mb), it takes quite a long time to finish. 
The evidence is a gif file so the speed is faster than actual.
![Peek 2020-10-27 15-41](https://user-images.githubusercontent.com/69950655/97279138-2bc89680-186d-11eb-9f5e-fb6d8deeda8e.gif)

The sent email has been duplicated:
![image](https://user-images.githubusercontent.com/69950655/97279052-0e93c800-186d-11eb-9f0d-5b20f8785401.png)

[thunderbird test attachment.zip](https://github.com/linagora/james-project/files/5444102/thunderbird.test.attachment.zip)

# Expected Result
Please investigate the cause. The attachments are not too heavy so our system should process faster. 

# Environment
DEV platform
openpaas-1.7.16-rc1

**Comment by chibenwa** [comment]
OVH experiences networking issues.

Not to mention marine cable leading to slow network in vietnam.

Not an issue
