### ISSUE TITLE
Bug > Thunderbird > It allows to execute scripts contains in mailbox name

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3969]
# Actual Result
Thunderbird cannot retrieve the mailbox that has scripts in the name:
![image](https://user-images.githubusercontent.com/69950655/97287398-1f493b80-1877-11eb-9b5b-19f01c908fbe.png)

# Expected Result
Scripts shouldn't be executed in the mailbox name

# Envỉonment
DEV platform
openpaas-1.7.16-rc1

**Comment by chibenwa** [comment]
This is a thunderbird bug, please report it on the Thunderbird bug tracker...

**Comment by chibenwa** [comment]
This is low, as it is the user itself which creates the mailbox name.

Please also confirm this happens on previous releases.

**Comment by tlle14** [comment]
It also happens on Production
This issue is a security concern. So I label it as high
![image](https://user-images.githubusercontent.com/69950655/97292030-4c98e800-187d-11eb-8039-fd64b81a34e1.png)

**Comment by chibenwa** [comment]
Please open a bug on thunderbird bug tracker.

It **needs** to be reported upstream.

**Comment by chibenwa** [comment]
HTML styling is a not a script btw 

```
<script>alert("PWND")</script>
```

Being executed would be more worrying to me IMO
