### ISSUE TITLE
about random ports

### ISSUE THREAD

**Issue by panglei1984** [linagora/james-project#3978]
Excuse me, except one random port in embedded ActiveMQ, I found that James also has two random ports. Could you tell me where it is set and what is its function. thank you very much

**Comment by chibenwa** [comment]
Hello,

No idea at first but they are likely related to JMX

See https://stackoverflow.com/questions/20884353/why-java-opens-3-ports-when-jmx-is-configured

**Comment by panglei1984** [comment]
thank you. BTW,how can JMX be shut down in James, the service on port 9999.
I want to try whether the random ports are opened by it

**Comment by chibenwa** [comment]
jmx.properties for guice packaged servers have a `enabled` property that can be turned to false.

This can not be disactivated with Spring.

**Comment by panglei1984** [comment]
OK,thanks.
Maybe comment the ‘serverconnector’ and ‘registry’ bean in spring-server.xml ,will turn off it.I try it:)

**Comment by panglei1984** [comment]
> jmx.properties for guice packaged servers have a `enabled` property that can be turned to false.
> 
> This can not be disactivated with Spring.

I stop jmx server, one random port display.But there is still one random port.Could you know what is it probably..

**Comment by panglei1984** [comment]
I know it.the another port is set by -Dcom.sun.management.jmxremote.
thanks
