### ISSUE TITLE
Bug  > Thunderbird > No email in the local when enable forwarding with local copy on OpenPaas

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3981]
# Precondition
Enable forwarding mail with local copy on OpenPaas
![image](https://user-images.githubusercontent.com/69950655/97667696-0d53dc80-1ab3-11eb-929e-96fd7a6f99fd.png)

# Actual Result
When sending an email from Thunderbird, the main user (local)  cannot receive the email, while the forwarded user can.
![image](https://user-images.githubusercontent.com/69950655/97667948-92d78c80-1ab3-11eb-83a0-1139647c0722.png)

**Local user:**
![image](https://user-images.githubusercontent.com/69950655/97667900-7b000880-1ab3-11eb-9dff-c9b640df09c2.png)

**Forwarded user:**
![image](https://user-images.githubusercontent.com/69950655/97668002-ad116a80-1ab3-11eb-910f-bf1430729609.png)

# Expected Result
Please confirm this issue. 
Email sent from Thunderbird should be kept a local copy

# Environment
DEV Environment
openpaas-1.7.16-rc1

**Comment by chibenwa** [comment]
Does it happens on openpaas.linagora.com ?

**Comment by tlle14** [comment]
> Does it happens on openpaas.linagora.com ?

Production now disables the Forwarding function.

**Comment by chibenwa** [comment]
That's then unrelated to the 1.7.16 release.

**Comment by chibenwa** [comment]
Does the bug also happen when sending a mail from JMAP ?

**Comment by tlle14** [comment]
> Does the bug also happen when sending a mail from JMAP ?

No, it doesn't. JMAP can send an email to external domain

**Comment by chibenwa** [comment]
We check the forward are well set on the JAMES server...

https://github.com/linagora/james-project/pull/3984 shows that it works. I'm confused.

**Comment by tlle14** [comment]
This is an invalid bug because of the configuration for linagora.com on DEV
