### ISSUE TITLE
Bug > Cannot update a parent folder to be a child of another 

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3988]
# Precondition
There're Folder 1, 2 and 3
- Folder 1 is sole
- Folder 2 has a child is Folder 3

# Actual Result
Cannot update folder 2 to be a child of folder 1. Please see the log related to JMAP
![image](https://user-images.githubusercontent.com/69950655/97851678-3e891280-1d28-11eb-8c42-f4b850c2297a.png)

On DEV:
![image](https://user-images.githubusercontent.com/69950655/97860650-17850d80-1d35-11eb-930a-67bd857c1c2d.png)

# Expected Result
It should be able to update folder 2 is a child of folder 1

# Environment
Production

**Comment by chibenwa** [comment]
This behaviour is the behaviour implemented in JMAP draft, we implemented it to in JMAP RFC-8621.

Production relies on Draft for inbox display, your JMAP queries on JMAP RFC-8621.

Maybe we can ask @MichaelBailly point of view but given that this behaviour exists for years, we can likely consider its impact as low.

Anyway, that's a good catch!

**Comment by tlle14** [comment]
Hi @chibenwa 

I don't see RFC-8621 mention updating the mailbox with a child. Only for destroying:
![image](https://user-images.githubusercontent.com/69950655/97945251-8e63ea00-1db9-11eb-900e-793d3b70217a.png)

**Comment by chibenwa** [comment]
Hi @tlle14 I know the spec says `We should handle this`.

However not supporting parentId updates to mailbox having childs is an implementation strategy we chose a long time ago.

Maybe the time has come to re-challenge it. Maybe not. Let's discuss if this is an acceptable behaviour or not.

**Comment by chibenwa** [comment]
Another simple way to allow this would be to check upon update, that no loop is created.

This can be done by checking that the parentId is not one of the childs of the mailbox we are moving (that's the condition creating the loop)

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project/pull/3993 fixes this for JMAP RFC-8621

Please note that fixing this for Draft (and thus OpenPaaS on production) is out of scope.

**Comment by chibenwa** [comment]
As reported by @rouazana , the simple strategy for avoiding loops I proposed is not safe in the face of concurrency.

That's likely why several years ago we decided to prevent this kind of updates.

We have no way to prevent that in a concurrent environment we never create a loop.

Staying 100% safe means relying on today code: always reject the update.

**Comment by tlle14** [comment]
Thank @chibenwa for your confirmation.  
I should close this ticket as an expected behavior
CC: @rouazana

**Comment by chibenwa** [comment]
I'm working on this, rechallenging the existing behaviour.

**Comment by tlle14** [comment]
> I'm working on this, rechallenging the existing behaviour.

That's great! Sorry for the misunderstanding.

**Comment by chibenwa** [comment]
Actually with very minimal changes the impact of a data race upon parentId update is very low - and we might very well live with it.

I added tests regarding this.

**Comment by tlle14** [comment]
I can update the mailbox parent by JMAP API, but it doesn't success on OpenPaas front-end. It returns error log on console:

**Comment by tlle14** [comment]
Because the frontend is not yet updated the new JMAP. 
=> Retest pass for new JMAP:
![image](https://user-images.githubusercontent.com/69950655/99023993-566a5d00-2598-11eb-87e1-1354e4b0efcc.png)
