### ISSUE TITLE
Bug > Email/get > Doesn't return default properties when omitting "properties" in the request

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3994]
# Actual Result
When omitting `properties` in the request, response returns only `id` and `size`
![image](https://user-images.githubusercontent.com/69950655/97964035-b15ac200-1dea-11eb-8014-bc058d8750bb.png)

# Expected Result
Please confirm this issue. 
When `properties` is omitted or null, it should return the default properties as defined in the JMAP spec
![image](https://user-images.githubusercontent.com/69950655/97964523-7b6a0d80-1deb-11eb-9f5e-ab9905e5547f.png)

# Environment
DEV environment

**Comment by chibenwa** [comment]
Right, we forgot to put back default properties. Well spotted.

**Comment by tlle14** [comment]
Retest pass:
When  "properties": null
![image](https://user-images.githubusercontent.com/69950655/98508759-a09ac800-2292-11eb-9e6c-950b7f24caaa.png)

When omitting "properties":
![image](https://user-images.githubusercontent.com/69950655/98509187-549c5300-2293-11eb-9c16-3fd4dfe79680.png)

**Comment by tlle14** [comment]
Hi @chibenwa 

When ` "properties": [] ` (an empty array), it returns only id. 
![image](https://user-images.githubusercontent.com/69950655/98511259-0db05c80-2297-11eb-967a-896849a0c68c.png)

Even we don't have the requirement for this case but I want to confirm if this behavior is as expected?

**Comment by Arsnael** [comment]
@tlle14 : It is expected. Empty array means that you don't want to return any properties. But by default, `id` is always returned even when not specified

**Comment by tlle14** [comment]
Thank you @Arsnael
