### ISSUE TITLE
Bug > Email/get > It doesn't get the last specified header item when not using :all suffix

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#3998]
# Actual Result
I get the email header `DKIM-Signature`, it returns the first item in the array `DKIM-Signature`

![image](https://user-images.githubusercontent.com/69950655/98100358-534ddd80-1ec3-11eb-9d95-8e9e24b71cd1.png)
![image](https://user-images.githubusercontent.com/69950655/98100521-8abc8a00-1ec3-11eb-89ae-c1097ead84d2.png)

# Expected Result
It should return the last item. 
![image](https://user-images.githubusercontent.com/69950655/98099061-af176700-1ec1-11eb-8660-bf6c9bf3f960.png)

# Environment
DEV environment

**Comment by chibenwa** [comment]
Hello Loan,

This is invalid, as of course the header request applies only to the email headers, **not the email body part headers**.

Come & ask me if you need.

**Comment by tlle14** [comment]
> Hello Loan,
> 
> This is invalid, as of course the header request applies only to the email headers, **not the email body part headers**.
> 
> Come & ask me if you need.

I updated the evidence. Could you check it again?

**Comment by chibenwa** [comment]
EML please!

**Comment by tlle14** [comment]
It seems I got the wrong email ID. 
And this issue is invalid because JMAP get the correct last item.
![image](https://user-images.githubusercontent.com/69950655/98103018-f3593600-1ec6-11eb-87b3-cf8916333b38.png)
Sorry for this mistake.
