### ISSUE TITLE
Bug > Email/get > Date (SendAt) property parsed fail returns an empty array

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4006]
# Actual Result

When using parsed type for Date is `Addresses`, it returns the empty array
![image](https://user-images.githubusercontent.com/69950655/98322156-58bd3c00-2019-11eb-8a37-6b03e1c53096.png)

# Expected Result
It should return null for failed parse
Please confirm this behavior. 
![image](https://user-images.githubusercontent.com/69950655/98322511-252ee180-201a-11eb-8da9-1253da2d9ae8.png)

# Environment 
DEV environment

**Comment by chibenwa** [comment]
No the typye is `EmailAddress[]` not `EmailAddress[] | null`

Given that the format is not an address header, there is no addresses in it, thus the empty array makes sense.

This behaviour is likely correct ;-)

(But thanks for raising the discussion!)

**Comment by tlle14** [comment]
Thank you @chibenwa
