### ISSUE TITLE
james-cli Create a user command

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4011]
## Why?

People need to use the CLI to create a new user . This task will implement that need.

## How?

* Write a ***PUT*** method in UserClient interface which send a PUT request to James Webadmin 

* Write class ***UserCreateCommand*** in cli/user - which is a subcommand of UserCommand, and call UserClient interface to create a new user

## Definition of Done

- [ ] This ```./james-cli --url "anURL" user create <username> <password>``` add a new user successfully.

- [ ] Unit test for user create command

**Comment by chibenwa** [comment]
Maybe now we can create a single ticket for all user commands? (and even a single PR?)

**Comment by chibenwa** [comment]
Can we try to not have password in the command line and thus in the history?

I propose:

```
./james-cli --url "anURL" user create <username>
```

It will prompt user to enter the password on the standard input:

```
password:
```

And we never show the user password ;-)

**Comment by rouazana** [comment]
> Can we try to not have password in the command line and thus in the history?

Both should be available.
