### ISSUE TITLE
Bug > Email/get > Returned keywords is not correct

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4014]
# Actual Result
`nonjunk` doesn't seem a keyword
![image](https://user-images.githubusercontent.com/69950655/98624569-b070e580-2340-11eb-82db-338561e42401.png)

# Expected Result
It should be $notjunk

# Environment
DEV environment

**Comment by chibenwa** [comment]
`It should be $notjunk`

Why ?

How were the flags created here? Flags are not forced to start with $...

Also plase note there is difference between `$nonjunk` and `nonjunk`: they are not the same!

And finally https://www.iana.org/assignments/imap-jmap-keywords/imap-jmap-keywords.xhtml defines `$notJunk`, not `$nonJunk`...

**Comment by chibenwa** [comment]
nonjunk is a perfectly valid.

Quote:

```
Users may add arbitrary keywords to an Email. For compatibility with IMAP, a keyword is a case-insensitive string of 1–255 characters in the ASCII subset %x21–%x7e (excludes control chars and space), and it MUST NOT include any of these characters:

  ( ) { ] % * " \
```

If you agree Loan we can close this...

**Comment by tlle14** [comment]
I agree with you that we can create a keyword without starting with $. I logged the issue in case nonjunk is just our test data.
By the way, when the email is marked as nonjunk?

**Comment by chibenwa** [comment]
> By the way, when the email is marked as nonjunk?

I have no idea...

**Comment by tlle14** [comment]
Thank @chibenwa,
So this is not the issue of James. James only read and returns the keyword for request email/get.
