### ISSUE TITLE
JMAP option to resolve relevant draft/RFC-8621 queries against EmailListView

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4022]
Optional for more flexibility.... (Can be turned off)

Email/query & GetMessageList should resolve relevant queries against EmailListView instead of using MailboxManager search methods.

This is limited to: 
 - `inmailbox=xxx sorted by sentAt` akka initial INBOX mailbox listing
 - `inMailbox=xxx sorted by sentAt since yyyy` akka INBOX refreshes

Includes + / - limit & position wich should be filtered on the resulting stream.

**Comment by rouazana** [comment]
> Optional for more flexibility.... (Can be turned off)

This is also for the migration time, no?

**Comment by chibenwa** [comment]
> This is also for the migration time, no?

Yes, and adoption is thus uncorelated with Cassandra schema version.

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/JAMES-3440
