### ISSUE TITLE
Implement CassandraMailboxChangeStore

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4078]
### Objective

Same purpose with the MemoryMailboxChangeStore, we now need to implement it in Cassandra.

### How

1. Define a MailboxChange table with these fields:

- accountId
- state
- created
- updated
- destroyed
- date

2. Implement the CassandraMailboxChangeStore APIs, based on the contract that has already been defined.

### DoD

Write unit tests to show that the MailboxChangeStore is working properly.

JIRA: https://issues.apache.org/jira/browse/JAMES-3462

**Comment by LanKhuat** [comment]
JIRA: https://issues.apache.org/jira/browse/JAMES-3462
