### ISSUE TITLE
james-cli Mailbox commands

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4094]
## Why?

People need to use the CLI to manage mailboxes:

1. Create a mailbox
2. Test a mailbox existence
3. Get mailboxes list
4. Delete a mailbox and its children
5. Delete all mailboxes of a user
6. Reindex a user mailboxes
7. Reindex all users mailboxes
    
This task will implement that need.

## How?

* Write methods in MailboxClient interface which send requests to James Webadmin.

* Write classes in cli/mailbox - which are subcommands of MailboxCommand, and call MailboxClient interface to do the jobs

## Definition of Done

- [x] This ```./james-cli --url "anURL" mailbox create <username> <mailboxName>``` create a mailbox successfully.

- [x] This ```./james-cli --url "anURL" mailbox exist <username> <mailboxName>``` check if a mailbox exists successfully.

- [x] This ```./james-cli --url "anURL" mailbox list <usernameToBeUsed>``` get mailbox list of a user successfully.

- [x] This ```./james-cli --url "anURL" mailbox delete <usernameToBeUsed> <mailboxNameToBeDeleted>```delete a mailbox of a user successfully.

- [x] This ```./james-cli --url "anURL" mailbox deleteAll <usernameToBeUsed>``` delete all mailboxes of a user successfully.

- [x] Unit tests for mailbox commands

**Comment by chibenwa** [comment]
reindex & reindexAll should return the task Id:

`Task xyz created.`
