### ISSUE TITLE
Implement CassandraEmailChangeRepository

### ISSUE THREAD

**Issue by LanKhuat** [linagora/james-project#4120]
### Objective

Same purpose with the MemoryEmailChangeRepository, we now need to implement it in Cassandra.

### How

1. Define a EmailChange table with these fields:

- accountId
- state
- created
- updated
- destroyed
- date

2. Implement the CassandraEmailChangeRepository APIs, based on the contract that has already been defined.

### DoD

Write unit tests to show that the EmailChangeRepository is working properly.

JIRA: https://issues.apache.org/jira/browse/JAMES-3470

**Comment by chibenwa** [comment]
Can we give the primary key + clustering keys + column types of the cassandra table declaration?
