### ISSUE TITLE
MailboxChangeListener needs to handle EmailChange events

### ISSUE THREAD

**Issue by LanKhuat** [linagora/james-project#4121]
### Objective

Update MailboxChangeListener so that it can record events related to Email objects and store them accordingly.

### How

Beside MailboxChangeRepository, MailboxChangeListener should rely also on EmailChangeRepository to store the changes for Email objects.

### DoD

Unit tests to show that MailboxListener can store changes in the EmailChangeRepository properly.

JIRA: https://issues.apache.org/jira/browse/JAMES-3471

**Comment by rouazana** [comment]
Need to have a PR to review
