### ISSUE TITLE
Mailbox/changes should handle delegated mailbox

### ISSUE THREAD

**Issue by LanKhuat** [linagora/james-project#4143]
### Objective

We should be able to store changes for user with access to a delegated mailbox. Also when fetching changes via Mailbox/changes, we should have an extension to decide whether to return "delegated changes" to the user or not.

### How

- Modified the MailboxChangeListener so that when an mailbox event occur, it can record multiple changes for all users who currently having access to that mailbox.
- Add a field to MailboxChange object in order to differentiate between normal/delegated changes.
- Use `Shares` capability to filter out delegated changes.

### DoD

- Unit tests in MailboxChangeRepository, MailboxChangeListener
- Integration tests to show that we can filter out delegated changes.

JIRA: https://issues.apache.org/jira/browse/JAMES-3481

**Comment by chibenwa** [comment]
We need to have a `MailboxChangesRepository::getLatestStateWithDelegation` method, we need to check the sahes capability presence to choose wich method Mailbox/get should use to resolve the state property.

This will be handled in a follow up PR.

**Comment by chibenwa** [comment]
Handled as part of https://github.com/linagora/james-project/pull/4146
