### ISSUE TITLE
Thunderbird > Forwarding a message on Thunderbird generates too much header fields

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4197]
# Precondition
- Using Thunderbird 68
- Sending a message from OpenPaas to Thunderbird 

# Actual Result
On Thunderbird, when forwarding an email sent from OpenPaas, it generates a lot of header fields.
![image](https://user-images.githubusercontent.com/69950655/103630133-d814b080-4f73-11eb-9b24-8f245493e7dd.png)

# Expected Result
The header fields should be less:
![image](https://user-images.githubusercontent.com/69950655/103630450-3f326500-4f74-11eb-88a5-22acee495dbd.png)

**Comment by Arsnael** [comment]
How is that an issue?

**Comment by tlle14** [comment]
> How is that an issue?

While on Thunderbird 78, it doesn't generate that much:
![image](https://user-images.githubusercontent.com/69950655/103634344-84a56100-4f79-11eb-9f75-d1a208009776.png)

**Comment by Arsnael** [comment]
You mean you don't want to see the header fields in the body of the forwarded message? I guess... I don't think it should have the high severity though, it sounds low to me?

**Comment by tlle14** [comment]
> You mean you don't want to see the header fields in the body of the forwarded message? I guess... I don't think it should have a high severity though, it sounds low to me?

I guess user don't want to be freaked out when reading an email like that. It looks suspicious.

**Comment by chibenwa** [comment]
EML please.

I suspect a bad display of some embedded EML.

**Comment by chibenwa** [comment]
And tyhe TB option you used as well.

**Comment by tlle14** [comment]
Hi @chibenwa 
This is the eml 
[Fwd_ fwd to me pleaseeeee.zip](https://github.com/linagora/james-project/files/5790399/Fwd_.fwd.to.me.pleaseeeee.zip)

**Comment by chibenwa** [comment]
Hello Loan.

```
Content-Type: multipart/alternative;
 boundary="------------8F78C4ED2BDFF78446200A41"
Content-Language: en-US

This is a multi-part message in MIME format.
--------------8F78C4ED2BDFF78446200A41
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 7bit

aaa



-------- Forwarded Message --------
Return-Path: 	<qatest1@linagora.com>
Delivered-To: 	tthnguyen@linagora.com
...
```

This is a mail user agent (the sender) concern. The crafted EML includes the full headers as part of the body parts.

This is in no way a James concern.

It's either an OpenPaaS or a TB problem, it's unclear which one as the **steps to reproduce** in your above ticket are really unclear.

**Comment by tlle14** [comment]
> Hello Loan.
> 
> ```
> Content-Type: multipart/alternative;
>  boundary="------------8F78C4ED2BDFF78446200A41"
> Content-Language: en-US
> 
> This is a multi-part message in MIME format.
> --------------8F78C4ED2BDFF78446200A41
> Content-Type: text/plain; charset=utf-8; format=flowed
> Content-Transfer-Encoding: 7bit
> 
> aaa
> 
> 
> 
> -------- Forwarded Message --------
> Return-Path: 	<qatest1@linagora.com>
> Delivered-To: 	tthnguyen@linagora.com
> ...
> ```
> 
> This is a mail user agent (the sender) concern. The crafted EML includes the full headers as part of the body parts.
> 
> This is in no way a James concern.
> 
> It's either an OpenPaaS or a TB problem, it's unclear which one as the **steps to reproduce** in your above ticket are really unclear.

It seems normal on other PCs, happens only on Ha's machine, even they are using the same Thunderbird version. Could you help check when you back?

**Comment by chibenwa** [comment]
> Could you help check when you back?

Sure.

Be sure to have a look at her settings (no idea were though)

**Comment by chibenwa** [comment]
I'm back next monday by the way.
