### ISSUE TITLE
Email create with attachment fails in distributed environment

### ISSUE THREAD

**Issue by LanKhuat** [linagora/james-project#4203]
### Problem

All Email/set create with attachment in distributed environment fail.

### Why

An IllegalStateException is thrown by the StoreAttachmentManager when we try to check the rights on the attachment. Stacktrace shows a blocking call from the method `getOwners` from CassandraAttachmentMapper:

`
return ownerDAO.retrieveOwners(attachmentId).collect(Guavate.toImmutableList()).block();
`

Calling block() when we are inside a reactive chain is likely to be the issue.

### The Fix

Reactify the above mentioned method?

**Comment by chibenwa** [comment]
> Reactify the above mentioned method?

That would be the perfect solution to be honnest.

If you encounter troubles doing so then please just use an elastic scheduler (dirty fix) while waiting to reactify this all.

**Comment by LanKhuat** [comment]
One thing i noticed is this only happened on the master branch (at the time). After EmailSetMethod with oldState & newState was implemented, the issue was gone. May be the problem lies somewhere else.

**Comment by Arsnael** [comment]
Should we still investigate on that or not then?

**Comment by chibenwa** [comment]
I did run the distributed tests (DistributedEmailSetMethodTest) successfully - all of them.

IMO we can close.
