### ISSUE TITLE
Gmail app cannot fetch mails in the mailbox 

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4208]
# Actual Result
I have a folder that cannot fetch emails, while others can on my Production account. 
I've tried to re-login but it wasn't successful
![image](https://user-images.githubusercontent.com/69950655/104268263-0fc8ae80-54c6-11eb-8e49-c9a1922d48de.png)

# Expected Result
Please help to investigate

# Environment
- Production
- Gmail App on iOS 14.3

**Comment by tlle14** [comment]
duplicated

**Comment by chibenwa** [comment]
When you close duplicated issues please always add the link to the other PR.
