### ISSUE TITLE
Gmail App > Cannot fetch mails of a mailbox on Gmail App

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4209]
# Precondition
The mailbox was created on OpenPaas
The mailbox has 2 filters on OpenPaas

# Actual Result
I have a folder that cannot fetch emails, while others can on my Production account. 
I've tried to re-login but it wasn't successful
![image](https://user-images.githubusercontent.com/69950655/104268263-0fc8ae80-54c6-11eb-8e49-c9a1922d48de.png)

# Expected Result
Please help to investigate

# Environment
- Production
- Gmail App on iOS 14.3

**Comment by chibenwa** [comment]
What do you call `filter` ? Is the result different in OpenPaaS? Thunderbird?

**Comment by tlle14** [comment]
> What do you call `filter` ? Is the result different in OpenPaaS? Thunderbird?

I set the filters on OpenPaas. The problem is the mails are stored in that mailbox, but Gmail cannot fetch them

**Comment by chibenwa** [comment]
What is the Gmail app configuration?

**Comment by tlle14** [comment]
Hey @chibenwa 
Suddenly I can see the emails in the mailbox. 
I don't remember if I re-login or not. 
But no more issue for me.
