### ISSUE TITLE
Email/set > It doesn't return error message when defined "headers" in the request

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4210]
# Actual Result
It is able to create a message with `headers` in the request Email/set:
![image](https://user-images.githubusercontent.com/69950655/104304025-6b625e80-54fd-11eb-9e10-fbbdcef2aae3.png)
![image](https://user-images.githubusercontent.com/69950655/104304262-c300ca00-54fd-11eb-8515-7d36525aec63.png)

# Expected Result
Should return the error when defining `headers` in the request Email/set

**Comment by tlle14** [comment]
Hi @LanKhuat @Arsnael is this ticket ready to be retested? If yes, please assign to me for retesting. 
Thank you

**Comment by chibenwa** [comment]
The `headers` property is likely ignored but u\it should be explicitly rejected.

**Comment by Arsnael** [comment]
> The `headers` property is likely ignored but u\it should be explicitly rejected.

No Lan did a PR rejecting that. i merged it this morning. However forgot to put it in QA my bad

**Comment by tlle14** [comment]
Thank team, 
Retest pass on DEV platform

![image](https://user-images.githubusercontent.com/69950655/104574677-e60bb500-5688-11eb-973a-5f6f86723e44.png)
