### ISSUE TITLE
Thunderbird > Cannot send a message to a mailing list created on OpenPaas Admin

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4212]
# Precondition
A mailing list (group mail) is created on OpenPaas Admin

# Actual Result
On Thunderbird, cannot send an email to the mailing list that created on OpenPaas Admin
![image](https://user-images.githubusercontent.com/69950655/104401263-65649000-5586-11eb-836f-412fd93d8560.png)

# Expected Result
It should be able to send an email to the mailing list from Thunderbird

# Environment
Linagora Production

**Comment by tlle14** [comment]
Cc: @MichaelBailly @chibenwa could you clarify which module this issue should belong to?

**Comment by rouazana** [comment]
Hello, on Linagora the master is still OBM regarding alias resolution. So if you want a group to be resolved you have to put it first in OBM. I can explain you in detail the architecture, but this is outside the scope of this ticket.
