### ISSUE TITLE
Email/set > Able to send an email via API using other's email

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4213]
# Precondition
Using userd credential on DEV platform

# Actual Result
It is able to use Email/set API to send an email personates another person's email:
![image](https://user-images.githubusercontent.com/69950655/104405225-035c5880-558f-11eb-851b-84d78af41b87.png)
![image](https://user-images.githubusercontent.com/69950655/104405594-e83e1880-558f-11eb-8824-d4029d2fc579.png)

# Expected Result
Please confirm if this is expected behavior? 
In my opinion, it should validate the email with the recent token.

# Environment
DEV platform

**Comment by Arsnael** [comment]
It is correct. However Email/set creates a mail, it does not send it. When sending it with emailsubmission api, it should check though if the from field is allowed for the sender or not

**Comment by Arsnael** [comment]
https://jmap.io/spec-mail.html#permission-to-send-from-an-address

https://jmap.io/spec-mail.html#email-submission

**Comment by tlle14** [comment]
Thanks, @Arsnael 
So this is not a valid bug and I should close the ticket.

**Comment by tlle14** [comment]
Email submission pass!
![Uploading image.png…]()
