### ISSUE TITLE
Email/set > Incorrectly describe the documentation

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4264]
# Actual Result
Our documentation:

![image](https://user-images.githubusercontent.com/69950655/107199100-8e166300-6a28-11eb-9480-0e1844777236.png)

# Expected Result
Should follow JMAP Implementation guide:
This part should belong to the bullet `Within the EmailBodyPart`

```
The charset property MUST be omitted if a partId is given (the part’s content is included in bodyValues, and the server may choose any appropriate encoding).
The size property MUST be omitted if a partId is given. If a blobId is given, it may be included but is ignored by the server (the size is actually calculated from the blob content itself).
A Content-Transfer-Encoding header field MUST NOT be given.
```

![image](https://user-images.githubusercontent.com/69950655/107199268-ca49c380-6a28-11eb-9745-8fcda4f2f12d.png)

**Comment by chibenwa** [comment]
Sorry can you give more details here? What is wrong according to you?

**Comment by tlle14** [comment]
Hi @chibenwa 

I mean the green part currently is the black bullets as if it is separated from the point `Within an EmailBodyPart`.  
They should be in the white bullets as they belong to the points of `Within an EmailBodyPart`. 

![image](https://user-images.githubusercontent.com/69950655/107201155-33cad180-6a2b-11eb-9e43-ad73369a9a73.png)

**Comment by chibenwa** [comment]
ok

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project/pull/4265 fixes it
