### ISSUE TITLE
Email/set > Incorrect describe the body type in the error message when using Content-Transfer-Encoding

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4268]
# Actual result
Error message returns incorrect body type
![image](https://user-images.githubusercontent.com/69950655/107207817-57921580-6a33-11eb-812b-6a8617900fa4.png)

# Expected Result
Should return the corresponding body type in the error message

**Comment by chibenwa** [comment]
Handled in https://github.com/apache/james-project/pull/301
