### ISSUE TITLE
Email/set > Cannot expose Forwarded flag on the front-end when created an email has the keyword

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4270]
# Precondition
Created an email by using new JMAP that has "$forwarded": true
![image](https://user-images.githubusercontent.com/69950655/107312475-1c3f2780-6ac3-11eb-9a5e-0f7a7ed4e931.png)

![image](https://user-images.githubusercontent.com/69950655/107312623-69bb9480-6ac3-11eb-9593-1312ebce7541.png)

# Actual Result
The forwarded flag doesn't display for the email on the front-end
![image](https://user-images.githubusercontent.com/69950655/107312557-4abd0280-6ac3-11eb-80f6-213098812267.png)

# Expected Result
Please work with the front-end team to accept the new JMAP implementation.
The forwarded flag should display for the email.

**Comment by chibenwa** [comment]
In `MessageMetadataView` line 159

```
    public boolean isIsForwarded() {
        return keywords.contains(Keyword.FORWARDED);
    }
```

That contains needs to be case insentive for the test to work ;-)

**Comment by chibenwa** [comment]
Good catch BTW
