### ISSUE TITLE
Email/set-destroy > The User doesn't have delete permission is able to delete an email in other's mailbox

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4276]
# Precondition
- UserB doesn't share mailboxes with UserA
- Using UserA credential to run Email/set - destroy API to delete an email in the Inbox of UserB

# Actual Result
When using Email/set-destroy an email in the shared mailbox, it returns error : notFound .
But the email disappears on the Front-end of UserB
![image](https://user-images.githubusercontent.com/69950655/108222704-9890d500-716b-11eb-968f-192d775c99ae.png)

# Expected Result
The deleting shouldn't be successful when the User doesn't have delete permission

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/301

**Comment by tlle14** [comment]
Retest pass!
Returns notFound
![image](https://user-images.githubusercontent.com/69950655/112107707-e2912e80-8be1-11eb-9af4-6f20bce8872a.png)
