### ISSUE TITLE
User should be able to access to other accounts given permissions

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4279]
### Objective

- We need a generic API answering the following questions: Can a user access this accountId
- Provide a simple implementation where the user simply access his account.

### In apache/james project:

1. Define an AccountProvider interface with these methods

- boolean canAccess(Username: username, accountId: accountId)
- List<AccountId> accessibleAccountIds(Username: username)

2. Write a simple implementation for the above interface where user can access their own accountId only. 

PersonalAccountProvider

- canAccess() returns true if accountId = userOwnAccountId, otherwise false.
- accessibleAccountIds() return a list in which contains user own accountId only.

### DoD

Write unit tests to show that PersonalAccountProvider API is functioning properly.

**Comment by chibenwa** [comment]
And what do you think this API should look like? Java example?

**Comment by Arsnael** [comment]
At the end it is Lan that wrote it so I'm not gonna edit it directly. However, this is what I think:

In terms of rest api I think we should rely on the username (and we can generate the accountId from the username), not the accountId for the table. So I would define AccountDelegation with those fields instead:

 * name (the user Username)
 * delegatedAccountIds (AccountIds that the user has access to)

Then I would add this in the users api

/users/{username}/accounts

Methods:
* boolean canAccess(username: Username, accountId: AccountId) -> GET /users/{username}/accounts/{accountId}
* List<AccountId> getDelegatedAccountIds(username: Username) -> GET /users/{username}/accounts

WDYT?

**Comment by Arsnael** [comment]
and once again I'm confused anyway... 

I thought the storage was for openpaas-james, thus should not have a table here right? 

But then, in apache james project point of view, what is the meaning of having an API just saying: I can access my own account? For me it makes no sense at all... I am really having a hard time trying to see the limit between the two projects

**Comment by chibenwa** [comment]
So we just need this API in James:

```
trait AcountProvider {
  def canAccess(username: Username, accountId: AccountId): Boolean
  def listAccessibleAccountIds(username: Username): List[AccountId]
}
```

And provide an implementation `SimpleAccountProvider` that associate each user with its personnal account.

This API **needs** to be in apache/james-project as:
  - API routes, download routes, upload routes, etc... will **need** to be modified to be calling it
  -  Session needs to call it

However we can provide another implementation (backed up by Cassandra storage) in openpaas-james. Clearer?

()
