### ISSUE TITLE
AccountDelegation Cassandra implementation

### ISSUE THREAD

**Issue by LanKhuat** [linagora/james-project#4280]
### Objective

Same purpose with the MemoryAccountDelegation, we now need to implement it in Cassandra.

### How

1. Define a AccountDelegation table with these fields:

- accountId
- delegatedAccountIds

2. Implement the AccountDelegation APIs, based on the contract that has already been defined.

### DoD

Write unit tests to show that the CassandraAccountDelegation is working properly.

**Comment by Arsnael** [comment]
Same remark as #4279, I would see fields:

* name (the user Username)
* delegatedAccountIds (AccountIds that the user has access to)

**Comment by chibenwa** [comment]
Needs to be in openpaas-james

**Comment by chibenwa** [comment]
FYI I proposed an API as part of https://app.zenhub.com/workspaces/team-james-5873652b2a0b13cc0b8bbe63/issues/linagora/james-project-private/78#issuecomment-784719859

```
trait DelegationStore {
  def listDelegatedUsers(username: Username): SFlux[Username]
  def addDelegatedUser(accessor: Username, accessee: Username): SMono[Unit]
  def removeDelegatedUser(accessor: Username, accessee: Username): SMono[Unit]
  def isDelegated(accessor: Username, accessee: Username): SMono[Boolean]
}
```

Here are some remaining questions:
 - Where (which maven project) do we locate this?
 - What is the table design (Primary Key, Clustering Key, Clustering column)? And their types? It is unclear reading the ticket...

**Comment by chibenwa** [comment]
See instead https://app.zenhub.com/workspaces/team-james-5873652b2a0b13cc0b8bbe63/issues/linagora/openpaas-james/49

This ticket should be part of openpaas-james
