### ISSUE TITLE
Integration tests for account delegation

### ISSUE THREAD

**Issue by LanKhuat** [linagora/james-project#4281]
### Objective

With AccountDelegationAPI (Memory/Cassandra) working, we can now add support for delegation where an user can act as another user using their accountId.

### How

Write additional test cases for all funtionalities that has the ability to support account delegation (mailbox, email, download...).

### DoD

All of the above test cases being able to run successfully.

**Comment by Arsnael** [comment]
I believe those integration tests should be done for openpaas-james, not here.
