### ISSUE TITLE
OpenPaas - Gmail > Inline image cannot display on Gmail 

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4283]
# Precondition
On OpenPaas, sending a message to the Gmail user with an inline image

# Actual Result
On Gmail, the inline image is displaying encoded
![image](https://user-images.githubusercontent.com/69950655/108814847-162e6800-75e6-11eb-91ca-a194a3337fda.png)

.eml on OpenPaas
[Test external with inline (1).zip](https://github.com/linagora/james-project/files/6027402/Test.external.with.inline.1.zip)

.eml on Gmail 
[Test external with inline.zip](https://github.com/linagora/james-project/files/6027399/Test.external.with.inline.zip)

# Expected Result
Please investigate if this is our side issue. 
The inline-image should be able to display on Gmail 

# Environment
DEV platform

**Comment by chibenwa** [comment]
I succeed to open both emails with TB, this likely is a problem on GMail app side I imagine.

**Comment by tlle14** [comment]
I should close this issue since we cannot do anything else.
