### ISSUE TITLE
MAILBOX-405 Task to create missing parents

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4292]
```
curl -XPOST http://127.0.0.1:8000/mailboxes?action=CreateMissingParents
```

implemented in webAdmin mailbox project.

Using the list of mailboxes (mailboxManager.list()) identify all the missing parents, and create them.

You will return in task details:

 - The list of created parent mailboxes
 - The count of created mailboxes

**Comment by LanKhuat** [comment]
MAILBOX-405: https://issues.apache.org/jira/browse/MAILBOX-405
