### ISSUE TITLE
MAILBOX-405 Task to subscribe mailboxes for the owner

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4293]
Because of MAILBOX-405 the subscritions for instance in TB do not correspond any longer to the mailboxes stored on the server.

This causes weird user experience and requires user action.

As updating his subscription is an advanced user action, we would like to automate it...

```
curl -XPOST http://127.0.0.1:8000/users/user@domain/mailboxes?action=Subscribe
```

Additional mailboxes should return the count of processed mailboxes as well as the count of created subscriptions.

**Comment by LanKhuat** [comment]
MAILBOX-405: https://issues.apache.org/jira/browse/MAILBOX-405
