### ISSUE TITLE
JAMES-1489 IMAP/ Search function > IMAP cannot search the keyword contains special characters

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4300]
# Actual Result 
When search with keyword contains special characters, the search always returns no result
Example:
Keyword `Đây là một email test 1=1;-`
![Peek 2021-03-26 10-07](https://user-images.githubusercontent.com/69950655/112571635-1014ec80-8e1b-11eb-99a0-f100382708d5.gif)

# Expected Result
IMAP should be able to search with a special characters keyword

# Environment
- Thunderbird /Bluemail
- DEV production

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/JAMES-1489 is related

**Comment by chibenwa** [comment]
OK, this **SHOULD** be easy: We loose a charset somewhere...

https://tools.ietf.org/html/rfc3501#section-6.4.4

```
      The OPTIONAL [CHARSET] specification consists of the word
      "CHARSET" followed by a registered [CHARSET].  It indicates the
      [CHARSET] of the strings that appear in the search criteria.
      [MIME-IMB] content transfer encodings, and [MIME-HDRS] strings in
      [RFC-2822]/[MIME-IMB] headers, MUST be decoded before comparing
      text in a [CHARSET] other than US-ASCII.  US-ASCII MUST be
      supported; other [CHARSET]s MAY be supported.


      If the server does not support the specified [CHARSET], it MUST
      return a tagged NO response (not a BAD).  This response SHOULD
      contain the BADCHARSET response code, which MAY list the
      [CHARSET]s supported by the server.
```

I do not see charset support TBH.

 -> Step 1: Support ASCII charset only
 -> Step 2: Support ASCII charset...

**Comment by chibenwa** [comment]
Ok, 2 problems:

 - continuation (ie `{34+}`) is badly handled by James
 - charset only applies for the next field, not to all

**Comment by chibenwa** [comment]
Edit:

 - UTF-8 single criteria works fine
 - That is the multi-criteria of it that is being broken...

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/980 is my renewed take on this.
