### ISSUE TITLE
JMAP EmailSubmission/set fails

### ISSUE THREAD

**Issue by iNPUTmice** [linagora/james-project#4310]
I managed to set up Apache James (latest commit as of today)

I’m trying to send an email, that is currently in my draft folder with the following JSON: (Submitting it and moving it to the Sent mailbox)

```json
{
  "methodCalls": [
    [
      "EmailSubmission/set",
      {
        "onSuccessUpdateEmail": {
          "#es0": {
            "keywords/$draft": null,
            "mailboxIds": {
              "dade5c10-9304-11eb-b57c-1b93c9e59cb7": true
            }
          }
        },
        "accountId": "cf2e474f942d8ea3192028d2e37d5b08b3ddd36fb986d2ad6a19d66277a981c4",
        "create": {
          "es0": {
            "emailId": "dfcbe610-930a-11eb-b57c-1b93c9e59cb7",
            "identityId": "cf2e474f942d8ea3192028d2e37d5b08b3ddd36fb986d2ad6a19d66277a981c4"
          }
        }
      },
      "0"
    ]
  ],
  "using": [
    "urn:ietf:params:jmap:core",
    "urn:ietf:params:jmap:mail",
    "urn:ietf:params:jmap:submission"
  ]
}
```

I’m getting the following in response.

```json
{
  "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
  "methodResponses": [
    [
      "EmailSubmission/set",
      {
        "accountId": "cf2e474f942d8ea3192028d2e37d5b08b3ddd36fb986d2ad6a19d66277a981c4",
        "newState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
        "created": {
          "es0": "3d22a88d-76cc-4fa3-b3e2-ca978229f0e1"
        }
      },
      "0"
    ],
    [
      "Email/set",
      {
        "accountId": "cf2e474f942d8ea3192028d2e37d5b08b3ddd36fb986d2ad6a19d66277a981c4",
        "oldState": "58f98410-930c-11eb-b57c-1b93c9e59cb7",
        "newState": "58f98410-930c-11eb-b57c-1b93c9e59cb7",
        "notUpdated": {
          "#es0": {
            "type": "invalidPatch",
            "description": "Message update is invalid: Invalid UUID string: #es0"
          }
        }
      },
      "0"
    ]
  ]
}
```

There are two things wrong with the response:

1. The value in the created map needs to be of type EmailSubmission and not of type String. Meaning it's not supposed to be `"es0": "uuid"` but `"es0": { "id: "uuid", "emailId": "foo", …}`
2. The patch object in in OnSuccessupdateEmail needs to resolve the creation id. As Per 7.5 of the spec: A map of _EmailSubmission id_ to an object containing properties to update on the Email object referenced by the EmailSubmission (That is if I'm understanding the spec correctly.)

**Comment by chibenwa** [comment]
Hello @iNPUTmice , thanks for the feedback.

I think there is a lot of mis-understandings here....

 - 1 I don't think creation ID resolution applies within the same method call.
 
 The pattern generally is:
 
 ```
 {
  "using": ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail", "urn:ietf:params:jmap:submission"],
  "methodCalls": [
    ["Email/set", {
      "accountId": "$ACCOUNT_ID",
      "create": {
        "e1526":{
          "mailboxIds": {"${draftId.serialize}": true},
          "to": [{"email": "${BOB.asString}"}],
          "from": [{"email": "${BOB.asString}"}]
        }
      }
    }, "c1"],
     ["EmailSubmission/set", {
       "accountId": "$ACCOUNT_ID",
       "onSuccessUpdateEmail": {
          "#e1526": {
            "keywords/$draft": null,
            "mailboxIds": {
              "dade5c10-9304-11eb-b57c-1b93c9e59cb7": true
            }
          }
        }
       "create": {
         "k1490": {
           "emailId": "#e1526",
           "envelope": {
             "mailFrom": {"email": "${BOB.asString}"},
             "rcptTo": [{"email": "${BOB.asString}"}]
           }
         }
    }
  }, "c2"]]
 ```
 
 You  can see here, contrary to your example, that the method call c2 reuses the method reference of the call c1.
 
 To go into the details, backreferences and creation ids are resolves with multi-stages JSON deserialisation. Each method call is deserialized independantly. If "#" is encountered we attenpts to see if we can substitute a back reference (deserializing the BackReference object, resolving it, and substituting its JSON), and if it fails, resolve the encountered creation Ids so far (so NOT including the ones of the deserialised method call). If it still fails we attempt a JSON deserialization. Never know...
 

 
  - 2. You get a problem of typing. An EmailSubmission can not be considered as an Email... You likely need to explicitly create the Email this another method call.
  
  - 3. Creation ids are not valid across API requests, and are scoped within an API request.
  
  Does it help?

**Comment by chibenwa** [comment]
Re-reading https://jmap.io/spec-mail.html#emailsubmissionset 

I must admit I am wrong...

```
onSuccessUpdateEmail: Id[PatchObject]|null A map of EmailSubmission id to an object containing properties to update on the Email object referenced by the EmailSubmission if the create/update/destroy succeeds. (For references to EmailSubmissions created in the same “/set” invocation, this is equivalent to a creation-reference, so the id will be the creation id prefixed with a #.)
```

I will fire a patch.

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/356 contributes this fix.

```
{
  "using": ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail", "urn:ietf:params:jmap:submission"],
  "methodCalls": [
     ["EmailSubmission/set", {
       "accountId": "$ACCOUNT_ID",
       "create": {
         "k1490": {
           "emailId": "${messageId.serialize}",
           "envelope": {
             "mailFrom": {"email": "${BOB.asString}"},
             "rcptTo": [{"email": "${ANDRE.asString}"}]
           }
         }
       },
       "onSuccessUpdateEmail": {
         "#k1490": {
           "keywords": {"$$sent":true}
         }
       }
   }, "c1"],
   ["Email/get",
     {
       "accountId": "$ACCOUNT_ID",
       "ids": ["${messageId.serialize}"],
       "properties": ["keywords"]
     },
     "c2"]]
}
```

Should do now.

Only limitation: as no storage for EmailSubmission in implemented on James side yet, creation ids are valid only in the scope of a method call. Reference accross API calls / methods calls will fail.

BTW I would invite you to interact with us rather on the community on ASF collaborative mediums rather  than on a third party (Linagora) repo. Especially I suggest bug reports to be reported on the JIRA https://issues.apache.org/jira/browse/JAMES-3434. This is more inclusive to the community (as they might not watch the Linagora repos), and would grant you some Apache karma as well.

**Comment by iNPUTmice** [comment]
> BTW I would invite you to interact with us rather on the community on ASF collaborative mediums rather than on a third party (Linagora) repo. Especially I suggest bug reports to be reported on the JIRA https://issues.apache.org/jira/browse/JAMES-3434. 

Yes. Will do that for future issues.

> You get a problem of typing. An EmailSubmission can not be considered as an Email... You likely need to explicitly create the Email this another method call.

I misspoke in my original issue. This is about the **value** (I wrote key) of the created Map. The value in the created Map of a Set<Foo> response is always Foo and not ID.
>  Meaning it's not supposed to be "es0": "uuid" but "es0": { "id: "uuid", "emailId": "foo", …}

> (symetry with onSuccessDestroyEmail)

FWIW the onSuccessDestroyEmail takes creation ids as well.

**Comment by chibenwa** [comment]
> FWIW the onSuccessDestroyEmail takes creation ids as well.

Crap. I guess I'm tired...

**Comment by chibenwa** [comment]
Fixed....
