### ISSUE TITLE
MDN/parse should position forEmailId property

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4312]
Context: https://www.rfc-editor.org/rfc/rfc9007.html

https://github.com/apache/james-project/pull/351 implements `MDN/parse` but did not implenent support for `MDN::forEmailId`

## How

Write a `MDNForEmailIdResolver` class that given a Mime `Message-Id` header field will do a search using the `MessageIdManager` class, and return a `Optional<MessageId>`.

Use this class to position the `forEmailIdProperty` of the MDN object within `MDN/parse` JMAP method.

## Definition of Done

Given an Email A having the following header `Message-Id: <A>` and messageId `messageId1` in the mailbox of BOB
When BOB have a MDN message B in his mailbox with `originalMessageId` having value `<A>`
Then `MDN/parse` called on B will have a `forEmailId`

**Comment by vttranlina** [comment]
Should we use `MessageIdManager` or `MailboxManager` ?

**Comment by chibenwa** [comment]
Likely MailboxManager yes you are right, sorry...
