### ISSUE TITLE
JMAP WebSocket: handle PING

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4320]
# Why?

If there is no traffic on an open connection, intermediate load balancers will abort the connection.

There is a mechanism of PING/PONG defined in the spec and it is not clear who should handle it: client? Server? Proxy?

I would vote server...

RFC-8887 does not contain ping topic. NGinx folks tend to say it is a server responsibility.

# How?

We need to have a configuration option for websocket ping within `jmap.properties `:

```
websocke.ping.interval=20s
```

Ommitting the property disactivate the ping.

In Websocket route, use this property to send pings on the websocket outbound:

```
Flux<PingWebSocketFrame> pings = Flux.interval(configuration.websocketPingInterval)
     .map(i -> new PingWebSocketFrame(... unique payload here...))

Flux<TextWebSocketFrame> applicativeMessages = // What we currently send in out.sendString

out.send(Flux.merge(pings, applicativeMessages));
```

## Definition of done

Connection should not be shut down upon gatling tests.

I am unsure we can easily set up unit/integration tests for this.

**Comment by Arsnael** [comment]
One concern, could that potentially leave to a starvation of connections in prod in case this option is enabled and clients are not cleaning up their connections well for example? 

If so, and if we want to add this is only regarding gatling tests, shouldn't we add in the doc of it that it's more for a test usage than a prod one?

**Comment by chibenwa** [comment]
> One concern, could that potentially leave to a starvation of connections in prod in case this option is enabled and clients are not cleaning up their connections well for example?

Connections are opened wether you ping or not. Nothing new to ping here.

We of course need to plan connection sizing accordingly to connected protocols.

> clients are not cleaning up their connections well for example?

If they are ponging then they are still responding ;-) If we do not receive a pong for 2* the ping interval then we may want to close the connection. 

> If so, and if we want to add this is only regarding gatling tests, shouldn't we add in the doc of it that it's more for a test usage than a prod one?

It gonna be a prod problem: relying on the client for the keepalive is brittle.

**Comment by Arsnael** [comment]
# Perf tests on preprod:

## IMAP

### Release 0.2.0

![imap-0.2.0.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/e458f9f9-d37b-4aaa-8d9f-ccddf59cb698)

### Release 0.3.0

![imap-0.3.0.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/64433f13-0ef9-4d57-900d-69757ac5e40b)

### Conclusion

Very little improvements but not much. But the performance upgrades have been made more for JMAP for this release so it's expected?

## JMAP

### Release 0.2.0

![jmap-0.2.0.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/92a8ce80-908d-4e6b-a45a-cbcfaf0b6048)

### Release 0.3.0

![jmap-0.3.0.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/3c730f78-66eb-46f1-a5d9-cf265d702625)

### Conclusion

We can see some good performance improvements in the mean and p99 in general.

**Comment by Arsnael** [comment]
So will close this after discussions. The rational being:

 * the RFC does not really states who is responsible for sending the ping
 * the trend nowadays seems to be clients send a ping and server answers with a pong. And Reactor netty does that already
 * we should adapt the gatling test to send regularly echo jmap methods (as Gatling doesn't seem to manage that mechanism), that could act as a ping/pong mechanism to keep the connection alive, in case infra running James has some limitations in terms of idle timeout
