### ISSUE TITLE
How to avoid cluster concurrency,please?

### ISSUE THREAD

**Issue by panglei1984** [linagora/james-project#4323]
I see in function  createAndDispatchMessage (Class is org.apache.james.mailbox.store.StoreMessageManager),there use locker.executeWithLock to avoid concurrency.I think it hope avoid duplication uid .
But when other node of cluster, can it  avoid duplication uid?
please tell me ,thank you very much

**Comment by chibenwa** [comment]
Hello,

Which flavor of James do you use?

Only the distributed flavour (Cassandra, RabbitMQ, S3, ElasticSearch) allows to run several James without further actions.

**Comment by panglei1984** [comment]
> Hello,
> 
> Which flavor of James do you use?
> 
> Only the distributed flavour (Cassandra, RabbitMQ, S3, ElasticSearch) allows to run several James without further actions.

Cassandra.Whether should we confirm we use NoMailboxPathLocker object,that means "run several James without further actions"?

**Comment by chibenwa** [comment]
`server/container/guice/cassandra-guice` (if that is what you use) is not made to have several James servers.

Only the version with RabbitMQ is.

I confirm Cassandra implem is intended to work without locks.
