### ISSUE TITLE
JMAP > search function doesn't return the expected result

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4330]
# Precondition
Have an email with the subject "there is a cat in front of my door"

# Actual Result
Cannot search the expected email on OpenPaas when input the word "there" in the search textbox
![Peek 2021-06-10 09-04](https://user-images.githubusercontent.com/69950655/121453881-14898400-c9cc-11eb-834a-02eaae1e564a.gif)

While on Thunderbird it works
![image](https://user-images.githubusercontent.com/69950655/121453326-33d3e180-c9cb-11eb-9eae-de8ffeb7c67b.png)

# Expected Result
JMAP search should return the matched email 

# Environment
DEV platform
OpenPaas

**Comment by chibenwa** [comment]
Not a bug. `There` is an english stopwords, which do not have any kind of relevance. ElasticSearch will filter it out upon the search.

Thunderbird applies its own logic.
