### ISSUE TITLE
When deleting a message in shared folder, the message is moved to delegated person's trash

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4331]
# Precondtion
UserA shares a folder to UserB with a "Consultant and Manage" permission

# Actual result
When UserB deletes a message in the shared folder, the message is moved to the Trash box of UserA
![Peek 2021-06-10 09-37](https://user-images.githubusercontent.com/69950655/121455986-88795b80-c9cf-11eb-98f2-c548ea61dea2.gif)

# Expected Result
I'm not sure about this behavior. But in my opinion, the deleted message should be moved to the Trash of the owner. He should know which email has been deleted. 

# Environment
DEv platform
OpenPaas

**Comment by Arsnael** [comment]
It seems that your actual result and expectations are the same the way I read it? You say you expect the mail of a shared mailbox to be moved to the trash of the mailbox owner, even if it's deleted by an other user...

And in your exemple you say if user B deletes a message in a shared mailbox owned by userA, it ends up in userA trash? Or did you make a mistake? It's hard to see on the video who the mailbox belongs to as well

**Comment by tlle14** [comment]
No I didn't make a mistake. In this case, userC shares a folder to userD. When userD deletes an email, it is removed to userD's Trash. Sorry for the ambiguous evidence.

**Comment by Arsnael** [comment]
I mean then your description of the bug is wrong. It should say instead:

Actual result: When UserB deletes a message in the shared folder, the message is moved to the Trash box of UserB

**Comment by chibenwa** [comment]
> When UserB deletes a message in the shared folder, the message is moved to the Trash box of UserB

We cannot give the right to UserB to write in UserA trash to be fairly honnest.

**Comment by tlle14** [comment]
>We cannot give the right to UserB to write in UserA trash to be fairly honnest.

This makes sense to me. I should close the issue

**Comment by chibenwa** [comment]
To be fair, the right way is implementing `Shared mailboxes` for real and to drop individual user mailbox sharing IMO

**Comment by tlle14** [comment]
@chibenwa @Arsnael 
The duplicated draft was displaying until I refreshed the page. Do you have any solution to automatically refresh the mailbox?
![Peek 2021-06-16 09-52](https://user-images.githubusercontent.com/69950655/122151219-5cefe880-ce89-11eb-9944-837bc9ec9568.gif)
