### ISSUE TITLE
Position Content-Length header on all JMAP calls

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4333]
https://stackoverflow.com/questions/33269448/why-is-the-gzip-minimum-length-directive-not-being-respected

TLDR without this header NGinx ingress GZIPs everything, which might be detrimental to performance, as small payloads compression might be expensive.

We should thus position content length for all responses being sent by JMAP server, both draft and RFC-8621.

Cc @fiery06 @tanandy

**Comment by tanandy** [comment]
it also join the tuning you will chose to activate GZIP compression

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/JAMES-3600

**Comment by tanandy** [comment]
remember what i writtern. following RFCs you have to set or not regarding uses cases. so reading this, i consider your different use cases respect RFC

**Comment by chibenwa** [comment]
I see that one should not set content length when there is not a bod payload, for sure.

However when we send a body, it makes sense to advertize the size when we know it for sure.

**Comment by tanandy** [comment]
exactly, thats a good start 

note:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.3
https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2

**Comment by chibenwa** [comment]
In these places we do not rel on ` Transfer-Encoding `.

Please be more explicit, I fail at understanding what you try to say here.

**Comment by tanandy** [comment]
> In these places we do not rel on `Transfer-Encoding`.
> 
> Please be more explicit, I fail at understanding what you try to say here.

? what do you mean

**Comment by chibenwa** [comment]
You are expressing expectations without clear explanation which is confusing.

Please express yourself clearly, giving links only to support your speech and not as a replacement of it.

**Comment by tanandy** [comment]
i dont have time to read the entire RFC for that case, i let people in charge of it to express different cases and when or not to set the header
