### ISSUE TITLE
External users cannot receive the forwarded email when enable the "keep local copy" mode

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4338]
# Precondition
On OpenPaas, set up forwarding email from Openpaas to external users
![image](https://user-images.githubusercontent.com/69950655/123194788-4113c480-d4d1-11eb-9169-99b941d95a8c.png)

# Actual Result
On Gmail or O365, the external users don't receive the forwarded mail. 
But when disable the "keep local copy" mode, external users are able to receive the forwarded email.

# Expected Result
The external users should be able to receive forwarded emails when the "keep local copy" mode is on.

# Environment
DEV platform

**Comment by Arsnael** [comment]
Ok hold on there, the fact that you don't see your mails in Gmail or Outlook because you forward from the dev platform might be more because they might think it's spam. Because of spamming, rules are getting stricter from those mail giants and you can't just send them mails from any random server. 

I think the IP of dev is just blacklisted. So for dev we don't care. There is efforts atm for being able to send to those from our preprod env. It requires a bit of work and time for sync to make them trust our server but we are working on it. When we can I will ask you to retest this on preprod :)

**Comment by tlle14** [comment]
>I think the IP of dev is just blacklisted. So for dev we don't care
@Arsnael I don't think so since other emails from DEV still be accepted

**Comment by Arsnael** [comment]
I'm gonna try that as I' surprised by this

**Comment by chibenwa** [comment]
@Arsnael  can you share mailetcontainer.xml used on DEV?

**Comment by tlle14** [comment]
Sorry @Arsnael , I can't check on Production since the feature is disabled.

**Comment by Arsnael** [comment]
Remind me to check it next week

**Comment by Arsnael** [comment]
As it seems the bug only happens when you toggle keep local copy and that the forward works when the local copy if off (from what @tlle14 says), would it be possible that the issue comes from openpaas as well?

**Comment by Arsnael** [comment]
ok so I just tested myself on dev with usera local copy activated and forward to my gmail and... I got the mail both in copy and in my gmail. So for me there is no bug. Or maybe it's an edge case on openpaas depending the order of your steps or maybe number of forward recipients, maybe openpaas is mixing things up. I don't know... Please record a video maybe with your exact steps, that looks like an edge case to me

**Comment by chibenwa** [comment]
Can we select rrt for this account using cqlsh?

**Comment by chibenwa** [comment]
Could not reproduce on prod op.lng.

Can we close?

dev plateform is likely not very trusted by third parties...

**Comment by tlle14** [comment]
I've tested on production.
It is able to forward an email to Gmail, Linagora mail, O365 àn G-suit. 

Linagora email:
![image](https://user-images.githubusercontent.com/69950655/140726460-3a3ea1e8-b397-4c45-b54a-b6b10810e93d.png)

O365
![image](https://user-images.githubusercontent.com/69950655/140726530-7d8fe30c-e490-4bd0-b188-888523f642f2.png)

G-suit
![image](https://user-images.githubusercontent.com/69950655/140726917-4a8dbb23-fed7-4802-8b26-2dafaac0a437.png)
