### ISSUE TITLE
RabbitMQ reconnection handlers should restart consummers

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4343]
## Why?

After upgrading RabbitMQ to 3.8.17 we noticed that, once in a while, messages were not consumed anymore. The consumers alocated to it died and were not replaced.

This results in emails / updates being delayed.

## Possible explanation

For any reason (GC, network failure) some timeout was exceeded and the connection deemed unusable.

Upon connection replacement, no attempt is made to resume the consumer.

## Current fix

Restart James.

## Expected behaviour

We expect James, upon connection replacement, to happily restart its consumers.

## How?

Reconnection handler should also resume consummers.

JIRA: https://issues.apache.org/jira/browse/JAMES-3605

**Comment by fiery06** [comment]
Can you confirm we dont have this issue with RabbitMQ 3.8.3 ?

**Comment by Arsnael** [comment]
We had, but less often

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/516
