### ISSUE TITLE
Set up checkstyle for scala

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4348]
https://www.mail-archive.com/server-dev@james.apache.org/msg70485.html

**Comment by vttranlina** [comment]
Tool: Scalafix (https://scalacenter.github.io/scalafix/)
Maven plugin: scalafix-maven-plugin (https://github.com/evis/scalafix-maven-plugin)

When using `scalafix-maven-plugin`, I got an error with the rule **ExplicitResultTypes** (https://scalacenter.github.io/scalafix/docs/rules/ExplicitResultTypes.html)
Errors:
```
error: The ExplicitResultTypes rule needs to run with the same Scala binary version as the one used to compile target sources (2.13). To fix this problem, either remove ExplicitResultTypes from .scalafix.conf or make sure the scalafixScalaBinaryVersion setting key matches 2.13.
```
Perhaps the error comes from an incompatible version.
- James using scala version: 2.13.4
- The lastest `scalafix-maven-plugin` using scala version 2.12.12

I tried to fork this plugin, and update the dependencies version to matching with James, and it works on local. (I will push code later).

So this will be acceptable?
