### ISSUE TITLE
UploadRepository - API, contract and memory implementation

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4349]
## Why?

We want a dedicated API for the upload and its specific lifecycle.

## How?

We will provide the following API in `data-jmap`:

```
interface UploadRepository {
    Publisher<UploadId> upload(InputStream data, User user);

    Publisher<Upload> retrieve(UploadId id, User user);
}

case class Upload(uploadId UploadId,
                               size: Size,
                                contentType: ContentType,
                                content: => InputStream /* We use the blobId to retrieve the underlying content */)
```

## Definition of done

API, contract test and memory implementation matching those tests.

No need to care about cleanup just yet.

**Comment by vttranlina** [comment]
[The ADR wrote: ](https://github.com/apache/james-project/pull/544/files#L22)
```
if reuploaded, the same blobId MAY be returned, but this SHOULD reset the expiry time.
```
This is a responsibility of the `BlobStore` layer or the `UploadRepository` layer?

**Comment by chibenwa** [comment]
UploadRepository

**Comment by chibenwa** [comment]
MAY means that we are able to do it if we want, in no way that we have to do it ;-).

So no, no incompatibility at all ;-)

(And it is a quote of the JMAP spec serving another purpose there....)
