### ISSUE TITLE
BlobStore: hability to list buckets

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4356]
Implement bucket listing in the BlobStore API

```
interface BlobStore {

   Publisher<BucketName> listUsedBuckets();

}
```

Add a few tests in the contract regarding this.

**Comment by vttranlina** [comment]
I thought the bucketName is unique. 
Do you mean is `searchUsedBuckets(String name)`?

**Comment by chibenwa** [comment]
I meant `Publisher<BucketName> listUsedBuckets();`
