### ISSUE TITLE
WebAdmin route for Upload repository cleanup

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4357]
```
curl -XDELETE http://ip:port/jmap/uploads?scope=expired
```

Should trigger a task to remove stale uploads, as defined in #4355

Provide some simple unit tests for it.

**Comment by vttranlina** [comment]
The method is `POST` or `DELTE`?
I see the same task is using `POST` method.

**Comment by chibenwa** [comment]
DELETE, because it is a task about deletion.

It mirrors what we did for the deleted message vault purge ( https://james.staged.apache.org/james-project/3.7.0/servers/distributed/operate/webadmin.html#_purge_deleted_messages )
