### ISSUE TITLE
All mail is not including emails in the mailbox

### ISSUE THREAD

**Issue by tlle14** [linagora/james-project#4362]
# Actual Result
All mail is not including emails in the mailboxes on My Folders
![Peek 2021-07-28 11-27](https://user-images.githubusercontent.com/69950655/127264290-c18aa6a1-2a72-44be-8570-7a7da6cf1327.gif)

# Expected Result
All mail should include emails in the mailboxes

#  Enviornment
- Environment: https://dev.open-paas.org/inbox/
- Chrome on Ubuntu
- Client: OpenPaas

**Comment by chibenwa** [comment]
ElasticSearch reindex please cc @Arsnael

**Comment by Arsnael** [comment]
Oh yeah I think forgot to add threadId in the ES schema as well (well I was gonna and then I lost my ssh access meanwhile). Will check this today!

**Comment by Arsnael** [comment]
I did the reindexing and just checked on that user, it looks ok to me now. Can you check and confirm @tlle14 ?

**Comment by tlle14** [comment]
It works now. Thank @Arsnael 
![screenshot_17](https://user-images.githubusercontent.com/69950655/127451923-07db15ad-e054-4ab3-9af2-1a23a182bde7.png)
