### ISSUE TITLE
endpoint to get mailbox size

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4363]
```
GET /users/bob@domain.tldmailboxes/mbxName/messageCount

36
```

Deliver it to Apache James project

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/JAMES-3621

**Comment by chibenwa** [comment]
@vttranlina  how long did you spend on that task?

(I do not see any spent Halth Days...)

**Comment by vttranlina** [comment]
> how long did you spend on that task?
2HD

> I do not see any spent Halth Days...
How I can log it? Give a comment directly in the issue? 
// I can not edit the issue and haven't edit permission on zenhub

**Comment by chibenwa** [comment]
`II` label
