### ISSUE TITLE
Endpoint to clear the content of a mailbox

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4364]
```
DELETE /users/bob@domain.tld/mailboxes/mbxName/messages

201

{"taskId": "ABC"}
```

Unit tests for this endpoint in UserMailboxesRoutes

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/JAMES-3621

**Comment by vttranlina** [comment]
`IV` half day

**Comment by Arsnael** [comment]
> `IV` half day

You need to set up the label @vttranlina , not comment :) On upper right of the issue you have a little section called `labels`. You click on it and you select the label `IV` (that's where you have the label `contributions` set up already)

**Comment by vttranlina** [comment]
> > `IV` half day
> 
> You need to set up the label @vttranlina , not comment :) On upper right of the issue you have a little section called `labels`. You click on it and you select the label `IV` (that's where you have the label `contributions` set up already)

Yes, I know, but I don't have permission to do that :(

**Comment by Arsnael** [comment]
Still not? rah... weird. Ok :)

**Comment by Arsnael** [comment]
Indeed, you are not part of the `James` group in Github... @chibenwa you are the maintainer of that group as I can see, can you add @vttranlina ? :)

**Comment by chibenwa** [comment]
Done. Should be good now.

**Comment by vttranlina** [comment]
Thanks @chibenwa @Arsnael , it works
