### ISSUE TITLE
 Write a generation aware BlobId / BlobIdFactory

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4366]
## WHY

- Jira ref: https://issues.apache.org/jira/browse/JAMES-XXX
- To avoid concurrency issues, where we could garbage collect a blob at the same time a new reference to it appears.
- For checking TTL of BlobId. Only the blob expired, and unreferenced will be clean by GC.

## HOW

- Write new `GenerationAwareBlobId` implements `BlobId` in `blob-storage-strategy` module.
- `GenerationAwareBlobId.asString()` has pattern `{family}_{generation}_{blobId}`. 
    - `monthNumber` is the number of current month when BlobId generated
    - Example: 
        - This month: 345-334eab334567234333
        - Next month: 346-334eab334567234333
- 

```java
public class GenerationAwareBlobId implements BlobId {

    public static class Factory implements BlobId.Factory {
        // TODO 
    }
    private final int generation;
    private final String generationFamily;
    private final BlobId delegateBlobId;
    
    // 

    public Predicate<BlobId> inActivePredicate() {
        // Get duration between monthNumber and currentMonthCount  > 1
        return // TODO
    }
}

```

## DOD
- Implement and Write unit test for `GenerationAwareBlobId`

**Comment by chibenwa** [comment]
Please add a `generationFamily` field.

It allows changing safely the generation duration...

**Comment by chibenwa** [comment]
Format: `{family}_{generation}_{blobId}`

**Comment by vttranlina** [comment]
> Format: `{family}_{generation}_{blobId}`

Can you give an example?

**Comment by chibenwa** [comment]
12_3546_UUID

**Comment by chibenwa** [comment]
JIRA https://issues.apache.org/jira/browse/JAMES-3150
