### ISSUE TITLE
Deduplicated blob garbage collection - Integration tests

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4372]
## WHY
- Jira ref: https://issues.apache.org/jira/browse/JAMES-XXX
- Integrate & Guice binding to James server

## PREPARE
https://github.com/linagora/james-project/issues/4370

## HOW 

Some core test cases:

1. Remove unreferenced & inActive blob 
```
- Email1 reference to Blob1
- Remove Email1
- Set clock 1 month later
- Run task BlobGC
- Expect: BlobId1 should remove
```

2. Do not remove referenced Blob 
```
- Email1 reference to Blob1
- Email2 reference to Blob2
- Remove Email1
- Set clock 1 month later
- Run task BlobGC
- Expect: Blob should not remove
```

3. Do not remove the unreferenced and still active blob
```
- Email1 reference to Blob1
- Remove Email1
- Run task BlobGC
- Expect: Blob should not remove
```

**Comment by chibenwa** [comment]
JIRA https://issues.apache.org/jira/browse/JAMES-3150
