### ISSUE TITLE
[Bug][JMAP] Something is wrong with limit and position usage in Email/query

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4375]
We got a report from someone trying to integrate with JMAP on James that there is an issue with Email/query method.

Given a mailbox with more than 20 mails, and let's say we want to request those mails by batch of 20:
```
{
    "using": [
        "urn:ietf:params:jmap:core",
        "urn:ietf:params:jmap:mail"
    ],
    "methodCalls": [
        [
            "Email/query",
            {
                "accountId": "{{account_id}}",
                "limit": 20,
                "filter": {
                    "inMailbox": "{{mailbox_id}}"
                },
                "sort": [{
                  "property":"sentAt",
                  "isAscending": false
                }],
                "position": 0
            },
            "c2"
        ]
    ]
}
```

Then the answer is as expected, we get the list of the 20 first emails of the mailbox. However when trying to fetch the next batch:

```
{
    "using": [
        "urn:ietf:params:jmap:core",
        "urn:ietf:params:jmap:mail"
    ],
    "methodCalls": [
        [
            "Email/query",
            {
                "accountId": "{{account_id}}",
                "limit": 20,
                "filter": {
                    "inMailbox": "{{mailbox_id}}"
                },
                "sort": [{
                  "property":"sentAt",
                  "isAscending": false
                }],
                "position": 20
            },
            "c2"
        ]
    ]
}
```
(basically same request except for the position put at 20), it returns nothing.

After having a looking and playing around with the API a bit myself, I observed something rather funny, that seems to be depending on the `limit` argument:
* if I put `limit` to 30, I get the 10 first ids of that batch
* if I put `limit` to 40, I get the desired 20 ids of the 20-40 batch

It seems `limit` always starts from 0 for some reason, making the position use completely wrong if it's not 0.

We need to investigate and fix this issue.

DoD: Unit tests demonstrating that this case is well taken care of

**Comment by chibenwa** [comment]
The fix https://github.com/apache/james-project/pull/603
