### ISSUE TITLE
Document on the Apache website how to set up sending process.

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4378]
This page dedicated to **SPF** should become `Outgoing email setup`: https://james.apache.org/howTo/spf.html

 - [x] https://www.mail-tester.com/ usage to debug stuff
 - [x] **PTR** records
 - [x] **SPF** record
 - [x] DKIM
        - How to create the keys?
        - How the DKIM record looks like?
        - Configuring the DKIMSign mailet before RemoteDelivery

Link on Github: https://github.com/apache/james-project/blob/master/src/homepage/howTo/spf.html

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/JAMES-3644

**Comment by fiery06** [comment]
PTR Record - I consider it to be a "General domain admin knowledge" rather than James's configuration. 
We can give few lines of introduction for mail-tester.com. The website content itself explained in detail how to debug mail score.

**Comment by chibenwa** [comment]
Yes please link mail-tester in imap-server.html....

**Comment by fiery06** [comment]
i finished the doc, please review
