### ISSUE TITLE
Sharing & quota extensions (over quota mailing, quota search)

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4388]
```
GIVEN BOB delegates his mailbox to ALICE
WHEN ALICE adds a message in BOB mailbox
THEN ALICE receives the overquota message in place of BOB 
AND ALICE quota ratio now have bob value
AND BOB quota ratio is not updated
```

This bug was demonstrated as part of the grooming - see https://issues.apache.org/jira/browse/JAMES-3655 and  https://github.com/apache/james-project/pull/675 pull request.

Demonstrate the bug as part of the grooming... And open a dedicated Apache bug report.

To solve this add the notion of `quotaRoot => email address` in QuotaRootResolver and uses it instead of the user issuing the event in quota extension

**Comment by Arsnael** [comment]
`WHEN ALICE adds a mailbox in BOB mailbox` 

you mean `WHEN ALICE adds a message in BOB mailbox` no?
