### ISSUE TITLE
Modularize Namespace of mailbox share extension in James

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4392]
## Why 
- `org.apache.james.jmap.mail.MailboxNamespace` is a **seal trait** object, We can not extend it to a new CustomNamespace for a custom project. 
-  Move it and related to a separate module, make it generic and usable for custom things to be able to use it.

## How
- Refactor `org.apache.james.jmap.mail.MailboxNamespace` 
```scala
sealed trait MailboxNamespace
```
-> 
```scala
trait MailboxNamespace
```
- Create interface `NamespaceFactory` and default implement 
```scala
trait NamespaceFactory {
  def from(mailboxPath: MailboxPath, mailboxSession: MailboxSession): MailboxNamespace
}

class DefaultNamespaceFactory extends NamespaceFactory {

  def from(mailboxPath: MailboxPath, mailboxSession: MailboxSession): MailboxNamespace =
    mailboxPath.belongsTo(mailboxSession) match {
      case true => PersonalNamespace()
      case false => DelegatedNamespace(mailboxPath.getUser)
    }
}
```
- Refactor `org.apache.james.jmap.mail.MailboxFactory#getNamespace` be like 
```scala
class MailboxFactory @Inject()(mailboxManager: MailboxManager,
                               namespaceFactory: NamespaceFactory) {
  private def getNamespace(mailboxPath: MailboxPath, mailboxSession: MailboxSession): MailboxNamespace =
    namespaceFactory.from(mailboxPath, mailboxSession)
```

**Comment by chibenwa** [comment]
`make it generic and usable for custom things` -> How? Why? (I have already answered these questions here: https://www.mail-archive.com/server-dev@james.apache.org/msg71116.html **## Being able to specify custom namespaces in JMAP Mailbox/get**)

**Comment by chibenwa** [comment]
## Definition of Done

Write a simple integration test with a custom namespace...

**Comment by chibenwa** [comment]
Why?
