### ISSUE TITLE
Cassandra implement for PushSubscriptionRepository

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4400]
## Why 
This is Cassandra's implementation for `PushSubscriptionRepository`.  
Detail: https://github.com/linagora/james-project/issues/4399

## Requires
- https://github.com/linagora/james-project/issues/4399

## How
- Create `CassandraPushSubscriptionDAO`
- Table structure

```
PK user TEXT
CK device_id TEXT
C id UUID
C expired timestamp()
C types frozen set
C url TEXT
C verification_code TEXT
C encrypt_public_key TEXT
C encrypt_auth_secret TEXT
C validated BOOLEAN
```
- Create `CassandraPushSubscriptionDAO` looks like:

```scala
class CassandraPushSubscriptionRepository @Inject()(dao: CassandraPushSubscriptionDAO) 
     extends PushSubscriptionRepository { }
``` 

## Dod 
Write test implement the contract and pass all test cases

**Comment by Arsnael** [comment]
How do we store the keys?

**Comment by vttranlina** [comment]
`keys` have several properties (p256dh, auth), I suggest one column for that. We can JSON deserialize it, and store them.

**Comment by chibenwa** [comment]
> keys have several properties (p256dh, auth), I suggest one column for that. We can JSON deserialize it, and store them.

No please. Nested collections are expensive, user defined types complex. Please add 2 text collumns.

**Comment by Arsnael** [comment]
Regarding this discussion https://github.com/linagora/james-project/issues/4411 , we should add a boolean field `validatedCode` (or if you find better) to say if the validationCode has been completed with the client or not
