### ISSUE TITLE
PushSubscription/get method

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4404]
The request is a classic /get jmap method call:

```
[[ "PushSubscription/get", {
  "ids": null
}, "0" ]]
```

or

```
[[ "PushSubscription/get", {
  "ids": ["a"]
}, "0" ]]
```

with the response looking like:

```
[[ "PushSubscription/get", {
  "list": [{
      "id": "e50b2c1d-9553-41a3-b0a7-a7d26b599ee1",
      "deviceClientId": "b37ff8001ca0",
      "verificationCode": "b210ef734fe5f439c1ca386421359f7b",
      "expires": "2018-07-31T00:13:21Z",
      "types": [ "Todo" ]
  }, {
      "id": "f2d0aab5-e976-4e8b-ad4b-b380a5b987e4",
      "deviceClientId": "X8980fc",
      "verificationCode": "f3d4618a9ae15c8b7f5582533786d531",
      "expires": "2018-07-12T05:55:00Z",
      "types": [ "Mailbox", "Email", "EmailDelivery" ]
  }],
  "notFound": []
}, "0" ]]
```

Note: 
* no accountId and no state in the request (push subs are not tied to specific accounts)
* `url` and `keys` properties are forbidden to be returned. If the properties field has one of those specified, it should be rejected with a forbidden error.
 * set up property filtering on the returned JSON (like mailbox / email)
 * not yet validated subscription codes should not be returned

**DoD**: integration tests

**Comment by Arsnael** [comment]
> IMO, `url` is not a sensitive data

It is, and we want to be spec compliant (the jmap specs forbid to return it, for that reason)

**Comment by chibenwa** [comment]
The question is 'why is it sensitive'. The answer is "because a compromised accounr would allow listing urls and thus pushing arbitrary content to the devices." If you do not list the url that class of attacks do not exist.
