### ISSUE TITLE
PushSubscritpion/set create

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4405]
Standard /set create method:

```
[[ "PushSubscription/set", {
  "create": {
    "4f29": {
      "deviceClientId": "a889-ffea-910",
      "url": "https://example.com/push",
      "types": [ "Mailbox", "Email" ],
      "expires": "2021-11-13T02:14:29Z"
    }
  }
}, "0" ]]
```

That returns something like:

```
[[ "PushSubscription/set", {
  "created": {
    "4f29": {
      "id": "P43dcfa4-1dd4-41ef-9156-2c89b3b19c60",
      "expires": "2021-11-12T02:14:29Z"
    }
  }
}, "0" ]]
```

Notes:
* accountId and states arguments are not being taken into account
* if `expires` is omitted in the request, the server must set one (like now + 7days) and it should be returned in the response
* the server should limit expiracy to a maximum of 7 days

**DoD**: integration tests

**Comment by chibenwa** [comment]
The server should limit expiracy to 7 day maximum (configurable?)

**Comment by vttranlina** [comment]
`"keys": [ "Mailbox", "Email" ]` 
It should is `types` right?
