### ISSUE TITLE
Memory IdentityRepository and contract tests

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4423]
## Why
We need a repository APIs to store user custom identity.

## How
- Move Identity POJO from jmap-8621 to data-jmap, name field should be Option
```scala
case class Identity(id: IdentityId,
                    name: Option[IdentityName],
                    email: MailAddress,
                    replyTo: Option[List[EmailAddress]],
                    bcc: Option[List[EmailAddress]],
                    textSignature: Option[TextSignature],
                    htmlSignature: Option[HtmlSignature],
                    mayDelete: MayDeleteIdentity)
                    
case class IdentityCreationRequest(name: Option[IdentityName],
                    email: MailAddress,
                    replyTo: Option[List[EmailAddress]],
                    bcc: Option[List[EmailAddress]],
                    textSignature: Option[TextSignature],
                    htmlSignature: Option[HtmlSignature])
```
- Define IdentityRepository:
```java
Publisher<Identity> save(Username username, IdentityCreationRequest identityCreationRequest);

Publisher<Void> update(Username username, Identity newIdentity);

Publisher<Identity> findByIds(Username username, Set<IdentityId> ids);

Publisher<Identity> findAll(Username username);

Publisher<Void> remove(Username username, IdentityId id);
```

## DoD
IdentityRepository interface + Memory implementation + contract tests

## Note
- Inject ```IdentityFactory``` and do merging identities stuff at this Repository layer (for update, findByIds, findAll, remove). Then we would separate a little logic from DAO layer.
- If  **name**, **textSignature**, **htmlSignature** is empty => set to "" string by default
- User custom identities should have **mayDelete** = true by default
- When update, if record not found => throw exception
- We have to check  **email**: is the user able to send from input address? (inject CanSendFrom). Otherwise throw exception
- We should validate **htmlSignature** (This text MUST be an HTML snippet to be inserted into the `<body></body>` section of the HTML). I think we should validate this upon Jmap deserialization.

**Comment by chibenwa** [comment]
revoke => remove IMO

**Comment by vttranlina** [comment]
// this bellow just is common my comment

When I work with the JPA library, I realized that it has one code convention for the method name. 
- If the method name starts with "findBy...", the result can return have value or empty.
- If the method name starts with "getBy...", the result implicates is a value or throw NotFound exception.

IMO it is a good convention, more clear. In James, sometimes I need to read inside the implement for sure

**Comment by vttranlina** [comment]
If the POJO wrote by scala, IMO the interface/implement repository should be written by scala too. (I know it is not mandatory) 
But it will help us less boilerplate than for the convert between two language

**Comment by quantranhong1999** [comment]
> When I work with the JPA library, I realized that it has one code convention for the method name.
```
Publisher<Identity> findByIds(Username username, Set<IdentityId> ids);

Publisher<Identity> findAll(Username username);
```
Does this comply with you?

**Comment by chibenwa** [comment]
> IMO it is a good convention, more clear. In James, sometimes I need to read inside the implement for sure

:+1: looks like a good convention, let's try to stick to it!
