### ISSUE TITLE
Cassandra implement for CustomIdentityDAO

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4424]
## Why
This is Cassandra's implementation for `CustomIdentityDAO`.

## Requires
- [Memory IdentityRepository and contract tests](https://github.com/linagora/james-project/issues/4423)

## How
- Create a user defined type for email address: email_address(name TEXT, email TEXT)
- Create CassandraIdentityModule with table structure:
```
PK user TEXT
CK identity_id UUID
C name TEXT
C email TEXT
C replyTo set<email_address>
C bcc frozen set<email_address>
C textSignature TEXT
C htmlSignature TEXT
C mayDelete BOOLEAN
```
- Create CassandraCustomIdentityDAO that implement CustomIdentityDAO

## DoD
Write test implement the contract and pass all test cases

**Comment by chibenwa** [comment]
`set<TEXT>` => `frozen<set<TEXT>>` we do not need to update individual elements, let's not pay the (expensive) cost of mutable collections in Cassandra...

**Comment by chibenwa** [comment]
`Mono<Identity> selectOne(Username username, IdentityId id);` ?

**Comment by chibenwa** [comment]
Also we should avoid leaking Mono/Flux usage in API interfaces. Please favor `Publisher`.

**Comment by quantranhong1999** [comment]
I changed to
```
C replyTo frozen map(<TEXT>, <TEXT>)
C bcc frozen map(<TEXT>, <TEXT>)
```
cause EmailAddress contains 2 fields

**Comment by chibenwa** [comment]
> cause EmailAddress contains 2 fields

Please use a (frozen) user defined type instead (set of a user defined type if need be.)

**Comment by quantranhong1999** [comment]
> Please use a (frozen) user defined type instead (set of a user defined type if need be.)

Can you tell me more about this? I am having class and can not inspect the code for more information now :')

**Comment by chibenwa** [comment]
Sure.

 - 1. You need to build a type using `CassandraModule`. Eg: `CassandraMailboxModule`
 - 2. Use the (frozen) type in your table definition. Note that you can do (frozen) collections of (frozen) types. Eg: `CassandraMailboxModule` still...
  - 3. You can work with your user defined type using `CassandraTypesProvider` class. A good example of this could be `CassandraMailboxDAO` + `MailboxBaseTupleUtil`.
