### ISSUE TITLE
Plug custom identities store to Identity/get

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4426]
## Why
We need to merge custom identities with server-set identities upon Jmap level.

## Requires
- [Memory IdentityRepository and contract tests](https://github.com/linagora/james-project/issues/4423)

## How
- Inject IdentityRepository to IdentityGetMethod, handle further JMAP stuff

## Example
Request:
```
[ "Identity/get", {
  "accountId": "acme"
}, "0" ]
```
with response:

```
[ "Identity/get", {
  "accountId": "acme",
  "state": "99401312ae-11-333",
  "list": [
    {
      "id": "XD-3301-222-11_22AAz",
      "name": "Joe Bloggs",
      "email": "joe@example.com",
      "replyTo": null,
      "bcc": [{
        "name": null,
        "email": "joe+archive@example.com"
      }],
      "textSignature": "-- \nJoe Bloggs\nMaster of Email",
      "htmlSignature": "<div><b>Joe Bloggs</b></div>
        <div>Master of Email</div>",
      "mayDelete": false
    },
    {
      "id": "XD-9911312-11_22AAz",
      "name": "Joe B",
      "email": "joe-alias@example.com",
      "replyTo": null,
      "bcc": null,
      "textSignature": "",
      "htmlSignature": "",
      "mayDelete": true
    }
  ],
  "notFound": []
```
## DoD
- Integration tests

## Note
- The ```ids``` argument may be `null` to fetch all at once.
- Above is get all case, for get ```Set<IdentityId> ids``` case just add a filter step which element in ids.
- We should not plan to support *@example.com
- We need to allow property filtering (already have this piece of code?)

**Comment by chibenwa** [comment]
Please take property filtering into account too.

**Comment by chibenwa** [comment]
Also modify the example: we should not plan to support `*@example.com`
