### ISSUE TITLE
Identity/set update + delete and Identity/get should fail for identities whose alias is deleted

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4433]
```
GIVEN an alias is removed,
THEN all identities using this alias should be deleted.
```

Sadly we do not have an event system for identities.

Hence I propose:

```
GIVEN an alias is removed,
THEN all identities using this alias should be ignored.
```

We need to:

 - 1. Create a ticket for this.
 - 2. Implement a failing test
 - 3. Do the extra filtering within the Identity repository.

## Definition of done

Integration tests for Identity/get Identity/set-update + Identity/set-delete.

**Comment by quantranhong1999** [comment]
Actually, Identity/destroy does not fail as we thought.
https://github.com/apache/james-project/pull/760
