### ISSUE TITLE
JAMES-2333 Docker links concidered legacy

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4434]
https://issues.apache.org/jira/browse/JAMES-2333

Do something like for TMail: https://github.com/linagora/tmail-backend/blob/master/tmail-backend/apps/distributed/README.md

Doc files to modify for apache/james-project:
 - `server/apps/distributed-app/docs/modules/ROOT/pages/run/run-docker.adoc`
 - `server/apps/distributed-app/README.adoc`
 - `server/apps/cassandra-app/README.adoc`
 - `server/apps/distributed-pop3-app/README.adoc`

**Comment by Arsnael** [comment]
I would add that in the docker-compose files we still use links and should move to networks as well?

**Comment by chibenwa** [comment]
> I would add that in the docker-compose files we still use links and should move to networks as well?

Which one: can you link them?

**Comment by Arsnael** [comment]
> Which one: can you link them?

No in fact forget my remark, I thought depends_on was similar to link and after checking the doc again not at all. I think the dockerfiles are good  sorry for bothering :)

**Comment by ducnm0711** [comment]
bump ;)

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/814
