### ISSUE TITLE
Document OIDC setup for JMAP

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4438]
Add an OIDC section in JMAP configration file explaining the setup:
   - https://github.com/apache/james-project/blob/master/server/apps/distributed-app/docs/modules/ROOT/pages/configure/jmap.adoc
   - https://github.com/apache/james-project/blob/master/src/site/xdoc/server/config-jmap.xml

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/JAMES-3680

**Comment by Arsnael** [comment]
https://github.com/apache/james-project/pull/828  => docker-compose PR

**Comment by chibenwa** [comment]
We need to add LDAP support for the memory image.
