### ISSUE TITLE
Implement an authentication strategy based on the X-USER header

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4447]
## Why
We need an authentication strategy based on a custom header X-USER eg X-USER: bob@linagora.com
So we can leverage from that to propagate authentication result from Krakend to James without James handling ID token things.
Example request echo method:
```
POST http://localhost:35049/jmap  
Accept: application/json  
jmapVersion: rfc-8621  
Content-Type: application/json  
Charset: UTF-8  
X-User: bob@linagora.com  
  
{"using":["urn:ietf:params:jmap:core"],"methodCalls":[["Core\/echo",{"arg1":"arg1data","arg2":"arg2data"},"c1"]]}
```
Example response should be something like this if bob@linagora.com is a valid user:
```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, DELETE, PUT
Access-Control-Allow-Headers: Content-Type, Authorization, Accept
content-type: application/json
content-length: 132

{
    "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
    "methodResponses": [
        [
            "Core/echo",
            {
                "arg1": "arg1data",
                "arg2": "arg2data"
            },
            "c1"
        ]
    ]
}
```
## How
 1. Create `UserHeaderAuthenticationStrategy` implement `AuthenticationStrategy` with `MailboxManager`, `UsersRepository` injected at `server/protocols/jmap/src/main/java/org/apache/james/jmap/authentication`
 - Implement createMailboxSession 
```java
@Override  
public Mono<MailboxSession> createMailboxSession(HttpServerRequest httpRequest) {  
	// Pseudo code
 - get Optional<String> username from X-USER header
 - If (username is present) {
	  var user = userRepository.getUserByName(Username.of(username))
	  If(user!=null) => createSession else throw UnauthorizedException
  } else {
	  just do nothing and then let Authenticator throw NoAuthorizationSuppliedException after
  }
}
```
Remind if we need to handle further Exception in AuthenticationRoutes, JMAPApiRoutes, SessionRoutes

- Implement correspondingChallenge
```java
@Override  
public AuthenticationChallenge correspondingChallenge() {  
  return AuthenticationChallenge.of(  
  AuthenticationScheme.of("QueryXUserHeader"),  
  ImmutableMap.of());  
}
```

2. Write tests:
- `UserHeaderAuthenticationStrategyTest` (have a look at `JWTAuthenticationStrategyTest` for similarity)
- Clone `JMAPApiRoutesTestWithUserHeaderAuthentication` from `JMAPApiRoutesTest` which using UserHeader authentication instead
- Add tests in `AuthenticationContract` for new strategy (Should we bind `UserHeaderAuthenticationStrategy` to `RFC8621MethodsModule` and `DraftMethodsModule` (At least for testing this))?

**Comment by vttranlina** [comment]
Can you post the curl example of an HTTP request?

**Comment by chibenwa** [comment]
ImmutableMap.of("realm", "Username") is likely not needed in the challenge, we could keep up with the empty map.

**Comment by quantranhong1999** [comment]
The response of JMAP-RFC8621 right now have a header:
```
Access-Control-Allow-Headers: Content-Type, Authorization, Accept
```
Should we add X-User to this response? And maybe remove Authorization depends on new authentication configuration?

**Comment by chibenwa** [comment]
> Should we add X-User to this response?

IMO no that's an implementation detail related to our API gateway setup.

Actually we should make sure the API gateway do not allow users to specify the `X-USER` header ;-) (or we have a trivial security breach!)

**Comment by Arsnael** [comment]
In the example request we don't need the Authorization header field, as this strategy relies only on the X-USER header here.

Also should precise this should come after the work on making auth strategies modular and configurable, to not expose the API dangerously by default with this strategy. This strategy should be disabled by default!

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/784
