### ISSUE TITLE
Make JMAP authentication strategies modular and configurable

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4448]
## Why
This work enables `UserHeaderAuthenticationStrategy` (with decent security protection caution) for OIDC support.

## How
- Define a configuration pair in `jmap.properties` file store Authentication Strategy class names
	```
	authentication.strategy.draft=org.apache.james.AuthStratA,org.apache.james.AuthStratB
	authentication.strategy.rfc8620=org.apache.james.AuthStratA,org.apache.james.AuthStratB
	```
- Add a field in `JmapRfc8621Configuration` store Option[List[String]] (class names list)
- Add a piece of code to `RFC8621MethodsModule` to provide Set[AuthenticationStrategy]. Eg:

```
@Provides  
@Singleton  
@Named("authenticationStrategies")  
public Set<AuthenticationStrategy> provideAuthenticationStrategies(GuiceGenericLoader loader, JmapRfc8621Configuration configuration) {  
	// Use GuiceGenericLoader to load Set<AuthenticationStrategy> from class names list
}
```
- Then inject this Set to provideAuthenticator
Similar works for Jmap draft (`DraftMethodsModule`).
## Note
- If the configuration pair is empty we should fallback to some specific AuthenticationStrategies to avoid breaking changes. My suggestion:
	- JMAP final version: Basic, JWT
	- JMAP draft version: jwtAuthenticationStrategy,  accessTokenAuthenticationStrategy, queryParameterAuthenticationStrategy (as it stands right now)

**Comment by chibenwa** [comment]
IMO we should have something like:

```
authentication.strategy=org.apache.james.AuthStratA,org.apache.james.AuthStratB
```

This would furthermore enable people to develop their own auhtentication stategies.

**Comment by quantranhong1999** [comment]
I just updated the proposal. Also any idea on how to test this work?

**Comment by chibenwa** [comment]
> Also any idea on how to test this work?

We can write a custom authentication strategy switching a static atomic boolean from false to true (to ensure it is called). Then a little integration test on top of the memory server would ensure this work...

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/781
