### ISSUE TITLE
Upgrade log4j to 2.16.0 version

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4453]
This work needs to be done for James, jdkim, jspf, mime4j, jsieve.

**Comment by quantranhong1999** [comment]
james (master):https://github.com/apache/james-project/pull/799
james (3.6.x): https://github.com/apache/james-project/pull/798
jdkim: https://github.com/apache/james-jdkim/pull/14
jspf: https://github.com/apache/james-jspf/pull/13
mime4j: https://github.com/apache/james-mime4j/pull/68
jsieve: I do not see any pom.xml use log4j

**Comment by chibenwa** [comment]
As explained by @mbaechler that is a really good opportunity to switch jdkim and jspf to slf4j ;-)

**Comment by quantranhong1999** [comment]
> 

So we just remove log4j in that projects and use slf4j instead. 
Or are we should use both and do some conversion as he said? I do not get his point TBH.

**Comment by chibenwa** [comment]
Yes. slf4j in src/main, we can keep log4j usages within src/test.

Also this could require a dedicated JIRA IMO

**Comment by quantranhong1999** [comment]
JIRA for jdkim: https://issues.apache.org/jira/projects/JDKIM/issues/JDKIM-47?filter=allopenissues

**Comment by chibenwa** [comment]
Can you please add this link in your JDKIM PR where this is discussed?
