### ISSUE TITLE
Docker compose example SLO

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4461]

**Comment by Arsnael** [comment]
PR: https://github.com/apache/james-project/pull/840

**Comment by Arsnael** [comment]
Demo: 

https://user-images.githubusercontent.com/9005025/149310405-c54f117f-e3ea-4220-a082-c75a134a1501.mp4

**Comment by chibenwa** [comment]
Good to me. Just making sure: sign in again after sign out works?

**Comment by Arsnael** [comment]
True  forgot to show that, but yes it works!

Little detail as well, I have to manually css show the logout button because the js script crashes before doing it. It seems it tries to set up the name in a div value that does not exist anymore (but last week was fine, maybe they did a buggy update on their test app)

**Comment by vttranlina** [comment]
Good demo (y)

When I tried jwt_revoker on local, I got an error "error on adding bloomfilter: connection is shut down" 
It is very similar here https://githubmate.com/repo/devopsfaith/bloomfilter/issues/11

Have you met it? Do you have any suggestions?

**Comment by Arsnael** [comment]
No never got that one sorry @vttranlina . What did you do exactly?

**Comment by vttranlina** [comment]
>  What did you do exactly?

Similar to your write-in Readme. But using `docker run` for each element, not docker-compose

**Comment by Arsnael** [comment]
ah yeah if you used docker (not the compose) without attaching your containers in the same network it does not work, it will not be able to resolve the krakend ip

**Comment by Arsnael** [comment]
Or you could fetch the IP of your docker krakend and then start the jwt-revoker with env variables (if you look in the code, I set up some) like `KRAKEND_HOST`
