### ISSUE TITLE
Normalize OIDC configuration for IMAP/SMTP

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4467]
IMAP oidc conf is under a `oauth` block, while smtp is under a `oidc`. The OIDC configuration should be normalized under one same block.

Here we are really relying on the oidc config endpoint to make clients aware of what they need so we should keep the  `oidc` choice for normalizing.

DoD : Change imap oidc conf from `oauth` block to `oidc`

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/855

**Comment by Arsnael** [comment]
That was fast :D
