### ISSUE TITLE
Issue with Redis configuration in James

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4480]
In k8s, a redis deployed cluster is served under a same headless service. So we point only to one address internally, then K8s does the job of routing the requests to the wanted pods composing the redis cluster.

However we have a problem in James in the configuration with the letuce library.

There is 2 kind of configuration: one for Redis standalone and one for a cluster. We consider having a cluster if we have more than one uri declared in the conf. But as we saw above, we can have cases of a cluster being served by one endpoint.

We need to fix this.

Proposing here to add a parameter in the `redis.properties` file, something like `cluster.enabled` to true or false, defaulting to false (likely so that the tests don't break?)

**Comment by chibenwa** [comment]
Is it a good practice in the first place to have a load balancer in front of the REDIS cluster?

**Comment by Arsnael** [comment]
it's not a lb...

**Comment by Arsnael** [comment]
It's statefulset, exact same principle with the rabbitmq cluster 

@ducnm0711 can better explain than me I think :)

**Comment by chibenwa** [comment]
Please discuss your K8s set up with @ducnm0711 

lb - service whatever the driver should talk directly to the redis servers (so 6 uris though we could configure less) and not to a virtual ip "under a same endpoint" as you wrote it yourself.

**Comment by chibenwa** [comment]
Yes but I hope Redis have better clustering support than rabbit.

**Comment by Arsnael** [comment]
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

**Comment by ducnm0711** [comment]
> In k8s, a redis deployed cluster is served under a same endpoint. So we point only to one address internally, then K8s does the job of balancing the requests to the pods composing the redis cluster.

> Proposing here to add a parameter in the `redis.properties` file, something like `cluster.enabled` to true or false, defaulting to false (likely so that the tests don't break?)

Okay you both misunderstand smt here. 

A `headless` service is NOT load-balancing and DOES NOT have an IP. It will return the IPs of our Redis Pods.  This allows us to interact directly with the Pods instead of a proxy.  
@Arsnael  => not lb bro, remember that. 

So how this is different with normal Cluster IP and why it's related to Statefulset ?

Normal ClusterIP provides a load-balanced IP address. 
Meaning send a request to PodA and we can have response from PodB or PodC. 

But we DON'T want that with Redis ! We want each request is send/response from same source.
So the solution is `headless` ClusterIP. It makes sure request session to PodA will get response by PodA. ( This is also core concept of a k8s StatefulSets)

DBs or Queue system, both mechanisms require a Request to be sent/responded by same Pod or specific order.

The only key different between you guys is WHICH component will control the routing? 
- @chibenwa put 6 uris in config, then it's the Java driver job. 
- @Arsnael  use Headless ClusterIP, then it's k8s job.

But Benoit setup will fucked up if a pod got restart or deleted => Pod IP change xD
What Rene proposed is correct, just bad explanation.

fyi:
https://www.baeldung.com/ops/kubernetes-deployment-vs-statefulsets#

**Comment by Arsnael** [comment]
I know we discussed it this morning, but yes it's much more detailed and complete this way. Clearer for me now, thanks :)

**Comment by Arsnael** [comment]
https://github.com/apache/james-project/pull/885

**Comment by chibenwa** [comment]
I don't buy this (the james changes and k8s archi) quite yet.

Any decently written cluster driver is able to connect to a miriad of hosts/whatever, and handle gracefully failover / loadbalancing by itself. You might be doing more harm than good by exposing a single logical ip to your app.

Let me take an example: cassandra in k8s. You likely want to have your app talking to each individual nodes as the driver is topology/ gossip aware. You likely configure several contact point. While you might want to abstract the pod away, you might want one "stable" ip per cassandra node, not one ip hidding the whole cluster.

Would it make sense for Redis?

I don't know but clearly I'd be happy we look how redis and lettuce clustering modes works.

**Comment by chibenwa** [comment]
https://lettuce.io/lettuce-4/release/api/com/lambdaworks/redis/cluster/RedisClusterClient.html

The wordings there let me think james could + should speak to a collection of redis...

**Comment by chibenwa** [comment]
![Screenshot_20220216-223600_Samsung Internet](https://user-images.githubusercontent.com/6928740/154299544-3c395ea1-b0c2-482b-b465-17a58fd37e99.jpg)

**Comment by chibenwa** [comment]
Like... How about relying on the fact the hostnames in a statefull set are stable?

![Screenshot_20220216-224053_Samsung Internet](https://user-images.githubusercontent.com/6928740/154300928-97276259-495c-4f36-af41-6696e370b51a.jpg)

**Comment by ducnm0711** [comment]
No, a single headless service can solve your issue.
Image having a list of all 6 URIs and it can auto update if any IP changes/
https://faun.pub/deploying-a-cassandra-cluster-in-kubernetes-on-ibm-cloud-59e840c1a9b7

Cassandra, Redis (or all Statefulsets app) based on this:
`
A normal [Service](https://kubernetes.io/docs/concepts/services-networking/service/) in Kubernetes allows you load balance between the pods behind a single service IP, and creates a DNS entry for you. A headless service in Kubernetes is a service definition that doesn’t have a service IP. This can be useful if you don’t need load balancing for a service but would rather have just a set of A records for the service, pointing to each individual pod.
`
https://faun.pub/deploying-a-cassandra-cluster-in-kubernetes-on-ibm-cloud-59e840c1a9b7
I think this question related:
https://stackoverflow.com/questions/69984241/what-is-the-redis-headless-service-used-for-in-kubernetes-cluster

**Comment by ducnm0711** [comment]
> Like... How about relying on the fact the hostnames in a statefull set are stable?

Yes, you can. But they both the same thing lol:
redis-0 redis-1 redis-2 , redis-3, redis-4,... = redis-headless-svc

**Comment by chibenwa** [comment]
Ok we want of course headless service and we want of course to specify several uri in james conf then.

**Comment by chibenwa** [comment]
Ps I am by no mean a k8s expert I don't know the wording... sorry of it make my points harder to grasp...

**Comment by Arsnael** [comment]
So after trying a few things around and checking for info on the internet...

The hostnames you see in Lens is just to name the ips of redis pods... James can't do anything with it.

I went upon this : https://marklu-sf.medium.com/deploy-and-operate-a-redis-cluster-in-kubernetes-94fde7853001

So the guy setted up a redis cluster using the same helm chart than us pretty much. And what is interesting is the last section `Redis Client Connection Issue upon Cluster Restart`:

```
The Redis client applications are using the Redis cluster’s service IP to connect to the cluster. The client application is a Java application which uses Redisson java client library to talk to the cluster. It looks like the client library use the service IP as the seed and get the IPs for all the nodes in the Redis cluster. After the completion of the initialization, the client will use individual node’s IP instead of the fronting service IP for further communication.
```

So ok we don't use Redisson but Lettuce here, but it's the same. The lib calls the headless endpoint in k8s to have the list of IPs of the nodes of the cluster, then it uses only those IPs for further communication. The headless is not used anymore after connection initialization. So that's pretty much what we want. 

However there is a limitation:

```
If the Redis cluster has been restarted due to upgrade or other maintenance operations, the redis nodes in the cluster will be running on new IPs even though its service IP remains the same. The client applications end up holding connections with the old IP and running into redis connection errors.
```

I checked and it's right. If I restart the redis cluster, new IPs have been assigned, then you can see that James panicks with error logs like this:

```
{"timestamp":"2022-02-17T05:03:09.120Z","level":"WARN","thread":"lettuce-epollEventLoop-4-2","logger":"io.lettuce.core.protocol.ConnectionWatchdog","message":"Cannot reconnect to [10.2.2.43:6379]: finishConnect(..) failed: Connection refused: /10.2.2.43:6379","context":"default"}
{"timestamp":"2022-02-17T05:03:12.318Z","level":"WARN","thread":"lettuce-epollEventLoop-4-2","logger":"io.lettuce.core.protocol.ConnectionWatchdog","message":"Cannot reconnect to [10.2.0.90:6379]: connection timed out: /10.2.0.90:6379","context":"default"}
```

So we see that we talk directly to IPs and if it changes james looses the connection to redis. So we need to restart James as well in this case for now.

The best would be to do an autoreload in this case in James but it's not easy and might take time. So for now a restart will do, as the rate limiting is not critical if it stops working for a bit.

We better add in our mailets the following `<onMailetException>ignore</onMailetException>` so that if we get an exception (because connection lost,etc) we still deliver emails without rate limiting (it's not critical).
