### ISSUE TITLE
Document Distributed James database benchmarks and base level performance

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4482]
Base yourself on https://ci.linagora.com/linagora/lgs/openpaas/james/-/wikis/DB-load-testing

Provide testing methods

Provide example results

**Comment by quantranhong1999** [comment]
Q: This is for James (community). So what computer will be the reference system?

**Comment by chibenwa** [comment]
A: 

1. We are using some publicly available cloud instance. Maybe not as popular than AWS but still
2. We should be clear about the pretentionof the exercise - with these benches results we got decent james perfs, if you got the same you should be fine, btw here is how to do it...

**Comment by quantranhong1999** [comment]
## Benchmark Elasticsearch for James

### Why?
Distributed James are using Elasticsearch as a search engine. James' community would likely be interested in benchmarking their Elasticsearch cluster performance and compare to another reference point to see if their cluster performing well. Here we would provide some benchmarking result on OVH machine as a reference point.

### How?
#### Benchmark tool
We proprose you to use [EsRally](https://github.com/elastic/rally) - an official Elasticsearch benchmarking tool. Any other tool can be considered as long as you think it is appropriate.
Esrally provides the following features:
1.  Automatically create Elasticsearch clusters, stress test them, and delete them.
2.  Manage stress testing data and solutions by Elasticsearch version.
3.  Present stress testing data in a comprehensive way, allowing you to compare and analyze the data of different stress tests and store the data on a particular Elasticsearch instance for secondary analysis.
4.  Collect Java Virtual Machine (JVM) details, such as memory and garbage collection (GC) data, to locate performance problems.

You can have a look at [https://elasticsearch-benchmarks.elastic.co/](https://elasticsearch-benchmarks.elastic.co/)  where Elasticsearch also officially uses esrally to test its performance and publishes the results in real time.
#### Let benchmark it!
Please follow [Esrally quickstart documentation](https://esrally.readthedocs.io/en/latest/quickstart.html?spm=a2c65.11461447.0.0.e26a498c3KJZNe) to setup it first.
Let see which tracks (simulation profiles) that esrally provides: `esrally list tracks`. The result would be like this:
```shell
Available tracks:

Name           Description                                                              Documents    Compressed Size    Uncompressed Size    Default Challenge        All Challenges
-------------  -----------------------------------------------------------------------  -----------  -----------------  -------------------  -----------------------  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
dense_vector   Benchmark for dense vector indexing and search                           10,000,000   7.2 GB             19.5 GB              index-and-search         index-and-search
noaa           Global daily weather measurements from NOAA                              33,659,481   949.4 MB           9.0 GB               append-no-conflicts      append-no-conflicts,append-no-conflicts-index-only,top_metrics,aggs
geonames       POIs from Geonames                                                       11,396,503   252.9 MB           3.3 GB               append-no-conflicts      append-no-conflicts,append-no-conflicts-index-only,append-fast-with-conflicts,significant-text
nyc_taxis      Taxi rides in New York in 2015                                           165,346,692  4.5 GB             74.3 GB              append-no-conflicts      append-no-conflicts,append-no-conflicts-index-only,append-sorted-no-conflicts-index-only,update,append-ml,date-histogram,indexing-querying
metricbeat     Metricbeat data                                                          1,079,600    87.7 MB            1.2 GB               append-no-conflicts      append-no-conflicts
percolator     Percolator benchmark based on AOL queries                                2,000,000    121.1 kB           104.9 MB             append-no-conflicts      append-no-conflicts
pmc            Full text benchmark with academic papers from PMC                        574,199      5.5 GB             21.7 GB              append-no-conflicts      append-no-conflicts,append-no-conflicts-index-only,append-sorted-no-conflicts,append-fast-with-conflicts,indexing-querying
sql            SQL query performance based on NOAA Weather data                         33,659,481   949.4 MB           9.0 GB               sql                      sql
geopointshape  Point coordinates from PlanetOSM indexed as geoshapes                    60,844,404   470.8 MB           2.6 GB               append-no-conflicts      append-no-conflicts,append-no-conflicts-index-only,append-fast-with-conflicts
so             Indexing benchmark using up to questions and answers from StackOverflow  36,062,278   8.9 GB             33.1 GB              append-no-conflicts      append-no-conflicts
tsdb           metricbeat information for elastic-app k8s cluster                       122,613,113  10.7 GB            129.2 GB             append-no-conflicts      append-no-conflicts
geoshape       Shapes from PlanetOSM                                                    60,523,283   13.4 GB            45.4 GB              append-no-conflicts      append-no-conflicts
geopoint       Point coordinates from PlanetOSM                                         60,844,404   482.1 MB           2.3 GB               append-no-conflicts      append-no-conflicts,append-no-conflicts-index-only,append-fast-with-conflicts
nested         StackOverflow Q&A stored as nested docs                                  11,203,029   663.3 MB           3.4 GB               nested-search-challenge  nested-search-challenge,index-only
eql            EQL benchmarks based on endgame index of SIEM demo cluster               60,782,211   4.5 GB             109.2 GB             default                  default,index-sorting
http_logs      HTTP server log data                                                     247,249,096  1.2 GB             31.1 GB              append-no-conflicts      append-no-conflicts,runtime-fields,append-no-conflicts-index-only,append-sorted-no-conflicts,append-index-only-with-ingest-pipeline,update,append-no-conflicts-index-reindex-only
```
Please choose the track that you are interested in. Here for James use cases, we think you would interested in `eql` and `nested` tracks. Note that the dataset for `eql` track is big (Uncompressed size ~ 110GB), so please make sure that your esrally hosted machine and your ES cluster have enough space first. 
Let benchmark your Elasticsearch cluster against Esrally!
```esrally race --pipeline=benchmark-only --track=[trackname] --target-host=[ip:port]```
In there: 

 - `--pipeline=benchmark-only`: benchmark against a running cluster
 - `trackname`: track you want to benchmark
 - `ip:port`: your Elasticsearch cluster' address

### Testing result
TODO: Waiting for OVH access, benchmark against ES7, note the result

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/937
