### ISSUE TITLE
Outdated Rules with RedisRateLimiter

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4486]
Regarding `org.apache.james.rate.limiter.redis.RedisRateLimiter` 
We can get outdated Rules when trying to update new specifications (via the `mailetcontainer.xml` file), **even already restart a James.**

Look via example code:

```java
    @Test
    public void outdatedProblem() {
        RedisClient client = RedisClient.create("redis://localhost:6379/1");

        RedisRateLimiterFactory factory = new RedisRateLimiterFactory(client);

        RequestRateLimiter requestRateLimiter = factory.getInstance(ImmutableSet.of(RequestLimitRule.of(Duration.ofMinutes(100), 1)));

        final String key = "Key1";
        assertThat(requestRateLimiter.overLimitWhenIncremented(key)) // accept
            .isEqualTo(false);
        assertThat(requestRateLimiter.overLimitWhenIncremented(key))  // exceed
            .isEqualTo(true);

        RequestRateLimiter newRequestRateLimiter = factory.getInstance(ImmutableSet.of(RequestLimitRule.of(Duration.ofMinutes(100), 10)));
        assertThat(newRequestRateLimiter.overLimitWhenIncremented(key))  // should be acceptable, but result is exceeded
            .isEqualTo(false);
    }
```

```
org.opentest4j.AssertionFailedError: 
expected: false
 but was: true
```

**Comment by Arsnael** [comment]
I'm not too surprised? You already created a key on Redis with a TTL, I don't think you can update with a set. 

However I see in redis doc this: https://redis.io/commands/expire 

An expire command can update the ttl of an existing key.

On lettuce, likely this? https://lettuce.io/lettuce-4/release/api/com/lambdaworks/redis/api/async/RedisKeyAsyncCommands.html#expire-K-long-

Can you try? :))

**Comment by vttranlina** [comment]
yes, updating a TTL is better than removing/recreating it. 
we will lose current counters.

**Comment by vttranlina** [comment]
NO, I rethinking, If only update TTL, the rate limit spec is still outdated, 
the counter (with old spec) still exists as the hash value.

**Comment by vttranlina** [comment]
Solution:
- change the prefix in containermailet file
- drop Redis DB
- Delay spec can be acceptable

**Comment by chibenwa** [comment]
> Solution: change the prefix in containermailet file

:+1:
