### ISSUE TITLE
JMAP Filters: support wildcards and choose explicitly the condition

### ISSUE THREAD

**Issue by fabienmoyon** [linagora/james-project#4497]
As a user, when I create a new filter,  I want to be able to choose explicitly the condition, the WHAT and the COMPARATOR by a list.

![image](https://user-images.githubusercontent.com/11298249/159046678-2f7dc62e-354e-4f4e-9706-6fb4b5db0736.png)

Reference: https://github.com/linagora/esn-frontend-inbox/issues/134

**Comment by chibenwa** [comment]
Hello @fabienmoyon 

Thanks for openning the issue.

We will takkle this when we will add filter support in TMail (not before Q4 2022)

**Comment by chibenwa** [comment]
See https://github.com/linagora/james-project/issues/4568
