### ISSUE TITLE
Document tools and benchmark result for James

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4504]
We should document the Gatling tool and the base benchmark result for James.
We can leverage the ticket: https://issues.apache.org/jira/browse/JAMES-3734

 - provision LDAP  (see gitlab wiki)
 - provision emails ? (smtp-source command + random storing mailet)
 - Run james-gatling IMAP / JMAP scenario
 - Sample results on top of OVH IMAP scenario.

**Comment by quantranhong1999** [comment]
IMO we can leverage Performance tests result of tmail 0.5.0 release.

**Comment by chibenwa** [comment]
- Provision: point to webadmin routes! It will be even easier (create domain, create user, create mailboxes)

Propose a little script to automate that.

**Comment by quantranhong1999** [comment]
> Provision: point to webadmin routes! It will be even easier (create domain, create user, create mailboxes)
Propose a little script to automate that.

Seems we already have that with `UsersFeederWebAdminFactory`.

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1005
