### ISSUE TITLE
Audit GC during massive imap perf tests

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4513]
**Why**: IMAP perfs test throughtput is subject to hickups: vary locally by a factor 4... 250 -> 1000 req.s. gc is a usual suspect regarding performance hickups so this is worth trying.

**how**

 - activate gc logs via jvm options for java 9+
 - Gcviewer ?

20 mins, big perf tests

**Comment by chibenwa** [comment]
Our metrics would tend to rule out GC...

```
{"timestamp":"2022-04-13T09:37:16.934Z","level":"DEBUG","thread":"metrics-logger-reporter-1-thread-1","logger":"org.apache.james.metrics","message":"type=GAUGE, name=jvm.gc.G1-Old-Generation.count, value=0","context":"default"}
{"timestamp":"2022-04-13T09:37:16.934Z","level":"DEBUG","thread":"metrics-logger-reporter-1-thread-1","logger":"org.apache.james.metrics","message":"type=GAUGE, name=jvm.gc.G1-Old-Generation.time, value=0","context":"default"}
```

**Comment by quantranhong1999** [comment]
Are we using Parallel Garbage Collector by default?

I read about Z Garbage Collector which seems a good GC implementation without stopping the execution of application threads for more than 10 ms.
But it is only production status for upward JDK 17. Maybe it would be one of the motivations to migrate to Java 17 in the future.

**Comment by chibenwa** [comment]
We are using G1GC so far.

> Maybe it would be one of the motivations to migrate to Java 17 in the future.

Yes!

**Comment by quantranhong1999** [comment]
## GC Log
### Many performance tests combined
#### Performance tests result
1. 20k users => simulation never finishs when users finishing his scenario (looks like SSL high concurrency issue?)
2. 12k users => respone time good
3. 14k users (850 req/s) => response time good
4. 16k users => simulation never finishes
5. 15k users (910 req/s) => response time good

[Details performance test result](https://pastebin.com/b4mTpAp6)

#### GC viewer
[gc-many-perf-test.log](https://github.com/linagora/james-project/files/8511143/gc-many-perf-test.log)
![image](https://user-images.githubusercontent.com/55171818/163957103-e88a2ea7-e6a6-4e52-b195-44cab9a5d0ae.png)

- Average pause time: 80ms
- Max pause time: 380ms
- GC pause time: 51s / Total time: 2h50m
- Throughput (GC time/ Perf test time): 99.5%

### A standalone hiccup performance test with 20k users

#### Performance test result
<details>
  <summary>Simulation never finishes with many K.O requests</summary>
  
================================================================================
2022-04-19 07:42:59                                        1355s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=1143962 KO=133502)
> Connect                                                  (OK=20000  KO=0     )
> login                                                    (OK=19504  KO=496   )
> heavyScenario / append                                   (OK=138852 KO=17004 )
> lightScenario / list                                     (OK=45630  KO=6301  )
> lightScenario / select                                   (OK=46070  KO=5535  )
> heavyScenario / list                                     (OK=268483 KO=41664 )
> lightScenario / fetch                                    (OK=47386  KO=4190  )
> heavyScenario / select                                   (OK=275613 KO=32649 )
> heavyScenario / fetch                                    (OK=282424 KO=25663 )
---- Errors --------------------------------------------------------------------
> Imap check failed                                              133502 (100.0%)
---- ImapPlatformValidation ----------------------------------------------------
[##################################################################--------] 89%
          waiting: 0      / active: 2075   / done: 17925
================================================================================
</details>

#### Gc viewer

[gc-hickup-standalone.log](https://github.com/linagora/james-project/files/8511232/gc-hickup-standalone.log)

![image](https://user-images.githubusercontent.com/55171818/163959560-bf4a175b-c13c-407d-bef5-c64c1d862c3c.png)

- Average pause time: 97ms
- Max pause time: 213ms
- GC pause time: 15s / Total time: 26m30s
- Throughput (GC time/ Perf test time): 99%
- Pause young numbers/ total: 153/165

It is clear that we do more GC when we have a more big request load.
A more detailed memory allocation in our heap:
![image](https://user-images.githubusercontent.com/55171818/163960686-454fd44a-b602-4179-90bb-3a39895f8bcb.png)

We can see that:
- We do many GC (165 times) but the total memory clean up is just 207MB.
- Young heap uses 1843MB/2056MB (90%) while Perm heap (metaspace) just uses 132.7MB/ 1144MB (11.6%).
- We use almost our memory (90% of 3GB)

My guess is that Young heap keeps almost running out of memory => JVM runs GC often but it does not really help (let's say 207MB/165 for each GC). This could suggest we need more memory for our heap (especially the Young heap).

So I think we need to provide more space to our Young heap by either adding more general memory (3GB -> 4GB) or switching some Perm heap (which stably uses a little space through many Perf tests) to Young heap.
This suggestion could improve GC (reduce GC executions number and GC quality). Overall I do not think GC is a blocker in our IMAP performance.

**Comment by chibenwa** [comment]
My takes on this:

 - Filling heap young generation is not worrying and is typical of apps exposed to high request rate
 - GC pauses linked to young generation are not particularily worrying
 - We could argue that short pauses (50 ms) every ~30 seconds could cause to some spikes in load leading to issues down the road.
 
 As such I think we could benefit from trying out ZGC on on a JRE 17. Maybe we could try this. Shall we create a separate issue?

**Comment by chibenwa** [comment]
The try of the evening...

```
           - name: JAVA_TOOL_OPTIONS
              value: >-
                -Xms3g -Xmx3g -Xlog:gc*:file=/root/gc.log
                -XX:MaxGCPauseMillis=20 -XX:ParallelGCThreads=2
                -XX:+PrintSafepointStatistics
                –XX:PrintSafepointStatisticsCount=1
```

Run 15k users...

At the end of inection:

```
james-imap-smtp-7d8bf6c67b-fsqft   1725m        1896Mi          
james-imap-smtp-7d8bf6c67b-x4r6s   1823m        1807Mi          
```

Results:

![Screenshot from 2022-04-19 23-55-05.png](https://images.zenhubusercontent.com/5ef2aee69879df3417738ce4/d4023c90-7b67-41d6-97eb-ba763d3a74fe)

I did also get very good results for 12k users for these settings...

```
================================================================================
---- Global Information --------------------------------------------------------
> request count                                     888364 (OK=888364 KO=0     )
> min response time                                      4 (OK=4      KO=-     )
> max response time                                  21498 (OK=21498  KO=-     )
> mean response time                                    49 (OK=49     KO=-     )
> std deviation                                         70 (OK=70     KO=-     )
> response time 50th percentile                         33 (OK=33     KO=-     )
> response time 75th percentile                         65 (OK=65     KO=-     )
> response time 95th percentile                        117 (OK=117    KO=-     )
> response time 99th percentile                        245 (OK=245    KO=-     )
> mean requests/sec                                737.232 (OK=737.232 KO=-     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                        886919 (100%)
> 800 ms < t < 1200 ms                                1117 (  0%)
> t > 1200 ms                                          328 (  0%)
> failed                                                 0 (  0%)
================================================================================

Reports generated in 22s.
Please open the following file: /root/upn/james/james-gatling/target/gatling/platformvalidationsimulation-20220419153830633/index.html
[info] Simulation PlatformValidationSimulation successful.
```

Maybe we should open a HELM PR?  :-)

**Comment by chibenwa** [comment]
For the record pulsar have even more aggressive GC pause targets...

**Comment by chibenwa** [comment]
Morning run, 15k users, same gc parameters

![Screenshot from 2022-04-20 09-22-44.png](https://images.zenhubusercontent.com/5ef2aee69879df3417738ce4/b4e123c6-0cff-4892-8357-4b94f6f996ad)

**Comment by quantranhong1999** [comment]
> Maybe we should open a HELM PR? :-)

https://ci.linagora.com/linagora/lgs/openpaas/packaging/helm-charts/helm-james/-/merge_requests/67

**Comment by quantranhong1999** [comment]
> As such I think we could benefit from trying out ZGC on on a JRE 17. Maybe we could try this. Shall we create a separate issue?

https://github.com/linagora/tmail-backend/issues/410

**Comment by Arsnael** [comment]
> https://ci.linagora.com/linagora/lgs/openpaas/packaging/helm-charts/helm-james/-/merge_requests/67

Merged
