### ISSUE TITLE
IMAP SEARCH from DATE should not be resolved against ElasticSearch

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4523]
This seems to be a frequent operation...

Many clients uses it to resynchronise themselves.

We could likely have a hook mechanism within the search index, allowing to recognise the pattern and optimise it against cassandra `email query view`. Having a Multibinder on these search overrides would allow minimal changes to the existing code.

## DOD

SEARCH date=12-4-2022 would no longer hit ElasticSearch but Cassandra

**Comment by quantranhong1999** [comment]
Title: `IMAP SEARCH from DATE should not be resolved against Cassandra`
-> `IMAP SEARCH from DATE should not be resolved against Elasticsearch` ?

**Comment by chibenwa** [comment]
```
Processing SearchRequest{operation=SearchOperation{key=SearchKey{type=TYPE_AND, date=null, size=0, value=null, seconds=-1, modSeq=-1, uids=null, sequences=null, keys=Optional[[
    SearchKey{type=TYPE_SEQUENCE_SET, date=null, size=0, value=null, seconds=-1, modSeq=-1, uids=null, sequences=[IdRange ( 1->9223372036854775807 )], keys=Optional.empty}, 
    SearchKey{type=TYPE_SINCE, date=8-5-2022, size=0, value=null, seconds=-1, modSeq=-1, uids=null, sequences=null, keys=Optional.empty}]]}, options=[]}, useUids=true}
```

**Comment by chibenwa** [comment]
Email query view refers solely the messageId, to retrieve the uid, we thus need to either...

 - Perform an extra Cassandra query per message to get the UID, which is expensive
 - Add UID to email query view which costs more storage space and also requires a data migration, which is complex.

Though they are used to resynchronize, apparently by GMAIL application, the queries return limited results as the results returned are mostly recent.

As such I believe this not to be desirable work as it requires significant work....

Closing for now.
