### ISSUE TITLE
Dependency upgrade round

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4539]
- [x] Maven dependencies for James 
 - [ ] Maven dependencies for TMail
 - [x] Maven plugins were applicable
 - [x] Docker images where relevant
 - [x] Recommended integrations for Tika, SpamAssassin

**Comment by vttranlina** [comment]
Some upgrade maven dependencies for James: https://github.com/apache/james-project/pull/1017

**Comment by vttranlina** [comment]
> Recommended integrations for Tika, SpamAssassin

Can you explain more it?

**Comment by chibenwa** [comment]
Upgrade our testing image for Tika to https://hub.docker.com/layers/tika/apache/tika/1.28.2/images/sha256-19e9d34aaa47b2e03bd8efee48adcd598e22298d547f2801f948f673466e7992?context=explore and adda third party section in the changelog advising people to upgrade tika.

For spamassassin we may consider switching to an image that is actually maintained: https://hub.docker.com/layers/spamassassin/instantlinux/spamassassin/3.4.6-1/images/sha256-2c1907ba1dcf1064cc2abeabc6d537f696188398f2333bef1369250fafba2263?context=explore and idem recommend people in the changelog to update to 3.4.6.

We may use NGinx 1.22.0 too.

We may also upgrade Rabbit to 3.9.18 and recommand the upgrade to it in the changelog.

We might be switching our testing openLDAP image to https://hub.docker.com/layers/openldap/bitnami/openldap/2.6.2/images/sha256-f975504e046208c17c541a18e5e6acec2fe45198cee90f17999362df3d5b12d4?context=explore cf `server/data/data-ldap/src/test/resources/invalid/ldif-files/Dockerfile` `server/data/data-ldap/src/test/resources/ldif-files/Dockerfile`

Please do a separate PR for those...

**Comment by vttranlina** [comment]
TODO: Upgrade Maven dependencies for TMail (do it after the pr for James merged)

**Comment by chibenwa** [comment]
> TODO: Upgrade Maven dependencies for TMail (do it after the pr for James merged)

Yes but because we use a BOM there will not be much job to do ;-)
