### ISSUE TITLE
JAMES-3755 IMAP/SMTP OIDC token introspection

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4541]
- Create an `IntrospectionClient` using reactor-netty that does submission of JWT tokens to an introspection endpoints and present the result of the instrospection as a response.

```
interface IntrospectionClient {
    Publisher<IntrospectionResponse> introspect(String client);
}
class IntrospectionResponse {
   boolean active;
   String scope;
   
```

 - Unit tests with a mocked http server for the introspection client.

 - Add an optional introspection.url option in imapserver.xml, smtpserver.xml

 - If specified, then the introspection endpoint is called. Have 2 unit tests in ImapServerTest:
    - Introspection succeeds
    - Introspection fails

 - Record a little video adapting the OIDC exemple to enable token introspection.

**Comment by vttranlina** [comment]
## Note
Keycloak token introspect
```bash
curl --location --request POST 'http://localhost:8080/auth/realms/oidc/protocol/openid-connect/token/introspect' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'token=TOKEN' \
--data-urlencode 'token_type_hint=requesting_party_token' \
--data-urlencode 'client_id=oidc2' \
--data-urlencode 'client_secret=07x0J2GV6lCS001Qnz9mq1pJI4attsbA'
```

Keycloak writes: 
https://www.keycloak.org/docs/latest/authorization_services/index.html#obtaining-information-about-an-rpt
```
The request above is using HTTP BASIC and passing the client’s credentials (client ID and secret) to authenticate the client attempting to introspect the token, but you can use any other client authentication method supported by Keycloak.
```
But I don't find anywhere a guide on how to pass authentication for keycloack client has AccessType = public.
=> We can use credential client (clientId+secret) that has `accessType=confidential` for introspecting the token that generated by another client (that has accessType=Public)

**Comment by chibenwa** [comment]
IMO we could pass the entire Authorization header as a parameter.

**Comment by vttranlina** [comment]
> IMO we could pass the entire Authorization header as a parameter. This is the most flexible IMO.

Yes, then we can have only one property in configure file (by passing basic authen in URL). 
// My miss when write down

**Comment by vttranlina** [comment]
PR https://github.com/apache/james-project/pull/1006
