### ISSUE TITLE
Write a webadmin route to feed spam to RSpamD

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4563]
```
XPOST /rspamd?action=reportSpam
```

Will iterate all users, read their `SPAM` folder and report the content to RSPamD.

Options:

 - `sampling`: float between 0 and 1, represent the chance to report each given messages to RSpamD. Optional, by default all messages are reported.
 - `period`: duration, only messages between `now` and `now - duration` are reported. By default all messages are reported
 - `messagesPerSecond`: int, optional, defaults to 10. Concurrent learns performed for RSpamD

Job to be done:
 - Task
 - TaskAdditional information
 - Webadmin endpoint
 - Unit tests

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1092
