### ISSUE TITLE
Write a webadmin route to feed Ham to RSpamD

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4564]
```
XPOST /rspamd?action=reportHam
```

Will iterate all users, read their `SPAM` folder and report the content to RSPamD.

Options:

 - `sampling`: float between 0 and 1, represent the chance to report each given messages to RSpamD. Optional, by default all messages are reported.
 - `period`: duration, only messages between `now` and `now - duration` are reported. By default all messages are reported
 - `messagesPerSecond`: int, optional, defaults to 10. Concurrent learns performed for RSpamD

**Comment by Arsnael** [comment]
I don't think sending the mails in spam folder on the ham webadmin route is the wanted thing here :)

Agreed with Quan that we would do just inbox for now to limit the load

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1098
