### ISSUE TITLE
Full review of Tasks

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4570]
https://issues.apache.org/jira/browse/JAMES-3779

`.details` should allow exposing a publisher.

Those tasks should be POJOs where a service is injected. Running their deserialisation logic should not trigger blocking calls.

Revert uggly logic in EventStoreDao and in CassandraTaskExecutionDetailsProjectionDAO (serialisation deserialization should not cost IOs)

**Comment by chibenwa** [comment]
Include TMAIL

**Comment by Arsnael** [comment]
Does this task create more instability? I know the current build is not super stable but I can't seem to have a green build despite running it way too many times...

We need to take the time to reinvestigate
