### ISSUE TITLE
[GCS-SARA] AttachmentToRabbitMQ listener

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4571]
Write a listener that, on `Added` events, reads the messageDAOV3 to get the list of blob Ids and publishes :

```
{
    "user" : "bob@domain.com",
    "attachments" : [ 
        {
             "blobId": "abcdef",
             "name":"file.pdf", // optional
              "contentType": "application/pdf",
              "size": 2685623
        }
    ]
}
```

The listener takes the following configuration parameters:

 * uri (mandatory): AMQP URI defining the server where to send the attachment.
 * exchange (mandatory): name of the AMQP exchange.
 * routing_key (optional, default to empty string): name of the routing key on this exchange.

## DOD

Unit tests

**Comment by vttranlina** [comment]
pr https://gitlab.com/linagora_private/saas/tmail/customers/james-gcs-sara/-/merge_requests/3
