### ISSUE TITLE
JAMES-3784 Ease mail repository / event dead letter operation

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4573]
https://issues.apache.org/jira/projects/JAMES/issues/JAMES-3784?filter=allopenissues

**Comment by Arsnael** [comment]
Together with https://github.com/linagora/james-project/issues/4574

**Comment by Arsnael** [comment]
Does this task create more instability? I know the current build is not super stable but I can't seem to have a green build despite running it way too many times...

We need to take the time to reinvestigate

**Comment by chibenwa** [comment]
Unlikely...

**Comment by Arsnael** [comment]
Why it keeps failing then?
