### ISSUE TITLE
JAMES03784 Develop and use a new HealthCheck for MailRepository

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4574]
Uses JamesMailSpooler.Configuration to know the error rapository

Checks it is empty.

Bind this class.

**Comment by Arsnael** [comment]
Does this task create more instability? I know the current build is not super stable but I can't seem to have a green build despite running it way too many times...

We need to take the time to reinvestigate

**Comment by chibenwa** [comment]
Unlikely....

**Comment by Arsnael** [comment]
Why it keeps failing then?
