### ISSUE TITLE
Error: Jmap - Identity/set method - Query timed out after PT2S

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4582]

**Comment by vttranlina** [comment]
`org.apache.james.jmap.rfc8621.distributed.DistributedIdentitySetTest` fail.
(I don't know why ci pass it)
![image.png](https://images.zenhubusercontent.com/60585c4b8db077d7bf15b627/50d2cb71-3061-470d-99f2-a012f9ba9316)

**Comment by chibenwa** [comment]
Environment? Jmap.linagora.com ?

**Comment by Arsnael** [comment]
Did you try with maven locally?

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/1103
