### ISSUE TITLE
RSpamD mailet: handle desiredRewriteSubject

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4584]
Add an option to the RSpamD mailet:

```
<mailet matcher="All", class="RspamDMailet">
    <rewriteSubject>true/false</rewriteSubject> <!-- default to false ? -->
</mailet>
```

If rewriteSubject is configured as true AND the RSpamD analysis of a specific email returns a value for `desiredRewriteSubject` then this value should be positioned as the new value of the subject of this email.

Write a corresponding test, and the corresponding logic.

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1106
