### ISSUE TITLE
Switch from high level rest client to new java OpenSearch client in Apache James

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4587]
https://github.com/apache/james-project/pull/1061

**Comment by Arsnael** [comment]
Might have an issue when running imap perf tests...

So as usual I ran perf tests for master and then opensearch new java client PR. I usually run 10 minutes 200 users first to warm the pods up then I run the simulation for an hour with 10k users on two imap pods.

Master branch result:

![old-client-opensearch.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/06baeee9-d17e-467d-b8ab-a7a23171fce3)

Then I tried from the PR with the new client... Two things here:
- the simulation didn't finish, I had 131 users hanging indefinitely at the end
- I could see some logs that don't smell good...

On gatling side, I could see from time to time when monitoring logs like that:
```
09:52:33.768 [nioEventLoopGroup-3-4] ERROR c.l.g.i.p.command.UIDSearchHandler - UIDSearchHandler command failed
```

On James side, no error, but a lot of warning logs like that:
```
{"timestamp":"2022-12-12T09:51:41.597Z","level":"WARN","thread":"imapserver-ssl-io-3","mdc":{"proxy.destination":"/146.59.203.62:30994","proxy.ip":"10.2.0.0","protocol":"IMAP","proxy.source":"/51.210.249.34:43086","ip":"/51.210.249.34:43086","sessionId":"SID-fbrtcsiewqke","user":""},"logger":"org.apache.james.imapserver.netty.ImapChannelUpstreamHandler","message":"Error while processing imap request","context":"default","exception":"java.net.SocketException: Connection reset\n\tat java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(Unknown Source)\n\tat java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)\n\tat io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258)\n\tat io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)\n\tat io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n"}
```

I didn't have the time to investigate yet... Any ideas? If not I will dig into it tomorrow

**Comment by Arsnael** [comment]
Might have an issue when running imap perf tests...

So as usual I ran perf tests for master and then opensearch new java client PR. I usually run 10 minutes 200 users first to warm the pods up then I run the simulation for an hour with 10k users on two imap pods.

Master branch result:

![old-client-opensearch.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/06baeee9-d17e-467d-b8ab-a7a23171fce3)

Then I tried from the PR with the new client... Two things here:
- the simulation didn't finish, I had 131 users hanging indefinitely at the end
- I could see some logs that don't smell good...

On gatling side, I could see from time to time when monitoring logs like that:
```
09:52:33.768 [nioEventLoopGroup-3-4] ERROR c.l.g.i.p.command.UIDSearchHandler - UIDSearchHandler command failed
```

On James side, no error, but a lot of warning logs like that:
```
{"timestamp":"2022-12-12T09:51:41.597Z","level":"WARN","thread":"imapserver-ssl-io-3","mdc":{"proxy.destination":"/146.59.203.62:30994","proxy.ip":"10.2.0.0","protocol":"IMAP","proxy.source":"/51.210.249.34:43086","ip":"/51.210.249.34:43086","sessionId":"SID-fbrtcsiewqke","user":""},"logger":"org.apache.james.imapserver.netty.ImapChannelUpstreamHandler","message":"Error while processing imap request","context":"default","exception":"java.net.SocketException: Connection reset\n\tat java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(Unknown Source)\n\tat java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)\n\tat io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258)\n\tat io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)\n\tat io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n"}
```

I didn't have the time to investigate yet... Any ideas? If not I will dig into it tomorrow

**Comment by chibenwa** [comment]
Likely some searches taking over 60 s and the Gatling runner finishes to shut down the connection.

 - [ ] A CPU + memory flame graph has the potential to highlight what might be wrong here
 - [ ] jstack can help spot extra stuff like blocking on parrallel / netty / cassandra threads

**Comment by Arsnael** [comment]
CPU flame graph, mem flame graph, jstack:  [os_diagnose.zip](https://github.com/linagora/james-project/files/10215786/os_diagnose.zip)

In the jstack we can see numerous threads blocked on some opensearch operations

In flame graph cpu, we can see two scrolledSearch stacks taking a lot of cpu (38% and 7%)

In flame graph mem , more than 50% of memory is taken by scrolledSearch...

Safe to assume something is clearly wrong with the ScrolledSearch^^'

Will try to investigate...

**Comment by Arsnael** [comment]
After the fix that @chibenwa helped me with this morning when looking at the jstack and flame graphs, this is the new files: [https://app.zenhub.com/files/39182136/026a0fff-9af1-4a13-baf6-1eb63e2ae015/download](https://app.zenhub.com/files/39182136/026a0fff-9af1-4a13-baf6-1eb63e2ae015/download)

There is no blocking threads anymore it seems on opensearch ScrolledSearch operations. The simulation finished as well and this is the result:

![opensearch_new_client.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/a35ccbeb-2a88-48fe-bc4b-fadcd866b589)

Regarding results we can see that it's slightly faster in general but not really significant. The append though seems faster (491ms P99 against 639ms for master).

**Comment by chibenwa** [comment]
Yes, it looks like the big perf problem is gone ;-)

**Comment by chibenwa** [comment]
Switch done if I am correct...
