### ISSUE TITLE
Stabilize RSpamD test

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4589]
RspamD scrores looks a bit machine dependents, sometine some tests reports `2.4` sometimes `2.9`

Make this test more stable (avoid asserting the scores returned by RSpamD ?)

**Comment by quantranhong1999** [comment]
Trying to make the score stable first according to a bit related RSpamD docs: https://rspamd.com/doc/faq.html#why-can-i-have-different-results-for-the-same-message

Added the `Pass: all` header but still archive the unstable score on the same machine:
![image.png](https://images.zenhubusercontent.com/5f7fe3b8b67a756e7c63d181/4dc6a172-12f7-4b03-9b1d-0f6703e290d0)

Will try to check internal RSpamD timeout tmr.

If the effort is not satisfied, we likely need to avoid the scoring assertion which is not really meaning (stated by RSpamD: https://rspamd.com/doc/faq.html#why-do-i-have-zero-score-for-a-spam-message)

**Comment by quantranhong1999** [comment]
Checked and there is no scoring unstable test on master but more on in-progress PRs (https://github.com/apache/james-project/pull/1093#issuecomment-1206016139 - resolved in place anyway). 
We are good with master.

**Comment by chibenwa** [comment]
Is it?

(master build)

![Screenshot from 2022-08-09 12-08-45.png](https://images.zenhubusercontent.com/5ef2aee69879df3417738ce4/4c35d521-5b04-41c7-8a1d-8197bb696785)

**Comment by quantranhong1999** [comment]
I checked and it is at least not related to the scoring topic.

```
04:42:41.934 [ERROR] ?.2.16.0-r0] - Could not start container
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [49264] should be listening)
```

I observed this type of docker startup error sometime in our builds (eg Cassandra container) before. It is an unstable container test issue.

```
2022-08-09 04:41:46 #51(main) rspamd_url_init: start compiling of 9628 TLD suffixes; it might take a long time
```
Maybe the CI is just slow ATM then causes timeout (I ran this rspamd before locally and this compiling is not fast).

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1112
