### ISSUE TITLE
Performance test for RSpamD

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4592]
We are interested in...

 - Latencies of the RSpmD mailet
 - Throughtput of the RSpamD mailet
 - Throughtput of RSpamD Ham/Spam routes

How to measure it?

 - SMTP: Send a few mail and look at RSpamD throughput without load.
 - SMTP: Send a lot of emails using smtp-source and look at throughtput/ latencies of RSpamD with load.
 - Run the ham route: define how many msg.sec can be ingested on pre-prod.

**Comment by quantranhong1999** [comment]
I see RSpamD advertises it can handle up to 100 msg/sec with 1 CPU core. Are we interested in verifying that (at least for our preprod, without interacting with James) by writing a simple HTTP loading test to RSpamD?

**Comment by chibenwa** [comment]
> Are we interested in verifying that 

Yes

> by writing a simple HTTP loading test to RSpamD?

No. We are interested to verify this through the James interactions.

**Comment by quantranhong1999** [comment]
To fully score a quite long mail (eg `spam8.eml`), `RSpamD` takes an average of 10s on my local:
![image](https://user-images.githubusercontent.com/55171818/183621681-84df9638-5de8-47ca-9076-689b5412e951.png)

While `SpamAssassin` the average is about 6s:
![image](https://user-images.githubusercontent.com/55171818/183621804-0b96a4fc-ef8d-413d-800c-219b32c770ef.png)

Should we need to consider the usage of this long checking in our mailet pipeline (synchronous processing)?

**Comment by chibenwa** [comment]
```
    @Test
    void checkSpamEmailWithExactPasswordHeaderShouldWork() {
        RequestSpecification rspamdApi = WebAdminUtils.spec(Port.of(rSpamDExtension.dockerRSpamD().getPort()));

        for (int i = 0; i < 20; i ++) {
            final Stopwatch started = Stopwatch.createStarted();
            rspamdApi
                .header(new Header("Password", PASSWORD))
                .body(ClassLoader.getSystemResourceAsStream("mail/spam/spam8.eml"))
                .post("checkv2")
                .then()
                .statusCode(HttpStatus.OK_200)
                .body("action", is("reject"));
            System.out.println("Took " + started.elapsed(TimeUnit.MILLISECONDS) + " ms");
        }
    }
```

Result in :

```
Took 9327 ms
Took 744 ms
Took 307 ms
Took 274 ms
Took 268 ms
Took 308 ms
Took 296 ms
Took 301 ms
Took 310 ms
Took 279 ms
Took 329 ms
Took 302 ms
Took 322 ms
Took 327 ms
Took 308 ms
Took 312 ms
Took 298 ms
Took 287 ms
Took 582 ms
Took 265 ms
```

To me it looks like the initial request in itself does massive resource allocation, follow up calls are 40x faster.

I also benchmarked concurrency:

```
        final Stopwatch started = Stopwatch.createStarted();
        ConcurrentTestRunner.builder()
            .operation((a, b) -> WebAdminUtils.spec(Port.of(rSpamDExtension.dockerRSpamD().getPort()))
                .header(new Header("Password", PASSWORD))
                .body(ClassLoader.getSystemResourceAsStream("mail/spam/spam8.eml"))
                .post("checkv2")
                .then()
                .statusCode(HttpStatus.OK_200)
                .body("action", is("reject")))
            .threadCount(10)
            .operationCount(20)
            .runSuccessfullyWithin(Duration.ofMinutes(1));
        System.out.println("Took (10x20) " + started.elapsed(TimeUnit.MILLISECONDS) + " ms");
```

Resulted in (after warmup)

```
Took (10x20) 6257 ms
```

Which means that checkv2 latencies are still ~300ms with 10 concurrent threads.

Playing with the count of threads...

```
Took (10x20) 6257 ms (so ~32 mail.sec)
Took (20x20) 6305 ms (so ~63 mail.sec)
Took (40x20) 10325 ms (so ~77 mail.sec)
Took (80x20) 18678 ms (so ~80 mail.sec)
 ```

**Comment by quantranhong1999** [comment]
On my local:
```
Warming up with another spam message (eg spam1)...
Took 5048 ms
Bench the spam8 message for 20 times
Took 8031 ms
Took 8015 ms
Took 4024 ms
Took 4023 ms
Took 4024 ms
Took 8011 ms
Took 8018 ms
Took 5688 ms
Took 4021 ms
Took 4022 ms
Took 4127 ms
Took 4019 ms
Took 4051 ms
Took 4025 ms
Took 8019 ms
Took 8013 ms
Took 4020 ms
Took 4018 ms
Took 4021 ms
Took 4023 ms
```

Could be because of my slower pc... Hope we will get good performance on preprod.

**Comment by vttranlina** [comment]
> Could be because of my slower PC

On my strong PC 
```
[INFO] Running org.apache.james.rspamd.DockerRSpamDExtensionTest
Took 9031 ms
Took 8040 ms
Took 8033 ms
Took 8027 ms
Took 8033 ms
Took 8033 ms
Took 8030 ms
Took 8026 ms
Took 8025 ms
Took 8026 ms
Took 8026 ms
Took 8026 ms
Took 8022 ms
Took 8019 ms
Took 8025 ms
Took 8030 ms
Took 8022 ms
Took 8017 ms
Took 8026 ms
Took 8021 ms

```

**Comment by Arsnael** [comment]
Took out Clamav and tried a run similar to the last one I did here: https://github.com/linagora/james-project/issues/4606#issuecomment-1240223645
```
time smtp-source -A -C100 -r 1 -l 50000 -m 10000 -s 40 -d -c -f any@other.com -M other.com -t firstname203.surname203@upn.integration-open-paas.org localhost:2525

=> 2,42s user 6,25s system 2% cpu 5:32,12 total
```

```
# HELP RspamdScanner Generated from Dropwizard metric import (metric=RspamdScanner, type=com.codahale.metrics.Timer)
# TYPE RspamdScanner summary
RspamdScanner{quantile="0.5",} 0.083886079
RspamdScanner{quantile="0.75",} 0.20342374300000002
RspamdScanner{quantile="0.95",} 1.3421772790000002
RspamdScanner{quantile="0.98",} 1.6106127350000001
RspamdScanner{quantile="0.99",} 1.778384895
RspamdScanner{quantile="0.999",} 2.030043135
RspamdScanner_count 2443.0
```
Strangely enough it's worse... but well it's never really consistent with ovh infra anyways. I did other runs in the morning as well... Now there is likely more activity on ovh infra in france, I don't know if it can influence? Anyways...

![screenshot-localhost_11334-2022.09.08-14_49_53.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/9c29a612-98bf-414b-badc-99ab3170432e)

Still 17 msgs/s max with that setup... the clamav impact seems minimal IMO

I will do an other run maybe going back with 5k messages on 20 parallel threads and then I'm done I think

**Comment by Arsnael** [comment]
Can compare with this one: https://github.com/linagora/james-project/issues/4606#issuecomment-1240195579

time smtp-source -A -C100 -r 1 -l 50000 -m 5000 -s 20 -d -c -f any@other.com -M other.com -t firstname203.surname203@upn.integration-open-paas.org localhost:2525
=> 1,10s user 2,58s system 1% cpu 4:43,25 total

```
# HELP RspamdScanner Generated from Dropwizard metric import (metric=RspamdScanner, type=com.codahale.metrics.Timer)
# TYPE RspamdScanner summary
RspamdScanner{quantile="0.5",} 0.078118911
RspamdScanner{quantile="0.75",} 0.106430463
RspamdScanner{quantile="0.95",} 0.37539020700000003
RspamdScanner{quantile="0.98",} 0.513802239
RspamdScanner{quantile="0.99",} 0.5620367350000001
RspamdScanner{quantile="0.999",} 0.603979775
RspamdScanner_count 248.0
```
Seems slower as well without clamav again... Honestly I don't get it...

![screenshot-localhost_11334-2022.09.08-15_27_39.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/c7909371-2e71-46e5-b760-43b26bd7d129)

10 or 11 msgs/s...

**Comment by Arsnael** [comment]
As well if you don't externalize the virus scan to clamav maybe it has sth embedded that he uses, which would explain the longer time perhaps? Honestly I'm not sure
