### ISSUE TITLE
Triage existing ClamAV code, see if it works

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4600]
`mailet/standard/src/main/java/org/apache/james/transport/mailets/ClamAVScan.java`

Using the newly developped ClamAV docker container, try to write a test suite for this mailet...

**Comment by quantranhong1999** [comment]
This `ClamAVScan` work is actually not done and also its ClamAV socket command is outdated (was STREAM/PORT ClamAV commands but actually just INSTREAM now) so I tried a quick refactoring.

I reference [an example](https://faun.pub/part1-virus-detection-service-using-clamav-and-java-48212a2e5af9) for the ClamAV socket scanning and at first, it works:
![image.png](https://images.zenhubusercontent.com/5f7fe3b8b67a756e7c63d181/13f5a791-27e9-4917-8b35-cd2c054008a1)

TODO: parse the socket input stream to get the scanning result (FOUND/OK), refactor the code, and unit tests.

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1134
