### ISSUE TITLE
Performance tests for RSpamD + ClamAV

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4606]
- Configure RSpamD to call clamAV
 - Configure virus processor in James

Measure latencies + throughtput of Rspamd mailet (high + low load)

**Comment by Arsnael** [comment]
I had to raise the resources of rspamd... So for a smtp-source request like that:

```
time smtp-source -A -C100 -r 1 -l 500000 -m 5000 -s 20 -d -c -f any@other.com -M other.com -t firstname203.surname203@upn.integration-open-paas.org localhost:2525
```
I did a port-forward locally to port 25 (to my 2525) as we only have the ssl port exposed and it's a pain with smtp-source... It sends 5000 mails of 500kb each with 20 parallel threads, simulating quite a high load

So this time rspamd didn't crash, but this are the results from metrics endpoint:

```
# HELP RspamdScanner Generated from Dropwizard metric import (metric=RspamdScanner, type=com.codahale.metrics.Timer)
# TYPE RspamdScanner summary
RspamdScanner{quantile="0.5",} 4.865392639
RspamdScanner{quantile="0.75",} 12.213813247000001
RspamdScanner{quantile="0.95",} 16.039018495
RspamdScanner{quantile="0.98",} 30.064771071000003
RspamdScanner{quantile="0.99",} 30.064771071000003
RspamdScanner{quantile="0.999",} 30.064771071000003
RspamdScanner_count 1254.0
```

I'm not sure to remember but the unit is in seconds correct? 30s P99... the fact that rspamd scanner count is at 1254 instead of 5000 is likely saying lots of timeouts? Probably too heavy load for rspamd.

Also I took this screenshot from rspamd web endpoint:
![screenshot-localhost_11334-2022 09 07-16_53_11](https://user-images.githubusercontent.com/9005025/188851239-cedc3911-56cd-4470-9da8-c44015f88307.png)

So there was multiple runs where I was adjusting resources... the last run corresponding to the above metrics is the last line on the right.

I will try to do maybe a lighter load... After I don't know if there is ways to optimize that better (likely I guess) but that's not really impressive right?

**Comment by vttranlina** [comment]
> the fact that rspamd scanner count is at 1254 instead of 5000

one more point, The total messages in rspamd (picture) is 8884

**Comment by Arsnael** [comment]
In the picture is different because it counts the total number of messages since I restarted it this morning... I did a previous run at 5000k, and various ones before for testing with jmap perf tests etc...

but I did two runs at 5k... so 10k... plus the tests I was doing before... and total (8884) is still under that

**Comment by Arsnael** [comment]
And the rspamd listener has been removed :)

**Comment by vttranlina** [comment]
Is the RspamdScanner's metric declaration a local code?
I don't see where to see the declare it in code master

**Comment by Arsnael** [comment]
Much lighter run:

```
time smtp-source -A -C100 -r 1 -l 500000 -m 1000 -s 10 -d -c -f any@other.com -M other.com -t firstname203.surname203@upn.integration-open-paas.org localhost:2525

=>    0,39s user 1,20s system 0% cpu 7:51,93 total
```
Sending 1000 messages but with 10 parallel threads instead of 20 (clearly less violent)

Metrics:

```
# HELP RspamdScanner Generated from Dropwizard metric import (metric=RspamdScanner, type=com.codahale.metrics.Timer)
# TYPE RspamdScanner summary
RspamdScanner{quantile="0.5",} 0.205520895
RspamdScanner{quantile="0.75",} 0.34603007900000005
RspamdScanner{quantile="0.95",} 0.574619647
RspamdScanner{quantile="0.98",} 0.7675576310000001
RspamdScanner{quantile="0.99",} 1.3002342390000001
RspamdScanner{quantile="0.999",} 1.7028874230000002
RspamdScanner_count 249.0
```
Much better :)

Rspamd screenshot:
![screenshot-localhost_11334-2022 09 07-17_38_24](https://user-images.githubusercontent.com/9005025/188858971-e0969c10-b88f-4fdb-b0e1-32c1fe257066.png)

If we cunt the difference of messages between that screenshot and previous, missing 13? No idea why honestly

**Comment by Arsnael** [comment]
> Is the RspamdScanner's metric declaration a local code? I don't see where to see the declare it in code master

Honestly I forgot with metrics, but likely unrelated to number of requests? It does not match with stats from rspamd for sure anyways

**Comment by quantranhong1999** [comment]
Q: How did you access the Rspamd webadmin UI?
Do you expose the Rspamd service publicly or do you have some trick?

**Comment by chibenwa** [comment]
Can we try with smaller messages?

Average message size likely ranges at 50K messages. Can we try with 50K messages?

**Comment by chibenwa** [comment]
Also, any way to know which modules in Rspamd takes time?

Finally, how are the redis perf wise? Are we sanctionned from using K8S persistant volumes?

Last but not least can we also try with 2 Rspamd pods and see if it makes a difference?

**Comment by vttranlina** [comment]
> Q: How did you access the Rspamd webadmin UI?

I guess use the Len tool and mapping port locally.
![image](https://user-images.githubusercontent.com/81145350/189009944-fefb3a67-0abc-4200-b465-2cd5f99f3903.png)

**Comment by Arsnael** [comment]
> Q: How did you access the Rspamd webadmin UI?

Port forwarding yes (except I did it in command line)

> Average message size likely ranges at 50K messages. Can we try with 50K messages?

Sure.

> Also, any way to know which modules in Rspamd takes time?

No idea...

> Finally, how are the redis perf wise? Are we sanctionned from using K8S persistant volumes?

I don't think we have any kind of metrics to measure this? You realize we started from "please just look at the metrics we have in the endpoint for rspamd should be enough" to "please check an other bunch of fined grained metrics stuff that I don't even know if we have them"?

> Last but not least can we also try with 2 Rspamd pods and see if it makes a difference?

Not sure if rspamd is really scalable but can try I guess...

**Comment by Arsnael** [comment]
Seems we can maybe access some metrics from Redis actually... that seems we can access via the redis cli? Need to dig more into it

**Comment by Arsnael** [comment]
Would like to add: the dns blacklist module can't actualize its list:
```
2022-09-08 03:15:11 #191(controller) <imhkkk>; monitored; rspamd_monitored_dns_cb: DNS query blocked on multi.uribl.com (127.0.0.1 returned), possibly due to high volume
```
I would think likely problems of trust with the IP (rspamd being in a closed k8s cluster not really accessible from outside initially... I think the answer `127.0.0.1 returned` speaks for itself)

**Comment by Arsnael** [comment]
Adding as well as didn't really have time yet to launch the ham and spam routes the bayes does not have enough data yet to really kick in too

**Comment by Arsnael** [comment]
So this time 5000 messages with 20 parallel threads and 50kb size each (which should be like a more normal load):

```
time smtp-source -A -C100 -r 1 -l 50000 -m 5000 -s 20 -d -c -f any@other.com -M other.com -t firstname203.surname203@upn.integration-open-paas.org localhost:2525

=>1,18s user 3,13s system 1% cpu 4:46,08 total
```
Metrics:
```
# HELP RspamdScanner Generated from Dropwizard metric import (metric=RspamdScanner, type=com.codahale.metrics.Timer)
# TYPE RspamdScanner summary
RspamdScanner{quantile="0.5",} 0.077594623
RspamdScanner{quantile="0.75",} 0.109051903
RspamdScanner{quantile="0.95",} 0.200278015
RspamdScanner{quantile="0.98",} 0.262143999
RspamdScanner{quantile="0.99",} 0.331350015
RspamdScanner{quantile="0.999",} 0.513802239
RspamdScanner_count 1250.0
```
Looks rather good to me :)

Rspamd graphics:

![screenshot-localhost_11334-2022.09.08-11_12_58.png](https://images.zenhubusercontent.com/5ef2b3b0a7d2c63f71b1e1f7/479ad3de-be06-4876-8270-7d4903caaa21)

Looks like rspamd was able to treat an average of 15 messages/second on this

**Comment by Arsnael** [comment]
Can't scale up rspamd at the moment... Can't attach the same volume to multiple pods. My guess is we might maybe switch the chart to a statefulset and not a deployment for this. 

But my knowledge is limited, need more time to sort it out, and you seem to wanna rush this for the end of sprint so... Will pass on this one for now if you don't mind

**Comment by quantranhong1999** [comment]
> So this time 5000 messages with 20 parallel threads and 50kb size each (which should be like a more normal load)

FYI: `So with this load rate (1500 messages per second) and with the average size of messages around 2Kb, Rspamd processes each message in around 100ms in average. I hope these numbers could give one some impression about Rspamd performance in general.`
rf: https://rspamd.com/misc/2019/05/16/rspamd-performance.html

It is clear that their 2KB is small for average mail size.

**Comment by Arsnael** [comment]
> It is clear that their 2KB is small for average mail size.

Sounds very light to me indeed

**Comment by Arsnael** [comment]
Run with 10000 messages of 50kb with 40 parallel threads 

```
time smtp-source -A -C100 -r 1 -l 50000 -m 10000 -s 40 -d -c -f any@other.com -M other.com -t firstname203.surname203@upn.integration-open-paas.org localhost:2525
=> 2,43s user 5,81s system 2% cpu 5:31,14 total
```

Metrics:
```
# HELP RspamdScanner Generated from Dropwizard metric import (metric=RspamdScanner, type=com.codahale.metrics.Timer)
# TYPE RspamdScanner summary
RspamdScanner{quantile="0.5",} 0.071303167
RspamdScanner{quantile="0.75",} 0.11062476700000001
RspamdScanner{quantile="0.95",} 0.809500671
RspamdScanner{quantile="0.98",} 0.9730785270000001
RspamdScanner{quantile="0.99",} 1.052770303
RspamdScanner{quantile="0.999",} 1.333788671
RspamdScanner_count 2503.0
```
Higher but still 1s in P99 I think it's acceptable?

Rspamd throughput:

![screenshot-localhost_11334-2022 09 08-11_56_12](https://user-images.githubusercontent.com/9005025/189038426-38839182-1314-424c-9d77-7c472b15cdb8.png)

Seems hard to get above 17 msgs/s with this setup

**Comment by quantranhong1999** [comment]
Did you try to increase CPU resources for rspamd (and maybe even clamav) to see if there is diff?

**Comment by chibenwa** [comment]
> Higher but still 1s in P99 I think it's acceptable?

Yes

> Can't scale up rspamd at the moment... Can't attach the same volume to multiple pods. My guess is we might maybe switch the chart to a statefulset and not a deployment for this.

What's in that volume?

Not scaling Rspamd is a pain point... We will need to eventually work on that but it could have had been nice to see big throughtput. IMO we need to have at the very least a ticket for it.

**Comment by Arsnael** [comment]
If somebody else wants to have fun with it... https://github.com/linagora/james-project-private/issues/472
