### ISSUE TITLE
NPE JmapApiRoutes

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4611]
I caught a NPE during a quick perf test jmap draft run on our staging env, seems to be related `CassandraMessageIdToImapUidDAO` class:

***
{"timestamp":"2022-09-06T03:08:52.653Z","level":"ERROR","thread":"s1-io-2","mdc":{"protocol":"JMAP","ip":"10.2.1.28","real-ip":"51.68.40.116"},"logger":"org.apache.james.jmap.http.JMAPApiRoutes","message":"Unexpected error","context":"default","exception":"java.lang.NullPointerException: Cannot invoke \"java.time.Instant.toEpochMilli()\" because \"<parameter1>\" is null\n\tat java.base/java.util.Date.from(Unknown Source)\n\tat org.apache.james.mailbox.cassandra.mail.CassandraMessageIdToImapUidDAO.toComposedMessageIdWithMetadata(CassandraMessageIdToImapUidDAO.java:406)\n\tat reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)\n\tat com.datastax.dse.driver.internal.core.cql.reactive.ReactiveResultSetSubscription.doOnNext(ReactiveResultSetSubscription.java:364)\n\tat com.datastax.dse.driver.internal.core.cql.reactive.ReactiveResultSetSubscription.drain(ReactiveResultSetSubscription.java:236)\n\tat com.datastax.dse.driver.internal.core.cql.reactive.ReactiveResultSetSubscription.lambda$fetchNextPageAndEnqueue$2(ReactiveResultSetSubscription.java:358)\n\tat java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)\n\tat java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)\n\tat com.datastax.oss.driver.internal.core.cql.CqlRequestHandler.setFinalResult(CqlRequestHandler.java:324)\n\tat com.datastax.oss.driver.internal.core.cql.CqlRequestHandler.access$1500(CqlRequestHandler.java:95)\n\tat com.datastax.oss.driver.internal.core.cql.CqlRequestHandler$NodeResponseCallback.onResponse(CqlRequestHandler.java:655)\n\tat com.datastax.oss.driver.internal.core.channel.InFlightHandler.channelRead(InFlightHandler.java:257)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n"}
***

**Comment by quantranhong1999** [comment]
I believe that somehow we inserted a `null` value for `INTERNAL_DATE` column in `imapUid` table. Now we read that, it's a null so we can not parse it to Date using `java.time.Instant.toEpochMilli()`.

Reproduce step:
1. Try to insert `null` value for `INTERNAL_DATE` column in `imapUid` table (dirty way, I could not find any other way to properly reproduce this with current code without `NoSuchElementException`):
  Change line 276 of `CassandraMessageIdToImapUidDAO` to insert directly a `null` for `INTERNAL_DATE`.
2. Read that entry with a `NullPointerException`:
```java
    @Test
    void testNPEInternalDate() throws NoSuchElementException {
        CassandraMessageId messageId = CassandraMessageId.Factory.of(Uuids.timeBased());
        CassandraId mailboxId = CassandraId.timeBased();
        MessageUid messageUid = MessageUid.of(1);

        testee.insert(CassandraMessageMetadata.builder()
                .ids(ComposedMessageIdWithMetaData.builder()
                    .composedMessageId(new ComposedMessageId(mailboxId, messageId, messageUid))
                    .flags(new Flags())
                    .modSeq(ModSeq.of(1))
                    .threadId(ThreadId.fromBaseMessageId(messageId))
                    .build())
                .internalDate(Optional.empty()) // enforce insert null value for INTERNAL_DATE column anyway
                .bodyStartOctet(18L)
                .size(36L)
                .headerContent(Optional.of(HEADER_BLOB_ID_1))
                .build())
            .block();

        assertThatThrownBy(() -> testee.retrieveAllMessages().collectList().block())
            .isInstanceOf(NullPointerException.class);
    }
``` 

I guess somehow with old code we were allowed to insert a null value. I check the current code (`CassandraMessageIdToImapUidDAO` scope) we can not insert a null value for e.g `INTERNAL_DATE` without `NoSuchElementException` which means it should fatally fail when inserting already. What are other cases that you could think of?

I think the current code should be fine avoiding creating more of this case. But there is a code smell to me that in `CassandraMessageMetadata` we consider e.g `internalDate` as Optional but when inserting/selecting to/from DB we consistently enforce using its value (just like it is always present). We also do it in `CassandraMessageMetadata::asMailboxMessage`.

=> **Do you think this is an issue that should be improved (either enforce CassandraMessageMetadata' `internalDate`... away from Optional or carefully check their present)?**
I would prefer enforcing `internalDate`... away from Optional cause of the way we are using them - it's just like they are always there.

**Comment by chibenwa** [comment]
How about https://github.com/apache/james-project/blob/master/upgrade-instructions.md#rework-message-denormalization as a root cause ?

> I think the current code should be fine avoiding creating more of this case. But there is a code smell to me that in CassandraMessageMetadata we consider e.g internalDate as Optional but when inserting/selecting to/from DB we consistently enforce using its value (just like it is always present). We also do it in CassandraMessageMetadata::asMailboxMessage.

To handle cases where the migration is badly applied / not yet applied, we need to treat `internalDate`, `bodyStartOctet`, `size`, `headerContent` fields as optional.

This regression was introduced as part of the Cassandra driver 4 migration.

**Comment by chibenwa** [comment]
(this could be considered a 0.6.2 blocker)

**Comment by quantranhong1999** [comment]
> Should be a no-brainer, easy to fix.

Do you mean a fix from migration point of view (We furthermore propose a migration task for adding missing information to `imapUidTable` and `messageIdTable` and thus ensure you leverage the benefits of this change) or a fix in the code (handle the possible null case)?

**Comment by chibenwa** [comment]
Yez thats it handle null case with optionzl please

**Comment by Arsnael** [comment]
Can we close this issue now that https://github.com/apache/james-project/pull/1182 has been merged?
