### ISSUE TITLE
Missing mails with JMAP???

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4612]
From the TMail flutter team: https://github.com/linagora/tmail-flutter/issues/929

They were surprised to see with jmap clients (OpenPaas -> jmap-draft, TMail -> jmap-rfc) that the counter of unread emails didn't match the actual number of unread emails they could see when opening the mailbox.

After checking the same mailbox with IMAP (like Thunderbird), we could see those missing emails. Reading them would clear the unread flag out and on jmap the counter would become accurate.

We seem to have some issues with missing mails when fetching mailbox messages with JMAP.

Need to investigate, find the issue and fix it.

**Comment by chibenwa** [comment]
Mailbox id?

Is there some stuff un dead letter?

How is the "email query view" projection compared to messageIdTable?

Recent mails?

**Comment by Arsnael** [comment]
> Mailbox id?

In my case: 3dcf7780-ef6a-11ea-8665-3109e4489b2e
And I have at least 4 mails in this case on that mailbox

> Is there some stuff on dead letter?

Yes but I think we have never really been much looking at it... There is quite a lot of stuff. But when fetching groups:

```
[
  "org.apache.james.mailbox.store.quota.ListeningCurrentQuotaUpdater$ListeningCurrentQuotaUpdaterGroup",
  "org.apache.james.jmap.event.ComputeMessageFastViewProjectionListener$ComputeMessageFastViewProjectionListenerGroup",
  "org.apache.james.events.EventDispatcher$DispatchingFailureGroup",
  "org.apache.james.jmap.change.MailboxChangeListenerGroup",
  "org.apache.james.jmap.event.PropagateLookupRightListener$PropagateLookupRightListenerGroup",
  "org.apache.james.jmap.event.PopulateEmailQueryViewListener$PopulateEmailQueryViewListenerGroup",
  "org.apache.james.quota.search.elasticsearch.events.ElasticSearchQuotaMailboxListener$ElasticSearchQuotaMailboxListenerGroup",
  "org.apache.james.mailbox.elasticsearch.events.ElasticSearchListeningMessageSearchIndex$ElasticSearchListeningMessageSearchIndexGroup"
]
```

I thought likely between `ComputeMessageFastViewProjectionListener` and `PopulateEmailQueryViewListener` perhaps? But `PopulateEmailQueryViewListener` has only one failed event, and flutter team noticed it too...

`ComputeMessageFastViewProjectionListener` has quite a good list of failures though. 
 
> How is the "email query view" projection compared to messageIdTable?

That I will try to check, that would make sense with the number of failures in `ComputeMessageFastViewProjectionListener` dead letter, right?

> Recent mails?

Yes in my case:
- 1 mail from 05/09
- 3 mails from 01/09

**Comment by Arsnael** [comment]
> How is the "email query view" projection compared to messageIdTable?

The email query view projection is composed of those 3 tables:
- email_query_view_date_lookup
- email_query_view_sent_at
- email_query_view_received_at

correct?

I counted the number of entries between those and messageidtable table for the mailboxId I posted above:

```
select count(*) from messageidtable where mailboxid=3dcf7780-ef6a-11ea-8665-3109e4489b2e;
=> 14237

select count(*) from email_query_view_sent_at where mailboxid=3dcf7780-ef6a-11ea-8665-3109e4489b2e;
=> 8018
```
To which then I thought we introduced the email query view quite late compared to the messageidtable so normal? (maybe I don't know)

So I tried to refine with the timestamps:

```
select count(*) from messageidtable where mailboxid=3dcf7780-ef6a-11ea-8665-3109e4489b2e and internaldate >= '2022-08-31 00:00:00+0000' ALLOW FILTERING;
=> 106

select count(*) from email_query_view_received_at where mailboxid=3dcf7780-ef6a-11ea-8665-3109e4489b2e and receivedat >= '2022-08-31 00:00:00+0000';
=> 105
```
Miss one... but I have 4 that don't show up though on LNG jmap.
Also if I use `2022-09-01 00:00:00+0000` (the day after) as a timestamp (so my missing mails are supposed to be after) then I get 96 for both.

@chibenwa if it talks to you... ^^'

**Comment by chibenwa** [comment]
Could be inconsistencies between messageIdTable <=> imapUidTable too

**Comment by Arsnael** [comment]
I can't seem to do a count on imapuidtable to compare with messageidtable...

Should we just run the task to solve message inconsistencies then and see?

**Comment by chibenwa** [comment]
Yes

**Comment by Arsnael** [comment]
Ok I just started the task for it. Let's hope it solves the problem

**Comment by Arsnael** [comment]
the message inconsistencies fixing task?

**Comment by Arsnael** [comment]
So... I believe there was a time frame last week when ossa restarted the james server, which then killed the task that was running so... I'm not sure sure how we should treat this, as with the number of mails we have it's a long task and every time the server is unstable it will be restarted...
