### ISSUE TITLE
Rspamd: per user reporting

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4614]
Todo have a different score for Bab and Alice

https://github.com/apache/james-project/pull/1157

**Comment by chibenwa** [comment]
To make progress on this, as part of the Rspamd presentation we identified the following actions

 - [ ] Dump Rspamd configuration 
 - [ ] Try switching from `/local.d/` to `/overrides.d/` directory...

**Comment by quantranhong1999** [comment]
> Dump Rspamd configuration

https://pastebin.com/xSrnwmKm
I dumped the rspamd configuration and I think we configured the per-user ones as we wanted.

**Comment by quantranhong1999** [comment]
Reworked: https://github.com/apache/james-project/pull/1191 (still on Tung PR)
The per-user Bayes works now.
