### ISSUE TITLE
[3.7.2] More backports

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4616]
- c57bf62155843f2577d2c62a205d5e064b2ea5d8 `JAMES-3803 RemoteDelivery uses different scheduler for dequeuing (#1121)`
 - 6003ecb236b4a2cab38ba73056e9babbaac15fc7 `JAMES-343 Mail: Fix resetting DSN parameters`
 - 5ad5cb6a4e07432502350f4ee1dee9a50fae9d01 `JAMES-3431 Stricter validation for DSN ENVID (#1002)`
 - JAMES-3753 Fix FlowedMessageUtils.deflow() (#972)
 - 06260220051a42522ff501e75f689d59f640744d `JAMES-3744 remove redundant hashmaps which lead to OOM`

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1197
