### ISSUE TITLE
Quota/get

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4624]
### Why
We need to implement Quota/get as a part of Quota (almost final) specs: https://www.ietf.org/archive/id/draft-ietf-jmap-quotas-05.html#name-quota-get

#### Sample request/response
Request:
```json
[[ "Quota/get", {
  "accountId": "u33084183",
  "ids": null
}, "0" ]]
```

Response:
```json
[[ "Quota/get", {
  "accountId": "u33084183",
  "state": "78540",
  "list": [{
    "id": "2a06df0d-9865-4e74-a92f-74dcc814270e",
    "resourceType": "count",
    "used": 1056,
    "warnLimit": 1600,
    "softLimit": 1800,
    "limit": 2000,
    "scope": "account",
    "name": "bob@example.com",
    "description": "Personal account usage",
    "datatypes" : [ "Mail", "Calendar", "Contact" ]
  }, {
    "id": "3b06df0e-3761-4s74-a92f-74dcc963501x",
    "resourceType": "octets",
    ...
  }, ...],
  "notFound": []
}, "0" ]]

```

### How
  - Data models: define POJO...
```scala
case class UnparsedQuotaId(id: Id)

case class QuotaIds(value: List[UnparsedQuotaId])

case class QuotaGetRequest(accountId: AccountId,
                           ids: Option[QuotaIds],
                           properties: Option[Properties]) extends WithAccountId

case class JmapQuota(id: Id,
                     resourceType: ResourceType,
                     used: UnsignedInt,
                     limit: UnsignedInt,
                     scope: Scope,
                     name: QuotaName,
                     dataTypes: List[DataType],
                     warnLimit: Option[UnsignedInt],
                     softLimit: Option[UnsignedInt],
                     description: Option[QuotaDescription])

case class QuotaName(string: String)

case class QuotaDescription(string: String)

sealed trait ResourceType {
  def asString(): String
}

case object CountResourceType extends ResourceType {
  override def asString(): String = "count"
}

case object OctetsResourceType extends ResourceType {
  override def asString(): String = "octets"
}

sealed trait Scope {
  def asString(): String
}

case object AccountScope extends Scope {
  override def asString(): String = "account"
}

case object DomainScope extends Scope {
  override def asString(): String = "domain"
}

case object GlobalScope extends Scope {
  override def asString(): String = "global"
}

trait DataType {
  def asString(): String
}

case object MailDataType extends DataType {
  override def asString(): String = "Mail"
}

case class QuotaGetResponse(accountId: AccountId,
                            state: UuidState,
                            list: List[JmapQuota],
                            notFound: QuotaNotFound)

case class QuotaNotFound(value: Set[UnparsedQuotaId]) {
  def merge(other: QuotaNotFound): QuotaNotFound = QuotaNotFound(this.value ++ other.value)
}
```

- `JmapQuotaManagerWrapper` (take a look at `QuotaReader`) converts James quota to JMAP quota standard + tests:

  ```scala
    getQuota(username: Username, quotaId: String): JmapQuota
    getQuotas(username: Username): Set[JmapQuota]
  ```

   We need to think about the QuotaId query/storage here.
     => I think about the way to avoid modifying the storage layer. Let's say we implicitly define an immutable value for each quota entry: Base64 encoding of `{$username}_message_quota/{$domain}_size_quota/global_message_quota/...` then:
     - Option 1 (optimal): we could decode the string Id and do further processing (check username/domain in access of that user, get quota type (message/storage), query to QuotaManager)
     - Option2 (not optimal but acceptable IMO): we can just get all quotas of a user and filter the Id.

- QuotaSerializer
- Quota/get method + integration tests

### Edge cases
- Note that quota object can contain a fixed value, an empty value (null) or an unlimited value (-1):
  - Unlimited quota case: the spec does not mention this case:`limit: UnsignedInt The hard limit set by this quota.` => We break the spec and return `-1` as an unlimited identifier?
  - empty value case -> consider as not found.
- James supports more scopes: `computed` and `occupation`. Should we introduce new custom scopes or just skip them?

### DoD
Pass integration tests.

**Comment by chibenwa** [comment]
`QuotaId` is the quotaroot valid?

Can't we hash the quota root in a worst case scenario?

**Comment by quantranhong1999** [comment]
> Can't we hash the quota root in a worst case scenario?

Yes, we can. Hash is 1-way function so we can compare (like my option 2) but not decode.

**Comment by quantranhong1999** [comment]
> Or encode in base64 ? (2-way)

That is also what I proposed: `Base64 encoding of {$username}_message_quota/{$domain}_size_quota/global_message_quota/...` then use my option 1 to decode.

The string structure to be encoded/decoded can be discussed more, basically that is the idea.

**Comment by chibenwa** [comment]
Encoding the quotaroot is more appropriate...

**Comment by vttranlina** [comment]
- Unlimited = no quota

**Comment by quantranhong1999** [comment]
warnLimit, softLimit, description => Optional.empty
