### ISSUE TITLE
Modular healthcheck

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4625]
https://issues.apache.org/jira/browse/JAMES-3826

Define extra healthchecks: `healthcheck.properties`

```
additional.healchecks=FQDNA,FQDNB
```

Use GuiceGenericLoader within PeriodicalHealthChecksModule to inject cusom helth checks within `Set<HealthCheck>.

Add a little integration test on the memory server to ensure this works.

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1220
