### ISSUE TITLE
Quota/query method

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4626]
Implement the quota/query method as defined in https://datatracker.ietf.org/doc/draft-ietf-jmap-quotas/

You need to use the existing underlying storage for quota and translate it into a quota/query response.

For example:

```
{
  "using": [
    "urn:ietf:params:jmap:core",
    "urn:ietf:params:jmap:mail",
    "urn:ietf:params:jmap:quota"],
  "methodCalls": [[
    "Quota/query",
    {
      "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
      "filter": {"scopes":"account"}
    },
    "c1"]]
}
```

Should return:

```
{
    "sessionState": "[SESSION_STATE]",
    "methodResponses": [[
            "Quota/query",
            {
                "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
                "queryState": "12345abc",
                "canCalculateChanges": false,
                "position": 0,
                "limit": 256,
                "ids": ["2", "3"]
            },
            "c1"
        ]]
}
```

**DoD**: integration tests

**Comment by chibenwa** [comment]
Which strategy can we follow to implement in a naive way.

**Comment by Arsnael** [comment]
Again honestly I forgot that part of the grooming but... what do you call naive already?

**Comment by chibenwa** [comment]
Naive here means "enough to honir the spec without changing our data model".

We could read all quota then do filtering on James side.

**Comment by vttranlina** [comment]
QuotaManager

**Comment by quantranhong1999** [comment]
How to implement: filtering user quotas list against input quota ids
