### ISSUE TITLE
Documentation Quota

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4628]
Write the documentation about quotas:

- next to `server/protocols/jmap-rfc-8621/doc/specs/spec/quota`, add the rfc one in https://datatracker.ietf.org/doc/draft-ietf-jmap-quotas/
- should we add a quotas section in antora? `docs/modules/concepts/pages/protocols/jmap.adoc` is an empty page... but maybe could be the first contribution?
- add an entry in the changelog

Anything else?

**Comment by chibenwa** [comment]
> in server/protocols/jmap-rfc-8621/doc/specs/spec/quota , change the custom jmap quota doc to the rfc one in https://datatracker.ietf.org/doc/draft-ietf-jmap-quotas/

Actually we need both.

We need to deprecate the old quota stuff before removing it...

**Comment by Arsnael** [comment]
https://github.com/apache/james-project/pull/1241
Probably should wait for the quotas implem to be done before merging it though
