### ISSUE TITLE
[Preprod] James stops consuming taskManagerWorkQueue queue

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4633]
`... no consumers ...` on RabbitMQ management for `taskManagerWorkQueue` queue.

There are many waiting tasks and 16 in-progress tasks:
https://james-admin.upn.integration-open-paas.org/tasks?status=inprogress

Looking at the tasks:
- There are no tasks being executed from 21/9 -> 28/9
- Only some tasks is executed around 3 4 Am (container time) 29/9 ~ just around the time we redeploy James on preprod
- The lastest finished task is around `2022-09-29T04:57` then no more finish
- The latest inProgress task is `FeedSpamToRspamdTask` which starts at `2022-09-29T04:57:16` - just around the time no more tasks are finished. -> seems suspicious.

I expect restarting James could bring consumers back, then let's observe the issue.

**Comment by vttranlina** [comment]
I thought the pr [JAMES-3825 Cancel tasks upon graceful shutdown](https://github.com/apache/james-project/pull/1214) 
will cancel the task before shutdown the server.
But it did not work
The `SerialTaskManagerWorker#close` method has been invoked, but it did not update the task status is canceled.

**Comment by chibenwa** [comment]
Maybe it was not given enough time to complete eg before cassandra resources shutdown?

**Comment by vttranlina** [comment]
Fix pr: https://github.com/apache/james-project/pull/1272
