### ISSUE TITLE
FeedSpamToRspamdTask hangs forever

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4634]
Just manually run a FeedSpamToRspamdTask. At first, it runs quite well, then after about 15m it just hangs at `"reportedSpamMessageCount": 7661` forever:
https://james-admin.upn.integration-open-paas.org/tasks/328ac94a-8bc1-4e0e-97af-26b0e2cd01c5
Even the timestamp does not change over time and also Rspamd learning throughput back to 0. Maybe some thread deadlock? (quickly try to get thread dump but "stack command is not found" on preprod pods)

#### Consequences
Afterward submitted tasks are in `waiting` status forever.

**Comment by chibenwa** [comment]
You need to install jre to use jstack.

Any logs?

**Comment by quantranhong1999** [comment]
> Any logs?

At that time (~6 PM) I can not access James preprod log (the logging system for James preprod was unstable at that moment).

Now I query "ERROR" again but there is an error `rpc error: code = ResourceExhausted desc = grpc: received message larger than max (11998447 vs. 8388608)`: https://staging-monitor.lin-saas.com/d/logs-saas-emaily-staging/application-logs?orgId=1&var-datasource=logs-saas-emaily-staging&var-app=tenant-upn%2Fjames&var-search=ERROR&from=now-6h&to=now
I don't get why the "INFO"/ "WARN" query work though. A bit doubt if we really emit that many 11998447 error log entries...

> Also share params of the task?

```json
{
    "additionalInformation": {
        "type": "FeedSpamToRspamdTask",
        "timestamp": "2022-09-29T10:58:53.550399477Z",
        "spamMessageCount": 21546,
        "reportedSpamMessageCount": 7661,
        "errorCount": 0,
        "runningOptions": {
            "periodInSecond": 86400,
            "messagesPerSecond": 10,
            "samplingProbability": 1.0,
            "classifiedAsSpam": null
        }
    },
    "type": "FeedSpamToRspamdTask",
    "submittedFrom": "james-jmap-99c55999d-z4bq9",
    "executedOn": "james-imap-smtp-85b6cf4d58-dczx6",
    "cancelledFrom": null,
    "submitDate": "2022-09-29T10:45:58.844+0000",
    "status": "completed",
    "taskId": "328ac94a-8bc1-4e0e-97af-26b0e2cd01c5",
    "startedDate": "2022-09-29T10:45:58.948+0000",
    "completedDate": "2022-09-29T10:58:53.575+0000"
}
```

**Comment by chibenwa** [comment]
That's the log entry size.

One biiiiiiig log.

By choosing smaller time ranges, you can still push forward with logs investigations....

**Comment by vttranlina** [comment]
My investigation:
- Hem chart issue: I tried to print Rspamd password when James start and I saw the password in James is `${env:OP_RSPAMD_PASSWORD}`, maybe the seq script has been wrong. (Now, I quickly fix it by hardcode value in Len/ConfigMaps)
- Rspamd not support HTTP reactive. Should we wrap RspamdHttpClient in BlockingCallWrapper?
- I tried to remove the calling to rspamd in Task, and the tasks were completed quickly => the issue related to the RsamdHttpClient 
- I tried to decrease the messagePerSecond to 2, and it was good

**Comment by chibenwa** [comment]
> Rspamd not support HTTP reactive. Should we wrap RspamdHttpClient in BlockingCallWrapper?

I do not understand. Why do you say so? You have logs?

> I tried to decrease the messagePerSecond to 2, and it was good

Ok then if we should not go too high that's OK. What was the previous value?

**Comment by vttranlina** [comment]
> I do not understand. Why do you say so? You have logs?

I checking HTTP log when request, and the HTTP protocol is http1.1


> Ok then if we should not go too high that's OK. What was the previous value?

default is 10. I tried to other 10, 20, 50, 100 and all is hanging

**Comment by chibenwa** [comment]
> I checking HTTP log when request, and the HTTP protocol is http1.1

Yes, and ?

> default is 10. I tried to other 10, 20, 50, 100 and all is hanging

Did we try 5 ?

**Comment by chibenwa** [comment]
I suggest writting a test with concurrentTestRunner: learns 1000 messages 10 at a time.

The goal would be to have a test proving that Rspamd learns deadlocks under load.

With this we could open a bug report to them.

**Comment by vttranlina** [comment]
> Yes, and ?

I remember the reactive support from http 2.0.
As my suggestion above: "Should we wrap RspamdHttpClient in BlockingCallWrapper?"

> Did we try 5 ?

Not yet, I tried to 2, because want to quickly ensure the deadlock from Rspamd

> I suggest writting a test with concurrentTestRunner: learns 1000 messages 10 at a time.

Let me do it

**Comment by Arsnael** [comment]
>     * Hem chart issue: I tried to print Rspamd password when James start and I saw the password in James is `${env:OP_RSPAMD_PASSWORD}`, maybe the seq script has been wrong. (Now, I quickly fix it by hardcode value in Len/ConfigMaps)

The rspamd password has been disabled so I hope you did not put it back because you forgot to update your local helm chart...

**Comment by vttranlina** [comment]
>  I hope you did not put it back because you forgot to update your local helm chart...

NO, I didn't

**Comment by quantranhong1999** [comment]
> The goal would be to have a test proving that Rspamd learns deadlocks under load.

I observed the Rspamd learning throughput (when running the FeedSpam task) and it is never above 1 message/sec. So this could encourage the theory IMO.

**Comment by vttranlina** [comment]
The concurrentTest already at https://github.com/apache/james-project/pull/1227

//  I limit the use of Jame's utils for easier follow

My view: the hanging of task will be easier produce when I decrease memory of rspamd

**Comment by vttranlina** [comment]
> Proposal: retry on preprod, set 01 RspamD pod and give it 1 VCPU + 2GB limit and see what happends

It still hanging (messagesPerSecond = 10), 
The usage memory is not exceed limit. 
![image](https://user-images.githubusercontent.com/81145350/193775613-d5536982-3874-44de-be28-f65f0b6263e9.png)

**Comment by vttranlina** [comment]
> Do you suceed to reproduce locally?

NO, When I set rspamd container memory on local is 1.4GB. The process work. Even I set the request concurrency = 32, 100... and I also increased the size of the message. 
I monitored the memory of rspamd, it was increased to near 1.4GB, and decreased. But the process didn't hang.

**Comment by chibenwa** [comment]
What message size did you use?

**Comment by vttranlina** [comment]
> What message size did you use?

100000, 1000000 byte.
_______________________

I tried to forward rspamd port from preprod to local, and run concurrentTest on my local (with preprod rspamd), 
Everything runs fine.
After that, I see on preprod, when `spamMessageCount` is far enough from `reportedSpamMessageCount`, the hanging will happen

PR fix it: https://github.com/apache/james-project/pull/1230/files

**Comment by chibenwa** [comment]
How about using `delaySequence` in ReactorUtils.throttle directly ?

**Comment by vttranlina** [comment]
After a debugging day, I don't think we should fix `ReactorUtils::throttle` (exactly is I don't know how to fix/improve it)

_________

I realize that when I add ` .timeout(Duration.ofSeconds(15))` after `rspamdHttpClient.reportAsSpam`, the tasks work fine, (messagePersecond = 100),  (code bellow)
After that `context.incrementErrorCount()` has been invoke. 
I doubt the definition `responseTimeout` of HttpClient in RspamdHttpClient has problem.
But when I write unit test for it, it passed. (https://github.com/apache/james-project/pull/1231)


```
    @Override
    public Result run() {
        Optional<Date> afterDate = runningOptions.getPeriodInSecond().map(periodInSecond -> Date.from(clock.instant().minusSeconds(periodInSecond)));
        return messagesService.getMailboxMessagesOfAllUser(SPAM_MAILBOX_NAME, afterDate, runningOptions, context)
            .transform(ReactorUtils.<MessageResult, Task.Result>throttle()
                .elements(runningOptions.getMessagesPerSecond())
                .per(Duration.ofSeconds(1))
                .forOperation(messageResult -> rspamdHttpClient.reportAsSpam(Throwing.supplier(() -> messageResult.getFullContent().getInputStream()).get())
                    .timeout(Duration.ofSeconds(15))
                    .then(Mono.fromCallable(() -> {
                        context.incrementReportedSpamMessageCount(1);
                        return Result.COMPLETED;
                    }))
                    .onErrorResume(error -> {
                        LOGGER.error("Error when report spam message to Rspamd", error);
                        context.incrementErrorCount();
                        return Mono.just(Result.PARTIAL);
                    })))
            .reduce(Task::combine)
            .switchIfEmpty(Mono.just(Result.COMPLETED))
            .block();
    }
```

**Comment by chibenwa** [comment]
👍 nice work!
