### ISSUE TITLE
Tweak the search overrides configuration

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4639]
We observed degraded IMAP commands performance regarding override search.

Regarding Cassandra, search overrides for `searchUnseen`, `searchDeleted` might filter a lot of data when executed against Cassandra, and might in the end be more optimal executed against a search index...

Maybe a little configuration tweak to be made:
```
opensearch.search.overrides=org.apache.james.mailbox.cassandra.search.AllSearchOverride, org.apache.james.mailbox.cassandra.search.DeletedWithRangeSearchOverride,org.apache.james.mailbox.cassandra.search.NotDeletedWithRangeSearchOverride,org.apache.james.mailbox.cassandra.search.UidSearchOverride
```
to
```
opensearch.search.overrides=org.apache.james.mailbox.cassandra.search.AllSearchOverride,org.apache.james.mailbox.cassandra.search.DeletedSearchOverride, org.apache.james.mailbox.cassandra.search.DeletedWithRangeSearchOverride,org.apache.james.mailbox.cassandra.search.NotDeletedWithRangeSearchOverride,org.apache.james.mailbox.cassandra.search.UidSearchOverride,org.apache.james.mailbox.cassandra.search.UnseenSearchOverride
```

Deploy on sandbox and do IMAP perf tests (compare to IMAP 0.6.3) for this. Consider switching back the search to OpenSearch if not improved.

**Comment by chibenwa** [comment]
Maybe not needed CF https://github.com/apache/james-project/pull/1244
