### ISSUE TITLE
Grooming #26

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4661]
**Delegation**

 -> Use Authorizator for non-default accountIds in JMAP, in order to check the access
 -> List accounts being delegated in the JMAP session
 -> JMAP API to CRUD delegates on your account
 -> JMAP API to refuse a delegation
 -> Some integration tests regarding delegation...

**Comment by chibenwa** [comment]
I did refine a bit the Epic https://github.com/linagora/james-project/issues/3949 related to this.

@vttranlina please plan a meeting related to this, next monday morning?
