### ISSUE TITLE
Release Tmail 0.6.4

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4663]
- [x] Update TMail
 - [x] Tag
 - [x] Deploy on sandbox
 - [x] Performance tests (IMAP/SMTP)
 - [x] Release materials on software.linagora.com
 - [x] Deploy on preprod
 - [x] QA tests
 - [x] Release on tmail.linagora.com

**Comment by Arsnael** [comment]
Tag 0.6.4-rc2

**Comment by Arsnael** [comment]
changelog: https://ci.linagora.com/linagora/lgs/software-linagora-com-website/-/merge_requests/41

**Comment by Arsnael** [comment]
sandbox: https://gitlab.com/linagora_private/saas/tmail/sandbox-emaily-apps/-/merge_requests/13

**Comment by Arsnael** [comment]
# performance tests

## IMAP

![screenshot--2022 11 02-15_34_15](https://user-images.githubusercontent.com/9005025/199439706-6ed23d65-bd2a-4dc7-93ad-3312d66211e6.png)

Results similar to 0.6.3 except:
- append a bit higher in p99 
- unselect twice faster in p99

Overall it's looking good

## JMAP draft

![screenshot--2022 11 02-15_39_40](https://user-images.githubusercontent.com/9005025/199440703-42e73525-ac19-4b06-97b3-b8406f6c9be9.png)

There is a nice gain in p99 for sendMessages and getMessages compared to 0.6.3

## JMAP RFC

![screenshot--2022 11 02-15_45_18](https://user-images.githubusercontent.com/9005025/199441850-ced95d14-bad7-4d61-8685-8f7795a6329b.png)

emailGet is twice faster than 0.6.3 in p99

I think overall we are good with this release TBH

**Comment by chibenwa** [comment]
Time to launch QA ?

Do we know in the changelog what makes this faster?

**Comment by Arsnael** [comment]
https://gitlab.com/linagora_private/saas/tmail/emaily-staging-apps/-/merge_requests/19

**Comment by Arsnael** [comment]
> Time to launch QA ?

I think we can yes

> Do we know in the changelog what makes this faster?

I tried looking at the changelog but I don't really see what made the get messages faster for jmap in general

**Comment by Arsnael** [comment]
QA tests done. No issues reported
