### ISSUE TITLE
Implement Delegate/get

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4670]
## Sample request

```
[[ "Delegate/get", {
      "accountId": "u33084183",
      "ids": null
    }, "0" ]]
```
will return:

```
[[ "Delegate/get", {
      "accountId": "u33084183",
      "list": [{
          "id": "e50b2c1d-9553-41a3-b0a7-a7d26b599ee1",
          "username": "bob@test.org"
      }, {
          "id": "f2d0aab5-e976-4e8b-ad4b-b380a5b987e4",
           "username": "alice@test.org"
      }],
      "notFound": []
    }, "0" ]]
```

## Definition of done

Integration tests

## Notes

- no state argument returned
- The id could be a hash based on the username

**Comment by chibenwa** [comment]
> no state argument returned?

Ok to me.

> normally in a usual get requests we have the ids of objects. Here actually the list of delegated users is a set of user names in the user table... So does it mean we need to return the account id of each of those users?

IMO it would be acceptable to say "only supports 'null'  for ids" though the code related to filtering ids can be trivially done so I do not even see the point of bothering, and would prefer to fit to a standard `/get method`.

**Comment by vttranlina** [comment]
"FirebaseRegistration/get" -> `Delegate/get`

**Comment by vttranlina** [comment]
pr: https://github.com/apache/james-project/pull/1385
