### ISSUE TITLE
Implement Delegate/set create

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4671]
## Sample requests

```
    [[ "Delegate/set", {
      "accountId": "abe325",
      "create": {
        "4f29": {
          "username": "bob@test.org"
        }
      }
    }, "0" ]]
```
The server adds the username "bob@test.org" in the list of delegated users of the account and will return:

```json
    [[ "Delegate/set", {
      "created": {
        "4f29": {
          "id": "abdfe762l"
        }
      }
    }, "0" ]]
```

## Definition of Done

Integration test. 

## Notes

 * Should check that the username exists in usersrepository before adding it to the list
 * a delegated user can't add other users to the list of the owner by himself

**Comment by chibenwa** [comment]
We should return the id of the created object, even if it is a hash of the username.

**Comment by chibenwa** [comment]
Also we should enforce that no delegated user is alloewed to do this.

**Comment by Arsnael** [comment]
> Also we should enforce that no delegated user is alloewed to do this.

What do you mean here? If a delegated user wants to delegate his own account to somebody else I don't see the issue... quite different?

**Comment by chibenwa** [comment]
I mean enforce that given alice give access to bob then bob can't given allice account access to say cedric. Only alice can.

**Comment by vttranlina** [comment]
We don't need "rights" at here?
Eg: 
```
[
    [
        "Delegate/set",
        {
            "accountId": "abe325",
            "create": {
                "4f29": {
                    "username": "bob@test.org",
                    "rights": "r"
                }
            }
        },
        "0"
    ]
]
```

**Comment by Arsnael** [comment]
No a delegation is full rights :)

**Comment by quantranhong1999** [comment]
draft: https://github.com/apache/james-project/pull/1375
