### ISSUE TITLE
Implement Delegate/set delete

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4672]
## Sample requests

```
    [[ "Delegate/set", {
      "destroy": ["P43dcfa4-1dd4-41ef-9156-2c89b3b19c60"]
      }
    }, "0" ]]
```

The server confirms the Delegate user to be destroyed:

```
    [[ "Delegate/set", {
      "destroyed":["P43dcfa4-1dd4-41ef-9156-2c89b3b19c60"]
    }, "0" ]]
```

## Definition of done

Integration test.

## Notes

- The id could be a hash based on the username

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/1394
