### ISSUE TITLE
Show the list of accounts being delegated accounts in JMAP session

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4680]
Epic: https://github.com/linagora/james-project/issues/3949

## Require
[Delegation store should allow listing accounts delegated to me](https://github.com/linagora/james-project/issues/4673)

## How

- Integration DelegatedStore in `org.apache.james.jmap.routes.SessionRoutes`, append delegatedAccount in `session.accounts`

## Dod
- Add integration test at `SessionRoutesContract`

**Comment by vttranlina** [comment]
PR https://github.com/apache/james-project/pull/1376

**Comment by chibenwa** [comment]
accounts: [ {personal: true, delegatedAccounts:[], .... }]

=> SHOULD BE

accounts: [ {personal: true, .... }, {personal: false, .... }]

**Comment by chibenwa** [comment]
Can be split into sub-parts. EG:

 - [ ] Delegation for JMAP API
 - [ ] Delegation for upload
 - [ ] Delegation for dowloads
 - [ ] Delegation for all kind of push
 - ...
