### ISSUE TITLE
 Implement DelegatedAccount/set - delete

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4682]
Epic: https://github.com/linagora/james-project/issues/3949

The Jmap method for delete delegatedAccount

## Sample request

```
    [[ "DelegatedAccount/set", {
      "destroy": ["P43dcfa4-1dd4-41ef-9156-2c89b3b19c60"]
      }
    }, "0" ]]
```

The server confirms:

```
    [[ "DelegatedAccount/set", {
      "destroyed":["P43dcfa4-1dd4-41ef-9156-2c89b3b19c60"]
    }, "0" ]]
```

## Definition of done

Integration tests

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1398
