### ISSUE TITLE
EmailDelivery push is used too much

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4687]
As of today, we push an EmailDelivery for each "added" event.

Yet, added event is used for copies, move, saving draft, sending email... In addition to received new emails.

We should revisit the APIs of `MessageManager::append` in order to allow passing a bit more context. This context would need to be carried other in the event system.

# Definition of Done

JMAP integration test showing that EmailDelivery` state change is reserved to receiving email...

# API proposal

Add a `isDelivery` field to the append command, defaulting to false.

Add a isDelivery field to the `Added` event, defaulting to false.

Ensure LocalDelivery sets the isDelivery to true.

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1327
