### ISSUE TITLE
Leverage saveDate at some further minor places

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4699]
Having a look at James, I only found `ExpireMailboxService` that is suitable for adapting this `saveDate`.

On the Docaposte side, I think we could adapt for `MessageV3CleanupTask` (however only be available at least when we release James 3.7.3).

I didn't find any `Purge...` relevant for this adaption. The Purge one on the Docaposte side, its implementation seems not related to internalDate/saveDate.

Any others places?

**Comment by chibenwa** [comment]
> On the Docaposte side, I think we could adapt for MessageV3CleanupTask (however only be available at least when we release James 3.7.3).

No, not needed. They would stay in 3.7.x on the short term.

**Comment by quantranhong1999** [comment]
> I only found ExpireMailboxService that is suitable for adapting this saveDate.

Read [its original JIRA ticket](https://issues.apache.org/jira/browse/JAMES-3758), I doubt we would gain more benefit doing this.

```
curl -XDELETE /messages?olderThan=1year

Would plan a task to delete emails older than a year accross all accounts.
```
I think in this case, the operator only want to delete messages that got into his system more than e.g 1 year, and he dont want to care how user manipulate the messages internally (switch mailbox/ create new save date).

Maybe we should consider closing this?

**Comment by chibenwa** [comment]
Yes makes sense...
