### ISSUE TITLE
MailRepositories: add a way to count retries

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4710]
Currently, mail repository reprocessing is unbounded. This is a pain as for instance a bug can cause processing to always fail. each failure will generate a bounce. combined with auto-reprocessing this set things up for flooding.

Proposition: count reprocessing:

```
curl -XPATCH 'http://127.0.0.1:8000/mailRepositories/var%2Fmail%2Ferror/mails?action=reprocess&processor=root&limit=5&maxRetries=5'
```

 - maxRetries being an option int (defaults to unlimited). maxRetries filtering happens first then limit.

**Comment by Arsnael** [comment]
Have a Matcher for knowing if a given email is a reprocessing retry. It could be used to trigger side effects only once, and as well acknowledge to the sender when the problem is fixed.

**Comment by chibenwa** [comment]
> Have a Matcher for knowing if a given email is a reprocessing retry. It could be used to trigger side effects only once, and as well acknowledge to the sender when the problem is fixed.

Can be done with `HasMailAttribute=mailRepository-reprocessing`
