### ISSUE TITLE
[JMAP] Apply changes related to the finalization of the JMAP quota RFC document

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4711]
There has been a few changes in the JMAP quota RFC document that we might need to address in our implementation when the consensus is finally reached with the community.

* "limit" property of Quota object becomes "hardLimit"
* filter conditions: 
  + "scopes" -> "scope" and it's not a list anymore, a single value
  + "resourceTypes" -> "resourceType" and it's not a list anymore, a single value

See latest draft version: https://datatracker.ietf.org/doc/draft-ietf-jmap-quotas/

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1417

**Comment by chibenwa** [comment]
Cc @Arsnael I re-add this to the team backlog nheeee

**Comment by quantranhong1999** [comment]
refreshed.

**Comment by chibenwa** [comment]
Compatibility issues escalated to the mobile app https://github.com/linagora/tmail-flutter/issues/1975
