### ISSUE TITLE
Security: Set a JMX password

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4716]
https://issues.apache.org/jira/browse/JAMES-3881

# Why ?

JMX is inherently insecure and it's usage can allow local non-root user, as they can access port 9999, to escalate their privileges.

# How? Solution summary

Set up JMX authentication: local users won't know which password to use (password file only readable to james user).

Generate JMX credentials on the fly so that we can activate JMX authentication by default without shipping some default credentials for it.

# How? Solution details

Try the `-Dcom.sun.management.jmxremote.password.file=/root/conf/jmxremote.password` JVM parameter.

Content of `jmxremote.password``:

```
admin magicpass
```

Modify the CLI code to take an optional username, optional password:

 - [ ] if username and password is unspecified, then use none
 - [ ] if only password is specified, default to `james-admin` username.
 - [ ] if only username is specified, prompt the user to enter a password.

```
java -cp /root/resources:/root/classes:/root/libs/* org.apache.james.cli.ServerCmd 
   -username james-admin
   -password p4$$w0rD
```

Specify the configured username and password when establishing the JMX connection.

BONUS: if no username / password is specified, attempt to read `conf/jmxremote.password` and see its content to use the configured username + password. Default to none only if this file cannot be found. This ensure no changes in the docker containers james-cli script.

BONUS x 2: When James starts, generate randomly `jmxremote.password` (fixed username, default password) if none exists. This makes the default package of james secure (no usage of hardcoded credential, a user do not need to change something to make this secure). Plan a system property to disable this behaviour `-Djames.jmx.credential.generation=true|false`.

 - [ ] Set up JMX authentication in the default applications with a DUMMY passwor (`jmxremote.password` only readable to the james user)
 - [ ] Document setting up authentication for JMX. Explain in security guidelines that JMX auth can prevent privilege escalation.

**Comment by vttranlina** [comment]
I tried some way but it looks like we can not hot reload the new value jmxremote.password when runtime (without restarting James). 
So when we use james-cli for generating a new username/password, we need to restart the James server

**Comment by vttranlina** [comment]
// bonus:

The `jmxremote.password` file when the user creates is

```
admin adminpassword
user userpassword
```

Then running the java application, it will be automatically converted to:

```
admin a/qxF3m6LTKxS1QFMTWrYOOAqnpwrkeqw64abYj3x+Ev4HGcbIVOxlPiNdM7VSc41ps2HjCD+0c5CpK8mSTFRw== R4BS4J3qicBhwSQb6qlLq0t0ukNOWBdGrL3a27f9SqaAW+Wef03GCweTaSypxL2TfdGoEJXcPN6jeu0t5GIRfQ== SHA3-512
user Vz/wZrsnUBihPJdHCFLY9lTf7PZjiztEL8Ql0HO8U3i6cWfdO8OMDE5PNjIPpVy8/8Hjvieh47e288oj0h/jJw== esaVA/sxg6YDdhtNoCfh6v4oPifrooOCRjNTk4AhfQ9jZ9oCMwumjY6sno8iMmZC9sBmZts5jyepZqw2theY8A== SHA3-512

```

_________

Need chmod 600 for `jmxremote.password` file

**Comment by chibenwa** [comment]
> Then running the java application, it will be automatically converted to:

That's cool actually :-) More secure. But ruins the overall action plan.

We can IMO:

 - [ ] Support auth on CLI side
 - [ ] Document setting up authentication on JMX configuration and recommend enabling it...

No need to auto-generate password and have CLI retrieving the actual data then...

**Comment by vttranlina** [comment]
wip pr https://github.com/apache/james-project/pull/1437
