### ISSUE TITLE
[Thunderbird] server responded: ID failed. Illegal arguments.

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4719]
![Screenshot from 2023-02-13 10-13-07](https://user-images.githubusercontent.com/6928740/218362310-9504fdf9-9f65-4c80-b051-18c8a815fdef.png)

Investigate...

**Comment by Arsnael** [comment]
Bunch of logs like this:
```
{"timestamp":"2023-02-13T04:22:47.694Z","level":"WARN","thread":"s1-io-1","logger":"org.apache.james.imap.encode.base.EndImapEncoder","message":"Unknown message ACL INBOX owner aeiklprstwx","context":"default"}	
{"timestamp":"2023-02-13T04:23:27.929Z","level":"WARN","thread":"s1-io-1","logger":"org.apache.james.imap.encode.base.EndImapEncoder","message":"Unknown message ACL INBOX.Message ordder owner aeiklprstwx","context":"default"}
```

I saw that INBOX.Message ordder submailbox in that user so I guess it's the right one... 
Is it trying to access messages in those mailboxes that belong to an other user? Is that even possible?

**Comment by chibenwa** [comment]
> Bunch of logs like this:

Interesting, but please open another bug report, that is unrelated to parsing issues for the ID command...

> I saw that INBOX.Message ordder submailbox in that user so I guess it's the right one... Is it trying to access messages in those mailboxes that belong to an other user? Is that even possible?

That's not an understandable statement to me. Please be more precise.

Also, it looks like we are missing an IMAP encoder. Related to ACL. Similar to the missing LOGOUT processor issue.

**Comment by chibenwa** [comment]
CF https://github.com/apache/james-project/pull/1438

**Comment by Arsnael** [comment]
How is that unrelated? That's the logs we get on James side when reproducing your issue with that user... could be this issue that troggers the message on TB side, despite TB understanding or not what's going on, no?

**Comment by chibenwa** [comment]
> How is that unrelated? 

That's unrelated to the ID command parsing being badly implemented.

There could be other polish to be done on IMAP. I do not say no to this.

**Comment by chibenwa** [comment]
Capture from what Thunderbird send in, rewritten as a MPT test...

```
C: a1 ID ("name" "Thunderbird" "version" "102.7.1")
S: \* ID \(\)
S: a1 OK ID completed.
```

=> 

```
Expected: '\* ID \(\)'
Actual   : 'a1 BAD ID failed. Illegal arguments.'
```

**Comment by chibenwa** [comment]
CF https://github.com/apache/james-project/pull/1439
