### ISSUE TITLE
Add a WebAdmin API allowing creating/editing the user default identity

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4721]
## Why
Expose a Webadmin API that allows creating user' JMAP default identity display name, so we can hook it with an LSC display name synchronization.

- Creating a new/first `mayDelete=true` identity API (if a user has no default identity yet)
```
POST /users/{username}/identities
{
	"name": "Bob",
	"email": "bob@domain.tld",
	"mayDelete": true,
	"htmlSignature": "a html signature",
	"textSignature": "a text signature",
	"bcc": [{
		"email": "boss2@domain.tld",
		"name": "My Boss 2"
	}],
	"replyTo": [{
		"email": "boss@domain.tld",
		"name": "My Boss"
	}],
	"sortOrder": 0
}
```
Creating with empty fields: `mayDelete` (always = true), `htmlSignature`, `textSignature`, `bcc`, `replyTo` should be supported cause we likely can not get these data from LDAP.

- Editing a user identity API
```
PUT /users/{username}/identities/{identityId}
{
	"name": "Bob",
	"email": "bob@domain.tld",
	"mayDelete": true,
	"htmlSignature": "a html signature",
	"textSignature": "a text signature",
	"bcc": [{
		"email": "boss2@domain.tld",
		"name": "My Boss 2"
	}],
	"replyTo": [{
		"email": "boss@domain.tld",
		"name": "My Boss"
	}],
	"sortOrder": 0
}
```
Updating with empty fields: `mayDelete` (always = true), `htmlSignature`, `textSignature`, `bcc`, `replyTo` should be supported cause we likely can not get these data from LDAP.

- Editing a use default identity API (the idea is to do filtering on James' side, if LSC can do it easily, we can skip this API)
```
PUT /users/{username}/identities?default=true
{
	"name": "Bob",
	"email": "bob@domain.tld",
	"mayDelete": true,
	"htmlSignature": "a html signature",
	"textSignature": "a text signature",
	"bcc": [{
		"email": "boss2@domain.tld",
		"name": "My Boss 2"
	}],
	"replyTo": [{
		"email": "boss@domain.tld",
		"name": "My Boss"
	}],
	"sortOrder": 0
}
```
Updating with empty fields: `mayDelete` (always = true), `htmlSignature`, `textSignature`, `bcc`, `replyTo` should be supported cause we likely can not get these data from LDAP.

## How
Use `CustomIdentityDAO` save, update API.

## DoD
 - Test
 - Documentation
   
## Notes
  - `email`, `id`, `mayDelete` fields are not allowed to be changed when updating

**Comment by chibenwa** [comment]
PUT to update an update an item

POST is to create ?

```
PUT /users/{username}/identities/{identityId}
PUT /users/{username}/identities
```

**Comment by Arsnael** [comment]
No need edit api anymore (only creating missing identities with ldap)

**Comment by vttranlina** [comment]
Jira https://issues.apache.org/jira/browse/JAMES-3893

**Comment by vttranlina** [comment]
PR : https://github.com/apache/james-project/pull/1471
