### ISSUE TITLE
Develop an LSC script that modifies the user default identity to create a new identity with the LDAP display name if no mayDelete=true identity is available.

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4722]
## Why

We need to dev an LSC job to gather the first name and surname from the LDAP entry and set the display name for user's default identity.
    E.g with LDAP entry:
    ```
    dn: uid=tungtranvan, ou=people, dc=james,dc=org
    mail: tungtranvan@james.org
    givenName: Tung
    sn: Tran Van
    [...]
    ```

- If the user does not have a default identity (no `mayDelete=true` identity yet) -> LSC calls james webadmin API to create the default identity for that user
   ```
    POST /users/{username}/identities
    {
      "name": "Tung Tran Van",
      "email": "tungtranvan@james.org",
      "sortOrder": 3
    }
    ```

- If the user' default identity display name is empty or equals the email (naive display name) -> LSC calls james webadmin API to update the default identity with display name from LDAP for that user
    ```
    PUT /users/{username}/identities?default=true
    {
      "name": "Tung Tran Van",
      "email": "tungtranvan@james.org",
      "sortOrder": 3
    }
    ```

- For the case that user's default identity has a display name that does not equal to the display name that can get from LDAP, we should not override the display name because may be that is user's intention.

## Notes

 - We could skip `mayDelete` (always = true), `htmlSignature`, `textSignature`, `bcc`, `replyTo` cause we likely can not get these data from LDAP.
- Could use default identity as a pivot: `GET /users/{username}/identities?default=true`
- Check again (via last LSC synchronization works) the pivot concept/ webadmin APIs that LSC scripts need to call before developing this topic: https://github.com/linagora/tmail-backend/issues/370

**Comment by chibenwa** [comment]
IMO:
 - No neee to care about the case "Naive display name"

**Comment by Arsnael** [comment]
No update lsc job anymore

**Comment by quantranhong1999** [comment]
Missing guice binding for the route...:
https://github.com/apache/james-project/pull/1474
https://github.com/linagora/tmail-backend/pull/585

**Comment by quantranhong1999** [comment]
WIP: https://github.com/linagora/tmail-lsc/pull/7
