### ISSUE TITLE
[JMAP Draft] Email/query team mailboxes without shares capability should not succeed

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4731]
EmailQueryView is not filtering team mailboxes by default, even for JMAP draft.
We need to check this for JMAP draft.
rf to JMAP RFC work: https://github.com/linagora/tmail-backend/issues/569

**Comment by Arsnael** [comment]
Why do we care about jmap-draft for new exclusive such as team mailboxes btw?

**Comment by chibenwa** [comment]
Because we do still have OpenPaaS INBOX clients that might see emails that are unrelated.

Though maybe it do not have sense, because JMAP draft do not have the notion of capabilities if I recall correctly. 

Mayb this can be closed too...

**Comment by quantranhong1999** [comment]
I checked JMAP draft and see the EmailQueryView is being used, however, the is no capability as Benoit said.
So the current behavior of JMAP draft is to display shared mailbox messages if possible.

**Comment by chibenwa** [comment]
Ok, closing then. Thanks for double checking...
