### ISSUE TITLE
Data race issue with JMAP email query view

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4736]
We spotted a possible data race issue when populating the query email view, giving potentially false results when fetching emails ids via the email query view with Email/query jmap method

For example, for a user

```json
{
    "using": [
        "urn:ietf:params:jmap:core",
        "urn:ietf:params:jmap:mail"
    ],
    "methodCalls": [
        [
            "Email/query",
            {
                "accountId": "59ecb678c68f69e90d50b580d14512b6c2ec520afe5a3c522113b100235df799",
                "filter": {
                    "inMailbox": "bb6b69d0-32cf-11eb-995c-a3ae66e9f96a"
                },
                "sort": [
                    {
                        "isAscending": false,
                        "property": "receivedAt"
                    }
                ],
                "limit": 20
            },
            "c2"
        ],
        [
            "Email/get",
            {
                "accountId": "59ecb678c68f69e90d50b580d14512b6c2ec520afe5a3c522113b100235df799",
                "#ids": {
                    "resultOf": "c2",
                    "name": "Email/query",
                    "path": "ids/*"
                }
            },
            "c3"
        ]
    ]
}
```

The mailbox targeted here is Outbox. Some emails returned are part of that mailbox, some others are part of the Sent mailbox, some others are part of both.

When sending email, normal sequence should be:

* users sends the email thus saves it in outbox
* populate email query view is populated for outbox
* system moves the email into sent box
* populate email query view is populated for sent

What maybe happens is:

* users sends the email thus saves it in outbox
* system moves the email into sent box
* populate email query view is populated for sent
* populate email query view is populated for outbox

We need to find a way to handle this case properly.

@chibenwa suggestion:
My bet is that we can create a system based on keywords to solve this.

If the message is created in outbox, be extra careful before triggering the change. Re read the mailbox ids from db do ensure this is still outbox.

Similar pb for sure happens with opensearch indexing.

**Comment by chibenwa** [comment]
> My bet is that we can create a system based on keywords to solve this.

Likely not needed.

> If the message is created in outbox, be extra careful before triggering the change. Re read the mailbox ids from db do ensure this is still outbox.

Likely enough.

**Comment by vttranlina** [comment]
I'm testing for  this case on my local

- A send a mail to B
- B received a mail

I don't see any mail in Outbox/Sent of A 
Did I miss some configuration?

**Comment by chibenwa** [comment]
Are you using JMAP?

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/1477
