### ISSUE TITLE
Measure code coverage with jacoco (experiment)

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4758]
**Why?**: Measure code coverage

Example set up:
 - Jacoco plugin https://github.com/yahoo/smtp-client-nio/blob/master/pom.xml#L482 + https://github.com/yahoo/smtp-client-nio/blob/master/pom.xml#L152
 - Jacoco java agent on surefire: https://github.com/yahoo/smtp-client-nio/blob/master/pom.xml#L450
 
 https://www.eclemma.org/jacoco/trunk/doc/report-aggregate-mojo.html to aggregate a report 
 
 Time box: 5 man-day.

**Comment by quantranhong1999** [comment]
Demo for James Docaposte:

https://user-images.githubusercontent.com/55171818/232467695-905e15e2-0bb4-4946-9ac7-f532f6be87ee.webm

WIP for James: https://github.com/apache/james-project/pull/1522

**Comment by chibenwa** [comment]
Curious about msgsv-purge-api low code coverage: isn't other module exercise it throughly?

Can we dig a bit more into it?

Please share the archive with the team.

**Comment by chibenwa** [comment]
BTW demo on a private project shall be shared privately ;-)

**Comment by quantranhong1999** [comment]
> Please share the archive with the team.

[archive.zip](https://github.com/linagora/james-project/files/11249530/archive.zip)

**Comment by chibenwa** [comment]
The aggregation looks legit so far...

**Comment by Arsnael** [comment]
Already 3 days spent on this...

Timebox left: 2
