### ISSUE TITLE
[EPIC] Blob/set delete

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4759]
## WHY

Delete uploaded attachments once the email is composed, without waiting for the retention period for uploaded attachments to kick in...

CF https://datatracker.ietf.org/doc/draft-ietf-jmap-blob/

**Comment by quantranhong1999** [comment]
Actually, destroy part has been removed out of the specs :(

```
4.1.  Blob/upload

   This is similar to a Foo/set from [RFC8620] in some ways, however
   blobs can not be updated or deleted, so only create is allowed in the
   method call, and blobs do not have state, so there is no state field
   present in the method response.
````

Unless we customize it, I am not sure that is what we will do.

**Comment by chibenwa** [comment]
Let's not work on this now then....
