### ISSUE TITLE
'Performance checklist' documentation

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4780]
Within the distributed app documentation have a page `Performance checklist` that references major point of attention and performance tradeoffs:

 - `cassandra.properties`: limit LWTs, important driver settings (thread, throttler), disable read-repairs, disable ACL if possible
 - `opensearch.properties`: search override + disable HDRS indexing.
 - `jmap.properties`: disable. Use emailqueryview.
 - `blobstore.properties`: tradeoffs for dedup. header caching,
 - `imap, smtp` important settings (threading, // requests), disable name resolution and other miniscule perf gains.
 - `rabbit`: disable CassandraMQView if possible, disable size metric, avoid publish confirms...
 - other ideas?

Goal: help people coming up with relevant perf settings,

**Comment by quantranhong1999** [comment]
`batchsizes.properties` -> Try a bigger batch size?

Disable glowroot?

Advice tuning GC options?

**Comment by chibenwa** [comment]
> Disable glowroot?

Not packaged in community James
