### ISSUE TITLE
Filters data deletion

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4785]
## Why

We need to delete all filter rules of a user.

## How

- A step implements `DeleteUserDataTaskStep` + Unit test for it
- Guice binding
- Documentate the step in `manage-webadmin.md` and `webadmin.adoc`
- Integration test for this step

## DoD
- Integration test

**Comment by chibenwa** [comment]
Handled in https://github.com/apache/james-project/pull/1569 ?
