### ISSUE TITLE
JAMES-3907 OIDC example with Apache APISIX

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4791]
https://issues.apache.org/jira/browse/JAMES-3907

**Comment by vttranlina** [comment]
James-project doesn't have the `ApisixXUserinfoAuthenticationStrategy` 
Should we duplicate it from tmail to james?

**Comment by chibenwa** [comment]
Or mve it from TMail to James ;-)

**Comment by vttranlina** [comment]
ISSUE-640 - Apisix plugin support Rewrite X-User in header
https://github.com/linagora/tmail-backend/pull/686

**Comment by vttranlina** [comment]
WIP pr in james https://github.com/apache/james-project/pull/1565
