### ISSUE TITLE
Allow WithStorageDirective mailet to target multiple mailboxes

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4792]
Today WithStorageDirective mailed allow only to save the mail in one particular mailbox. If you want to save it into x mailboxes, you might need to duplicate the mailet x times. It would be more convenient, flexible and less verbose if we could specify multiple mailboxes to save the mail into with one WithStorageDirective mailet.

Current syntax:
```
<mailet match="All" class="WithStorageDirective">
    <targetFolderName>mailbox1</targetFolderName>
</mailet>

<mailet match="All" class="WithStorageDirective">
    <targetFolderName>mailbox2</targetFolderName>
</mailet>
``` 

New syntax :
```
<mailet match="All" class="WithStorageDirective">
    <targetFolderName>mailbox1,mailbox2</targetFolderName>
</mailet>
``` 
Can do a split on the comma ","

Should adapt the test suite to this change

**Comment by chibenwa** [comment]
Can we use xml list for specifying multiple folders?

**Comment by Arsnael** [comment]
I'm not too proefficient with xml list but do you mean sth like that @chibenwa ?

```
<mailet match="All" class="WithStorageDirective">
    <targetFolderNames>
        <list>
            <targetFolderName>mailbox1</targetFolderName>
            <targetFolderName>mailbox2</targetFolderName>
        </list>
    </targetFolderNames>
</mailet>
```
I'm not against it but I'm more afraid of the consequences of such a breaking change
Or should we keep <targetFolderName></targetFolderName> out of the list for retro compatibility?

**Comment by chibenwa** [comment]
Yes

```
<mailet match="All" class="WithStorageDirective">
    <targetFolderNames>
            <targetFolderName>mailbox1</targetFolderName>
            <targetFolderName>mailbox2</targetFolderName>
    </targetFolderNames>
</mailet>
```

**Comment by chibenwa** [comment]
It might require some modifications to MailetConfig though...

**Comment by chibenwa** [comment]
So I had a quick shot at this.

The config change is hard to perform and might be non consensual,

Also coma separated names is likely acceptable (as long as the storage directive, and it's encoding as attributes) preserves a list.
