### ISSUE TITLE
JMAP naive Mailbox/queryChanges implementation

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4799]
From https://issues.apache.org/jira/browse/JAMES-3551

Mailbox/queryChanges spec: https://jmap.io/spec-mail.html#mailboxquerychanges

Core spec for queryChanges: https://jmap.io/spec-core.html#querychanges

We could consider the following naive implementation: always return cannotCalculateChanges errors - which technically is specification compliant but do not add much value.

You cann look at https://github.com/apache/james-project/pull/1555 for an example of a naive jmap method implementation...

**Comment by hungphan227** [comment]
i created PR https://github.com/apache/james-project/pull/1624
Please review

**Comment by hungphan227** [comment]
I have updated code by all comments
Please review
