### ISSUE TITLE
Backport JAMES-3924 on 3.7.x

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4810]
https://github.com/apache/james-project/pull/1623

https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-1623/4/testReport/org.apache.james.queue.rabbitmq/RabbitMQMailQueueTest$DeDuplicationTest/dequeueShouldStillRetrieveAllBlobsWhenIdenticalContentAndDeduplication/

Related. 

Investigate and fix.

**Comment by Arsnael** [comment]
Aren't the title and description not related? 

Title says backport JAMES-3924 on 3.7.x... 

Description says JAMES-3924 PR (on master) is failing and needs to be fixed

**Comment by chibenwa** [comment]
Yes sorry.

**Comment by chibenwa** [comment]
Fixed. I reopened https://github.com/linagora/james-project-private/issues/637#issuecomment-1630078374

**Comment by quantranhong1999** [comment]
> Ah cool I was investigating and now I see quan took the new issue you opened... Not optimal ^^'

Ahah sry I just take it, do you wish to continue on that?

**Comment by quantranhong1999** [comment]
Well I guess I would leave that ticket so you did not waste your time on that, if you are ok with that.
