### ISSUE TITLE
JMAP filtering: combine rule conditions

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4811]
## What 

Today, filters only take a single condition which forbids to write complex rules.

![Screenshot from 2023-07-10 10-29-44](https://github.com/linagora/james-project/assets/6928740/f5ade406-070d-42f5-aa08-9f31cd5d10b9)

We need to combine conditions together in a songle rule to make things smarter:

![download](https://github.com/linagora/james-project/assets/6928740/5de2979f-4750-4dfc-9496-1950631ca4de)

## How

Add a `ConditionCombiner` enum that takes two possible values, `And` or `Or`.

Add a `Conditions` POJO that takes a `ConditionCombiner` and a list of `Condition`.

Modify the `Rule` POJO to replace the `Condition` by `Conditions`.

Modify the storage layer within `server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/filtering`. Preserve retro-compatibility: be able to read previous values...

Modify the presentation layers (JMAP Draft): adapt it to the new API. No need to support JMAP conditions there!

In another ticket, adapt the JMAP RFC-8621 TMail filter API accordingly.

**Comment by hungphan227** [comment]
I have created draft PR https://github.com/apache/james-project/pull/1643

**Comment by hungphan227** [comment]
@chibenwa "No need to support JMAP conditions there". Could you explain this?

**Comment by Arsnael** [comment]
No need to support combine rules conditions for JMAP draft, as it's a legacy API :)

**Comment by hungphan227** [comment]
@chibenwa @Arsnael There is a package called mailet in JMAP draft module (server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/mailet). Do we not need to support combine rules conditions for this as well?

**Comment by Arsnael** [comment]
I believe not :)

**Comment by chibenwa** [comment]
> Do we not need to support combine rules conditions for this as well?

Of course we do!

And on the storage layer too ;-)
