### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4813]
Update all relevant James dependencies, docker images, etc...

**Comment by vttranlina** [comment]
https://github.com/apache/james-project/pull/1647

**Comment by vttranlina** [comment]
# Upgrade dependencies - only lib https://github.com/apache/james-project/pull/1655

The quick performance test result:
## JMAP
1pod, 5k user, charge1 -> sandbox
### Before
![image](https://github.com/linagora/james-project/assets/81145350/ce7be07a-b849-4025-966e-1401a618df2d)

### After
![image](https://github.com/linagora/james-project/assets/81145350/3e86a206-fb9a-4098-b31b-dd41b8cb548d)


## IMAP
1pod, 6k user, charge1 -> sandbox
### Before
![image](https://github.com/linagora/james-project/assets/81145350/08cbb5df-881e-40f9-a990-c5f419a0aa69)
### After 
![image](https://github.com/linagora/james-project/assets/81145350/51a02a4f-5878-4590-808a-7f700ac17069)


## Conclusion
Both IMAP & JMAP decrease performance after updating libraries

//Maybe we should re-test more times for sure?

**Comment by quantranhong1999** [comment]
If Benoit is here, I guess he would be interested in Flamegraph.

BTW is there any other suspect change/commit between "before" and "after" besides the libs upgrade?

**Comment by vttranlina** [comment]
:( one more time I forgot to dump the flame graph

**Comment by vttranlina** [comment]
> BTW is there any other suspect change/commit between "before" and "after" besides the libs upgrade?

yes

before:  james-commit: 76ac78344d489d2935b62d8cfefc5266eba3588d
After: james-commit: bb4999080da726532aace900d855551abe57f1f6

**Comment by Arsnael** [comment]
JMAP looks ok I think, negligeable, could be related to the platform and OVH.

IMAP looks suspicious but I would redeploy fresh pods and retest to make sure.

Also when testing, do you do a small preflight perf test before the real one or not? James is like a diesel, need to run it a bit first until it gets warmer, then it can handle better :)
