### ISSUE TITLE
JAMES-3925 JMAP quota for uploads

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4816]
https://issues.apache.org/jira/browse/JAMES-3925

**Comment by hungphan227** [comment]
I break this ticket to the list below:

- Create quota DAO for memory version
- Store the current size of total user uploads
- Store the global limit of total user uploads
- Expose a webadmin API to see user quota usage for JMAP uploads
- Enforce the quota checks upon uploads

Please give comments

**Comment by chibenwa** [comment]
- webadmin task to recompute current values?

**Comment by hungphan227** [comment]
> * webadmin task to recompute current values?

Updating current values would be done in the task "Store the current size of total user uploads". Current values would be automatically updated whenever user upload new things.

I do not get what you mean here?

**Comment by Arsnael** [comment]
As discussed:
-> current webadmin task to recompute quotas for users: https://james.apache.org/server/manage-webadmin.html#Recomputing_current_quotas_for_users

We need a task to recompute those values if necessary as, like any projection and async operations in Cassandra, it can go potentially out of sync, leading to inconsistencies :)

**Comment by hungphan227** [comment]
Ok tks. There would be a task to implement recomputing current values of JMAP upload. In addition, there would be a task relating to "JAMES-3926 Refactor quota for Cassandra" to create a generic web admin API to recompute any types of current value.

**Comment by hungphan227** [comment]
I have two questions:
- Do we have domain limit for total user uploads?
- Should we create a web admin API to create and update global limit?

**Comment by Arsnael** [comment]
> * Do we have domain limit for total user uploads?

If we have a global limit I would think it makes sense to have domain as well?

> * Should we create a web admin API to create and update global limit?

I think with the refactoring we are trying to make, I would see the same api, with a query parameter allowing to choose on which scope you want to recompute upload jmap quotas (for users? for domains? for global?)
But maybe the team has a different view on this :)

**Comment by Arsnael** [comment]
Added note, I think we had a big misunderstanding about quotas. We thought that 
- global limit quota was to apply on computed values of quota usage of users on all the server
- domain limit quota was to apply on computed values of quota usage of users part of a same domain

Well... no. After rechecking the code quite deeply (and I asked @QuangHoang1210 to recheck with me so i have a witness :) ):
- there is no storage of computed values of user quota usage for global and domain (which made me think ok maybe we misunderstood something here)
- in fact the way it works: global defines the default quota limit for every user on the server. if you have a global limit of 20 messages (count), it means each user will have a limit of 20 messages, it's not calculated on a computed values of all users quotas. Same for domain, but applied on the scope of a domain
- on which quota scope do we apply the user to, it ends up in matters of priority of which are defined -> account first, domain second, global latest. 

Examples:
- global defined at 20 count. Each user will have a limit of 20 messages on the server
- user has account quota defined to 10 count. That particular user will have quota of 10 messages
- global limit defined at 10 count, and account limit for userA defined at 20 count. 2 quotas are defined for userA. It will pick by order of priority => so userA has a limit of 20 messages, picking account limit first, even if global one is lower.

@team Regarding this, please  modify grooming / your own thinking in consequence :) 

@chibenwa if you happen to see this and think I'm wrong and I should be burnt to the pier for heresy, please step forward :)

**Comment by hungphan227** [comment]
@Arsnael "Listener upon jmap uploads set and delete" -> do you mean that we should use events for any changes to quota tables?

**Comment by Arsnael** [comment]
That's how it works I would guess? Maybe I should check that more though... or could just increase while doing an upload

**Comment by hungphan227** [comment]
Ah ok I misunderstood your idea. Yeah it make sense to me. We would use a listener to listen to the event "updating quota current value" sent when JMAP upload is executed, is that right?
