### ISSUE TITLE
JAMES-3926 Refactor quota for Cassandra

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4817]
https://issues.apache.org/jira/browse/JAMES-3926

**Comment by hungphan227** [comment]
I intend to create POJO for quota like below:

public class QuotaLimit {
    private String identifier;
    private Component component;
    private QuotaType quotaType;
    private Scope scope;
    private Long maxValue;
}

public enum Component {
    MAILBOX, SIEVE, JMAP_UPLOADS
}

Component, QuotaType, Scope are enum.

Do you agree with my idea?

**Comment by chibenwa** [comment]
Component need to be open, not closed. Don't assume a central place knows all values as it will kill extensibility.

**Comment by hungphan227** [comment]
I propose below model to make it extensible:

public class QuotaLimit {
  private String identifier;
  private String component;
  private String quotaType;
  private String scope;
  private Long maxValue;
}

public class QuotaComponent {
  public static final String MAILBOX = "MAILBOX"
  public static final String SIEVE = "SIEVE"
  public static final String JMAP_UPLOADS = "JMAP_UPLOADS"
}

**Comment by Arsnael** [comment]
Why did we loose the strong types in QuotaLimit?

**Comment by quantranhong1999** [comment]
How about

```java
interface QuotaComponent {
   String getQuotaComponentName();
}
```

**Comment by hungphan227** [comment]
@Arsnael because I want to make it extensible. Currently I do not know a better way.

@quantranhong1999 could you give more detail?

**Comment by quantranhong1999** [comment]
> @quantranhong1999 could you give more detail?

An example: have a look at `trait TypeName`.

**Comment by Arsnael** [comment]
With what Quan suggest it does not limit you on extensions. You API will rely on QuotaComponent and everytime you need to have quota for a new component, it will be a new implementation of that interface

**Comment by hungphan227** [comment]
I have a simple implementation for this case:

public class QuotaComponentEnumeration {

    public static final QuotaComponent MAILBOX = new QuotaComponent("MAILBOX");
    public static final QuotaComponent SIEVE = new QuotaComponent("SIEVE");
    public static final QuotaComponent JMAP_UPLOADS = new QuotaComponent("JMAP_UPLOADS");

    public static QuotaComponent toQuotaComponent(String value) {
        if (MAILBOX.getValue().equals(value)) {
            return MAILBOX;
        } else if (SIEVE.getValue().equals(value)) {
            return SIEVE;
        } else if (JMAP_UPLOADS.getValue().equals(value)) {
            return JMAP_UPLOADS;
        } else {
            throw new RuntimeException("Could not convert");
        }
    }

    public static class QuotaComponent {

        private final String value;

        protected QuotaComponent(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }
    }

}

What do you think?

**Comment by chibenwa** [comment]
The factory (method) wont behave well in the face of extensibility.

Me I would go for a simple POJO

**Comment by Arsnael** [comment]
I would tend to think like @quantranhong1999 . Have a generic interface, that declare an abstract method returning the name of the component. Then any extension (even outside of James) declaring a new component for quota would just implement that interface returning the proper name

**Comment by Arsnael** [comment]
Something like: 

```
interface QuotaComponent {
   String getQuotaComponentName();
}

public class MailboxQuotaComponent implements QuotaComponent {
    public String getQuotaComponentName() {
        return "MAILBOX";
    }
}

public class SieveQuotaComponent implements QuotaComponent {
    public String getQuotaComponentName() {
        return "SIEVE";
    }
}

...
```

**Comment by hungphan227** [comment]
Personally I do not prefer creating too many classes

**Comment by Arsnael** [comment]
@hungphan227 : Regarding the first part of refactoring, the list of tickets I would see, to keep things short and simple, and easy to review and merge:

```
* POJO definitions
* DAO interface and memory implementations
* Cassandra tables definitions and implementation 
```
