### ISSUE TITLE
Error when S3 upload: SdkClientException: Unable to execute HTTP request: Duplicate handler name

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4819]
## reproduce
 
Run test `readBytesShouldReturnBigSavedByteSource(StoragePolicy)[1] – org.apache.james.blob.objectstorage.aws.S3NamespaceTest` (**repeat until failure** )

Error:
```
org.apache.james.blob.api.ObjectStoreIOException: Error saving blob
	at org.apache.james.blob.objectstorage.aws.S3BlobStoreDAO.lambda$save$24(S3BlobStoreDAO.java:312)
	at reactor.core.publisher.Mono.lambda$onErrorMap$27(Mono.java:3769)
	at reactor.core.publisher.Mono.lambda$onErrorResume$29(Mono.java:3859)
...

Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Duplicate handler name: HttpStreamsClientHandler#0-body-subscriber
```

**Comment by vttranlina** [comment]
Some guys got the same issue, but it looks not resolved
https://github.com/aws/aws-sdk-java-v2/issues/1903

**Comment by vttranlina** [comment]
I'm not sure the changing image `zenko/cloudserver:8.2.6` ->  `registry.scality.com/cloudserver/cloudserver:8.7.25`  will fix that issue at all.

But with a new image (registry.scality.com/cloudserver/cloudserver:8.7.25), I didn't see it fail (at least on my pc when running IDE with mode: repeat until failure)

_____________
## zenko/cloudserver:8.2.6


![image](https://github.com/linagora/james-project/assets/81145350/0a6d2c60-1c94-4fd8-a06d-7dac58c2db51)

## registry.scality.com/cloudserver/cloudserver:8.7.25
Tests passed:748 
![image](https://github.com/linagora/james-project/assets/81145350/2ea305e0-b104-4038-a610-3e4f07ebc514)

**Comment by Arsnael** [comment]
@vttranlina can we consider it done then? I don't recall seeing this error lately on failing builds

**Comment by vttranlina** [comment]
yes, I don't see it too
