### ISSUE TITLE
JAMES-3928 ReadOnlyUsersRepository: Master slave set up

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4820]
https://issues.apache.org/jira/browse/JAMES-3928

**Comment by quantranhong1999** [comment]
I would care about some more points:
- Scale read using the fallback LDAPs as well
- Failover on LDAP setup without the application (James) to be acknowledged, if possible?

**Comment by chibenwa** [comment]
> Scale read using the fallback LDAPs as well

Why not but with a single LDAP you can handle a monstrous load of IMAP/SMTP logins per seconds. IMO clearly overkill.

> Failover on LDAP setup without the application (James) to be acknowledged, if possible?

Isn't this what the ticket is all about? The failover is handled at driver level...

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1649
