### ISSUE TITLE
Vacation responder should not respond to self

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4823]
When I send a mail to myself apparently I get a message like this:

![Screenshot from 2023-07-24 21-38-31](https://github.com/linagora/james-project/assets/6928740/0d93665a-717e-4f37-8d47-f7bb95b5ce92)

DOD: ensure that the responder ignore the sender.

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1665
