### ISSUE TITLE
Refactor quota for Cassandra: create POJOs

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#4824]
**original ticket**: https://github.com/linagora/james-project/issues/4817

**WHY**

to create POJOS for 2 new tables QuotaLimit and QuotaCurrentValue

**HOW**

```
public class QuotaLimit {
    private final String identifier;
    private final QuotaComponent quotaComponent;
    private final QuotaType quotaType;
    private final QuotaScope quotaScope;
    private final long maxValue;
}

public class QuotaCurrentValue {
    private final String identifier;
    private final QuotaComponent quotaComponent;
    private final QuotaType quotaType;
    private final long currentValue;
}

public class QuotaComponent {
    private final String value;
    // constructor, getter, equals, hashcode, toString
}
```

**DOD**: Integration test

**Comment by hungphan227** [comment]
You can view in the PR I have just created. Please review.
https://github.com/apache/james-project/pull/1666

**Comment by hungphan227** [comment]
We need to check how we are currently store the current value of domain/global quota (if there is?)

**Comment by hungphan227** [comment]
TODO add table structure

**Comment by Arsnael** [comment]
Well from what I get from Benoit's comments in your draft, it seems we should go more like this way:

```
public class QuotaComponent {
    private final String value;
    // constructor, getter, equals, hashcode, toString
}

public class QuotaType {
    private final String value;
    // constructor, getter, equals, hashcode, toString
}

public class QuotaScope {
    private final String value;
    // constructor, getter, equals, hashcode, toString
}
```

Let's just start simple. If we want to do something more complex later we always can.

Please also actually it would be better as I said quickly this morning at the end that there is some quick memory DAOs (maybe try to define at least the interfaces) implementation with those POJOs for quotas (I believe what is https://github.com/linagora/james-project/issues/4826)

Or it's ok to keep the memory implem in an other ticket. But the Cassandra implem should be an other ticket, with Cassandra tables design in the ticket description

**Comment by hungphan227** [comment]
@Arsnael if I follow this way, how could we create constants for these fields? (For example, we only have three values for QuotaComponent: mailbox, sieve, jmapuploads)

**Comment by Arsnael** [comment]
something like public static final MAILBOX_COMPONENT = new QuotaComponent("mailbox");

?

**Comment by hungphan227** [comment]
Do you still remember? I have proposed something like this previously and you rejected immediately.

**Comment by hungphan227** [comment]
I have created PR https://github.com/apache/james-project/pull/1670

**Comment by hungphan227** [comment]
Currenly I create simple POJOs as @chibenwa suggested. However, our concern about this design still remains. I copy the comment of @Arsnael from old draft PR: 

@chibenwa : I think @hungphan227 is concerned at the end that with this simple way, we might not be able to tell the user if we have quotas for the component or not when calling the webadmin api generic route.

Maybe you don't care if we return an empty list in that case? Or maybe you don't want generic routes in the first place, and want to keep routes separated like it is the case now? (I think would be easier to have a generic route with the quota component in it though, as groomed)
