### ISSUE TITLE
JMAP quota for uploads: Create quota DAO for memory version

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#4826]
**original ticket**: #4816

**WHY**

to implement quota DAO to interact with quota data store in memory.

**HOW**

- create QuotaLimitDAO and QuotaCurrentValueDAO interface if not existed
- implement MemoryQuotaLimitDAO and MemoryQuotaCurrentValueDAO

```
public class MemoryQuotaLimitDAO implements QuotaLimitDAO {
	Set<QuotaLimit> set;
	
	Mono<QuotaLimit> getQuotaLimit(...) {
		...
	}
}
```

**DOD**: integration test

**Comment by Arsnael** [comment]
description missing

**Comment by Arsnael** [comment]
I think we can close this one, not needed anymore correct?

**Comment by hungphan227** [comment]
Do you want to me to close it or delete it?
