### ISSUE TITLE
JMAP quota for uploads: Update the current size of JMAP uploads of users

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#4827]
**original ticket**: #4816

**WHY**

to implement updating the current size of total upload of a specific user after the user upload new stuff. In case the user reach the limit, update should be rejected.

**HOW**

- in CassandraUploadRepository, use QuotaLimitDao to get limit of the user and check if the user reach the limit
- if not, update the current size of JMAP uploads of the user by using event (create new event in MailboxEvents class, create new event listener similar to ListeningCurrentQuotaUpdater)

**DOD**: integration test

**Comment by Arsnael** [comment]
description missing

**Comment by Arsnael** [comment]
Should probably involve some event listener on jmap uploads, and we should be able to increase/decrease quotas depending on the treated even

**Comment by chibenwa** [comment]
Remarks:
 - Quota for JMAP uploads needs to be supported for memory too.
 - For the update we, as we do not need to deal with other protocols, I propose not to use a listener system and rather plug the quota update directly in the code.
 - Please tell where you would write these integraton tests...
 
 (sorry for the late ticket review)

**Comment by chibenwa** [comment]
https://jmap.io/spec-core.html#binary-data

Please read the spec...

```
When an upload would take the user over quota, the server MUST delete unreferenced blobs in date order, oldest first, until there is room for the new blob.
```

IE NEVER block the user.

That's a MUST so we NEED to comply.

**Comment by chibenwa** [comment]
See https://github.com/linagora/james-project/issues/4848
