### ISSUE TITLE
JMAP quota for uploads: Implement a web admin API to create limit of jmap uploads

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#4828]
**THIS TICKET WOULD BE DELETED**

**original ticket**: #4816

**WHY**

to implement a web admin API to create the limits of jmap uploads

**DESIGN**

Request: curl -XPOST '[http://ip:port/quota/limit](http://ip:port/quota/limit/%7BquotaComponent%7D/%7BquotaType%7D/%7BquotaScope%7D/%7Bidentifier%7D)'

    quotaComponent: mailbox, sieve, jmapUploads
    quotaType: count, size
    quotaScope: global, domain, user
    identifier: name of user, domain, ...

Request body: 
```
       {
          "quotaComponent": "jmapUploads",
          "quotaType": "size",
          "quotaScope": "global",
          "identifier": "abc",
          "quotaLimit": 100
       }
```

**Example**:

    Request: curl -XPOST 'http://ip:port/quota/limit/jmapUploads/size/global/abc'

**HOW**

- Create QuotaLimitRoutes if not existed
- Create a route to create the limit
- Create QuotaLimitService if not existed
- Create a method in QuotaLimitService to use QuotaLimitDao to create new quota limit

**DOD**: integration test

**Comment by Arsnael** [comment]
description missing

**Comment by hungphan227** [comment]
Should put idetifier in url or leave it in the body?

**Comment by chibenwa** [comment]
See https://github.com/apache/james-project/pull/1688: after careful consideration I do not think a webadmin API is needed.
