### ISSUE TITLE
JMAP quota for uploads: Implement a webadmin API to see user quota usage for JMAP uploads

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#4829]
**original ticket**: #4816

**WHY**

to implement a webadmin API that admin can use to view JMAP upload current value/ limit of each user

**DESIGN**

Request: curl -XGET '[http://ip:port/quota/limit/{quotaComponent}/{quotaType}/{identifier}](http://ip:port/quota/limit/%7BquotaComponent%7D/%7BquotaType%7D/%7Bidentifier%7D)'

    quotaComponent: mailbox, sieve, jmapUploads
    quotaType: count, size
    identifier: name of user

Example:

    Request: curl -XGET 'http://ip:port/quota/current-value/jmapUploads/size/abc'
    Response: 
                     {
                        "limit": 100,
                        "currentValue": 50,
                        "ratio": 0.5
                     }

**HOW**

- Create QuotaCurrentValueRoutes if not existed
- Create a route to see user quota usage
- Create QuotaCurrentValueService if not existed
- Create a method in QuotaCurrentValueService to use QuotaCurrentValueDao to get user quota usage

**DOD**: integration test

**Comment by Arsnael** [comment]
description missing
