### ISSUE TITLE
Investigate IMAP perfs after dependencies update

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4832]
After upgrading libs and dependencies of the project https://github.com/linagora/james-project/issues/4813 , it seems performances degraded in IMAP, as tested here: https://github.com/linagora/james-project/issues/4813#issuecomment-1658090779

We should investigate and fix issues

**Comment by vttranlina** [comment]
When I tried to investigate it, I realize the unstable in Gatling performance result

1. Here is the result of IMAP Gatling's performance last week
https://github.com/linagora/james-project/issues/4813#issuecomment-1658090779

And below is the result today of `linagora/tmail-backend:distributed-branch-master:latest`
Last commit: `0d522d79db4f39242a8e5b574c40a460c7ce0f03`
with same configuration (1pod, 6k user, duration=15minutes, charge1 -> sandbox)
![image](https://github.com/linagora/james-project/assets/81145350/e55f540f-46e3-4cee-9970-23f97b667d67)

The result is totally different: ~343 cnts/s, 99th =388. 
No degree performance, it is even better

For sure, I re-tested both "before"/"after" today.
**The configuration:**
- 1 pod
- charge 1 - > sandbox
- before `linagora/tmail-backend:distributed-0.7.0-rc1`
- After `linagora/tmail-backend:distributed-branch-master:latest` (0d522d79db4f39242a8e5b574c40a460c7ce0f03)
```
export DURATION=7
export USER_COUNT=10000
export MAX_DURATION=20
```

### Before
![image](https://github.com/linagora/james-project/assets/81145350/35d1e67e-d39f-4d63-97eb-5966a6d79103)

### After
![image](https://github.com/linagora/james-project/assets/81145350/b09dbb19-5bfa-4e05-a5a9-0f3815397151)

### The image immediately before upgrade dependency commit
 `vttran1/tmail-backend-distributed:750dceba9efe59541c6cd2798d789b0424f943f2`  (750dceba9efe59541c6cd2798d789b0424f943f2)

![image](https://github.com/linagora/james-project/assets/81145350/04be3773-d3c9-4cce-9ef7-b2fd1cad36a9)


___________
### Conclusion 

No degree IMAP performance

**Comment by quantranhong1999** [comment]
Can you kindly rerun the IMAP perf test for `tmail-backend-0.7.1-rc0` with the configuration (Env: 2 pods, 10k users, 60m simulation, warmed up)? 

I spotted in https://github.com/linagora/james-project-private/issues/696#issuecomment-1663755580 a bit IMAP perf degradation.

And I am curious about the result when OVH infra is in a "stable" state.

**Comment by Arsnael** [comment]
So finally no degradation? Did we get unlucky with some flaky ovh infra? 

What I have been thinking as well, maybe it depends on how busy the ovh infra is? If we run tests in the morning maybe we can get better run (night night time in France, probably having more bandwidth) compared to afternoon when it's the start of the day in Europe..?

Anyways... glad to see it looks ok now

**Comment by vttranlina** [comment]
> Can you kindly rerun the IMAP perf test for tmail-backend-0.7.1-rc0 with the configuration (Env: 2 pods, 10k users, 60m simulation, warmed up)?


![Image](https://github.com/linagora/james-project/assets/81145350/08fe0174-b239-4371-89d0-cf67ce7eff84)

we should test before/after at the same time,
