### ISSUE TITLE
JMAP quota for uploads: Implement a web admin API to update limit of uploads

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#4839]
**original ticket**: https://github.com/linagora/james-project/issues/4816

**WHY**

to implement a web admin API to update limits of jmap uploads

**DESIGN**

Request: curl -XPUT '[http://ip:port/quota/limit/{quotaComponent}/{quotaScope}/{identifier}](http://ip:port/quota/limit/%7BquotaComponent%7D/%7BquotaType%7D/%7BquotaScope%7D/%7Bidentifier%7D)'

quotaComponent: mailbox, sieve, jmapUploads
quotaScope: global, domain, user
identifier: name of user, domain, ...

Request body: {"count":52,"size":42}

Example:

Request: curl -XPUT 'http://ip:port/quota/limit/jmapUploads/domain/abc.com'
Request body: {"count":52,"size":42}

**HOW**

    Create QuotaLimitRoutes if not existed
    Create a route to create the limit
    Create QuotaLimitService if not existed
    Create a method in QuotaLimitService to use QuotaLimitDao to update new quota limit

**DOD**: integration test

**Comment by hungphan227** [comment]
quota type not necessary in url

**Comment by hungphan227** [comment]
I have just updated the API design. The ticket for creating limit would be removed.

**Comment by hungphan227** [comment]
I have created a draft PR https://github.com/apache/james-project/pull/1686 for this
@Arsnael could I move it to the column Review so that I could change to official PR?

**Comment by chibenwa** [comment]
Ok but do this only for JMAP uploads for now...
