### ISSUE TITLE
[BUILD] Unstable spamTrapHandlerTest.testSpamTrap

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4844]
org.apache.james.protocols.smtp.core.fastfail.SpamTrapHandlerTest.testSpamTrap seems failing quite a lot (twice tonight)

CF https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-1660/14/testReport/junit/org.apache.james.protocols.smtp.core.fastfail/SpamTrapHandlerTest/testSpamTrap/

TODO investigate

**Comment by quantranhong1999** [comment]
I tried to rerun the test locally a lot (repeated 1000 times), and none failed.

I think there is nothing wrong with the test itself, maybe an unstable issue with James CI. Without being able to reproduce, it is hard to "fix" anyway.

IMO let's put this on standby and observe the CI for a while.

**Comment by chibenwa** [comment]
Any issues related to the DNS available o the environment? Networking differences? (eg local addresses ranges) etc...

**Comment by quantranhong1999** [comment]
> Any issues related to the DNS available o the environment? Networking differences? (eg local addresses ranges) etc...

The tests use mock IPs, so should not.

But by paying more detailed attention to the test, I succeed to reproduce why the tests fail on CI:

```java
    // Spam from ip should be blocked for blockTime time frame
    HookReturnCode result = handler.doRcpt(setUpSMTPSession(ip), MaybeSender.nullSender(), new MailAddress(SPAM_TRAP_RECIP1)).getResult();
    assertThat(result).describedAs("Blocked on first connect").isEqualTo(HookReturnCode.deny());

    // The following sleep code does not exist in test, just add it to reproduce what happened on CI
    Thread.sleep(blockTime + 1); // CI's CPU busy doing some other tests, when CPU is available back -> time past the blockTime time frame

    // Spam from ip should still be blocked within blockTime time frame, but the time frame is past now -> no longer DENY
    result = handler.doRcpt(setUpSMTPSession(ip), MaybeSender.nullSender(), new MailAddress(RECIP1)).getResult();
    assertThat(result).describedAs("Blocked on second connect").isEqualTo(HookReturnCode.deny());
```

The rationale is a CPU race condition between tests on CI, leading to the test failed after a time frame.
-> Maybe I would try to increase a bit the `blockTime` to allow more resilience to wait for the CPU available.

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1685
