### ISSUE TITLE
Rework JMAP upload APIs

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4846]
# Why?

Reference: https://github.com/apache/james-project/pull/1688

JMAP upload storage evolutions:
 - As we add an application behaviour, common for any implementation, we need further layers in the design in
order to mutualize quota handling for all implementations. A service layer `UploadService` would expose the JMAP facade
(today `UploadRepository` interface) and would be responsible to enforce quotas, and related behaviour. Ten it would 
act on the storage layer, `UploadReposiory`, implemented by `cassandra` and `memory`.
 - Upon exceeded quota, we need to delete older uploads. In order to do so, we need to add the date of upload to the
upload metadata. Migration is trivial: we can assume UNIX timestamp when missing, causing the upload to be considered 
the oldest.
 - Recomputation of JMAP upload quotas requires listing stored upload metadata, we need to add a way to list uploads 
of a user on `UploadReposiory` (without retrieving the uploads contents).
 - `UploadService` needs a method to delete 
 
 # How
 
 1. Provide an `UploadService`.
 
 ```
 public class UploadService {
    Publisher<UploadMetaData> upload(InputStream data, ContentType contentType, Username user);

    Publisher<Upload> retrieve(UploadId id, Username user);
}
```

This service calls the existing `UploadRepository`.  This service is used instead of the `UploadRepository` by JMAP layer (blob resolvers, downloads, uploads).

2. Add the date of the upload within `UploadMetaData`. Add a column for this (timestamp data type is enough) within the Cassandra datamodel, and fallback to UNIX timestamp 1970 if missing.

`UploadService is the entity responsible to record the time of the upload and should embed a clock (configurable for tests).

3. Within `UploadRepository` add a method to delete a given blob.

4. Within `UploadRepository` add a method to list bobs.

As such `UploadRepository` should now look something like this:

 ```
 public class UploadRepository {
    Publisher<UploadMetaData> upload(InputStream data, ContentType contentType, Username user, Instant uploadTime);

    Publisher<Upload> retrieve(UploadId id, Username user);
    
    Publisher<UploadMetaData> listUploads(Username user); // many
    
    Publisher<Void> delete(UploadId id, Username user);
}
```

**Comment by vttranlina** [comment]
We need one more table for ` Publisher<UploadMetaData> listUploads(Username user);`
```
.withPartitionKey(USER, DataTypes.TEXT)
.withColumn(ID, DataTypes.TIMEUUID)
```

**Comment by chibenwa** [comment]
No CF CassandraUploadRepository

**Comment by chibenwa** [comment]
We `may` need to restructure the exisitng table if needed (user in the PK).

We can just create a new table and drop the old one. Impact: uploads wiil be lost -> not an issue.

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/1698
