### ISSUE TITLE
Define an API to store current values of JMAP uploads

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4847]
# Why ?

See https://github.com/apache/james-project/pull/1688 and https://jmap.io/spec-core.html#binary-data

Not implementing quota limitation for JMAP uploads essentially means we offer a free, really easy to use HTTP blob store to our users.

Thus in order to enforce a limitation we need to  store current values first.

# How?

1. Within `data-jmap` maven module implement a `UploadUsageRepository` interface:

```
public interface UploadUsageRepository {
    Publisher<Void> increaseSpace(User user, QuotaSizeUsage usage);
    Publisher<Void> decreaseSpace(User user, QuotaSizeUsage usage);
    Publisher<QuotaSizeUsage> spaceUsag(User user); // Need to log WARNING upon negative values and sanitize them to ZERO
     Publisher<Void> resetSpace(User user, QuotaSizeUsage usage);
}
```

2. Provide a memory implementation of this interface (LoadingCache + AtomicCounter: should be non-blobking concurrent frindly data structure) CF InMemoryCurrentQuotaManager to not reinvent the wheel.

3. Provide a contrat test excercizing the `UploadUsageRepository` methods and their edge cases.

4. Using [JAMES-3926](https://issues.apache.org/jira/browse/JAMES-3926) implement a Cassandra interface for this.

**Comment by hungphan227** [comment]
@chibenwa Why do we have to use LoadingCache?

**Comment by chibenwa** [comment]
> @chibenwa Why do we have to use LoadingCache?

For easier concurrency management?

If we succeed to do a thread safe version with `ConcurrentHashMap` I am happy too, to be honnest.

**Comment by hungphan227** [comment]
what do you mean? ConcurrentHashMap is thread safe

**Comment by hungphan227** [comment]
I change the interface a bit:

> public interface UploadUsageRepository {
>     Publisher<Void> increaseSpace(Username username, QuotaSizeUsage usage);
> 
>     Publisher<Void> decreaseSpace(Username username, QuotaSizeUsage usage);
> 
>     Publisher<QuotaSizeUsage> getSpaceUsage(Username username);
> 
>     Publisher<Void> resetSpace(Username username, QuotaSizeUsage usage);
> }

**Comment by hungphan227** [comment]
I have created PR https://github.com/apache/james-project/pull/1699
