### ISSUE TITLE
Rework JMAP quota cleanup

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4849]
The task should be based on the dates stored within the JMAP `UploadRepository`. 

Reimplement the task accordingly.

Discard any unrelevant code. Remove TTL in `UploadDAO`.

Note: requires https://github.com/linagora/james-project/issues/4846

**Comment by quantranhong1999** [comment]
Do you mean rework the current `UploadRepositoryCleanupTask`?

**Comment by chibenwa** [comment]
Yes that's a typo

**Comment by vttranlina** [comment]
the `uploads_2` table doesn't need a `bucket_id` column, we can have only one bucket for uploads
in past, we had a `bucket_id` column because we made a name based on the week number, which purpose to clean up.
And now we are based on upload_date
What do you think?

**Comment by Arsnael** [comment]
I would be alright with that personally

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/1701
