### ISSUE TITLE
JAMES-3926 Adopt Cassandra quota helpers for Mailbox quota (limits)

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4852]
-> Implement `CassandraPerUserMaxQuotaManagerV2`  a new version of `MaxQuotaManager` based on [JAMES-3926](https://issues.apache.org/jira/browse/JAMES-3926), and rename `CassandraPerUserMaxQuotaManager` into `CassandraPerUserMaxQuotaManagerV1`.
 
  -> Implement a `CassandraPerUserMaxQuotaManagerV2Migration` (`org.apache.james.backends.cassandra.migration.Migration` )
It takes `@Named("old") MaxQuotaManager maxQuotaManager` as a parameter and use it to set values in `CassandraPerUserMaxQuotaManagerV2`. + register the migration.

  -> Implement a `FakeMaxQuotaManager`.
 
 -> Configuration for the compatibility mode in `cassandra.properties`
 
```
cassandra.quota.compatibility.mode=false
```

And use it in a module choose. If true

 - `MaxQuotaManager` is bound to `CassandraPerUserMaxQuotaManagerV1`
 -  `@Named("old") MaxQuotaManager maxQuotaManager` is bound to `CassandraPerUserMaxQuotaManagerV1`
 - Binding for `CassandraCurrentQuotaManagerV1` tables
 
If false:

 - StartupCheck to enforce James is running a high enough Cassandra schema version. Tells ow to enable compatibility mode + URL to the webadmin doc to trigger the migration...
 - `MaxQuotaManager` is bound to `CassandraPerUserMaxQuotaManagerV2`
 -  `@Named("old") CassandraCurrentQuotaManager cassandraCurrentQuotaManager` is bound to `FakeMaxQuotaManager`

-> Upgrade instruction:enable comatibility mode + trigger the Cassandra migration

-> Deprecate `CassandraPerUserMaxQuotaManagerV1` and related classes, DAO, modules, tables

**Comment by hungphan227** [comment]
PR https://github.com/apache/james-project/pull/1706
