### ISSUE TITLE
Double URL encoding for MailAddress parsing in WebAdmin

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4855]
URL decoding is performed both by Spark and by us.

Example for forwards:

```
http://localhost:43353/address/forwards/alice%40b.com/targets/bob%252Btag%2540b.com
=>
http://localhost:43353/address/forwards/alice@b.com/targets/bob%2Btag%40b.com
=>
http://localhost:43353/address/forwards/alice@b.com/targets/bob+tag@b.com
```

Only one URL encoding is enough...

 - [ ] Fix it for forwards and all places related to `MailAddressParser`

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1697

**Comment by Arsnael** [comment]
Why reopen? The PR is merged, anything left to do?

**Comment by quantranhong1999** [comment]
> Why reopen? The PR is merged, anything left to do?

Not sure from my side, maybe Benoit wants backports?

**Comment by Arsnael** [comment]
Ah possible yeah :)

**Comment by chibenwa** [comment]
No not especially. Maybe false manipulation.
