### ISSUE TITLE
Manage deletion in  ComputeMessageFastViewProjectionListener

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4867]
If the message is no longer referenced (metadata level read using the MessageIdManager) then delete the corresponding preview.

## Why ?

Privacy...

And data consumption....

## How I noticed

`nodetool -u linagora -pw xxxxx tablestats` showed `message_fast_view_projection` was having ~11M entries while `messagev3` has ~9.5 entries

## Dod

Write unit tests for ComputeMessageFastViewProjectionListener showing how deletion and moves are handled.

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/1730
