### ISSUE TITLE
blob_cache table needs to use STCS

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4868]
## Why

The use of TWCS creates MANY small SSTABLE and puts a loot of pressure on the Cassandra server

## Dod

Switch to STCS

## How the issue was spotted 

```
nodetool -u linagora -pw xxx tablestats linagora_james.blob_cache
...
		Table: blob_cache
		SSTable count: 1907
```

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/1731
