### ISSUE TITLE
WHEN I move a message I should not store again its messageFastView projection

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4869]
## Step 1: reproduction

Currently, write a test demonstrating that when I move a message, we do not store again it's fast view projection.

To that end, we can leverage StatementRecorder of Cassandra testing session.

## Why this is a problem?

This design mistake causes expensive computations upon message moves. It causes unecessary object store reads.

Also, it leads to unnecessary data being stored in Cassandra. Here is the `nodetool` output before and after a compaction:

```
		Table: message_fast_view_projection
		Space used (live): 3 677 832 422
		...
                Space used (live): 2 297 014 061
```

## Architecture of a solution

We need to cary over in the event system of the fact that a given `Added` event is a new message in the store or not (copy move).

Then, listeners can take educated decisions and avoid unecessary work. Here only compute projection for appends.

## Step 2: add isAppended():boolean method to Added

Add a `isAppended():boolean` method to the `Added` event.

Add this metadata in the serialized event.

Backward compatibility needs to be enforced when deserializing an event: missing ``isAppended` property needs to be handled. Defaults to true...

# Step 3: Use Added::isAppended in ComputeMessageFastViewProjectionListener

This should fix the test written in step 1

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/1733
