### ISSUE TITLE
James Gatling: performance test for move

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4871]
Add in the JMAP simulations with a 1% chance the following step:

 - User move a message from mailboxA to mailbox B sleep 1 second and move message back to message A
 
Message needs to be randomly selected

Report on the performance of moving a message on preprod here.

**Comment by chibenwa** [comment]
https://github.com/linagora/james-gatling/pull/172 scenario implemented.

**Comment by chibenwa** [comment]
Benchmarks settings:
 - Injection time: 4 minutes
 - Test time: 12 minutes
 - moveTwice probability: 33%
 - Pause time: exactly one second
 - 2000 users
 - Run on my laptop against pre-prod

[INSERT PIC HERE]

Note that measuring listeners execution time. seeing RabbitMQ queue depth would be REALLY valuable variable. Feel free to re-run and monitor these variables too.

Conclusion:
 - I miss background metrics measurement
 - But on user facing metrics this seems already not bad.

**Comment by chibenwa** [comment]
During the bench:

```
hp@hp-HP-ProBook-440-G5:~$ kubectl top nodes
NAME                                         CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
node-a991ce2a-d56c-4728-9971-97abf73e0567    1615m        42%    5965Mi          47%       
node-b5d24256-a3f2-4b4a-9202-82eb33289fd3    411m         10%    1384Mi          10%       
node-dbea1041-b2ee-4277-b591-deb258ab83d7    2638m        68%    7708Mi          61%       
nodepool-cda51cb9-accc-45f9-80-node-2ab666   2418m        63%    9202Mi          72% 
```

A RabbitMQ queue is forming:



![Image](https://github.com/linagora/james-project/assets/6928740/b35c8953-d408-48ba-b605-74d25ce4216c)

**Comment by vttranlina** [comment]
> TMail version: linagora/tmail-backend:distributed-0.7.1-rc1
> does this includes the preview fix?

You mean https://github.com/apache/james-project/pull/1730, https://github.com/apache/james-project/pull/1733 ?
It not yet

**Comment by vttranlina** [comment]
> mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.999",} 0.281018367
> mailbox_listener_OpenSearchListeningMessageSearchIndex_count 757707.0
> 
> mailbox_listener_PopulateEmailQueryViewListener{quantile="0.5",} 0.009764863
> mailbox_listener_PopulateEmailQueryViewListener{quantile="0.75",} 0.013434879

How I can get this metric on sandbox?

**Comment by Arsnael** [comment]
> How I can get this metric on sandbox?

On your terminal, port-forward locally the webadmin port of james :

```
kubectl port-forward svc/tmail-admin 8000:8000 -n sandbox
```

Then access the exposed metrics route from your browser => http://localhost:8000/metrics
