### ISSUE TITLE
OpenSearch search index: upon move, GET then INDEX

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4872]
Currently upon message move we query the full message within the mailbox (causing S3 reads, and expensive parsing) in order to reindex it in OpenSearch.

We likely could...

... if the message is not appended then we could attempt to retrieve the sources from OpenSearch from the old mailbox, 
... deserialise them
... patch them to update the savedDate, uid, mailboxId
... and index them again

If we do not succeed to find the sources in OpenSearch, we can fallback to the current indexing (read full message...)

Benchmark this changes with https://github.com/linagora/james-project/issues/4871 prior to adoption on preprod...

Note: I strongly suspect that it might be trickier to avoid data races upon move... (ie content is deleted from ES before we read it)
    In order to avoid such data race we could...
    ... Add a Expunged::isMoved property and use it to ignore the deletion in OpenSearch
    ... Add a Added::isMoved property and use it to ignore indexing in OpenSearch
    .. And manage everything (indexing new value and deleting old value) with the moved event...

**Comment by chibenwa** [comment]
Possible side effect: https://issues.apache.org/jira/browse/JAMES-3728

By adding flags in the Moved event we could also get rid of a data race?

**Comment by vttranlina** [comment]
When `moved`
- with `Added` event, we can't know the `target` mailbox (or I don't know how to get the target mailbox)
- same with `Expunged` event, we can't know the `source` mailbox

=> We can't get the original message from OpenSearch

I propose we add one more field to Added event, `MailboxId moveToMailboxId`

**Comment by Arsnael** [comment]
You sure it's not the other way around? Can't know the source with Added and target with Expunged? Cause I would think we expunge on the source and add on the target to make the move?

But getting the general idea :)

**Comment by vttranlina** [comment]
> In order to avoid such data race we could...
> ... Add a Expunged::isMoved property and use it to ignore the deletion in OpenSearch
> ... Add a Added::isMoved property and use it to ignore indexing in OpenSearch

The current James used MailboxId for OpenSearch documented, routingkey. 
When we moved the message from mailbox A -> B, the mailboxId was changed 
I don't know another way if not remove the old document, then create  index a new document

**Comment by vttranlina** [comment]
> You sure it's not the other way around? Can't know the source with Added and target with Expunged? Cause I would think we expunge on the source and add on the target to make the move?

Yes, it should be "moved FROM" in `Added` and "moved TO` in `Expunged`

**Comment by vttranlina** [comment]
> I don't know another way if not remove the old document, then create index a new document

I got an idea, delete immediately after recreating index, Don't need wait to next Event

**Comment by Arsnael** [comment]
Hmmm sorry I just rechecked the code and task details.

To resume:

In `ListeningMessageSearchIndex`, in the `handleMailboxEvent` private method, if : 
- added event => index
- expunged event => delete index

If you add and have `isMoved` to true  you ignore those above operations on those events.

Then you can decide for example to add the missing mailbox  source field on Added event, and on the case of Added event and isMoved, you fetch the current index with the old mailboxId, then reindex it with the new mailboxId, and delete the old one. And Expunged event with isMoved you ignore :)

If that is what you meant above then yes I believe it should work :)

**Comment by quantranhong1999** [comment]
> .. And manage everything (indexing new value and deleting old value) with the moved event...

I quoted from Benoit's idea in the ticket description.
I see actually upon `StoreMessageManager::move` we emit `MessageMoveEvent`. 
This `MessageMoveEvent` contains `messageIds` moved from `sourceMailboxId` to `targetMailboxId`.
How about handling `MessageMoveEvent` in `ListeningMessageSearchIndex`? (no need to add any mailbox information to `Added` or `Expunged` events)

**Comment by vttranlina** [comment]
Some disadvantages of `MessageMoveEvent`
- Now it does not include `MessageUid`, while we need it for OpenSearch now
- The "logic" for decreasing the request to Cassandra we can also adapt for `Copy` logic (not only move)

**Comment by vttranlina** [comment]
# Benchmark result

james charge 1  -> sandbox (2pod)

- Image: `tungtv202/tmail-backend-distributed:2809_v4`
- Scenario
```
export DURATION=10
export USER_COUNT=5000
export MAX_DURATION=25
```
- `moveTwice` : 26%

```
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.5",} 0.034865151000000004
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.75",} 0.071827455
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.95",} 0.142606335
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.98",} 0.201326591
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.99",} 0.316669951
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.999",} 2.105540607
mailbox_listener_OpenSearchListeningMessageSearchIndex_count 56860.0


mailbox_listener_PopulateEmailQueryViewListener{quantile="0.5",} 0.010485759
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.75",} 0.013565951000000001
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.95",} 0.029753343
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.98",} 0.061603839
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.99",} 0.090177535
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.999",} 0.205520895
mailbox_listener_PopulateEmailQueryViewListener_count 56860.0
```
![image](https://github.com/linagora/james-project/assets/81145350/76ec0e1b-3925-415c-9e18-707fff8aef7f)
![image](https://github.com/linagora/james-project/assets/81145350/ce4941b8-f8ba-44c6-a924-302c87461eba)

![ttungtv](https://github.com/linagora/james-project/assets/81145350/c35a9b74-02fd-4220-b356-6156d3bc5b53)

**Comment by vttranlina** [comment]
Same scenario, but `Image: linagora/tmail-backend:distributed-0.7.1-rc1` result 

```
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.5",} 0.022020095
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.75",} 0.068157439
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.95",} 0.142606335
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.98",} 0.207618047
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.99",} 0.306184191
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.999",} 2.046820351
mailbox_listener_OpenSearchListeningMessageSearchIndex_count 52092.0

mailbox_listener_PopulateEmailQueryViewListener{quantile="0.5",} 0.012058623000000001
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.75",} 0.016580607
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.95",} 0.054788095
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.98",} 0.09856614300000001
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.99",} 0.141557759
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.999",} 0.343932927
mailbox_listener_PopulateEmailQueryViewListener_count 52092.0
```

![image](https://github.com/linagora/james-project/assets/81145350/d07acc01-fa56-4b45-a0e4-f76363e9fb8e)
![image](https://github.com/linagora/james-project/assets/81145350/3555976c-1274-4bac-adf2-d6a761b4cfe5)
![0 7 1-rc1](https://github.com/linagora/james-project/assets/81145350/cc5c7f45-d149-4a5e-8838-5bedfb391893)

**Comment by chibenwa** [comment]
We see an improvment on the Preview front for sure
But it looks like we have no improvment on OpenSearch side.

Correct?

**Comment by Arsnael** [comment]
> But it looks like we have no improvment on OpenSearch side.

Don't you mean no degradation of perf for OpenSearch instead? (which is good^^)

As instead of just delete -> reindex, we do more things as : fetch -> reindex -> delete ?

**Comment by vttranlina** [comment]
Should we collect the metric `ComputeMessageFastViewProjectionListener` or `PopulateEmailQueryViewListener`?

**Comment by chibenwa** [comment]
> The perf on the move action looks better as well :)

Measuring a user facing action for a background work is not relevant.

Pearformance of the OpenSearch indexer seems poorer. For adoption of a performance improvment, it is generally a good idea to have a clear benefit.

**Comment by Arsnael** [comment]
> Pearformance of the OpenSearch indexer seems poorer. For adoption of a performance improvment, it is generally a good idea to have a clear benefit.

I'm sorry I still do not understand how you expect we get a better perf out of Opensearch for this work on move while we do end up asking more work from opensearch (for the sake of not hitting S3 with a full read anymore). Explain to me please, and the team, cause the team in general was confused about your comments during daily as well :)

**Comment by quantranhong1999** [comment]
Today our Cassandra seems to handle more workload than OpenSearch.

Being able to switch some (listener) load from Cassandra to OpenSearch is still a good point to me. I would take it IMO.

**Comment by chibenwa** [comment]
I'm unsure to be honnest.

**Comment by chibenwa** [comment]
Maybe do the test with bigger messages, with attachments?

=> Small messages are easy to retrieve, parse and index, but likely the overhead is higher for big messages.

**Comment by vttranlina** [comment]
yes

**Comment by vttranlina** [comment]
Please ignore the benchmark result of https://github.com/linagora/james-project/issues/4872#issuecomment-1738950186
Reason: the "isMoved" logic did not work as we expected. I missed the case when moved by JMAP Email/set update. The commit fix that: https://github.com/apache/james-project/pull/1740/commits/5bf516c9915d45407133edd460e9bc35b91f5892

## The benchmark result again

## Before (`linagora/tmail-backend:distributed-0.7.1-rc1`)
```
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.5",} 0.015138815000000002
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.75",} 0.061079551
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.95",} 0.12582911900000002
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.98",} 0.18874367900000003
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.99",} 0.287309823
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.999",} 2.466250751
mailbox_listener_OpenSearchListeningMessageSearchIndex_count 55168.0

mailbox_listener_PopulateEmailQueryViewListener{quantile="0.5",} 0.010944511
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.75",} 0.014942207
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.95",} 0.035127295
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.98",} 0.077070335
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.99",} 0.119013375
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.999",} 0.312475647
mailbox_listener_PopulateEmailQueryViewListener_count 55168.0
```

## After (

```
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.5",} 0.015269887000000001
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.75",} 0.022675455
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.95",} 0.09804185500000001
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.98",} 0.153092095
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.99",} 0.20866662300000002
mailbox_listener_OpenSearchListeningMessageSearchIndex{quantile="0.999",} 1.0401873910000001
mailbox_listener_OpenSearchListeningMessageSearchIndex_count 111993.0

mailbox_listener_PopulateEmailQueryViewListener{quantile="0.5",} 0.010616831
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.75",} 0.013697023000000001
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.95",} 0.030015487
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.98",} 0.063176703
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.99",} 0.096468991
mailbox_listener_PopulateEmailQueryViewListener{quantile="0.999",} 0.25794969500000003
mailbox_listener_PopulateEmailQueryViewListener_count 111993.0
```

Expunged.isMoved counter:
- Total: 53007
- Found the indexed in OpenSearch: 40250
- Not found: 6380

(Note that: to increase the Found, we should re-run the scenario several times. It was quite low in my first time)


## Conclusion
- The performance of OpenSearchListeningMessageSearchIndex looks better. Because fewer fetch data from blobstore

**Comment by chibenwa** [comment]
What was the average size of messages?

Do playing this with bigger messages helps?

**Comment by chibenwa** [comment]
With a workqueue mean time is more meaningful than p99

**Comment by vttranlina** [comment]
> Possible side effect: https://issues.apache.org/jira/browse/JAMES-3728
> By adding flags in the Moved event we could also get rid of a data race?

Relate to this, I created a new issue for the split task https://github.com/linagora/james-project/issues/4882
