### ISSUE TITLE
Email address case sensitivity

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4873]
Within `james-server-memory-app` tests, write the following RCPTCaseSensitivityTest :

```
GIVEN I have an email benoit.tellier@linagora.com
WHEN I send an email from external user (SMTP port 25 not authenticated) to Benoit.Tellier@linagora.com
THEN the email arrives in benoit.tellier@linagora.com mailbox
```

```
GIVEN I have an email benoit.tellier@linagora.com
WHEN I send an email from internal user (SMTP port 25 authenticated as internal@linagora.com) to Benoit.Tellier@linagora.com
THEN the email arrives in benoit.tellier@linagora.com mailbox
```

```
GIVEN I have an email benoit.tellier@linagora.com
WHEN I send an email from internal user (JMAP authenticated as internal@linagora.com) to Benoit.Tellier@linagora.com
THEN the email arrives in benoit.tellier@linagora.com mailbox
```

(case insentivity by default)

Note that this is not applicable for login.

Is it the case already?

Maybe we could have a `NormalizeRecipientCase` mailet within the mailet container?
How about SMTP hooks? Is it a problem not to have case there? EG in `ValidRcptHandler` ?

**Comment by quantranhong1999** [comment]
I just played a test case on `tmail.linagora.com` and it is the above case ^^

Of course, we should write tests anyway.

**Comment by chibenwa** [comment]
Because of James or because of the above postfix?

**Comment by quantranhong1999** [comment]
> Because of James or because of the above postfix?

I tested with JMAP. Mail sent by JMAP should not go through Postfix Y, no?

**Comment by chibenwa** [comment]
It currently do

**Comment by quantranhong1999** [comment]
I retested that with JMAP preprod, and it still succeeds:
![image](https://github.com/linagora/james-project/assets/55171818/62914ec6-df70-4c5d-8282-45b9649a1bca)

For preprod: mails sent via JMAP do not go through `postfix-in` pod (no logs). Makes sense with the [conf in mailetcontainer.xml](https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/emaily-staging-apps/-/blob/main/tmail/configs/mailetcontainer.xml#L122) though.

**Comment by Arsnael** [comment]
Yes I think we changed the conf for it not to be relayed in this case with jmap. I wasn't sure yesterday as I tinkered so much the conf between preprod and prod, sometimes I'm lost :) Thanks for checking though

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1737
