### ISSUE TITLE
[EPIC] Crowdsec integration to James

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4874]
[CrowdSec](https://www.crowdsec.net/) is a free, modern & collaborative behavior detection engine, coupled with a global IP reputation network, based on AI behaviour refinement.

Develop a third-party plugin in James for questionning CrowdSec:

- Create a SMTP EHLO hook questionning via a REST call the CrowdSec local agent
- Create a mailet questionning via a REST call the CrowdSec local agent
- Create a mailet to provision local CrowdSec database (for highest level of spam for instance)
- Think about the interfaces we would need to question CrowdSec upon incoming IMAP connections
- Externalize behaviour linked to failed login attempts (sleep, 3 failure connection closure) as configurable extensible - plugins.
- Use it to manage IP reporting to crowdSec, especially upon failed authentications (~fail2ban).

rf: https://issues.apache.org/jira/browse/JAMES-3897, https://github.com/linagora/tmail-backend/issues/803

cc @guimard @chibenwa

**Comment by quantranhong1999** [comment]
@thanhbv200585 please research the topic and make a proposal about the list of tasks (could think more or less than the above tasks if needed) with basic ticket details first.

**Comment by vttranlina** [comment]
`query mode ip` API looks like what we want 
https://doc.crowdsec.net/docs/local_api/bouncers#query-mode--ip

**Comment by thanhbv200585** [comment]
Task proposal:
- ADR
- Create a SMTP EHLO hook questionning via a REST call the CrowdSec local agent
- Create a mailet questionning via a REST call the CrowdSec local agent
- Create a mailet to provision local CrowdSec database (for highest level of spam for instance) (https://doc.crowdsec.net/docs/local_api/bouncers#query-mode--ip)
- Think about the interfaces we would need to question CrowdSec upon incoming IMAP connections (check a mail used for spam)
- Externalize behaviour linked to failed login attempts (sleep, 3 failure connection closure) as configurable extensible - plugins.
- Use it to manage IP reporting to crowdSec, especially upon failed authentications (~fail2ban).

**Comment by guimard** [comment]
> Task proposal:
> 
>     * ADR
>     * Create a SMTP EHLO hook questionning via a REST call the CrowdSec local agent

Not only SMTP, IMAP/POP also

>     * Create a mailet questionning via a REST call the CrowdSec local agent
>     * Create a mailet to provision local CrowdSec database (for highest level of spam for instance) (https://doc.crowdsec.net/docs/local_api/bouncers#query-mode--ip)
>     * Think about the interfaces we would need to question CrowdSec upon incoming IMAP connections (check a mail used for spam)
>     * Externalize behaviour linked to failed login attempts (sleep, 3 failure connection closure) as configurable extensible - plugins.
>     * Use it to manage IP reporting to crowdSec, especially upon failed authentications (~fail2ban).

**Comment by quantranhong1999** [comment]
> Task proposal:

Basic details for each task, and are there any possible tasks?

**Comment by Arsnael** [comment]
I didn't have time to really have a look myself tbh, but I would think you would need first a client to communicate with crowdsec, which would force you to implement a docker extension for testing too

**Comment by quantranhong1999** [comment]
> (later) one to push information to Crowdsec (~fail2ban)

Do you suggest letting CrowdSec access the James logs, or we let James push directly alerts/decisions via CrowdSec HTTP API?

**Comment by guimard** [comment]
It's easy to write the first plugin: [Lemonldap-NG plugin as example](https://gitlab.ow2.org/lemonldap-ng/lemonldap-ng/-/blob/v2.0/lemonldap-ng-portal/lib/Lemonldap/NG/Portal/Plugins/CrowdSec.pm?ref_type=heads#L50-100)

**Comment by quantranhong1999** [comment]
> (later) one to push information to Crowdsec (~fail2ban)

I succeeded to report IP via HTTP API directly
[Screencast from 21-09-2023 14:35:08.webm](https://github.com/linagora/james-project/assets/55171818/6bed6022-711e-455e-b73d-46c08ab1d2f5)

**Comment by chibenwa** [comment]
>  or we let James push directly alerts/decisions via CrowdSec HTTP API?

This one eliminate the need to plug James logs to crowdsec and might save headaches with fluentbit / loki...

**Comment by quantranhong1999** [comment]
Rene:

> This one eliminate the need to plug James logs to crowdsec and might save headaches with fluentbit / loki...

You mean implement the magic on our side about if we should ban an IP or not and just report to crowdsec? I feel it would be more of an headache than just letting crowdsec scraping our logs and doing the magic itself that he is supposed to know to do well already, no? It would mean you need to track all failed attempts (like with Redis?) 

I would be more interested to know if we can just report via HTTP API to crowdsec IPs that are failing to login and if crowdsec is able to detect many reports of failed attempts from a same IP from us and act in consequence?

 > (later) one to push information to Crowdsec (~fail2ban)

Can we have more detail on that? I'm not sure if it means we do the magic implementation of determining ourselves which IPs to ban, or if we just tell crowdsec this IP failed to login and let crowdsec take the decision after a couple of similar reports... (joins my previous point)

Looks confusing to me (and the team)

**Comment by quantranhong1999** [comment]
Propose other tasks:  
    - Crowdsec Docker extension
    - Crowdsec configuration + Crowdsec HTTP client
    ... above tasks: https://github.com/linagora/james-project/issues/4874#issuecomment-1728951196
    - Integrate Crowdsec modules into TMail backend
    - Helm chart for Crowdsec (crowdsec already provides helm chart)
    - Deploy Crowdsec in preprod/sandbox
    - Setup Prometheus + Grafana dashboard for CrowdSec (CrowdSec does provide /metrics endpoint)
    - Performance test TMail with CrowdSec

**Comment by quantranhong1999** [comment]
FYI, CrowdSec supports 
- [Ingress Nginx Bouncer](https://docs.crowdsec.net/docs/bouncers/ingress-nginx) / [OpenResty Bouncer](https://docs.crowdsec.net/docs/bouncers/openresty) (which APISIX based on) / [NGINX bouncer](https://docs.crowdsec.net/docs/bouncers/nginx) -> cover JMAP, and even other Linagora services
- [HAProxy Bouncer](https://docs.crowdsec.net/docs/bouncers/haproxy) -> cover IMAP

Missing SMTP though.
If we want a no-code solution, and not only for TMail but for other services as well, we have the choice :-)

**Comment by chibenwa** [comment]
>  Integrate Crowdsec modules into TMail backend

Why not James?
