### ISSUE TITLE
[FILTER] Forward action

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4877]
# Why

I want to be more flexible than regular forwards eg only forward mails from a given sender.

# How

In order to do this, write a new filter action: fowardTo.

Forward to can take the following form:

```
{
    "addresses": ["rcordier@linagora.com", "hqtrong@linagora.com"],
    "keepACopy": true
}
```

A new mail will be submitted to the addresses mentioned (using `MailetContext`), and the processing would either continue or be stopped depending of "keepALocalCopy".

# Steps

 - [ ] Needs evolution on the Filter DTO object for storing filters in the event store. We need to test and handle retro - compatibility - default to NO forwardTo action. Unit test in `FilteringManagementContract`.
 - [ ] Need to expose this through JMAP draft layers
 - [ ] Need to expose that in the TMail backend extension
 - [ ] Implement the action in `ActionApplier` for JMAPFiltering mailet and unit test this (using `FakeMailetContext`)
 - [ ] Write an integration test for forwardTo.
 - [ ] Update tmail backend JMAP doc for filter
 - [ ] Ping mobile team: https://github.com/linagora/tmail-flutter/issues/2084

**Comment by hungphan227** [comment]
@Arsnael @chibenwa I do not understand how "keepACopy" work. I could not see where users add this value on the frontend (the only thing I see on the frontend is the textbox to add forwarding addresses)

**Comment by chibenwa** [comment]
Then design team need to add a checkbox: keep a copy....

Like regular forwards today:

![image](https://github.com/linagora/james-project/assets/6928740/5ce4f6c5-4660-401a-b534-7dc2a5d0c8bb)

**Comment by Arsnael** [comment]
> @Arsnael @chibenwa I do not understand how "keepACopy" work. I could not see where users add this value on the frontend (the only thing I see on the frontend is the textfield to add forwarding addresses)

The keep a copy checkbox appears I believe at the moment you have a list of forwards. If it's empty, it does not show, as it's not necessary (cause no forwards)

**Comment by hungphan227** [comment]
> Needs evolution on the Filter DTO object for storing filters in the event store. We need to test and handle retro - compatibility - default to NO forwardTo action. Unit test in FilteringManagementContract.

@chibenwa @Arsnael  Are "Filter DTO object" are Rule and RuleDTO classes?

**Comment by chibenwa** [comment]
Yes

**Comment by Arsnael** [comment]
> @chibenwa @Arsnael Is "Filter DTO object" Rule and RuleDTO classes?

Should be yes

**Comment by Arsnael** [comment]
Not necessary, just need to update tmail with the james submodule with that work merged :)

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/JAMES-3951 should have been the JIRA ticket here
