### ISSUE TITLE
ICALAttributeDTO: support missing fields

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4880]
```
java.lang.IllegalStateException: uid is a compulsory property of an ICAL object
...
```

Reason: Compulsory fields within `ICALAttributeDTO`

Issue is that if any of these field is missing, James would abort event processing, preventing Calendar from recovering and ingesting the event...

Solutions: in `ICALAttributeDTO` make 

```
    private final String uid;
    private final String dtstamp;
    private final String method;
```

Optional. 

Breaking change needs to be documented.

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1756
