### ISSUE TITLE
JAMES-3944 [FILTER] Forward action: forward loop issue

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#4888]
**Why**

The forward loop occurs when user A forward the email to user B, user B forward the email to user C, user C forward email to user A and this happen forever.

**How**

Potential solution: set an attribute in the email to store all forwarded users. Use this list to check if a specific user has been forwarded or not

**Integration test cases**

-  User A setup filter forward to user B. User B setup filter forward to user C. User C setup filter forward to user A. Send an email to user A, user C should not send the email to user A.
-  User A setup regular forward (RRT) to user B. User B setup regular forward to user C. User C setup regular forward to user A. Send an email to user A, user C should not send the email to user A.
-  User A setup filter forward to user B. User B setup regular forward to user C. User C setup filter forward to user A. Send an email to user A, user C should not send the email to user A.

**Comment by hungphan227** [comment]
PR https://github.com/apache/james-project/pull/1758

**Comment by chibenwa** [comment]
JIRA https://issues.apache.org/jira/browse/JAMES-3944 (comment)
