### ISSUE TITLE
JAMES-3897: Crowdsec check with SMTP Authentication

### ISSUE THREAD

**Issue by thanhbv200585** [linagora/james-project#4890]
EPIC https://github.com/linagora/james-project/issues/4874

**Comment by quantranhong1999** [comment]
Can you add a bit of description?

**Comment by thanhbv200585** [comment]
Jira: https://issues.apache.org/jira/browse/JAMES-3897
Add more patterns for Crowdsec to check login attack by SMTP Authentication

**Comment by thanhbv200585** [comment]
PR: https://github.com/apache/james-project/pull/1759

**Comment by thanhbv200585** [comment]
Demo: https://github.com/apache/james-project/pull/1759#issuecomment-1774533163
