### ISSUE TITLE
[Postgres] Introduce Postgres Container extension

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4894]
- Create a new submodule (postgres) in `backends-common/postgres` (<artifactId>apache-james-backends-postgres</artifactId>)
- Create a Postgres container extension 
ref: 
```
<dependency>
        <groupId>org.testcontainers</groupId>
        <artifactId>postgresql</artifactId>
        <version>1.17.2</version>
</dependency>
```

- Extension should support import PostgresModule and init table when starting. Same with [CassandraClusterExtension](https://github.com/apache/james-project/blob/master/backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/CassandraClusterExtension.java)

## Dod
- create a pr to "postgres" branch
- simple extension test suite

## Ref
[pulsar PostgresExtension](https://github.com/apache/james-project/blob/master/server/apps/scaling-pulsar-smtp/src/test/java/org/apache/james/PostgresExtension.java)

**Comment by quantranhong1999** [comment]
> Extension should support import PostgresModule and init table when starting

May need to depend on [Postgres] Implement PostgresTableManager #4898 to create tables in tests.

But [Postgres] Implement PostgresTableManager #4898 needs this extension to test as well.

Therefore I propose starting this extension first with the dummy create/truncate tables parts, and mostly expose the Postgres container.

**Comment by quantranhong1999** [comment]
Or start [Postgres] Implement PostgresTableManager https://github.com/linagora/james-project/issues/4898 first and rely on pure Postgres @Testcontainers.

Then properly do this extension.

**Comment by Arsnael** [comment]
@quantranhong1999 Don't hesitate to break this task down to smaller ones if it makes more sense :)

**Comment by quantranhong1999** [comment]
> @quantranhong1999 Don't hesitate to break this task down to smaller ones if it makes more sense :)

Hmm I just discuss with Tung and we think should go for this https://github.com/linagora/james-project/issues/4894#issuecomment-1784468020

**Comment by vttranlina** [comment]
> But [Postgres] Implement PostgresTableManager https://github.com/linagora/james-project/issues/4898 needs this extension to test as well.

We can test`PostgresTableManager` with simple `PostgreSQLContainer`

// PostgresContainerExtension is more complex than `PostgreSQLContainer`

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1772
