### ISSUE TITLE
[Postgres] Implement DAO for MAIL_USERFLAG table 

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4900]
Epic: https://github.com/linagora/james-project/issues/4895

## How

- Define Table. JPA JAMES_MAIL DDL reference
```sql
create table JAMES_MAIL_USERFLAG
(
    USERFLAG_ID   bigint       not null
        primary key,
    USERFLAG_NAME varchar(500) not null,
    MAILBOX_ID    bigint       null,
    MAIL_UID      bigint       null,
    constraint JAMES_MAIL_USERFLAG_ibfk_1
        foreign key (MAILBOX_ID, MAIL_UID) references JAMES_MAIL (MAILBOX_ID, MAIL_UID)
            on delete cascade
);
```
- location: `mailbox/postgres`

## Dod
Unit test

**Comment by chibenwa** [comment]
Please do NOT reuse JPA table as is.

We can and very likely SHOULD create our own table for PGSQL.

Also `MESSAGE_ID` needs to be in the table I bet. Also use UUIDs for identifiers (mailboxId, messageId).  https://www.postgresql.org/docs/current/datatype-uuid.html 

For keywords I would personnally prefer https://www.postgresql.org/docs/current/arrays.html array data types as it prevents a **JOIN**.

**Comment by vttranlina** [comment]
The Flag will be done in MAIL table, with the array data type 
https://github.com/linagora/james-project/issues/4899
