### ISSUE TITLE
[Postgres] Implement PGMailboxMapper

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4901]
Epic https://github.com/linagora/james-project/issues/4895
Require: Mailbox DAO https://github.com/linagora/james-project/issues/4897

## How
Implement MailboxMapper interface 
```java
public class PGMailboxMapper implements MailboxMapper {
    private final PGMailboxDAO mailboxDao;
   /// 
}
```

## Dod
Pass contract test [MailboxMapperTest](https://github.com/apache/james-project/blob/5ccf47c38a651653a79283f9f83b491d72b852e9/mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MailboxMapperTest.java)

**Comment by chibenwa** [comment]
What table structure will we choose?

**Comment by chibenwa** [comment]
> What table structure will we choose?

Please?

And implement ACLs while we are at it...

**Comment by vttranlina** [comment]
> Please?
> 
> And implement ACLs while we are at it...

The table structure will be defined in DAO https://github.com/linagora/james-project/issues/4897

As your previous comment

> Use UUID for mailboxId

-> Clone JPA JAMES_MAILBOX structure, and change MAILBOX_ID from bigint to uuid

**Comment by Arsnael** [comment]
> And implement ACLs while we are at it...

We agreed to do ACLs in an other ticket for next sprint initially :)

**Comment by hungphan227** [comment]
PR https://github.com/apache/james-project/pull/1791
