### ISSUE TITLE
[Postgres] Init project

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4906]
To initialize the implementation, let's first:
- create a dedicated feature branch 'postgresql' on James
- copy mailbox/jpa into mailbox/pg module
- copy jpa-app into pg-app module
- change the bindings in pg-app to bind to mailbox/pg and not mailbox/jpa

DOD: apache/james:pg-latest docker image + docker-compose

**Comment by chibenwa** [comment]
We would need some modules in the middle but this would be the idea to me, yes!

**Comment by vttranlina** [comment]
pr: https://github.com/apache/james-project/pull/1767
