### ISSUE TITLE
[Postgres] Performance tests imap for pg-app and jpa-app

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4909]
We need to see if we gain performance already after plugging PGMailboxMapper and PGSubscriptionMapper or not.

Locally, run perf tests on a jpa-app and on a pg-app, and compare the results.

**Comment by vttranlina** [comment]
- Do it on local
- Run james-gatling IMAPsimulation

**Comment by quantranhong1999** [comment]
PR for perf test materials: https://github.com/apache/james-project/pull/1794

**Comment by quantranhong1999** [comment]
## JPA app performance test
With 1000 users, 7 minutes injection and 15 minutes scenario.

![image](https://github.com/linagora/james-project/assets/55171818/8aa8c6f9-5213-4297-bbc2-00020016b80a)

**Comment by chibenwa** [comment]
(Did you correctly do a warm up for JPA run?)

**Comment by quantranhong1999** [comment]
> (Did you correctly do a warm up for JPA run?)

I did not warm up by simulation. But Is provisioning tons of messages enough? Anyway, I could redo it for sure.

**Comment by quantranhong1999** [comment]
> Anyway, I could redo it for sure.

It is true better.


![Image](https://github.com/linagora/james-project/assets/55171818/2af799aa-1d38-407a-a294-c26da6ab1e79)

**Comment by quantranhong1999** [comment]
Some more hardcore tests for JPA app (warmed up):

## 2000 users, 15m scenario, 7m injection
![image](https://github.com/linagora/james-project/assets/55171818/917eec23-a989-47f9-9802-4db70c0b9198)

Still usable IMO.

## 5000 users, 30m scenario, 20m injection
![image](https://github.com/linagora/james-project/assets/55171818/e6ed5f75-464f-4170-baad-d410daeb22b2)

Very bad performance, let's forget about JPA with 5000 users, at least on my local laptop :-)

**Comment by Arsnael** [comment]
You scenario with 2k users looks like a good candidate to me :)

**Comment by quantranhong1999** [comment]
## Postgres app performance

2000 users, 15m scenario, 7m injection.

![image](https://github.com/linagora/james-project/assets/55171818/72ff9e86-b38a-467b-a643-769c1252dcfb)

The LSUB performance (related to PostgresSubscriptionMapper) seems better with Postgres (p99 800ms compared to JPA p99 1500ms).

But TBH just refer this result and do not expect much at this early stage, my local PC performance is not stable all the time as well (tried to do nothing while performance testing...)

**Comment by chibenwa** [comment]
5.000 users?

**Comment by quantranhong1999** [comment]
> 5.000 users for PG?

If you want I would provision 5k users overnight (takes a long time) and let you the answer tomorrow.

TBH with just PostgresSubscriptionMapper, I do not think Postgres app would make much diff overall compared to JPA.

**Comment by chibenwa** [comment]
> TBH with just PostgresSubscriptionMapper, I do not think Postgres app would make much diff overall compared to JPA.

I know. That's why I wanted to have mailboxes too ^^

**Comment by quantranhong1999** [comment]
> I know. That's why I wanted to have mailboxes too ^^

We can test 5k users in the next performance test round https://github.com/linagora/james-project/issues/4936, and consider this done as the last day of the sprint. If you are ok with this ^^.
