### ISSUE TITLE
[Postgres] Guice binding + Read postgres configuration from file 

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4910]
Epic https://github.com/linagora/james-project/issues/4895

## Why 
1. 
We need to read the configuration from `postgres.properties` for init `Connection`
- URL
- DB username + Password
- Database name + Schema

... etc 

2. 
Implement `PGMailboxModule extends AbstractModule`, bind related dependency injections

## How
Reference `<artifactId>james-server-guice-mailbox-jpa</artifactId>`

## Dod
`postgres-app` starting success with new Guice binding
pass JamesServerContract

**Comment by Arsnael** [comment]
Thought that might have been part of the init... but I'm ok with that :0 a simpler init task would allow parallelism of work quicker

**Comment by quantranhong1999** [comment]
WIP: https://github.com/apache/james-project/pull/1780
