### ISSUE TITLE
[Postgres] Demo

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4911]
Start docker-compose with `postgres-latest` 
try IMAP server ...

**Comment by hungphan227** [comment]
https://linshare.linagora.com/sharedspace/workgroups/b77d3d86-0569-411a-9050-fccb485709e2/James-team/3ac757a3-333f-4bc3-8040-bfc2f63ffab7/Sprint%2034

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project/assets/6928740/02229ab0-02ea-4fd7-b316-2fc650b0a6b4
