### ISSUE TITLE
[RabbitMQ] Reconnecting to a channel when rabbitmq closes the connection with an exception

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4916]
Context: https://issues.apache.org/jira/browse/JAMES-3955

When RabbitMQ detects that a message has not been acknowledged properly by James after a certain time, it closes the channel with a `PRECONDITION_FAILED` channel exception.

We need to be able to catch it and try to reconnect to the channel when it's the case.

The mail queue, task manager work queue and event bus should be at least concerned.

DoD: tests simulating a `PRECONDITION_FAILED` channel exception from RabbitMQ and making sure we reconnect  to it successfully?

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project/assets/6928740/9fd6438c-2b94-4d82-b400-169df7dec50c

Recovery from simulated disconnection

**Comment by Arsnael** [comment]
Nice one! 

Just curious, how did you simulate the disconnection? It looks like code forced :)

**Comment by chibenwa** [comment]
A: manually sleep and disconnect cobsumers with java code
