### ISSUE TITLE
[RabbitMQ] Increase consumer timeout for TaskManagerWorkQueue

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4917]
Context: https://issues.apache.org/jira/browse/JAMES-3955

As sometimes we play heavy tasks on James, some other can get stuck for a while on the TaskManagerWorkQueue. By default, RabbitMQ closes the channel if James fails to acknowledge consuming items after 30 minutes. 

We could add a `x-consumer-timeout` queue argument when creating the TaskManagerWorkQueue. We should make it optional and configurable as this feature on a queue requires to use actually RabbitMQ 3.12 (so need to upgrade it in tests as well maybe)

DoD: tests + upgrade instructions that it needs rabbitmq 3.12 to be able to use it

**Comment by quantranhong1999** [comment]
Q:  Given that James resiliently consumes the queue again upon (disconnect) exception, do we really need to increase the timeout though?

**Comment by Arsnael** [comment]
Better safe than sorry I think. For queue like the task manager were we know some tasks can take hours to run having other tasks pilling up meanwhile, I think it's good to have the option of allowing a higher timeout in those cases

**Comment by chibenwa** [comment]
>  do we really need to increase the timeout though?

We need at the very least for distributed task manager work queue. As processing a task can be expected to take that long...

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1802
