### ISSUE TITLE
[PGSQL] PostgresDelegationStore

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4926]
Prerequisites: https://github.com/linagora/james-project/issues/4925

## WHY
Postgres implementation for DelegationStore.

## HOW
Add AUTHORIZED_USERS + DELEGATED_USERS (array data type) columns to the user table (just like Cassandra).

## DoD
pass contract test + guice binding

**Comment by hungphan227** [comment]
Should we use hstore to save AUTHORIZED_USERS and DELEGATED_USERS?

**Comment by chibenwa** [comment]
array should be enough?

**Comment by hungphan227** [comment]
Initially I thought of using hstore for better performance (hstore use hash table). However, because UsersDAO only add or remove one user from the list at a time, probably array should be enough :))

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/1851
