### ISSUE TITLE
RLS for Subscription mapper

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4930]
The mappers should have as an optional parameter the domain of the current user.

The mapper factory will be able to derive the domain from the MailboxSession of the current user.

We would need to add the domain into the table structure to enforce RLS

=> Have dedicated test class enforcing domain isolation with RLS turned on.
=> Set up rights for RLS

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/1793
