### ISSUE TITLE
[Postgres] Implement PostgresUidProvider and PostgresModSeqProvider

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4931]
## Epic 
https://github.com/linagora/james-project/issues/4912

## How
- PostgresUidProvider
`public class PostgresUidProvider implements UidProvider`

evaluated on column `PostgresMailboxTable#MAILBOX_LAST_UID`

- PostgresModSeqProvider
`public class PostgresModSeqProvider implements ModSeqProvider` 

evaluated on column `PostgresMailboxTable#MAILBOX_HIGHEST_MODSEQ`

## Dod 
- Pass all test-related
- Adapt to Mailbox Mapper...
- Guice binding (if needed)

**Comment by vttranlina** [comment]
## Alternative

If we don't want to evaluate uid on MAILBOX table (same JPA way) (1), we can create a new dedicated table for it (same Cassandra way) (2).

IMO:
+ With (2), we can decrease all total queries to MAILBOX table (one way to help decrease "db lock exception")

WDYT?

**Comment by chibenwa** [comment]
Please provide a strategy regarding concurrency...

If you need to `GET-INCREMENT-SET` then it needs to be wrapped into a transaction...

My good old friend chatGPT however suggest we could do better with the `RETURNING` keyword...

```
UPDATE ma_table
SET mon_entier = mon_entier + 1
WHERE condition
RETURNING mon_entier;
```

Of course concurrency tests needed!

**Comment by chibenwa** [comment]
Using the mailbox table and having a consldated view of the mailbox means fewer requests and thus better performance. I am strongly in favor of that idea...

**Comment by chibenwa** [comment]
Switched to `TODO` as it is required for plugging PG-mailbox-mapper

**Comment by vttranlina** [comment]
WIP https://github.com/apache/james-project/pull/1804
