### ISSUE TITLE
[Postgres] Guice bindings for PostgresMailboxMapper

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4932]
We need to do the Guice bindings for it and remove JPAMailboxMapper. However, there is an issue, raised by @vttranlina : https://github.com/apache/james-project/pull/1791#issuecomment-1809490693

The problem is that it's not a simple cast to change in the code, as `JPAId` is a Long, and `PostgresMailboxId` is a UUID. That would require refactoring on the JPA code but do we really want that?

Thus we need to migrate other structures to Postgres to be able to do those bindings:
- JPAAnnotationMapper
- JPAMessageMapper
- JPAModSeqProvider
- JPAUidProvider
Then we should be able to change all the JPAId to PostgresMailboxId and do proper bindings in james-server-guice-mailbox-postgres

**Comment by chibenwa** [comment]
We can generate a jpaidby taking a digest of the uuid

**Comment by Arsnael** [comment]
I'm alright with that

**Comment by chibenwa** [comment]
In JpaId:

```
public static JpaId of(MailboxId mailboxId) {
    if (mailboxId instanceof JpaId) {
        return (JpaId) mailboxId;
    }
    if  (mailboxId instanceof PgId) {
        return ((PgId) mailboxId).asJpaId();
    }
    throw new InvalidArgumentException(...);
}
```

**Comment by Arsnael** [comment]
https://github.com/apache/james-project/pull/1797

@chibenwa Not as simple as you think... I stopped

Would at least (I aint 100% sure) to refactor JPAUidProvider and JPAModSeqProvider further, as they do direct operations on the mailbox table. Would be better to wait for the https://github.com/linagora/james-project/issues/4931 to be done first (maybe other too, so we don't need to do some hacks with JPAId anymore) than wasting time on refactorings that would be dropped/refactored the next sprint.

Also it's an absolute pain in the tests too... Have some other weird issues I can't explain (mind it's the first time I put my nose in the postgresql code as well)

IMO it's not worth trying to rush this just for a perf test, better to accept to push this to next sprint :)

**Comment by chibenwa** [comment]
Fair.

Let's prioritize a rewrite of `JPAUidProvider` and `JPAModSeqProvider`.
Then with that plug the PG mapper ;-)

**Comment by chibenwa** [comment]
Appart from the Uid / Modseq stuff, we might need to relax some JPA message coonstraints that requires the mailbox to exist...

https://github.com/apache/james-project/blob/4215e592cd37a2ea88796dc742481e449ff585aa/mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/model/openjpa/AbstractJPAMailboxMessage.java#L160

Maybe needs to be replaced by a long...

Just like https://github.com/apache/james-project/blob/4215e592cd37a2ea88796dc742481e449ff585aa/mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/model/JPAMailboxAnnotation.java#L48

**Comment by Arsnael** [comment]
Ah could explain potentially some errors I noticed, thanks :)

**Comment by Arsnael** [comment]
Also: add mailbox mapper for imap mpt tests

**Comment by vttranlina** [comment]
When I tried to bind the Postgres Uid/ModSeq provider, I also binding PostgresMailboxMapper. 
But It depends on another that is not yet completed
WIP pr https://github.com/apache/james-project/pull/1808

**Comment by Arsnael** [comment]
Should bind everything together then maybe I think. The bindings could be done on the other ticket/PR

**Comment by hungphan227** [comment]
PR https://github.com/apache/james-project/pull/1818

**Comment by vttranlina** [comment]
If it requires `PostgresMessageMapper`, 
you can rebase on "no review" https://github.com/apache/james-project/pull/1812
