### ISSUE TITLE
[Postgres] Implement PostgresMessageMapper

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4934]
Epic https://github.com/linagora/james-project/issues/4895

After implementing https://github.com/linagora/james-project/issues/4899 and https://github.com/linagora/james-project/issues/4931, we can implement the mapper for messages with postgresql.

=> Implement MessageMapper interface for `PostgresMessageMapper`

DoD: Pass contract test MessageMapperTest with Postgres implementation

**Comment by vttranlina** [comment]
PR https://github.com/apache/james-project/pull/1812
