### ISSUE TITLE
Implement PostgresQuotaLimitDAO

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4937]
## Why
We need a mutualized storage for all types of quotas, just like what we did with Cassandra.

In `backends-common/postgres`: Implement `PostgresQuotaLimitDAO` (APIs/queries refer to `CassandraQuotaLimitDao`)

`quota_limit` table structure:

      - scope TEXT not null
      - identifier TEXT not null
      - component TEXT not null
      - type TEXT not null
      - limit BIGINT null (QuotaLimit POJO has an Optional quotaLimit value)
      Primary key: scope + identifier + component + type

## DoD
Unit tests for common queries.

**Comment by chibenwa** [comment]
You likely do not need a primary key with Postgres - at least not according to chatGPT.

But we likely want an index on the access pattern.

**Comment by quantranhong1999** [comment]
> You likely do not need a primary key with Postgres - at least not according to chatGPT.

It is true. I verified with Google.

> But we likely want an index on the access pattern.

FYI: "PostgreSQL automatically creates a unique index when a unique constraint or primary key is defined for a table".

We want:
- scope + identifier + component + type to be unique
- scope + identifier + component + type is also the access pattern (at least following Cassandra impl)

Then set the primary key would both enforce uniqueness and index for fast access :-)

**Comment by chibenwa** [comment]
Ok thanks for sharing :-)

**Comment by hungphan227** [comment]
PR https://github.com/apache/james-project/pull/1814
