### ISSUE TITLE
[Postgres] PostgresMailboxAnnotationDAO + PostgresAnnotationMapper

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4940]
Table structure:

```
mailboxId uuid  
key             text
value          text

PK (mailboxId, key)
```

DoD: Pass AnnotationMapperTest 

EDIT: use hstore for key => value

**Comment by chibenwa** [comment]
### Topic 1

`key             varchar(200) ` 

I am not sure the `MailboxAnnotationKey` is limited in size, so we maybe rather just use `text` data type.

### Topic 2

Also my friend chatGPT says that "When you use a composite primary key and do a select on one of its single componants, there is a performance penalty in the absence of an index".

I see two way around this limitation:

 - Option 1: Use hstore: pk mailboxId + C `Map<MailboxAnnotationKey, Value` with hstore.
 - Option 2: Add an index on the mailboxId.

**Comment by quantranhong1999** [comment]
> key varchar(200)

I found a best practice regarding this: "Always use the `text` data type when storing strings in PostgreSQL. There is no performance benefit of using `char(n)` or `varchar(n)`."

So for short, unless we want a constraint on the characters number, otherwise, using the `text` data type would be more flexible (maybe one day we have a special data exceeded the limit).

rf: https://maximorlov.com/char-varchar-text-postgresql/#:~:text=Always%20use%20the%20text%20data,flexible%20and%20easier%20to%20change

**Comment by chibenwa** [comment]
You are right!

But still it brings safety when we define maximum variable lengths on james side to enforce it on DB side... The usages of varchar we have to far are rather meaningful.

**Comment by Arsnael** [comment]
I think I saw it limited to 200 in JPA (dunno why), it's true in cassandra though we just have a text field. So more than ok :)

Cassandra as well: PK mailboxId, key is clustering column. Both options could work yes. Option 1 maybe if we dont wanna bother with too many indexes on postgres

**Comment by chibenwa** [comment]
TBH for mailbox annotations we do not really care. Option one if the count of annotation per mailbox is low
OR if we do not access much annotations by mailboxId + key

**Comment by Arsnael** [comment]
Hardly have the time to work on it, I put it back to todo... There is a draft that I barely started here: https://github.com/apache/james-project/pull/1817 if somebody wants to take over

**Comment by hungphan227** [comment]
created another PR based on Rene's PR: https://github.com/apache/james-project/pull/1822
