### ISSUE TITLE
JAMES 3897: Block IP connection to IMAP server

### ISSUE THREAD

**Issue by thanhbv200585** [linagora/james-project#4942]
When client connects to IMAP server, james will check its IP and question to Crowdsec whether the IP is secure or not. If it is unsecure, the connection will be closed

**Comment by quantranhong1999** [comment]
IMO question to Crowdsec upon IMAP authentication phase is OK too and maybe is easier to do (at least with the current extension code style). Extending Netty network layer atm is impossible.

We can use [the custom IMAP package mechanism](https://github.com/apache/james-project/blob/master/examples/custom-imap/README.md) to extend the CrowdSec behavior by overriding the authentication commands like `AuthenticateProcessor`, `LoginProcessor` (to check CrowdSec first before authentication).

A customer example where we did extend the `AuthenticateProcessor` behavior for them: https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/customers/james-gcs-sara

Not sure this is the best way though. Any other ideas/feedback would help :-)

**Comment by chibenwa** [comment]
Or add a `ConnectionCheck` that takes info available at the time of connection. (defined in `/protocols/imap api package`).

```
interface ConnectionCheck {
    Publisher<Void> validate(InetSocketAddress remoteAddress);
}
```

We can aggregate several ConnectionCheck into a `ConnectionChecks` class by injecting a Set with a multi-binder...

We would then need to call it within `ImapChannelUpstreamHandler` `channelActive` method if proxy-protocol is off, or within `HAProxyMessageHandler` if proxy protocol is on.

> We can use [the custom IMAP package mechanism](https://github.com/apache/james-project/blob/master/examples/custom-imap/README.md)

:+1: for this we just need to add a list of `ConnectionCheck` in there too...

However please avoid overloading whole commands like we did for GCS for the sole purpose of connecting to Crowdsec. We can do cleaner...

**Comment by thanhbv200585** [comment]
PR: https://github.com/apache/james-project/pull/1824

**Comment by thanhbv200585** [comment]
- [ ] Introduce ConnectionCheck interface and noop guice binding for it
- [ ] Implement additionalConnectionChecks extension for IMAP (configuration + guice loading + binding + example and documentation)
- [ ] Implement CrowdSecConnectionCheck and binding to James using the additionalConnectionChecks extension.

**Comment by thanhbv200585** [comment]
Scenario:
```
Start James memory + crowdsec
 (connect, bad login x3)
 Ensure connection is rejected
```

```
Start James memory + crowdsec + proxy protocol
 (connect, proxy message, bad login x3)
 Ensure (connect + proxy message) is rejected
 + add another test that other people connecting through the proxy should be rejected.
```

**Comment by Arsnael** [comment]
Left to do: fixing a spring wiring issue
