### ISSUE TITLE
[POSTGRES] Postgres Connection concurrency issue

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#4950]
https://ci-builds.apache.org/blue/organizations/jenkins/james%2FApacheJames/detail/PR-1803/7/tests

The test (ConnectionThreadSafetyTest) that check the concurrency issue of postgres connection FAILED

**Comment by chibenwa** [comment]
`@RepeatedTest` to reliably reproduce this...

`java.util.concurrent.ExecutionException: java.lang.RuntimeException: io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42P05] prepared statement "S_0" already exists`

As said in the PR, prepared statement on the fly are subject to dataraces. When faced with this error we likely can safely retry...

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1840
