### ISSUE TITLE
DKIM Private Key store as file path

### ISSUE THREAD

**Issue by ducnm0711** [linagora/james-project#4951]
Load the private key as Env is very error-prone and create unecessary ops overhead work. This is already done for imap and smtp config. 
Should do the same for DKIM.
```xml
                <tls socketTLS="false" startTLS="true">
                    <privateKey>file://conf/private.key</privateKey>
                    <certificates>file://conf/fullchain.pem</certificates>
                </tls>   
```

Current configuration:
```xml
 <privateKey>${env:DKIM_PRIVATE_KEY}</privateKey>
```

Wanted behavior:
```xml
<privateKey>file://conf/dkim.private.key</privateKey>
```

**Comment by ducnm0711** [comment]
Or please confirm if this is already implemented.

**Comment by chibenwa** [comment]
Already implemented.

`<privateKeyFilepath>file://conf/dkim.private.key</privateKeyFilepath>
