### ISSUE TITLE
[Postgres] Fix flaky test

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4952]
I saw this breaking builds a few times now:

https://ci-builds.apache.org/job/james/job/ApacheJames/job/PR-1815/6/testReport/junit/org.apache.james.backends.postgres/ConnectionThreadSafetyTest/connectionShouldWorkWellWhenItIsUsedByMultipleThreadsAndAllQueriesAreSelect/

We have potentially some concurrency issue? It needs to be investigated and fixed.

**Comment by quantranhong1999** [comment]
as Benoit commented, we likely can retry upon prepared statement conflict there (and adapt test for it)

**Comment by Arsnael** [comment]
https://github.com/linagora/james-project/issues/4950 duplicate
