### ISSUE TITLE
[PGSQL] MessageMapper::add - single request to generate UID and MODSEQ

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4953]
https://github.com/apache/james-project/pull/1812/files/210221dc5627899640489bf759b985b63c87fe74..b25de17726a22392133852d03fd26a147bfd9ffd#r1405767900

Allows reducing the write load on metadata. BTrees will appreciate...

**Comment by vttranlina** [comment]
I added the new method `public Mono<Pair<MessageUid, ModSeq>> incrementAndGetLastUidAndModSeq(MailboxId mailboxId)` 
in `PostgresMailboxDAO` 
Then using it in Mapper
 https://github.com/apache/james-project/pull/1812

**Comment by chibenwa** [comment]
COOL ^^
