### ISSUE TITLE
[PGSQL] Port the DeleteMessageListener from the Cassandra implementation into the PGSQL one...

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4954]
https://github.com/apache/james-project/pull/1812/files/210221dc5627899640489bf759b985b63c87fe74..b25de17726a22392133852d03fd26a147bfd9ffd#r1405881696

Deletes only work on message's-mailbox-metadata and to not delete underlying message table. GREAT. That's a good thing.

But upon delete we need a MailboxListener looking if a given messageid is referenced or not and actually deletes its `message` content, and related blobs.

**Comment by hungphan227** [comment]
draft pr https://github.com/apache/james-project/pull/1869
