### ISSUE TITLE
[PGSQL] Implement the same SearchOverride than for Cassandra

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4955]
# Why

 -> Use postgres if we can, instead of OpenSearch... Coherence, speed, etc...
 
 Resyncs for IMAP should solely hit "Postgres SQL"

**Comment by chibenwa** [comment]
-> AllSearchOverride
 -> DeletedSearchOverride
 -> DeletedWithRangeSearchOverride
 -> NotDeletedWithRangeSearchOverride
 -> UidSearchOverride
 -> UnseenSearchOverride

**Comment by quantranhong1999** [comment]
Just a remark. In Cassandra, we use denormalization tables but this is not the case with Postgres as we would query directly on the "source of truth" tables. We should create appropriate indexes on the search override queries with Postgres.

**Comment by chibenwa** [comment]
Yes exactly.

**Comment by chibenwa** [comment]
We could also think to "more search overrides" if relevant...

**Comment by Arsnael** [comment]
https://github.com/apache/james-project/pull/1874

**Comment by vttranlina** [comment]
fixup related: https://github.com/apache/james-project/pull/1880
