### ISSUE TITLE
[PGSQL] ADR on mailbox table sturctures

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4957]
Describe the tables, relations between them, and how those relations are enforced.

Tables:
 - mailbox
 - message
 - mailbox_message
 - subscription
 
 Let's edict a rule that for new tables into the PGSQL 
 
 Note that we should join `message` table with `mailbox_message`. We will try to push the join to postgres first but an alternative is to do the join on the app side (read message then read mailbox_message). Later performance benchmarks will confirm our choice.

**Comment by hungphan227** [comment]
PR https://github.com/apache/james-project/pull/1857
