### ISSUE TITLE
[PGSQL] Concurrency control for flags updates

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4958]
https://github.com/apache/james-project/pull/1812/files/210221dc5627899640489bf759b985b63c87fe74..b25de17726a22392133852d03fd26a147bfd9ffd#r1405908909

```
We also need to add a `WHERE` clause on the modseq with the old value of the modseq. 
This is used to ensure optimistic concurrency control on flag updates.
We should then use RETURNING to see if the update was applied.
And if not, the caller should retry.

Implementing this IS tricky as we need to retry updates only for those who did not succeed...

OR we just wrap the flag updates onto a transaction, AND use a dedicated connection pool for that.

I am more in favor of the optimistic concurrency option but let's write an ADR on the topic.

(Comment edited): This topic is very hard. I propose to NOT care about concurrency control for now.  We know that we are able to do it (eventually) with concurrency control. So let's do it later.
```

**Comment by chibenwa** [comment]
Or likely overkill after thinking twice...
We can get along with CRDT:

---------------------------------------------------------------------------------------------------------------------

Please we need flag updates to commute.
Which mean we need a ADD/REMOVE semantic, and not a SET semantic when updating user-flags.

Let's SAY IF we only add elements:

```
user_flag = user_flag || ARRAY['nouvel_element1', 'nouvel_element2']
```

Let's SAY IF we only remove elements:

```
user_flag = array_remove(user_flag, ARRAY['nouvel_element1', 'nouvel_element2'])
```

If we both add and remove elements it is OK to do 2 requests...

**Comment by quantranhong1999** [comment]
> If we both add and remove elements it is OK to do 2 requests...

credit to ChatGPT for putting it as 1 query. e.g. we want to add flag `stringA` and remove flag `stringB`:
```sql
UPDATE your_table
SET user_flag = array_remove(array_append(user_flag, 'stringA'), 'stringB')
WHERE your_condition;
```

**Comment by chibenwa** [comment]
Really that works???? O_O

Your prompt is more clever than mine!

**Comment by vttranlina** [comment]
> ```sql
> array_remove
> ```

As my comment at https://github.com/apache/james-project/pull/1812#discussion_r1407580995
The array_remove doesn't support Array input.  
// If we still want to use native sql to do this idea, maybe we need to declare the new custom function (not sure it is possible)

**Comment by quantranhong1999** [comment]
> The array_remove doesn't support Array input.

How about using nested `array_remove` to remove multiple elements?

```sql
UPDATE your_table
SET user_flag = array_remove(array_remove(array_append(user_flag, 'stringA', 'stringC', 'stringD'), 'stringB'), 'stringE')
WHERE your_condition;
```

![image](https://github.com/linagora/james-project/assets/55171818/cc6ea3bc-9218-4e2e-baea-0b6f24922ab8)

jOOQ example code:
```java
dsl.update(table("your_table"))
    .set(field("user_flag"), 
        arrayRemove(arrayRemove(arrayAppend(field("user_flag"), "stringA", "stringC", "stringD"), "stringB"), "stringE"))
    .where(your_condition)
    .execute();
```

**Comment by quantranhong1999** [comment]
BTW given that Postgres already handles concurrent UPDATE on the same key (using row lock by default), do we really need to care about concurrency at the application layer?

![image](https://github.com/linagora/james-project/assets/55171818/f27bc106-c281-4818-88b6-65919b8fb835)

In Cassandra's case, it is distributed and not ACID assurance, so we needed to care about concurrent access at the application layer. Maybe this is not the case with Postgres, WDYT?

**Comment by Arsnael** [comment]
> In Cassandra's case, it is distributed and not ACID assurance, so we needed to care about concurrent access at the application layer. Maybe this is not the case with Postgres, WDYT?

I guess as long as we have a concurrency test suite for flag updates and if it does not break with Postgresql, cause robust enough with what you said, then I guess we could consider ourselves good enough? 

Can always refactor later if problems arise

**Comment by chibenwa** [comment]
```
BTW given that Postgres already handles concurrent UPDATE on the same key (using row lock by default), do we really need to care about concurrency at the application layer?
```

Yes if we read then update.

No if we only update then use RETURNING...

**Comment by quantranhong1999** [comment]
> Yes if we read then update.

Maybe putting SELECT as a sub-query into an UPDATE query could do the trick?
e.g. (do not care too much about what SELECT below is doing, just getting the user_flag and do some manipulation on that)
```
UPDATE your_table
SET user_flag = (
  SELECT array_agg(elem)
  FROM unnest(user_flag) AS elem
  WHERE elem NOT IN ('stringA', 'stringB', 'stringC')
)
WHERE your_condition;
```

**Comment by chibenwa** [comment]
Let's do complicated things only if necessary - if concurrency related tests fails.
If they pass, then let's not over engineer.

IE `MessageMapperTest::userFlagsUpdateShouldWorkInConcurrentEnvironment`
`MessageMapperTest::setFlagsShouldWorkWithConcurrencyWithRemove`

**Comment by chibenwa** [comment]
Capabilities.THREAD_SAFE_FLAGS_UPDATE was missing, the test wasn't run.

(I KNEW it! Did not take those distributed system classes tests for nothing... )

![image](https://github.com/linagora/james-project/assets/6928740/b7ccbdd1-9e6c-4f89-8d4a-0b83529812c9)

**Comment by vttranlina** [comment]
How about a query to remove array + append array in a single query:

```sql
update message_mailbox
set user_flags=(select array_agg(elements)
                from (select unnest(array_cat(user_flags, array ['append1', 'append2']))
                      from message_mailbox
                      where message_uid = 1
                      except
                      select unnest(array ['remove1', 'remove2'])) t (elements))
where message_uid = 1;
```
It looks quite verbose, but I will try

**Comment by vttranlina** [comment]
WIP https://github.com/apache/james-project/pull/1858
