### ISSUE TITLE
[PGSQL] [STORY] Plug OpenSearch

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4959]
- Module chooser: scanning, Opensearch, opensearch_disabled & Add it in `docker-compose-distributed.yml` https://github.com/linagora/james-project/issues/4987
 - Implement and bind search overrides CF https://github.com/linagora/james-project/issues/4955

 
 - https://github.com/linagora/james-project/issues/4988

**Comment by Arsnael** [comment]
Perf tests for the searchOverrides make sense yes :)
