### ISSUE TITLE
[PGSQL][Story] Plug S3

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4960]
- Implement a PGSQL blobstore based on `bytea` (automatic offloading to files is supported <3 )
 - Module chooser: S3, postgres
 - Add it in a docker-compose-distributed.yml

**Comment by vttranlina** [comment]
Draft integrate S3 as blobStore: https://github.com/apache/james-project/commit/9f0356be466d57158ac5a7a2fd606bbc0ab9ea6e

**Comment by chibenwa** [comment]
Thanks for putting this together.
I have lots of things to say.
I commented directly into the PR.

**Comment by vttranlina** [comment]
Split tasks:

1. https://github.com/linagora/james-project/issues/4983 [PGSQL] Implement Postgres BlobStore DAO
2. https://github.com/linagora/james-project/issues/4984 [PGSQL] Module chooser: S3, postgres blobStore
