### ISSUE TITLE
[PGSQL][Story] Bind the rabbit Event Bus

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4961]
- Implement EventDeadLetter with postgres and bind it!
 - Module chooser: either memory or rabbitmq
 - Put it into `docker-compose-distributed.yml`

**Comment by chibenwa** [comment]
Eventually yes,
But not in next Sprint.

**Comment by quantranhong1999** [comment]
Ticket split:
- https://github.com/linagora/james-project/issues/4985
- https://github.com/linagora/james-project/issues/4986

BTW @chibenwa do you want `EventSourcingTaskManager` backed by Postgres and MailQueue using RabbitMQ in the next sprint too, or later?

**Comment by chibenwa** [comment]
> BTW @chibenwa do you want EventSourcingTaskManager backed by Postgres and MailQueue using RabbitMQ in the next sprint too, or later?

Later. Let's stick to memory for now.
