### ISSUE TITLE
Implement PostgresMessageManager + PostgresMailboxManager

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4965]
## How
In `apache-james-mailbox-postgres` module, implement then replace `OpenJPAMessageManager` -> `PostgresMessageManager`.

Also, Implement `PostgresMailboxManager` and replace + remove `OpenJPAMailboxManager`.
Guice binding

Guice binding.

## DoD
No real contract test for `MessageManager` (can try `AbstractMessageManagerTest` though)
For `PostgresMailboxManager`, we need to pass the contract test `MailboxManagerTest`.
Pass current postgres-app IT.

**Comment by vttranlina** [comment]
`AbstractMessageManagerTest` requires `MailboxManager`
And `MailboxManagerTest` requires `MessageManager`

We have a circle lock here, not sure we can do it separately, maybe we should do `PostgresMessageManager` and `PostgresMailboxManager` in the same ticket?

**Comment by quantranhong1999** [comment]
> We have a circle lock here, not sure we can do it separately, maybe we should do PostgresMessageManager and PostgresMailboxManager in the same ticket?

Would be more convenient indeed. Thank you for having a look. I fixed the ticket.

**Comment by chibenwa** [comment]
>  maybe we should do PostgresMessageManager and PostgresMailboxManager in the same ticket?

Yes.

But those classes are SUPER simple/ CF CassandraMessageManager / CassandraMailboxManager.

We should not be doing something harder than that. 

Just get the capabilities right, and reflecting what is implemented...
