### ISSUE TITLE
Implement PostgresPerUserMaxQuotaManager

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4966]
## How 
Can base on `CassandraPerUserMaxQuotaManagerV2`, using the common Postgres quota storage API.
Guice binding
Remove `JPAPerUserMaxQuotaManager` and related code.

## DoD
Pass contract test `GenericMaxQuotaManagerTest`.

**Comment by hungphan227** [comment]
PR https://github.com/apache/james-project/pull/1839
