### ISSUE TITLE
[PGSQL] Implement correctly FetchType

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4968]
## WHY

Reading just enough data is CRITICAL for performance.
Current implementation rushed to get a working PgMessageMapper and always read all data.
This work but read waaaay to much data.

## What

Do not request the properties and the headers when doing a fetch at the level "metadata" in the SELECT done to postgres.

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/1834
