### ISSUE TITLE
[PGSQL] Experiment a materialized view for Applicable flags

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4969]
## Current

```
dslContext.selectDistinct(UNNEST_FIELD.apply(USER_FLAGS))
                .from(TABLE_NAME)
                .where(MAILBOX_ID.eq(mailboxId.asUuid())))
```

Potentially heavy queries upon SELECT.

Maybe we could be better served with a materialized view?

# DOD

Test still pass.
Measured a performance improvement for ihe IMAP SELECT command.

**Comment by chibenwa** [comment]
Materialized views are manually synced, (or via a trigger that essentially negates the benefits of it)

The topic remain: applicable flags would deserve to be enhanced, but not through that mean.

(Source: PG community met at OSXP)

**Comment by Arsnael** [comment]
> The topic remain: applicable flags would deserve to be enhanced, but not through that mean.

To be groomed then!

**Comment by vttranlina** [comment]
Not related to `materialized view`
I see in [Cassandra Application flags DAO](https://github.com/apache/james-project/blob/6f33b2c3369a81f73797f09372d836061d9bcbd5/mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraApplicableFlagDAO.java#L92)
We only append new flags, (no replace, no remove one). 
In Postgresql now, We don't have a dedicated table for that, we fetch union distinct flags from all message flags.  
So, we will get a case that after removing flags of messages. That application flag still keep in Cassandra, but Not in Postgresql

WDYT?

**Comment by chibenwa** [comment]
This behaviour divergence is minor and already accounted for. CF `MapperProvider.Capabilities.INCREMENTAL_APPLICABLE_FLAGS`
