### ISSUE TITLE
[Bug?] DKIM private key as file path

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4970]
Our ops team is trying to load the DKIM private key via `privateKeyFilepath` argument, but it seems James does not load it. The NPE seems to suggest it fails finding the key.

Find that strange as we have tests covering this piece of the code, but it's maybe trickier.

Investigate, try to reproduce maybe locally, and if there is an issue, fix it.

**Comment by chibenwa** [comment]
Use of classpath resources is hard coded in DKIMSign.

We need to rely on `FileSystem` implementation here.

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/1830
