### ISSUE TITLE
[PGSQL]  Investigate why failed on Mailbox Annotation test

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4971]
When binding Postgres Mailbox Anotation in mpt-imap test
The test failed, 
Investigate why and fix it.

The pr mpt-imap test https://github.com/apache/james-project/pull/1828

Test class: `mpt/impl/imap-mailbox/postgres/src/test/java/org/apache/james/mpt/imapmailbox/postgres/PostgresMailboxAnnotationTest.java` 

Error message:

```
org.apache.james.mpt.protocol.ProtocolSession$InvalidServerResponseException: 
Location: /org/apache/james/imap/scripts/Metadata.test:86
LastClientMsg: g4 GETMETADATA "INBOX"
Expected: '\* METADATA "INBOX" \(\/private\/comment "My own comment" \/shared\/comment "The shared comment"\)'
Actual   : '* METADATA "INBOX" (/shared/comment "The shared comment" /private/comment "My own comment")'

```

**Comment by hungphan227** [comment]
> When binding Postgres Mailbox Anotation in mpt-imap test The test failed, Investigate why and fix it.
> 
> The pr mpt-imap test [apache#1828](https://github.com/apache/james-project/pull/1828)
> 
> Test class: `mpt/impl/imap-mailbox/postgres/src/test/java/org/apache/james/mpt/imapmailbox/postgres/PostgresMailboxAnnotationTest.java`
> 
> Error message:
> 
> ```
> org.apache.james.mpt.protocol.ProtocolSession$InvalidServerResponseException: 
> Location: /org/apache/james/imap/scripts/Metadata.test:86
> LastClientMsg: g4 GETMETADATA "INBOX"
> Expected: '\* METADATA "INBOX" \(\/private\/comment "My own comment" \/shared\/comment "The shared comment"\)'
> Actual   : '* METADATA "INBOX" (/shared/comment "The shared comment" /private/comment "My own comment")'
> ```

@Arsnael @chibenwa is there any syntax like OR in the test script? The annotation list returned by postgres version does not have the same order as the expected result.

**Comment by chibenwa** [comment]
We can use

```
SUB {
S: line 1
S: line 2
}
```

Which would match:

```
S: line 1
S: line 2
```

OR

```
S: line 2
S: line 1
```

**Comment by hungphan227** [comment]
Found solution: 
S: \* METADATA "INBOX" \((\/private\/comment "My own comment" \/shared\/comment "The shared comment"|\/shared\/comment "The shared comment" \/private\/comment "My own comment")\)

**Comment by chibenwa** [comment]
I'm not sure I agree with your solution ^^

**Comment by hungphan227** [comment]
PR https://github.com/apache/james-project/pull/1836
