### ISSUE TITLE
[PGSQL] Missing RLS tests for some DAOs

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4972]
We seem to miss RLS tests for some DAOs in the PGSQL implementation.

We need to add them

DoD: add all missing RLS tests for DAOs concerned by RLS and have them green

**Comment by hungphan227** [comment]
Below are the list of tables that miss RLS tests:
domain list, recipient rewrite table, users, mailbox annotation, message, mailbox message, quota

@Arsnael @chibenwa is there any table above that do not need RLS?

**Comment by quantranhong1999** [comment]
IMo we just need to add RLS tests for current RLS tables. Not add RLS to tables.

**Comment by chibenwa** [comment]
RLS tests needed `mailbox annotation, message, mailbox message` ie for the mailbox

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/1862
