### ISSUE TITLE
Subject sort: investigate

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4976]
https://github.com/linagora/tmail-flutter/issues/2392

Remove emojis and keep only text before indexing?

Look for other issues. Basically raw text on which the sorting is done is not sanitized by an analyser thus extra cleanup needs to be done.

**Comment by Arsnael** [comment]
Needs more grooming maybe?

**Comment by chibenwa** [comment]
Well yes and no. Yes there is still a lot of uncertainity on this topic.

And no, we can already do a bit of sanitizing from what's written above.

**Comment by chibenwa** [comment]
Maybe we could let this as a PO homework?

For sure an OpenSearch topic would relax me (a lot).

**Comment by Arsnael** [comment]
Well I'm always happy to have the PO dealing tickets helping with support of the frontend team.

I have other ways of relaxing though :D

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project/pull/5035

IMO let's keep it simple: base subject was not normalized, which is a serious issue for sorting...
