### ISSUE TITLE
Crowdsec Integration for JMAP

### ISSUE THREAD

**Issue by thanhbv200585** [linagora/james-project#4977]
When client connects to JMAP server, james will check its IP and question to Crowdsec whether the IP is secure or not. If it is unsecure, the connection will be closed

**Comment by quantranhong1999** [comment]
A suggestion, we can do connection check within `JMAPServer`:
```scala
    public void start() {
        if (configuration.isEnabled()) {
            server = Optional.of(HttpServer.create()
                .port(configuration.getPort()
                    .map(Port::getValue)
                    .orElse(RANDOM_PORT))
                .handle((request, response) -> checkConnections(resquest, response)
                    .handleVersionRoute(request)
                    .handleRequest(request, response))
                .wiretap(wireTapEnabled())
                .bindNow());
        }
    }

  Mono<Void> checkConnections(HttpServerRequest request, HttpServerResponse response) {
       //Extract remote IP from HttpServerRequest and do connection checking. If connection is banned then terminate the request process and response an an appropriate HTTP code.
  }
```

**Comment by chibenwa** [comment]
On HTTP connection we can either...

 - Invest on an Apisix module 
 - Use the LemonLDAP extension for that (already exists).
 
 No need to write James specific code.
 
 Cc @guimard

**Comment by chibenwa** [comment]
No we can still document it ;-)

**Comment by quantranhong1999** [comment]
> Invest on an Apisix module

https://github.com/linagora/james-project/issues/4874#issuecomment-1729448717

**Comment by guimard** [comment]
> On HTTP connection we can either...
> 
>     * Invest on an Apisix module
>     * Use the LemonLDAP extension for that (already exists).
> 
> No need to write James specific code.

Hi,

the Lemonldap-NG module is a bouncer that detects bad IP and apply policy inside LLNG (reject, requires 2FA, warn,...)
