### ISSUE TITLE
[Postgresql] Fix branch

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4978]
Somebody did try to do a force push in an attempt to rebase postgresql branch with master.

Now code has been lost on it (last commit 1 month old) and last commit from master branch is 2 months old... How has that been done is a mystery. 

Screenshots:

![Image](https://github.com/linagora/james-project/assets/9005025/6e2d696b-2cac-4033-8a94-5ba30402533d)

![Image](https://github.com/linagora/james-project/assets/9005025/e5599717-7f55-4e6a-9391-5a49d0568aa9)

Gonna need to be careful as a bunch of PR's have been merged lately together... 

I will first create a backup branch rebuilding what we had. Then we will try to fix the postgresql branch from there wth a rebase on latest master. 

The backup branch will be kept afterwards to avoid this kind of issue again. Before a force push rebase master on postgresql, should backup the branch.

**Comment by Arsnael** [comment]
Actually Hung's PR, that was lastly merged for postgresql branch before the force push, was rebased on latest work (thanks Hung, avoids heaches^^)

Source of truth =>  https://github.com/apache/james-project/pull/1844

Backup branch with the wrk in latest state before rebase on master: https://github.com/apache/james-project/tree/postgresql-backup

**Comment by quantranhong1999** [comment]
Thank you @Arsnael and @hungphan227 :D

**Comment by Arsnael** [comment]
https://github.com/apache/james-project/tree/postgresql => fixed (please help double check)

I reused extra commit from @vttranlina to fix the build after rebase: https://github.com/apache/james-project/commit/ddad6b5951dbe9f2b3aeb550c69b38bb27faa60b

**Comment by chibenwa** [comment]
What I did:

```
git fetch apache master
git fetch apache postgresql
git checkout postgresql
git reset --hard apache/postgresql
git rebase apache/master
(FIX a problem with QuotaKey)
git push apache postgresql
```

**Comment by chibenwa** [comment]
Github commit order was messed up for sure but a git log locally was fine

```
hp@hp-HP-ProBook-440-G5:~/Documents/james-project$ git log --oneline 
9c7e66b724 (HEAD) Fix compilation
0c8995c18a JAMES-2586 PostgresRecipientRewriteTableDAO and PostgresRecipientRewriteTable (#1844)
0016dd4b4a JAMES-2586 PostgresTableManager - Cleanup
c13e1c109a JAMES-2586 PostgresTableManager - Check the existence of RLS column/policy before alter the table
d308e15c14 JAMES-2586 PostgresExecutor: better recognize prepared statement conflict
047308cf3c JAMES-2586 Add a unit test for recreate RLS column should not fail
877714caf2 JAMES-2586 Rename JPAAttachmentContentLoader to PostgresAttachmentContentLoader
28b6b7e419 JAMES-2586 Postgres app – Remove server test for authentication database sql validation
4dbc612105 JAMES-2586 Fixup - Postgres app - Use junit 5 (replace to junit 4)
```

**Comment by Arsnael** [comment]
I don't know what got messed up in the end then, cause what you did is more or less what I did. 

Anyways it got fixed :)
