### ISSUE TITLE
[PGSQL] Implement Postgres BlobStore DAO

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4983]
Epic: https://github.com/linagora/james-project/issues/4960

## How 
- Create a new module `blob-postgres` in `server/blob/`

- Create a table `blob_storage`
```sql
CREATE TABLE blob_storage (
    bucket_name VARCHAR(200) NOT NULL,
    blob_id VARCHAR(200) NOT NULL,
    data BYTEA NOT NULL,
    size INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_unique_object
ON blob_storage (bucket_name, blob_id);
```

- Create an implement `public class PostgresBlobStoreDAO implements BlobStoreDAO` and implement 

## Dod 
- Create an implemented test, and pass contracts: `BlobStoreDAOContract`, `BucketBlobStoreDAOContract`, `DeleteBlobStoreDAOContract`,  `ReadSaveBlobStoreDAOContract`

**Comment by vttranlina** [comment]
I think we can save all data in a single column `data` is a good choice for Postgres blobStorage. 
Splitting it into smaller chunks (like Cassandra) is not simple. 
As Postgres specific, the maximum of `bytea` is 2GB,

**Comment by Arsnael** [comment]
Primary key? No primary key? Feel it's ok like that, just wanna be sure

**Comment by hungphan227** [comment]
draft pr https://github.com/apache/james-project/pull/1882
