### ISSUE TITLE
[PGSQL] Module chooser: S3, file blobStore

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4984]
Epic https://github.com/linagora/james-project/issues/4960

Right now `pg-app` using MemoryBlobStore. 

## How

- Create a `BlobStoreConfiguration` in `postgres-common` for read configuration from `blob.properties`
It looks like exists [distributed BlobStoreConfiguration](https://github.com/apache/james-project/blob/c704a8f7464c151a9fe207654902336f70f97af6/server/container/guice/distributed/src/main/java/org/apache/james/modules/blobstore/BlobStoreConfiguration.java#L44) 
It will supports: `s3`, `file blob`

- Create a `BlobStoreModulesChooser` in `postgres-common` for guice binding Module of blobStore
It looks like exists [distributed BlobStoreModulesChooser](https://github.com/apache/james-project/blob/bc6549a740f73e75d29bbc926e85bb6da3ccb149/server/container/guice/distributed/src/main/java/org/apache/james/modules/blobstore/BlobStoreModulesChooser.java#L55)

## Dod

- Choice `file` blobStore in [docker-compose](https://github.com/apache/james-project/blob/6c47b076adf5777d6cadb766f5f48037d2d4ef87/server/apps/postgres-app/docker-compose.yml)
- Choice `s3` blobStore in new docker-compose-distributed
- Update document related

**Comment by Arsnael** [comment]
Two remarks:
- File blob store missing?
- is it necessary to do postgres blob store before doing this? Wouldn't it be better to do module chooser first between file storage and s3, then adding the postgres option after we do it? It would allow us to plug quickly the pg-app to a s3 blob store for example :)

**Comment by vttranlina** [comment]
> is it necessary to do postgres blob store before doing this

No, But then we need one more task: Guice Binding PostgresBlobStore and adapt to Module Chooser

**Comment by chibenwa** [comment]
Fully agree with @Arsnael

**Comment by vttranlina** [comment]
Task for guice binding postgres blobstore module: https://github.com/linagora/james-project/issues/4989

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1870
