### ISSUE TITLE
Plug RabbitMQ EventBus into Postgres-app

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4986]
## Why
  Currently, postgres-app uses in memory event bus cf `DefaultEventModule`. It is not scalable, we need to be able to use RabbitMQ which is more robust.

  ## How
  - Implement an Eventbus module chooser in postgres-app: if `rabbitmq.properties` is available then try to use RabbitMQ event bus (`RabbitMQEventBusModule`), otherwise fallback to the InMemory event bus.
  - Add RabbitMQ in `docker-compose-distributed.yml`,

  ## DoD
  Write an Integration test in postgres-app that uses RabbitMQ as eventbus, and make sure the `JamesServerContract` passes.

**Comment by Arsnael** [comment]
The TaskManager should be MemoryTaskManager for now (easier to handle)

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/1879
