### ISSUE TITLE
[PGSQL] Module chooser:  scanning, Opensearch, opensearch_disabled

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4987]
# Epic
https://github.com/linagora/james-project/issues/4959

## How

Now postgres-app using `LuceneMessageSearchIndex` 
We need adapt [SearchModuleChooser](https://github.com/apache/james-project/blob/3363a285a1407bb9cc50a903cbaa97e5e619e25b/server/container/guice/opensearch/src/main/java/org/apache/james/SearchModuleChooser.java#L59) to `PostgresJamesServerMain` 

## Dod
- pg-app start-up success
- Update document related
- Using `opensearch` in `docker-compose-distributed.yml`

**Comment by quantranhong1999** [comment]
> pg-app start-up success

Just a remark that we should write 2 more Integration tests in postgres-app: 1 uses OpenSearch, 1 uses opensearch_disabled (e.g. `CassandraWithOpenSearchDisabled`).

**Comment by Arsnael** [comment]
Team question: why using scanning in module chooser and not LuceneMessageSearchIndex` for example?

**Comment by chibenwa** [comment]
Answer: classpath clashes between lucene and opensearch?

Lucene could be tried, if achievable but is less a priority than opensearch

**Comment by Arsnael** [comment]
https://github.com/apache/james-project/pull/1866
