### ISSUE TITLE
[PGSQL] Performance test Postgres SearchOverride

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#4988]
epic https://github.com/linagora/james-project/issues/4959

Require 

1. https://github.com/linagora/james-project/issues/4955
2. https://github.com/linagora/james-project/issues/4987

## How

- Using `james-gatling` for  performance test IMAP SEARCH command 
- [provision](https://github.com/apache/james-project/blob/8c6a055755f4768ed5dde39952da704c06aa00bd/server/apps/postgres-app/provision.sh) data if necessary (case using docker-compose sample)

**Comment by Arsnael** [comment]
Perf tests: opensearch, one run with search overrides and one without, see difference

**Comment by vttranlina** [comment]
The first test
I increased the percent of `searchUnseen`, `searchDeleted` in Scenario from 2%->10%
`docker-compose-distributed.yml` on my local
```
export DURATION=10
export USER_COUNT=2500
```
![image](https://github.com/linagora/james-project/assets/81145350/5b4afe14-f4c6-4ea4-a8e9-af518eecec18)

We can see the "Max (Response time)" when enabled search overrides is better

Detail:
- enabled search overrides: https://vttranlina.github.io/gatling_20231225/enable_search_overrides/index.html
- disabled search overrides:  https://vttranlina.github.io/gatling_20231225/disable_search_overrides/index.html

////

I will try one more test with increase sample data

**Comment by quantranhong1999** [comment]
> We can see the "Max (Response time)" when enabled search overrides is better

Wow, about max response time Postgres is indeed more stable than OpenSearch <3 (likely because OpenSearch with JVM nature: Garbage collection...)

**Comment by Arsnael** [comment]
Or maybe cause the load to opensearch is lower?

Can we try to increase the load? Or can you run a few times to have more data? I think it is hard to see as well the result here as we don't have a proper testing platform yet, so the size of data is very low. I think it would show more differences for searches if we had a lot of mails

**Comment by vttranlina** [comment]
## 2nd

`select count(*) from message_mailbox;` = `262790`

Opensearch stats: `"count": 10545465,` 
[opensearch_stats.json](https://github.com/linagora/james-project/files/13765733/opensearch_stats.json)

![search_overrides_2500_2](https://github.com/linagora/james-project/assets/81145350/6cc87a6a-5c43-4b80-9829-31bb67ce0aad)
Detail:

enabled search overrides: https://vttranlina.github.io/gatling_20231225/2nd/enable/index.html
disabled search overrides: https://vttranlina.github.io/gatling_20231225/2nd/disable/index.html

**Comment by vttranlina** [comment]
## 3rd
Increased the sample data

```
export DURATION=10
export USER_COUNT=5000
```
`select count(*) from message_mailbox;` = `444153`

opensearch index stats
```
"docs": {
                "count": 19448958,
                "deleted": 2248004
            },
```
[opensearch_index_stats.json](https://github.com/linagora/james-project/files/13767882/opensearch_index_stats.json)
![image](https://github.com/linagora/james-project/assets/81145350/2bc26e72-f01d-4f6d-a54c-2f5fa0bd73c9)
Detail:

enabled search overrides: https://vttranlina.github.io/gatling_20231226/enable/index.html
disabled search overrides: https://vttranlina.github.io/gatling_20231226/disable/index.html

///
_______________

At this time the "enable" looks not better than

**Comment by Arsnael** [comment]
Not much of a difference IMO 

I appreciate the big effort on local provisioning though, you must have spent some time for it
