### ISSUE TITLE
[PGSQL] Test for body deduplication

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4990]
Write an integration test in postgres-app

```
WHEN bob sends a mail to alice and cedric in SMTP
THEN the body of the mail is stored only once
```

This needs to be done with `AddDeliveredTo` mailet

To achieve this we likely need to only  only store the body onto the object store in PostgresMessageDAO.

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1873
