### ISSUE TITLE
Crowdsec Integration for POP3

### ISSUE THREAD

**Issue by thanhbv200585** [linagora/james-project#4994]
When client connects to POP3 server, james will check its IP and question to Crowdsec whether the IP is secure or not. If it is unsecure, the connection will be closed

### How
Add a `CrowdsecCheckHandler` into POP3 server in `pop3server.xml`

        <handlerchain>
            <handler class="org.apache.james.pop3server.core.CoreCmdHandlerLoader"/>
            <handler class="org.apache.james.CrowdsecCheckHandler"/>
        </handlerchain>
```

public class CrowdsecCheckHandler implements ConnectHandler<POP3Session> {
    @Override
    public Response onConnect(POP3Session session) {
        String ip = session.getRemoteAddress().getAddress().getHostAddress();
        return crowdsecHttpClient.getCrowdsecDecisions()
            .map(decisions -> apply(decisions, ip)).block();
    }

    private Response apply(List<CrowdsecDecision> decisions, String ip) {
        return decisions.stream()
            .filter(decision -> isBanned(decision, ip))
            .findFirst()
            .map(banned -> POP3Response.DISCONNECT)
            .orElse(POP3Response.OK);
    }
}
```

### DoD
Register `CrowdsecCheckHandler` successfully via `pop3server.xml`

**Comment by quantranhong1999** [comment]
> Add a CrowdsecCheckHandler into POP3 server

Please confirm that is via the extension mechanism. A direct plugin is not acceptable.

BTW the ticket is not detailed enough as part of a sprint. Please add more context, how to plug this as an extension, how to reuse the `ConnectionCheck` interface, definition of done...

**Comment by quantranhong1999** [comment]
It is good that you found `ConnectHandler` though. Now mostly just how to plug it into James.

**Comment by thanhbv200585** [comment]
PR: https://github.com/apache/james-project/pull/1887

**Comment by quantranhong1999** [comment]
I am working on POP3 + CrowdSec with proxy support. But it seems the PROXY protocol only fully supports SMTP/IMAP and not the case for POP3 (POP3 just uses a dummy `false` `proxyRequired`).

Should we invest on PROXY protocol support for POP3 first cc @chibenwa ?

**Comment by chibenwa** [comment]
Drop crowdsec support for POP3 IMO, this feel unecessary.

**Comment by Arsnael** [comment]
I'm ok with this

**Comment by quantranhong1999** [comment]
Sorry, but I came up with an almost-finished work for this issue. Could I open a PR to contribute the work? I feel wasteful to just drop the time I have spent on this.

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1936

I took the chance to conduct a polish round too.

**Comment by Arsnael** [comment]
I did not think you were advanced on the work sorry, as you were asking if support is necessary or not, I concluded you likely weren't. But if you have a PR for this no problem

**Comment by quantranhong1999** [comment]
> I did not think you were advanced on the work sorry, as you were asking if support is necessary or not, I concluded you likely weren't. But if you have a PR for this no problem

Sorry for making you confused. No problem ^^.
