### ISSUE TITLE
[HowTo] Custom mail processing howTo not working with distributed app?

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4995]
Somebody in Gitter was asking for support cause it seems he was experimenting custom matchers / mailets with the how to tutorial for custom mail processing (https://james.apache.org/howTo/mail-processing.html).

It seems it was working with james jpa (as in the tutorial). But when he tried to do something similar with the distributed app, it seems the custom mailet is not loading, cause he gets a ClaaNotFoundException, despite mounting it in the extension-jars folder like with jpa.

Try to check if there is an issue with distributed app and if yes, fix it.

**Comment by chibenwa** [comment]
Hello,
looking at the class name, should be org.apache.james.examples.custom.mailets.IsDelayedForMoreThan and not IsDelayedForMoreThan which implicitly is interpreted as org.apache.james.transport.mailets.IsDelayedForMoreThan and do not exist.

This is a configuration problem, I bet.

CF example:

```
            <mailet match="org.apache.james.examples.custom.mailets.IsDelayedForMoreThan=1 day"
                    class="org.apache.james.examples.custom.mailets.SendPromotionCode">
                <reason>Your email had been delayed for a long time. Because we are sorry about it, please find the
                    following promotion code.</reason>
                <promotionCode>1542-2563-5469</promotionCode>
            </mailet>
```

While in your file:

```
            <mailet match="org.apache.james.mailets.IsDelayedForMoreThan=3 seconds"
                    class="org.apache.james.mailets.SendPromotionCode">
                <reason>Your email had been delayed for a long time. Because we are sorry about it, please find the
                    following promotion code.</reason>
                <promotionCode>1542-2563-5469</promotionCode>
            </mailet>
```

**Comment by Arsnael** [comment]
That was the first mistake, which I noticed and told him about. Then he fixed according your suggestion above, and he pretends still having the same issue

Saying it worked with jpa app though...

**Comment by Arsnael** [comment]
Closing this, as it seems the guy made it work by configuring the mailetcontainer.xml correctly, as he claimed :)
