### ISSUE TITLE
[PSQL] Implement BlobReferenceSource(s) for postgres-app

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#4998]
## Why
When using deduplication mode for blob store, we need to trigger [the blob garbage collection task](https://james.apache.org/server/manage-webadmin.html#Running_blob_garbage_collection). (rationale: in deduplication mode, we do not remove the blob immediately while deleting a message, because that blob can still be referenced by other messages).

The blob GC task relies on `Set<BlobReferenceSource>` which stores the blob references in the database. However, there is no source using Postgres ATM.

We need to implement BlobReferenceSource(s) using Postgres.

## How
Mimic Cassandra ones for Postgres:
- `AttachmentBlobReferenceSource`: not sure because we do not support attachment yet with postgres-app. But likely would need this in the end when we implement JMAP?
- `MailQueueViewBlobReferenceSource`: not sure about this. Depending if we implement `MailQueueView` for postgres-app or not?
- `MailRepositoryBlobReferenceSource`
- `MessageBlobReferenceSource`

And guice binding.

## DoD
Integration test: in deduplication mode, after storing duplicated messages and deleting them, triggering the blob GC task would clean the blob.

**Comment by chibenwa** [comment]
Good catch!

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/1900
