### ISSUE TITLE
[PGSQL] Implement Deleted Message Vault

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5000]
This includes:

 - Metadata implementation on top of PGSQL and implementation that leverages object store.
 - Guice bindings and module chooser for Deleted message vault
 - Add `DeletionCallback` + `DeletedMessageVaultDeletionCallback`  in PG modules

**Comment by quantranhong1999** [comment]
WIP: https://github.com/apache/james-project/pull/1891
