### ISSUE TITLE
Refactor and update apache-james-mailbox-lucene

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#5001]
During the implementation of Postgresql, starting from a copy of JPA James, we had the Lucene mailbox module for search. We switched to search module chooser proposing scanning, Opensearch and opensearch_disabled later on. 

Why not keeping the Lucene local file storage system in the module chooser?

Well, it's old, very old, likely full of vulnerabilities in terms of security and completely outdated.

Can find the implementation in `apache-james-mailbox-lucene` module, where we can see the version of Lucene used there is `3.6.2` while the latest release is... `9.9.1`

Investigate how much of an effort it wold require to upgrade the Lucense mailbox search module implem to the latest release. If it's doable, it could become an option in the SearchModuleChooser for distributed and postgres apps versions of James!

**Comment by quantranhong1999** [comment]
wip: https://github.com/apache/james-project/pull/2315

**Comment by quantranhong1999** [comment]
Status so far (for future continuation): code compiling + contract tests are OK for version 6, but some IMAP Lucene MPT tests are failing (since version 4)).

**Comment by Arsnael** [comment]
woj-tek help finishing this work, so closing the ticket
