### ISSUE TITLE
[Postgres] Webadmin integration tests for postgres-app

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5005]
## Why
We should have webadmin integration tests for the postgres-app to make sure features that are exposed via webadmin function well.

## How
- introduce a module `server/protocols/webadmin-integration-test/postgres-webadmin-integration-test`, add CI test run in `Jenkinsfile`.
- Implement contract tests from the `webadmin-integration-test-common` module, and other tests if relevant.
  Fix guice binding issues and bugs if any.

## DoD
Webadmin ITs green.

**Comment by hungphan227** [comment]
draft pr https://github.com/apache/james-project/pull/1909

**Comment by Arsnael** [comment]
Note: some pre tasks are related tot his, should do them before (like jmap bindings for pg-app for example)
