### ISSUE TITLE
[PGSQL] Implement PostgresMailboxChangeRepository

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5008]
### Why
PGSQL: JMAP implementation

### How 
- Require [PostgresStateFactory](https://github.com/linagora/james-project/issues/5007)
- Require https://github.com/linagora/james-project/issues/5015
- Declare `PostgresMailboxChangeModule` table with constructor:

```sql
CREATE TABLE mailbox_change (
    account_id TEXT,
    state uuid,
    date TIMESTAMP WITH TIME ZONE,
    is_delegated BOOLEAN,
    is_count_change BOOLEAN,
    created uuid[],
    updated uuid[],
    destroyed uuid[],
    PRIMARY KEY (account_id, state)
);
```

- Create `class PostgresMailboxChangeRepository implements MailboxChangeRepository`

### Dod 
- Pass contract: `MailboxChangeRepositoryContract`

**Comment by chibenwa** [comment]
Unsure we need the timezone in the date.
The timestamp should be enough...

**Comment by Arsnael** [comment]
Unsure too but all the logic in base code relies on timezones (EmailChange and MailboxChange objects)

Also should think of adding TTL too (date column?)

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1943
