### ISSUE TITLE
[PGSQL] Implement PostgresMessageFastViewProjection

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5009]
### Why
PGSQL: JMAP implementation
### How 
- Require https://github.com/linagora/james-project/issues/5015
- Declare `PostgresMessageFastViewProjectionModule` table with constructor:

```sql
CREATE TABLE message_fast_view_projection (
    message_id UUID PRIMARY KEY,
    preview TEXT,
    has_attachment BOOLEAN
);
```
- Create `class PostgresMessageFastViewProjection implements MessageFastViewProjection`

### Dod 
- Pass contract: `MessageFastViewProjectionContract`

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1923
