### ISSUE TITLE
[PGSQL] Implement PostgresAttachmentMapper

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5011]
### Why
PGSQL: JMAP implementation
### How 
- Module location: `apache-james-mailbox-postgres`
- Declare `PostgresAttachmentModule` table with constructor:
```sql
CREATE TABLE attachment (
    id UUID PRIMARY KEY,
    blobId TEXT,
    type TEXT,
    message_id UUID,
    size BIGINT
);
```
- Create `class PostgresAttachmentMapper implements AttachmentMapper` and `PostgresAttachmentDAO`

## Dod
- Pass contract `AttachmentMapperTest`

**Comment by vttranlina** [comment]
## Note
- The methods of DAO will be tested by `AttachmentMapperTest`, we don't need DAO test class

**Comment by Arsnael** [comment]
Should manage the delete of attachments as well in DeletmessageListener?

AttachmentLoader, usage in MessageMapper and MessageIdMapper, ...

**Comment by Arsnael** [comment]
@chibenwa why is there in Cassandra two id fields: idAsUuid and id?

We have the feeling it's maybe because for retro compatibility issues between v1 and v2 for cassandra DAO (but v1 has been deleted in the code since). We think you likely know :)

If it's the case, one id for postgres should be enough correct? the uuid one perhaps?

**Comment by chibenwa** [comment]
> We have the feeling it's maybe because for retro compatibility issues between v1 and v2 for cassandra DAO (but v1 has been deleted in the code since). We think you likely know :)

I do not fully remember but yes that's retro-compatibility issues...

**Comment by Arsnael** [comment]
Alright let's just try to do it with only one id then :) (the uuid one)

**Comment by quantranhong1999** [comment]
We need to store attachment metadata (create a new column in the **message** table), and store the real `hasAttachment` into deleted message vault:
    - store attachment metadata in the `message` table. The data type is similar to `CassandraMessageV3Table.Attachments`. We can consider using [PostgreSQL User-defined Data Types](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-user-defined-data-types/).
    - add `List<MessageAttachmentRepresentation> attachments` into `MessageRepresentation`
    - In `DeletedMessageVaultDeletionCallback`: store the real `hasAttachment`.

**Comment by quantranhong1999** [comment]
We need to implement `PostgresAttachmentBlobReferenceSource` too.

`AttachmentBlobReferenceSource: not sure because we do not support attachment yet with postgres-app. But likely would need this in the end when we implement JMAP?` 

cf: https://github.com/linagora/james-project/issues/4998

**Comment by chibenwa** [comment]
- Pass AbstractMailboxManagerAttachmentTest

**Comment by vttranlina** [comment]
> - store attachment metadata in the message table. The data type is similar to CassandraMessageV3Table.Attachments. We can consider using [PostgreSQL User-defined Data Types](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-user-defined-data-types/).

I think we can use JSON type, more flexible, no need to define more, schema-less

**Comment by chibenwa** [comment]
JSONB is ok

**Comment by vttranlina** [comment]
Draft pr: https://github.com/apache/james-project/pull/1925
