### ISSUE TITLE
[PGSQL] Implement PostgresThreadIdGuessingAlgorithm

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5014]
## Why
We need a ThreadIdGuessingAlgorithm backed by Postgres (for Thread/get usage).

## How
- Table structure:
```sql
  CREATE TABLE thread (
    username TEXT,
    mime_message_id INT,
    message_id UUID,
    thread_id UUID,
    base_subject INT,
    PRIMARY KEY (username, mime_message_id, message_id)
);
```
- Implement `PostgresThreadIdGuessingAlgorithm`
- Need to delete Thread data upon message delete in `DeleteMessageListener` of Postgres too (just like what we did with Cassandra)
- Guice binding in `PostgresJMAPModule`.

## DoD
Pass contract test `ThreadIdGuessingAlgorithmContract`.

**Comment by vttranlina** [comment]
Do we need a DAO for it, or implement the query directly in `PostgresThreadIdGuessingAlgorithm` class?

**Comment by quantranhong1999** [comment]
> Do we need a DAO for it, or implement the query directly in PostgresThreadIdGuessingAlgorithm class?

IMO separating a DAO class or not, it could depend on the one who takes this. If the persistence code looks too complicated, we can extract them to a DAO class IMO.

**Comment by hungphan227** [comment]
PR https://github.com/apache/james-project/pull/1941
