### ISSUE TITLE
[PGSQL] Implement PostgresCustomIdentityDAO

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5017]
## Why
We need a `CustomIdentityDAO` backed by Postgres (for Identity/get + set usage).

## How
- Table structure:
```sql
CREATE TABLE custom_identity (
    username TEXT,
    id UUID,
    name TEXT,
    email TEXT,
    reply_to TEXT[],
    bcc TEXT[],
    text_signature TEXT,
    html_signature TEXT,
    sort_order INT,
    may_delete BOOLEAN,
    PRIMARY KEY (username, id)
);
```
An additional index on `username` would help list all identities for a given user quickly.

- Implement `PostgresCustomIdentityDAO`
- Guice binding in `PostgresJMAPModule`.

## DoD
Pass contract test `CustomIdentityDAOContract`.

**Comment by chibenwa** [comment]
Listing all signature of a given user shall be quick.

Otherwise OK to me.

**Comment by Arsnael** [comment]
> Listing all signature of a given user shall be quick.

why? There is no api  that fetches only signatures for theuser, we always return the full identity object. Or is it something new? A query fetching just signatures of a user? But I think the front just get directly the all Identity so we are confused here, as we don't do that with Cassandra too.

**Comment by chibenwa** [comment]
I mean listing all identities for a given user shall be quick.

**Comment by quantranhong1999** [comment]
> I mean listing all identities for a given user shall be quick.

This should be solved with an additional index on `username`.

**Comment by hungphan227** [comment]
CassandraCustomIdentity use UDT array for reply_to and bbc. Postgresl support UDT but jooq does not support it well. Therefore, I intend to use 2 dimension array (TEXT[][]) for reply_to and bbc

**Comment by vttranlina** [comment]
> CassandraCustomIdentity use UDT array for reply_to and bbc. Postgresl support UDT but jooq does not support it well. Therefore, I intend to use 2 dimension array (TEXT[][]) for reply_to and bbc

or JSON for simple

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/1960
