### ISSUE TITLE
[PGSQL] Implement PostgresPushSubscriptionRepository

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5018]
## Why
We need a `PushSubscriptionRepository` backed by Postgres (for PushSubscription/get + set usage).

## How
- Table structure:
```sql
CREATE TABLE push_subscription (
    user TEXT,
    device_client_id TEXT,
    id UUID,
    expires TIMESTAMP,
    types TEXT[],
    url TEXT,
    verification_code TEXT,
    encrypt_public_key TEXT,
    encrypt_auth_secret TEXT,
    validated BOOLEAN,
    PRIMARY KEY (user, device_client_id)
);
```
- Implement `PostgresPushSubscriptionRepository`
- Guice binding in `PostgresJMAPModule`.

## DoD
Pass contract test `PushSubscriptionRepositoryContract`.

**Comment by hungphan227** [comment]
@Arsnael @chibenwa do we need to implement this? We still use firebase anyway

**Comment by quantranhong1999** [comment]
> @Arsnael @chibenwa do we need to implement this? We still use firebase anyway

I am against this. Here is Apache James. There is no firebase whatever in Apache James. 
Let's respect and balance the community's need IMO.

**Comment by chibenwa** [comment]
Technically @hungphan227 that's needed for being JMAP compliant.

It also enables to be GAFAM free on push architecture if need be.

**Comment by Arsnael** [comment]
Yes we need it. Anything JMAP implemented with Cassandra => needs Postgres implem too. What we do in TMail is our own business, here it's the Apache James community work, the duty towards the community here is different.

Implement it please.

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/1954
