### ISSUE TITLE
Remove JMAP draft implementation in JMAPServerModule

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#5021]
## How 
- update in main branch first and then rebase on postgresql branch
- remove JMAPModule in JMAPServerModule
- add RFC8621MethodsModule to JMAPServerModule

## DoD
Pass TestJMAPServerModule

**Comment by chibenwa** [comment]
Please provide more details: why? How?

**Comment by hungphan227** [comment]
I do not understand why JMAPModule is in package org.apache.james.jmap.draft but it contains RFC8621MethodsModule

**Comment by chibenwa** [comment]
Ok, looks great to me then!

**Comment by Arsnael** [comment]
>  I do not understand why JMAPModule is in package org.apache.james.jmap.draft but it contains RFC8621MethodsModule

jmap draft was dev before the rfc... it was an attempt to implement jmap in james when the doc was still in a draft, well before the final rfc, and it's quite different but not completely. 

There is definitely some code from draft that is being used in rfc one and where we need to be careful of transferring it back, like the JMAPModule :)

**Comment by Arsnael** [comment]
=> Master branch, postgres branch will be rebased on that.

**Comment by Arsnael** [comment]
Can remove the header for choosing jmap implementation as well

**Comment by vttranlina** [comment]
We should do it first
- https://github.com/linagora/james-project/issues/5147

It we just only "remove" code, we will fail test cases

**Comment by Arsnael** [comment]
Yes I thought that was implicit :) need the work on master branch first before postgresql branch

**Comment by vttranlina** [comment]
// I don't have permission to apache repository. 

I rebased the `apache/postgresql` branch onto `apache/master` (command: `git rebase -i`), resolved conflicts, and integrated 2 new commits (2afd8618ec and 616cd954d8). If these commits are not included, the Maven build will fail. 
You can find the code branch at: https://github.com/vttranlina/james-project/tree/postgresqlRebased

Git log: 
```
2afd8618ec JAMES-2586 [UPDATE] [PGSQL] more javax APIs migrated to jakarta
616cd954d8 JAMES-2586 Update postgresql guice binding - adapt after rebase master (remove Jmap draft)
f108080bcf JAMES-2586 Create metrics for PostgresExecutor
d87f9e123f JAMES-2586 Mitigate fix for https://github.com/jOOQ/jOOQ/issues/16556
2e73c881ed JAMES-2586 Apply reactor timeout for jOOQ
...
```

// note
I tested maven build & test (PostgreSQL modules) locally. (this morning)

**Comment by Arsnael** [comment]
Done :)

**Comment by vttranlina** [comment]
green: https://ci-builds.apache.org/blue/organizations/jenkins/james%2FApacheJames/detail/postgresql/135/pipeline/

I will update it for tmail-backend

**Comment by vttranlina** [comment]
tmail-backend pr
- master: https://github.com/linagora/tmail-backend/pull/1014
- postgresql:  https://github.com/linagora/tmail-backend/pull/1015
