### ISSUE TITLE
[Postgres] JMAP Guice bindings modules to pg-app

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#5022]
## How 
- create PostgresJMAPModule: based on memory
- add PostgresJMAPModule, JMAPServerModule, JMAPEventBusModule, JmapEventBusModule, JMAPListenerModule, JMAPTasksModule to PostgresJamesServerMain
- create PostgresJmapJamesServerTest, PostgresJmapTestRule

Note: JMAPEventBusModule should have the chooser possibility depending if rabbimq is chosen or memory for the event bus

## DoD
Pass PostgresJmapJamesServerTest, PostgresJmapTestRule

**Comment by Arsnael** [comment]
A bit more things needed for binding here, cf https://github.com/linagora/james-project-private/issues/750#issuecomment-1869922555 :)

**Comment by Arsnael** [comment]
Tung suggestion: we can create initially a PostgresJMAPModule with memory bindings, and then replace step by step each binding with a postgres one when doing implementation.

@chibenwa : WDYT? we think it could be a good approach and would deserve a ticket for it.

**Comment by Arsnael** [comment]
Also add the TestJMAPServerModule a bit everywhere in our integration tests for Postgres, like we do with Cassandra and Memory

To do after removing draft code from james base code.

**Comment by chibenwa** [comment]
> @chibenwa : WDYT? we think it could be a good approach and would deserve a ticket for it.

Yes that is a GREAT idea !

**Comment by Arsnael** [comment]
Updated the ticket. This could be done earlier (after getting done attachment and messageId tickets) to have a jmap memory running on top of pg-app, with then the approach of binding bits by bits to postgres implems while integration is progressing.

I also moved the JmapUploadCleanupModule to https://github.com/linagora/james-project/issues/5010#issuecomment-1876710872 as we could only bind it then only when we have PG upload repository

**Comment by Arsnael** [comment]
Extract work from https://github.com/apache/james-project/pull/1909 and fix issues for binding jmap to pg-app in a first step

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/1922
