### ISSUE TITLE
[PGSQL] Implement PostgresNotificationRegistry

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5023]
## Why
We need a `NotificationRegistry` backed by Postgres (for background Vacation notification usage).

## How
- Table structure:
```sql
CREATE TABLE vacation_notification_registry (
    account_id TEXT,
    recipient_id TEXT,
    PRIMARY KEY (account_id, recipient_id)
);
```
- Implement `PostgresNotificationRegistry`
- Guice binding in `PostgresJMAPModule`.

## DoD
Pass contract test `NotificationRegistryContract`.

**Comment by chibenwa** [comment]
Cassandra implementation leverages TTL in order to reclaim space.

Do we have similar mecanisms in PGSQL? If not, what is the implementation strategy here?

**Comment by Arsnael** [comment]
> Do we have similar mecanisms in PGSQL? If not, what is the implementation strategy here?

Tried to look into it, seems not unfortunately :(

People seem to have different approaches, but the two I saw the most are resumed here I think: https://www.reddit.com/r/PostgreSQL/comments/ikyjtz/autoexpiring_db_records_whats_the_standard_way/

- create a column with a timestamp (that would be your TTL), probably an index on it and a cron job to delete the old records based on the ttl timestamp value
-  if ttl is not too strict, use partitions => https://www.postgresql.org/docs/current/ddl-partitioning.html and create partitions of the table based on a timestamp column, and then drop the partition when you know for sure that range is old enough to be fully disposed of

I prefer the first one though

**Comment by quantranhong1999** [comment]
>create a column with a timestamp (that would be your TTL), probably an index on it and a cron job to delete the old records based on the ttl timestamp value

```sql
-- Install pg_cron extension (if not already installed)
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Schedule a job to run every day and delete rows older than 7 days
SELECT cron.schedule('0 0 * * *', 'DELETE FROM your_table WHERE created_at <= NOW() - INTERVAL ''7 days'';');
```

Looks cool.

But the problem is that the `pg_cron` seems to not be an built in extension of Postgres:
```sql
postgres.public> CREATE EXTENSION IF NOT EXISTS pg_cron
[2024-01-03 15:43:01] [0A000] ERROR: extension "pg_cron" is not available
[2024-01-03 15:43:01] Detail: Could not open extension control file "/usr/share/postgresql/16/extension/pg_cron.control": No such file or directory.
[2024-01-03 15:43:01] Hint: The extension must first be installed on the system where PostgreSQL is running.
```

If we really want to install it, we would need to tweak the Postgres installation.

**Comment by vttranlina** [comment]
I remember when I did with MSSQL, the `Delete where...` (when I want to remove all old data), it will create a lot of transactions (not remember exactly is "transaction" or another), and it is a heavy query. 
It takes time to delete a few million rows. While that time the Postgres server will "lag"

About the delete/truncate partitions, it is very fast and light

**Comment by Arsnael** [comment]
I was thinking of a nomral cron with a script... but if there is a pg_crom and not too hard to include why not :)

For the we will delete millions of rows at once... not necessary. If you play the cron job every night for example that should not be too bad?

The problem of partitions is that you need to create a new table each time you get into a new range period. Might make the code a bit more complex. You still need a cron job behind to drop the partitions after a while too.

**Comment by quantranhong1999** [comment]
> It takes time to delete a few million rows. While that time the Postgres server will "lag"

Maybe a careful index could ease the headache too?

**Comment by Arsnael** [comment]
Ah you definitely need an index I think yes

**Comment by Arsnael** [comment]
Need to add date timestamp column + index for TTL

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/1985
