### ISSUE TITLE
[PGSQL] Implement PostgresFilteringProjection

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5026]
## Why
We need an `EventSourcingFilteringManagement.ReadProjection` backed by Postgres (for faster latest filter calculation?).

## How
- Table structure:
```sql
CREATE TABLE filters_projection (
    aggregate_id TEXT PRIMARY KEY,
    event_id INT,
    rules JSONB,
    PRIMARY KEY (aggregate_id)
);
```
- Implement `class PostgresFilteringProjection implements EventSourcingFilteringManagement.ReadProjection, ReactiveSubscriber`
- Guice binding in `PostgresJMAPModule`.

## DoD
- Pass contract test `PostgresEventSourcingFilteringManagementWithReadProjectionTest implements FilteringManagementContract`

**Comment by quantranhong1999** [comment]
BTW looking at [the `EventSourcingFilteringManagement`'s constructor](https://github.com/apache/james-project/blob/master/server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/EventSourcingFilteringManagement.java#L105), it is always `NoReadProjection` hard code regardless we put `ReadProjection` or not.

Maybe it was a mistake cc @chibenwa?

**Comment by chibenwa** [comment]
> Maybe it was a mistake cc @chibenwa?

Likely yes. Fix welcomed.

>     RULES JSONB,

Tiny detail: `rules JSONB`

**Comment by quantranhong1999** [comment]
> Likely yes. Fix welcomed.

Ok. Let's me fix it.

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/1968
