### ISSUE TITLE
[Postgresql] Final guice binding cleanup

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#5030]
Make sure all the memory bindings are gone and everything has been replaced correctly with postgres JMAP implementations

DoD: pg-app is using postgresql JMAP fully and integration tests are green

**Comment by quantranhong1999** [comment]
@hungphan227 what is the state of this? I guess should be in the review column with the JMAP integration tests ticket?

**Comment by Arsnael** [comment]
No PR? Can we conclude all bindings and cleanup is there already then?

**Comment by hungphan227** [comment]
This is already included in PR JMAP integration tests
