### ISSUE TITLE
[PGSQL] Investigate a few Postgres driver issues

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5036]
## Why
While working with `r2dbc-postgresql` and `jOOQ`, I encountered some issues that I think could be driver libraries issues.

I would like to verify them and open bug tickets on the driver side if any.

My 3 suspect issues so far:

### 1. Can not change thread while using the postgres driver thread
I remember I tried to use `.subscribeOn(Schedulers.boundedElastic())` but did not succeed in manipulating the thread. It was always the `reactor-epoll...` - Postgres driver thread.
If that is a real issue, then all our blocking code would be executed on the Postgres driver thread - which is bad for performance.

### 2. Using `Flux` (postgres publisher) + `concatMap` could lead to hanging forever issue
 We encountered an hanging issue with `rename` API: https://github.com/apache/james-project/pull/1828#discussion_r1409121102

I recently encountered a hanging issue while working with `DeleteMessageListener` too. If I change `flatMap` at https://github.com/apache/james-project/blob/postgresql/mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/DeleteMessageListener.java#L101 to `concatMap`, then the tests hang.

I found two temporary solutions for this:
- stick to `.flatMap`: not good for the low concurrency case though
- use `.concatMap`, but we must `.collectList` first (just like [Benoit's fix for the `rename` issue](https://github.com/apache/james-project/blob/postgresql/mailbox/postgres/src/main/java/org/apache/james/mailbox/postgres/mail/dao/PostgresMailboxDAO.java#L195-L196)): collect a big list is not performance wise though.

### 3. Sometimes jOOQ' compilation return type is different from the actual return type at runtime
Once I get data with `Hstore` data type, the compilation return type is `Hstore`, but at runtime `LinkedHashMap` was returned instead...
And another case which I do not remember now.

## How
Verify if they are our side issues or driver-side issues. If driver-side issues, open bug tickets.

**Comment by quantranhong1999** [comment]
On the issue **1.** Can not change thread while using the Postgres driver thread: **TLDR it is not an issue**.

If we `.subscribeOn` directly on postgres Publisher, we really can not change the thread:
```java
            Flux.from(connection.createStatement("SELECT 1")
                    .execute())
                .take(1)
                .flatMap(result -> {
                    System.out.println("Thread after executing Postgres query: " + Thread.currentThread().getName());
                    return result.map((row, rowMetadata) -> row.get(0, String.class));
                })
                .subscribeOn(Schedulers.boundedElastic())
                .collect(ImmutableList.toImmutableList())
                .block().get(0);
```
Result:
`Thread after executing Postgres query: reactor-tcp-epoll-2`

But if we .subscribeOn` on blocking code Publisher instead (just like what we are doing with our blocking code), then we can change the thread for blocking code:
```java
            Flux.from(connection.createStatement("SELECT 1")
                .execute())
            .flatMap(result -> {
                System.out.println("Thread after executing Postgres query: " + Thread.currentThread().getName());
                return result.map((row, rowMetadata) -> row.get(0, String.class));
            })
            .flatMap(result ->
                // assume we execute some blocking call code here e.g.
                Mono.fromCallable(() -> {
                        System.out.println("Thread executing blocking call code: " + Thread.currentThread().getName());
                        Thread.sleep(1000L);
                        return result;
                    })
                    .subscribeOn(Schedulers.boundedElastic()))
            .map(result -> {
                System.out.println("Thread after execute blocking call code: " + Thread.currentThread().getName());
                return result;
            })
            .collect(ImmutableList.toImmutableList())
            .block().get(0);
```

Result:
```
Thread after executing Postgres query: reactor-tcp-epoll-2
Thread executing blocking call code: boundedElastic-1
Thread after execute blocking call code: boundedElastic-1
```

**Comment by quantranhong1999** [comment]
## 2. Using Flux (DELETE returning) + concatMap could lead to a hanging forever issue

I succeeded in reproducing this via a unit test. The following test would always hangs:

```java 
   @Test
    void deleteQueryWithReturningFieldsAsFluxAndConcatMap() {
        // Create person table
        postgresExecutor.executeVoid(dslContext -> Mono.from(dslContext.createTableIfNotExists("person")
                .column("id", SQLDataType.INTEGER.identity(true))
                .column("name", SQLDataType.VARCHAR(50).nullable(false))
                .constraints(DSL.constraint().primaryKey("id"))))
            .block();

        // Insert some data into the person table
        BiFunction<Integer, String, Mono<Void>> insertARecordMono = (id, name) -> {
            System.out.println("Inserting user with id " + id + " and name " + name);
            return postgresExecutor.executeVoid(dslContext ->
                Mono.from(dslContext.insertInto(DSL.table("person"), DSL.field("id"), DSL.field("name"))
                    .values(id, name)));
        };
        Flux.range(0, 100)
            .flatMap(i -> insertPersonMono(i, "oldName"))
            .then()
            .block();

        // Delete query with returning id, then insert again using Flux.concatMap
        Flux<Integer> deleteQueryWithReturningFlux = postgresExecutor.executeRows(dslContext ->
                Flux.from(dslContext.deleteFrom(DSL.table("person"))
                    .where(DSL.field("name").eq("oldName"))
                    .returning(DSL.field("id")))) // if We do not use returning here, it would not hangs
            .map(record -> record.get(DSL.field("id", Integer.class)));

        deleteQueryWithReturningFlux
            .concatMap(id -> insertARecordMono.apply(id, "newName")) // it hangs upon first Flux element
            .then()
            .block();
    }
```

Now time to summarize and open a ticket on jOOQ github I guess.

**Comment by quantranhong1999** [comment]
> Now time to summarize and open a ticket on jOOQ github I guess.

https://github.com/jOOQ/jOOQ/issues/16055

**Comment by Arsnael** [comment]
Ok I get more the push for jdk 21 now :) Thanks for the investigations

**Comment by quantranhong1999** [comment]
> 3. Sometimes jOOQ' compilation return type is different from the actual return type at runtime

https://github.com/jOOQ/jOOQ/issues/16069
