### ISSUE TITLE
[Postgres] Create cronjob to clean email_change table

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#5040]
## WHY
Old data in email_change table needs to be removed

## How
Create cronjob in James to remove old data

## Dod
Tests

**Comment by hungphan227** [comment]
Previously I have investigated creating cronjob in Postgresql (https://github.com/citusdata/pg_cron). However, it requires a package installed in the OS and currently only Linux is supported. If Postgresql is installed in Windows, this feature will be unavailable. Therefore, this solution is not appropriate.

**Comment by Arsnael** [comment]
More like for an ops deployment task though :) + mailbox change and the other TTLs we are supposed to have later

**Comment by vttranlina** [comment]
When grooming, I thought with a cron extension, we would be easier than.
Now when hear we need to install the cron tool, I don't know what is difference with the way: Use cron tab to trigger run a bash script (in bash script we will execute SQL query for delete).

**Comment by chibenwa** [comment]
> When grooming, I thought with a cron extension, we would be easier than.

:+1:

**Comment by Arsnael** [comment]
Well I mean if the cron extension in question is not compatible with other systems than Linux, it's not great community wise for compatibility. I would tend to agree with @hungphan227 in this case

At least everybody can run a cronjob with a bash script

**Comment by vttranlina** [comment]
So we should add the `postgres_cleanup.sh` in `pg-app` directory, and add SQL query in to it. 
also document it

**Comment by Arsnael** [comment]
Could have that yes

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/1959
