### ISSUE TITLE
[PGSQL] Implement TaskExecutionDetailsProjection 

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5042]
## Why?
Implement task-distributed for postgresql variant
## How

- Create a DAO for it, the table DDL looks like:

```sql
create table PostgresTaskExecutionDetailsProjectionTable (
    task_id uuid primary key,
    additional_information text,
    type text,
    status text,
    submitted_date timestamp ,
    submitted_node text,
    started_date timestamp ,
    ran_node text,
    completed_date timestamp,
    canceled_date timestamp,
    cancel_requested_node text,
    failed_date timestamp
);
```
- Create PostgresTaskExecutionDetailsProjection implement [TaskExecutionDetailsProjection](https://github.com/apache/james-project/blob/395dad3c3286185ca55c9f694448158452bc6061/server/task/task-memory/src/main/scala/org/apache/james/task/eventsourcing/TaskExecutionDetailsProjection.scala#L31)
& implement method service

## Dod
- pass contract test `TaskExecutionDetailsProjectionContract`
- Guice binding

**Comment by quantranhong1999** [comment]
guice binding issue left: https://github.com/apache/james-project/pull/2166
