### ISSUE TITLE
JAMES-4000 JMAP should guess charset of text parts when missing

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5050]
Given an email with a text part without charset

```
------------=_1706602778-31669-7
Content-Type: text/plain; name="avertissement.txt"
Content-Disposition: inline; filename="avertissement.txt"
Content-Transfer-Encoding: base64

Q2UgbWVzc2FnZSDpbGVjdHJvbmlxdWUgZXQgdG91cyBsZXMgZmljaGllcnMgYXR0YWNo6XMgcXUn
aWwgY29udGllbnQgc29udCBjb25maWRlbnRpZWxzIGV0IGRlc3RpbulzIGV4Y2x1c2l2ZW1lbnQg
```

[iso-8859-1.eml.txt](https://github.com/linagora/james-project/files/14110550/iso-8859-1.eml.txt)

Today TMail fails at rendering this properly:

![image](https://github.com/linagora/james-project/assets/6928740/2a8ec95e-5fbb-47c7-8e45-eb85851b0fa7)

This is because we uses `US_ASCII` as a default when no charset is specified.

Suggestion: we should rather "guess" the charset when that's the case: https://github.com/albfernandez/juniversalchardet

JIRA https://issues.apache.org/jira/browse/JAMES-4000

**Comment by chibenwa** [comment]
Likely not easily doable with MIME4J.

However I found the way to customize the default charset...

**Comment by Arsnael** [comment]
What about putting utf-8 as default? Not really solving the issue I know, but that should likely cover more than US_ASCII?

**Comment by chibenwa** [comment]
Yes we could ^^ Fixup welcome.
