### ISSUE TITLE
[PGSL] Implement a way to track the stats of statement 

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5052]
## Why
It will help us catch which query has issue, heavy, slow...

## How
1.  Install `pg_stat_statements` on postgres site, https://www.postgresql.org/docs/current/pgstatstatements.html
Not sure it is enough, (my quick search result)

2. Add metric to PostgresExecutor on James's site?

**Comment by vttranlina** [comment]
Using `pg_stat_statements` alone suffices; we don't require duplication in James.

In the initial trial, I observed the following:
- query: Text of a representative statement
- calls: Number of times the statement was executed
- total_exec_time, mean_exec_time, min_exec_time, max_exec_time

IMO it's enough. Although it has another property,  I didn't focus on them initially.

SQL Query:

`select query, mean_exec_time, total_exec_time, calls from pg_stat_statements order by total_exec_time desc;`

The resulting sample: 

![image](https://github.com/linagora/james-project/assets/81145350/aeff984f-92c4-420d-8e1a-a880ea7e8974)


__________
To install pg_stat_statements, execute the following query:

```sql
create extension if not exists pg_stat_statements;
alter system set shared_preload_libraries='pg_stat_statements';

-- restart postgres
-- optional
alter system set pg_stat_statements.max = 100000;
alter system set pg_stat_statements.track = 'all';
```
To reset statistics, use:  `select pg_stat_statements_reset();`

-> I think we can manually install it on staging. It is for analysis, then we don't need to implement it in James's code

**Comment by vttranlina** [comment]
- [x] install `pg_stat_statements` on staging

**Comment by chibenwa** [comment]
What is the unit on th picture? Seconds?

**Comment by vttranlina** [comment]
> What is the unit on th picture? Seconds?

milisecond

**Comment by quantranhong1999** [comment]
>  I think we can manually install it on staging. It is for analysis, then we don't need to implement it in James's code

Should we document this in a readme doc in a Postgres module on how to debug/optimize the Postgres DB performance?

**Comment by vttranlina** [comment]
Documentation pr https://github.com/apache/james-project/pull/2006
