### ISSUE TITLE
JAMES-3999 Listener: define priority and apply priority

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5053]
Some listener should be executed quicklier than others.

This is paramount to ensure best effort upon resynchronisation.

The idea would be to prioritize in the execution order listeners that have a higher priority to avoid causing delays.

JMAP listener especially (EmailQueryView, MailboxChange) should be executed with the highest priority possible.

**Comment by Arsnael** [comment]
JIRA: https://issues.apache.org/jira/browse/JAMES-3999

**Comment by chibenwa** [comment]
Not a priority

**Comment by chibenwa** [comment]
(commented on the JIRA issue)
