### ISSUE TITLE
[Postgres] Index for RLS column (domain) when RLS enabled

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5054]
## Why

Upon RLS enabled, we set a session attribute for each Postgres connection: https://github.com/apache/james-project/blob/postgresql/backends-common/postgres/src/main/java/org/apache/james/backends/postgres/utils/DomainImplPostgresConnectionFactory.java#L78

Likely when Postgres filters following the RLS policy, it would do the query "... WHERE domain = app.current_domain".

Then we should index the RLS column (`domain`), otherwise, the performance would be bad when using RLS.

## How

Check how and if Postgres implicitly indexes the RLS column.

Index RLS column if needed.

## DoD
Index enabled for RLS column.
Would be good to benchmark perf before and after (e.g. Query execution plan with `EXPLAIN ANALYZE`?)

**Comment by vttranlina** [comment]
I think we should test it first.
We can dump sample data.
use the rlsUser for query with `explain verbose` and compare the difference between before and after.

Or at least the Postgres document has the recommendation to do that

**Comment by Arsnael** [comment]
What do you think would happen if you turn on first RLS in this case, it creates the db and everything, you play with it a bit around creating data... then you turn it off? and the other way around?

**Comment by quantranhong1999** [comment]
RLS enabled -> RLS disabled: I think it would be fine.
RLS disabled -> RLS enabled: Postgres would complain the `domain` column does not exist while inserting data. The existing data would be lost to James (during query time as there was no domain bounded).

**Comment by Arsnael** [comment]
We should specify that limitation in the doc then :)

**Comment by vttranlina** [comment]
> RLS enabled -> RLS disabled: I think it would be fine.

Yes, The condition that James must run with "super user"

**Comment by hungphan227** [comment]
I did some tests and found out that when RLS is applied, indexes (without RLS column) are not used by Postgres

**Comment by hungphan227** [comment]
draft PR https://github.com/apache/james-project/pull/2082

**Comment by vttranlina** [comment]
> I did some tests and found out that when RLS is applied, indexes (without RLS column) are not used by Postgres

I don't see the same in my lab:
Here is my query plan when I enabled rls and query on `mailbox` table
```sql

set app.current_domain = 'example.tld';
explain select * from mailbox where user_name ='benwa' and mailbox_namespace='#private';

```
result
![image](https://github.com/linagora/james-project/assets/81145350/33b73353-c574-4e2d-8fa3-22adcf194dba)
As the query plan, Postgres order:
- Index Scan using `mailbox_username_namespace_index` on mailbox  
- Filter: ((domain)::text = current_setting('app.current_domain'::text))


Or I miss something?

Detail my lab:

https://github.com/linagora/james-project/assets/81145350/a711a424-cea0-481e-be7c-4cf800472c96

**Comment by vttranlina** [comment]
The same result was on the other tables (`subscription`, `message_mailbox`).
After discussing with @hungphan227 @quantranhong1999 ,
the size input for phase `Filter: ((domain)::text = current_setting('app.current_domain'::text))` is not big, 
the index for the domain doesn't get much benefit 
=> We don't need more index 
=> We can close this ticket
