### ISSUE TITLE
`PostgresCommons.DataTypes.TIMESTAMP` should be stored under UTC time

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5056]
## Why
   `ZonedDateTime.toLocalDateTime()` seems to lose the timezone information, and just keep the time information. 

While upon reading we assume it is in UTC timezone, but it is not as it could be time in other timezones. e.g. https://github.com/apache/james-project/blob/postgresql/server/data/data-jmap-postgres/src/main/java/org/apache/james/jmap/postgres/pushsubscription/PostgresPushSubscriptionDAO.java#L68

   We need to convert the timestamp to UTC time first before converting it to `LocalDateTime`:
 `zonedDateTime.withZoneSameInstant(ZoneId.of("UTC")).toLocalDateTime()`

## How

Can easily reproduce the issue by writing a test storing a not UTC timestamp.

Check and provide fixes where relevant.

# DoD
Fixed.

**Comment by vttranlina** [comment]
resolve https://github.com/apache/james-project/pull/2070
