### ISSUE TITLE
[Postgres] Implement PostgresEmailQueryView

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#5062]
## How
- Table structure:
```sql
CREATE TABLE email_query_view (
    mailbox_id UUID,
    message_id UUID,
    received_at TIMESTAMP,
    sent_at TIMESTAMP,
    PRIMARY KEY (account_id, recipient_id)
);
```
- Implement `PostgresEmailQueryView`
- Guice binding in `PostgresDataJmapModule`.

## DoD
Pass contract test `EmailQueryViewContract`.

**Comment by Arsnael** [comment]
Good catch, thanks! :)

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/2007
