### ISSUE TITLE
Tmail-backend 0.9.0 release

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#5063]
Note: better to have ICS reply extension and redis event bus merged first for this release

- [x] Tag release 0.9.0-rc1 (needs a James sha-1 submodule upgrade first)
- [x] changelog
- [x] deploy sandbox
- [ ] perf tests
- [x] deploy preprod
- [ ] QA tests
- [ ] Tag final release 0.9.0
- [x] Update notion pages for tmail-backend release log and features tracking (https://www.notion.so/linagora/Back-end-s-release-note-cb529c89d588492aac5ba1f76c0cd494 and https://www.notion.so/linagora/Backend-features-support-2e077cb3f00443c9a8154f0fdc954daf)
- [ ] deploy prod

**Comment by Arsnael** [comment]
Changelog https://ci.linagora.com/linagora/lgs/software-linagora-com-website/-/merge_requests/50

**Comment by Arsnael** [comment]
@chibenwa regarding QA, as it seems we don't have anymore a QA tester, how do we proceed? Based on what criteria?

**Comment by chibenwa** [comment]
Do minimal QA (~30 minutes) before deploying to tmail.linagora.com

Use Linagorians as QA tester.

Deploy in VN morning to limit impact.

**Comment by Arsnael** [comment]
sandbox: https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/sandbox-emaily-apps/-/merge_requests/15
preprod: https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/emaily-staging-apps/-/merge_requests/33

**Comment by chibenwa** [comment]
You can also ask Yen/Minh anh to help a quick QA

**Comment by Arsnael** [comment]
OK... do we have a checklist of things to test or...?

**Comment by Arsnael** [comment]
> Deploy in VN morning to limit impact.

Usually QA testing were done until now on staging. Feels like you are talking about prod here?

**Comment by quantranhong1999** [comment]
BTW this ticket should be either in `linagora/tmail-backend` or `james-project-private` instead.

**Comment by quantranhong1999** [comment]
cc @dab246 the charset fix should be deployed on staging env.

**Comment by Arsnael** [comment]
Moved
