### ISSUE TITLE
JAMES-3998 Empty password should not lead to worrying error

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5064]
![image](https://github.com/linagora/james-project/assets/6928740/fbd338b1-16d1-465d-a2c3-19f0924cf2d3)

![image](https://github.com/linagora/james-project/assets/6928740/bb437877-46c0-4f45-be76-dfced2f045ac)

DOD: not an error, info only...

**Comment by Arsnael** [comment]
JIRA: https://issues.apache.org/jira/browse/JAMES-3998

**Comment by vttranlina** [comment]
It is not an empty password
It is a password that has the character `""`
I tested locally, the empty password had another error ` BAD LOGIN failed. Illegal arguments.`
<img width="472" alt="image" src="https://github.com/linagora/james-project/assets/81145350/50ebc491-a88d-4d21-b25d-3efd7344bc3b">

**Comment by quantranhong1999** [comment]
> It is a password that has the character ""

Hmm anyway, it is still a user error, and the server should likely not log an error.

**Comment by Arsnael** [comment]
It's 2 use cases where we should not throw an error instead of one then. Problem still remains :)

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/2026
