### ISSUE TITLE
JAMES-3997 Netty backpressure for IMAP Fetch

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5065]
![image](https://github.com/linagora/james-project/assets/6928740/6d16064d-9b43-4ffb-bf22-50fd264dc287)

Cc @Arsnael do you think you can find back code snipset on this netty best practice?

I'd happily get a go at this ASAP...

**Comment by Arsnael** [comment]
JIRA: https://issues.apache.org/jira/browse/JAMES-3997

**Comment by chibenwa** [comment]
![image](https://github.com/linagora/james-project/assets/6928740/8a039382-19a0-478c-8628-dfa17e0b77f1)

http://normanmaurer.me/presentations/2014-twitter-meetup-netty/slides.html#9.0

I did found it back!

**Comment by Arsnael** [comment]
https://github.com/apache/james-project/pull/2031

**Comment by Arsnael** [comment]
# IMAP perf test netty backpressure for imap fetch 

![Image](https://github.com/linagora/james-project/assets/9005025/c77247d0-107f-4fc4-a88c-b702e837825d)

A bit better than 0.8.2 on the fetch, but... could be the platform? (cause a bit better overall) very minimal.

really wondering though btw if the simulation is adapted to the case encountered on CNB with the fetch, cause I guess it was on a big fetch, while in the simulation we do fetch on `MessageRanges(Last())` for fetchBody and fetchHeaders. Not really relevant?

**Comment by Arsnael** [comment]
Image for this, based on 0.8.2 with the imap fetch backpressure commit: rcordier/tmail-backend:distributed-imap-backpressure
