### ISSUE TITLE
Should be able to save a draft with invalid email address

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5075]
Actual:

![image](https://github.com/linagora/james-project/assets/6928740/9b06558b-125a-426c-8f35-00f470f4d409)

DOD: should be able to save such a draft, with a recipient in the typing

https://jmap.io/spec-mail.html#emailset

```
The final message generated may be invalid per RFC 5322. For example, if it is a half-finished draft, the To header field may have a value that does not conform to the required syntax for this header. The message will be checked for strict conformance when submitted for sending (see the EmailSubmission object description).
```

**Comment by vttranlina** [comment]
Jira: https://issues.apache.org/jira/browse/JAMES-4008

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/2040
