### ISSUE TITLE
org.apache.james.protocols.smtp.core.esmtp.MailSizeEsmtpExtension: is error log needed?

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5076]
`Rejected message from MaybeSender{mailAddress=Optional.empty} to 40.107.9.103 of size 89015453 exceeding system maximum message size of 73400320 based on SIZE option.`

![image](https://github.com/linagora/james-project/assets/6928740/448b6437-31ee-4dc3-b8aa-a56a6cfe3c6e)

Likely should not be ERROR

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/2053
