### ISSUE TITLE
[Postgres] Fix some JMAP postgres integration tests

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#5077]
Fix the following:

server/protocols/jmap-rfc-8621-integration-tests/postgres-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/postgres/PostgresEmailGetMethodTest.java

server/protocols/jmap-rfc-8621-integration-tests/postgres-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/postgres/PostgresEmailQueryMethodTest.java

server/protocols/jmap-rfc-8621-integration-tests/postgres-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/postgres/PostgresMailboxSetMethodTest.java

server/protocols/jmap-rfc-8621-integration-tests/postgres-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/postgres/PostgresPushSubscriptionSetMethodTest.java

server/protocols/jmap-rfc-8621-integration-tests/postgres-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/postgres/PostgresThreadGetTest.java

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/2048

**Comment by hungphan227** [comment]
Split to smaller PRs:

- https://github.com/apache/james-project/pull/2107
- https://github.com/apache/james-project/pull/2108

**Comment by quantranhong1999** [comment]
(Summary in case we forgot about PRs)

We suspect the postgres-jmap-it are actually slow => increase the timeout to 1 hour for now: https://github.com/apache/james-project/pull/2114

We try to fully run the Distributed JMAP test suite to compare to the Postgres one:
- https://github.com/apache/james-project/pull/2116
- https://github.com/apache/james-project/pull/2115

If the runtime distribution between Distributed and Postgres is kinda the same, then likely the performance of the Postgres one is ok, which means we can just increase the timeout.

**Comment by Arsnael** [comment]
> If the runtime distribution between Distributed and Postgres is kinda the same, then likely the performance of the Postgres one is ok, which means we can just increase the timeout.

Means we can probably put back the remaining disabled tests as well and considering timeout isn't an issue anymore
