### ISSUE TITLE
[Bug] [james-mime4j] AddressListFieldLenientImpl parse AddressList incorrect

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5086]
When parsing the rawField `To: name1 <invalid1>` 
by [AddressListFieldLenientImpl](https://github.com/apache/james-mime4j/blob/8a109f0ccdffebe6f15b3e29483a5e22b401e6dc/dom/src/main/java/org/apache/james/mime4j/field/AddressListFieldLenientImpl.java#L39)
The AddressList return incorrect

Actual: size 2 ("invalid", ">")

Expected: size 1 ("invalid")

![image](https://github.com/linagora/james-project/assets/81145350/43c1bca4-f63f-48fe-9018-b964879cd6f9)

**Comment by vttranlina** [comment]
Bug of repo https://github.com/apache/james-mime4j
But I can not create new issue on that repository. 
Please move it if creation the issue here is incorrect

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/projects/MIME4J/issues/MIME4J-251?filter=allopenissues

**Comment by chibenwa** [comment]
We can keep the isues here.

**Comment by chibenwa** [comment]
And what if... `To: invalid` how would mime4j parse this?

![image](https://github.com/linagora/james-project/assets/6928740/db0b474d-eef3-43d3-a808-1691c4ed1d8a)

![image](https://github.com/linagora/james-project/assets/6928740/73f7235f-4b67-4ce6-9a12-d11361826974)

![image](https://github.com/linagora/james-project/assets/6928740/bd5115dd-297d-45f7-95ff-52f6e78e7960)

The current use case would be `to: [{name: null, email: "invalid"}]`.

So this corner case is not a blocker.

**Comment by vttranlina** [comment]
I think have a confusion here.
Currently, Tmail does not approve invalid email addresses when saving a draft
However, this behavior is expected to change after addressing ticket  https://github.com/linagora/james-project/issues/5075

Then. Tmail will save a draft email, that has `to: [{name: null, email: "invalid"}]` 
And because of this issue, when "Email/get" the draft email, it will appear as: 
```
"to": [
  {
      "name": "name1",
      "email": "invalid1"
  },
  {
      "email": ">"
  }
]
```

**Comment by chibenwa** [comment]
Ok

**Comment by chibenwa** [comment]
Not a critical blocker, just a very very nice to have.

How about by the time we get this fixed we filter in the JMAP stack the lone `>` email? Not clean but it would do as a temporary fix...

**Comment by vttranlina** [comment]
james-mime4j pr: https://github.com/apache/james-mime4j/pull/102
