### ISSUE TITLE
[Postgres] Fix flaky tests in PostgresEmailQueryMethodTest

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#5092]
Fix the following:
- listMailsShouldBeSortedWhenUsingTo
- listMailsShouldBeSortedWhenUsingFrom
- inMailboxOtherThanShouldBeRejectedWhenInOperator

**Comment by hungphan227** [comment]
In SortConverter:
```
            case MailboxTo :
                return Stream.of(new FieldSort.Builder().field(TO + PATH_SEPARATOR + NAME + PATH_SEPARATOR + RAW),
                    new FieldSort.Builder().field(CC + PATH_SEPARATOR + ADDRESS + PATH_SEPARATOR + RAW));
```

When I change NAME to ADDRESS, test listMailsShouldBeSortedWhenUsingTo pass

**Comment by vttranlina** [comment]
I see it still not resolved
https://github.com/apache/james-project/blob/postgresql/server/protocols/jmap-rfc-8621-integration-tests/postgres-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/postgres/PostgresEmailQueryMethodTest.java#L68
Do we miss something here?
Reopen? @Arsnael @hungphan227

**Comment by Arsnael** [comment]
I must have made a mistake here sorry. Good catch @vttranlina

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/2183
