### ISSUE TITLE
Investigate why SelectedMailboxImpl could be slow to process Added.

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5105]
![image](https://github.com/linagora/james-project/assets/6928740/1681ea3d-d127-4dec-b239-2b56702752a1)

Possible deadlock?

I do not think writing data to the client takes that much time.

UID-MSN converter looks ok. Adding 40.000 randonm ints in it completed in 7.6 sec

**Comment by chibenwa** [comment]
Could be also caused by contention on the boundedElastic schedulers....

**Comment by vttranlina** [comment]
Tried some cases but the timeout exception was not thrown
- Tried to modify `IdleProcessor#reactiveEvent` take more time 600000ms (11 minutes), 
- Tried to immediately stop client connection when idling new add message event

**Comment by vttranlina** [comment]
The concurrent test code for select inbox and IDLE (it works fine)
https://github.com/apache/james-project/commit/477a30d182a4976881723210968a7e26026c1b4e
//
no idea now

**Comment by chibenwa** [comment]
I think some of the refactoring I did could help...
(cross object locking is never a good idea)

**Comment by chibenwa** [comment]
Never happened again.

Recent refactoring should had fixed that.
