### ISSUE TITLE
MimeMessageWrapper error Charsets

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5125]
When I implemented i18n, I got the case that the content of mimMessage was not keeping the correct charset like the original

How to reproduce: https://github.com/apache/james-project/commit/7270004d3fc8e07f2caebbc3e2f818374d9a8d18

- In `eml` file: `ACCEPTÉ`
- After parse with mimeMessage: `ACCEPTÃ`

// related: https://github.com/linagora/tmail-backend/pull/970#discussion_r1522795500

**Comment by chibenwa** [comment]
Q encode the value in the headers
