### ISSUE TITLE
[Postgres] Reworking AttachmentID

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#5127]
## Why
ID in attachment table should be UUID? (https://github.com/apache/james-project/pull/2108/commits/19caaf72ff47904e2427b2a8f7fefb11221102f6)

## How
- An interface with a Factory for AttachmentId
- Current AttachmentId class be renamed as LegacyAttachmentId and used by Cassandra app, JPA, memory
- Have a new UuidBackedAttachmentId used in the Postgres app ?

**Comment by hungphan227** [comment]
```
public static AttachmentId random() {
        return new AttachmentId(RANDOM_STRING_GENERATOR.generate(20));
    } 
```
@chibenwa IMO 20 characters is not big. Is it necessary to use UUID?

**Comment by chibenwa** [comment]
It's not only a question of space but also of efficiency...
Let me have a look.

**Comment by chibenwa** [comment]
The biggest issue I faced when trying to "drop" the use of String in favor of UUID in existing code - namely CassandraMessageDAOV3.

**Comment by chibenwa** [comment]
Yet, I would still prefer a clean use of UUID please

**Comment by hungphan227** [comment]
pr for master branch https://github.com/apache/james-project/pull/2133

**Comment by hungphan227** [comment]
pr for postgresql branch https://github.com/apache/james-project/pull/2142

**Comment by hungphan227** [comment]
unbind AttachmentBlobResolver in master branch https://github.com/apache/james-project/pull/2150
