### ISSUE TITLE
[Postgres] Fix MailboxSetMethodContract

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#5133]
The change made here created issues in Memory and Distributed tests for MailboxSetMethodContract.webSocketShouldPushNewMessageWhenChangeSubscriptionOfMailbox https://github.com/apache/james-project/pull/2108/files#diff-ac1365541e08f69dc4e57ee445faa58e904eb86a908f3b76c359ace9b0aa376f

Need to fix it. A test should not be changed to satisfy a new implem at the detriment of others.

**Comment by Arsnael** [comment]
Have a look at `ModularizeJmapRFC8621AuthenticationStrategyContract` too, in local it breaks on my end on the postgresql branch

**Comment by vttranlina** [comment]
> Have a look at `ModularizeJmapRFC8621AuthenticationStrategyContract` too, in local it breaks on my end on the postgresql branch

It passed on my local
(I tried to run with mode "repeat to until failure")

![image](https://github.com/linagora/james-project/assets/81145350/0ea0f1d4-2f3f-46f3-9765-acd5cc994e27)

**Comment by Arsnael** [comment]
Possible my intellij went a bit crazy, I keep switching branches :)

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/2136
