### ISSUE TITLE
[BUILD] weave/rest-smtp-sink issue with deprecated Docker schema

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5138]
This is causing some tests to fail cf: https://ci-builds.apache.org/blue/organizations/jenkins/james%2FApacheJames/detail/PR-2149/7/tests/

Can reproduce locally after upgrading Docker to version 26.
https://docs.docker.com/engine/deprecated/#pushing-and-pulling-with-image-manifest-v2-schema-1

DoD: fix the issue (may need to refactor to another image...)

**Comment by Arsnael** [comment]
So if I understand we need to be able to maybe investigate if other images are concerned by this or not and move all of them to a more recent one using the new docker manifest version correct?

**Comment by quantranhong1999** [comment]
> So if I understand we need to be able to maybe investigate if other images are concerned by this or not and move all of them to a more recent one using the new docker manifest version correct?

Yes, so far we have only encountered the issue with the  `weave/rest-smtp-sink` image (9 years old).

I am trying to find a way to avoid refactoring to another image (that may need to change our test code with the new REST API...)

**Comment by Arsnael** [comment]
A quick way to unlock the build for now would be to add that environment variable `DOCKER_ENABLE_DEPRECATED_PULL_SCHEMA_1_IMAGE` when pulling that image. 

Of course we should still fix this problem asap as this env variable will be removed next docker version, which means getting this issue back soon enough

**Comment by quantranhong1999** [comment]
> A quick way to unlock the build for now would be to add that environment variable DOCKER_ENABLE_DEPRECATED_PULL_SCHEMA_1_IMAGE when pulling that image.

I tried but it does not work (via normal terminal session env set), likely it needs to be configured within the docker config file.

**Comment by Arsnael** [comment]
What about adding it as an environment var in the testcontainer docker builder of the fake smtp container?

**Comment by quantranhong1999** [comment]
> What about adding it as an environment var in the testcontainer docker builder of the fake smtp container?

Do you mean smth like this?
![image](https://github.com/linagora/james-project/assets/55171818/9457027a-3604-416a-aa5a-735009c46d6a)

Then it does not work.

But good news: likely I found a way.

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/2152

**Comment by chibenwa** [comment]
Cool, thanks a lot!
