### ISSUE TITLE
[Postgres] Create metrics for PostgresExecutor

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#5157]
## Why

PostgresExecutor is used to execute all postgresql queries. Metrics for this class is needed to test performance 

## How

Use MetricFactory in PostgresExecutor (metricFactory.decoratePublisherWithTimerMetric)

**Comment by chibenwa** [comment]
Lacks a description

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/2195
