### ISSUE TITLE
James should be able to point to multiple RabbitMQ nodes endpoints

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5162]
## Why
We are currently pointing to only 1 rabbitMQ service endpoint.

@chibenwa thinks it would be better to point the rabbitmq uri directly to e.g. list of 3 RabbitMQ nodes so the RabbitMQ driver can be better acknowledged about the cluster usage and recover quicker during the RabbitMQ node outage for example.

## How

Making the `uri` config in `rabbitmq.properties` support multiple URIs?

## DoD
Tested.

**Comment by quantranhong1999** [comment]
Jira ticket: https://issues.apache.org/jira/projects/JAMES/issues/JAMES-4031

**Comment by chibenwa** [comment]
I think one can already pass several hosts obto a single amqp uri if i am not mistken.

Please double check syntax.

Keep using ingress for rabbitmq mgt is fine

**Comment by quantranhong1999** [comment]
> I think one can already pass several hosts obto a single amqp uri if i am not mistken.

Yes, we should be good. I just added a few tests for sure.
https://github.com/apache/james-project/pull/2206
