### ISSUE TITLE
[PGSQL] Investigate ci error JamesWithNonCompatibleElasticSearchServerTest

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5165]
https://ci-builds.apache.org/blue/organizations/jenkins/james%2FApacheJames/detail/PR-2199/4/tests

jamesShouldStopWhenStartingWithANonCompatibleElasticSearchServer(GuiceJamesServer) – org.apache.james.JamesWithNonCompatibleElasticSearchServerTest
```
Expecting actual throwable to be an instance of:
  org.apache.james.StartUpChecksPerformer.StartUpChecksException
but was:
  org.opensearch.client.opensearch._types.OpenSearchException: Request failed: [mapper_parsing_exception] Failed to parse mapping [_routing]: Root mapping definition has unsupported parameters:  [required : true]
 at org.opensearch.client.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:270)
 at org.opensearch.client.transport.rest_client.RestClientTransport$1.onSuccess(RestClientTransport.java:163)
 at org.opensearch.client.RestClient$FailureTrackingResponseListener.onSuccess(RestClient.java:700)
 ...(17 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
```

- apache/master -> passed
- apache/postgresql -> failed (latest hash 4720ef72f6ad8571b85fc72b330c9b502e5e8b72)

//Because the PostgreSQL branch only ci runs on some special PostgreSQL modules -> we lack it

**Comment by Arsnael** [comment]
Did you reproduce that locally? I really dont see why you get an error like this, opensearch version and implementation should be the same in both branches

**Comment by vttranlina** [comment]
> Did you reproduce that locally? 

yes
I checked out master and PostgreSQL branch 
and 
apache/master -> passed
apache/postgresql -> failed

**Comment by vttranlina** [comment]
Cassandra-app is no longer deprecated
I think we can ignore it

**Comment by vttranlina** [comment]
> Cassandra-app is no longer deprecated I think we can ignore it

IMO don't need to take time for it
