### ISSUE TITLE
Redis: allow to read from Replicas

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5172]
## Prerequisites
Better wait for https://github.com/linagora/james-project/issues/5171 to configure master/replica read settings.

## Why
By default, Lettuce sends read requests to only master nodes cf https://github.com/redis/lettuce/wiki/ReadFrom-Settings.

Thus we can not leverage read scale using other Replica nodes.

IMO we do not need strong consistency for our Redis use cases (Rate limiting, potentially event bus notifications). We may leverage reading from the Replica nodes for better performance.

## How

Introduce in `redis.properties` smth like:
```java
read.from=MASTER/MASTER_PREFERRED/REPLICA/REPLICA_PREFERRED/LOWEST_LATENCY/ANY/ANY_REPLICA # Default to MASTER?. cf https://github.com/redis/lettuce/wiki/ReadFrom-Settings#read-from-settings
```

## DoD
Tested.

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/2240

**Comment by quantranhong1999** [comment]
Could you apply this to Tmail Redis event bus key too?

**Comment by hungphan227** [comment]
> Could you apply this to Tmail Redis event bus key too?

maybe another ticket?
