### ISSUE TITLE
JMAP - fault tolerance when Redis down

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5175]
## Why

When setting `event.bus.keys.choice=redis` in `queue.properties` file. 
If Redis is down,  the method  `Email/set + EmailSubmission/set` is waiting response for a long time

It is not good for the client
Ref https://github.com/linagora/tmail-backend/issues/1013

## How 
- Set the default timeout to 5 seconds. It can be configurable via `jmap.properties`
- Ignore the dispatch event via Redis in this failure time. 
- Re-lookup other methods that are similarly affected. 

## Dod
- Integration test 
- Document

**Comment by chibenwa** [comment]
> Ignore the dispatch event via Redis in this failure time.

I would like this to be configurable please

**Comment by quantranhong1999** [comment]
How about configuring it in the `redis.properties` or `queue.properties` something like `event.bus.keys.failure.ignore=true`? And ignore the error directly in the EventBus.

If we catch and handle the error in the higher layer e.g. JMAP for example, I think it is harder to track all places where we are calling the dispatch.

**Comment by vttranlina** [comment]
> I would like this to be configurable please

The default value is `yes`?

**Comment by chibenwa** [comment]
> event.bus.keys.failure.ignore=true

Yes precisely what I have in mind. IMO in `redis.properties`.

**Comment by chibenwa** [comment]
> The default value is yes?

Until we are really sure we want this by default, then keep false as a default value please.

**Comment by vttranlina** [comment]
pr https://github.com/linagora/tmail-backend/pull/1026

**Comment by quantranhong1999** [comment]
> > The default value is yes?
> 
> Until we are really sure we want this by default, then keep false as a default value please.

Hi guys,
Today the Rspamd VM (which has Redis of tmail.linagora.com) was down which caused JMAP to be almost unusable (downtime 30 minutes) with 504 Gateway Timeout error.

Maybe now is a good time to put `eventBus.redis.failure.ignore=true` by default?

**Comment by chibenwa** [comment]
> Maybe now is a good time to put eventBus.redis.failure.ignore=true by default?

Yes!

**Comment by chibenwa** [comment]
-> Updated for tmail.linagora.com
 
 And https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/merge_requests/94
 
 CNB is not using redis stuff
 
 Remains MU...

**Comment by chibenwa** [comment]
https://ci.linagora.com/linagora/lrs/saas/infrastructures/gov-mauritius/-/merge_requests/46

**Comment by quantranhong1999** [comment]
Great, thanks!
