### ISSUE TITLE
[Crash test] [RLS] [PGSQL] [OVH] handling many domains

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5177]
## What 

Tests on preprod, (scripting on top of webadmin) that we can host many tenenants (ie domains) on top of the current OVH infrastructure.

Do create 2000 domains with one user ease and one user in theire INBOX each. (fake the users repository if need be).

## The expected result...

Multi-tenant is currently enforces via a bucket

But OVH by default support 100 buckets in a project and could expend the count to 1.000 upon request

Thus, we expect this test to (sadly) fail

## The alternative

Find a way to encode the tenant (ie the domain) as part of the key, as a prefix.

IE

`linagora.com/{regularBlobId}`

We need to demonstrate that the resulting setup do still supports the GC algorithm.

cc @PatrickPereiraLinagora @ccartierlng

**Comment by Arsnael** [comment]
> Multi-tenant is currently enforces via a bucket

Happens that it's not the case for the moment, would need to wait for multi-tenancy work to be finished before being able to test that assumption

**Comment by chibenwa** [comment]
> Happens that it's not the case for the moment, 

Normal as apparently we did not yet implement s3 multitenancy based on buckets.

Imo we can clise this ticket.
