### ISSUE TITLE
Redis: James should work normally when redis cluster change

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#5181]
## Why

James should be able to adapt and work normally when redis cluster change. For example, if one node (master or slave) in redis cluster is down, James should be able to detect, adapt new cluster structure to work normally.

 ## How

Enable automatic topology update for redis client

## DoD

Tests for RedisRateLimiter and RedisHealthCheck

**Comment by hungphan227** [comment]
One issue I detected is that when one node in cluster is down, James would not be able to upload redis lua script

**Comment by vttranlina** [comment]
> One issue I detected is that when one node in cluster is down, James would not be able to upload redis lua script

My debug with lettuce code:
The method `.scriptLoad` was executed in all nodes of the cluster (both all master + slave)
Then one node down -> scriptLoad will fail

ref: https://github.com/redis/lettuce/issues/590
[io.lettuce.core.cluster.RedisAdvancedClusterAsyncCommandsImpl#scriptLoad](https://github.com/redis/lettuce/blob/8457a41a7596dc41829cbfcc4d54a0579bd7abba/src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterAsyncCommandsImpl.java#L445)
[io.lettuce.core.cluster.RedisAdvancedClusterAsyncCommandsImpl#executeOnNodes](https://github.com/redis/lettuce/blob/8457a41a7596dc41829cbfcc4d54a0579bd7abba/src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterAsyncCommandsImpl.java#L645)

**Comment by hungphan227** [comment]
I posted a question in stackoverflow

https://stackoverflow.com/questions/78475444/why-does-lecttuce-send-lua-script-load-command-to-all-nodes-including-replicas

**Comment by Arsnael** [comment]
I think it's better to open an issue on the lettuce backlog, asking their community directly?

**Comment by hungphan227** [comment]
https://github.com/redis/lettuce/issues/2853

**Comment by Arsnael** [comment]
Just a design decision regarding lettuce and redis. Honestly not a blocker, if it fails we just run without redis until it's back up.
