### ISSUE TITLE
RabbitMQ classic queue: apply recommend classic Queues v2

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5182]
## Why

Currently, for RabbitMQ <= 3.12, the default classic queue version is v1.

RabbitMQ claims the v2 to be better than v1:

```
In many use cases, switching to CQv2 will result in a 20-40% throughput improvement and lower memory usage at the same time.

Most users still use CQv1, but starting with 3.12 we highly recommend switching to, or at least evaluating, CQv2. Version 2 will become the default in 3.13 and will become the only implementation later on.
```
cf: 
- https://www.rabbitmq.com/blog/2023/05/17/rabbitmq-3.12-performance-improvements#classic-queues-massively-improved-classic-queues-v2-cqv2
- https://www.rabbitmq.com/docs/classic-queues#classic-queue-implementation-version-2

We should try to perf test the classic queue using v2. If the result is good, we should apply it.

## How

- Perf test using classic queue v2 on sandbox
- Either recommend the classic queue v2 usage in James docs, or enforce the queue argument `x-queue-version=2`

**Comment by chibenwa** [comment]
Noce findings.

Please do not forget to document inter-operability with previous James version if needed.

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/2243
