### ISSUE TITLE
[Antora] Migrate back James Distributed server doc to antora doc root folder

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#5186]
We should just have one location for Antora documentation. Makes it easier to manage but also to reuse some parts of the doc that are similar between different versions of James.

In master branch:

- [x] migrate back distributed doc of Antora (in  `server/apps/distributed-app/docs`) to root docs folder
- [x] make sure the distributed part of the doc is still rendered after merge in https://james.staged.apache.org

After the merge on master has been done:

- [ ] rebase postgresql branch on master, to be able to work on the postgres new documentation afterwards and the refactoring work necessary to not have duplicate parts of documentation with distributed.

**Comment by Arsnael** [comment]
Migration PR: https://github.com/apache/james-project/pull/2287

James-site migration: https://github.com/apache/james-site/pull/48

**Comment by vttranlina** [comment]
rebase postgresql branch on master -> Will do it in task https://github.com/linagora/james-project/issues/5214

**Comment by Arsnael** [comment]
Thanks for taking a shot at this :)

**Comment by Arsnael** [comment]
=> Website update with distributed section back in root doc : https://james.staged.apache.org/james-project/3.8.1/servers/distributed/index.html

**Comment by Arsnael** [comment]
The rebase will be done in https://github.com/linagora/james-project/issues/5214
