### ISSUE TITLE
[Antora] [PGSQL] Objectives and motivation page for postgres doc

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#5188]
Similar to the distributed page: https://james.staged.apache.org/james-distributed-app/3.8.1/objectives.html but oriented for Postgresql James Server

**Comment by vttranlina** [comment]
Q: the antora doc for postgres should be located in 
`james-project/docs` 
or `james-project/server/apps/postgres-app` ?

**Comment by Arsnael** [comment]
Root folder james-project/docs

The point of migrating the distributed doc back to the root folder was to be able to use a lot of common pieces of doc with distributed as partials, and not having duplicate parts

**Comment by vttranlina** [comment]
I'm facing some issues with the user interface of Antora (or our bug?)

After the pr https://github.com/linagora/james-project/issues/5186 was merged
When I go to https://james.staged.apache.org/
The panel is 
![Screenshot_20240626_091915](https://github.com/linagora/james-project/assets/81145350/b47ec1ac-bc6b-46b7-9dca-25c847368409)
When I clicked to `3.8.1 SNAPSHOT`
Then:
![image](https://github.com/linagora/james-project/assets/81145350/8398ca04-5e43-4311-a5c6-3d0e843108be)

the "Distributed James Application" section is not visible.

However, when I directly visit the URL https://james.staged.apache.org/james-distributed-app/3.8.1/objectives.htm 
 
I can see the section displayed.

![image](https://github.com/linagora/james-project/assets/81145350/78cb25e1-d504-4d81-b2e6-92f8d1d10810)

**Comment by Arsnael** [comment]
In servers section, with the other distribution. I guarantee you it's visible =>  https://james.staged.apache.org/james-project/3.8.1/servers/distributed/index.html

**Comment by vttranlina** [comment]
> In servers section, with the other distribution. I guarantee you it's visible => https://james.staged.apache.org/james-project/3.8.1/servers/distributed/index.html

What is difference between:
https://james.staged.apache.org/james-project/3.8.1/servers/distributed/index.html
and 
https://james.staged.apache.org/james-distributed-app/3.8.1/

**Comment by Arsnael** [comment]
Not sure why https://james.staged.apache.org/james-distributed-app/3.8.1/ is still accessible. Or I missed something in james-website, or this section didn't get cleaned up when being redeployed

IMO not a blocker for now

**Comment by vttranlina** [comment]
> or this section didn't get cleaned up when being redeployed

right, I tried to build `james-site` locally, and the path `**/james-distributed-app/**` is not available

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/2316
