### ISSUE TITLE
[Antora] [PGSQL] Architecture section for postgres doc

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#5189]
Same structure as distributed doc: https://james.staged.apache.org/james-distributed-app/3.8.1/architecture/index.html

For this, you will need to refactor the distributed doc as well, as some parts can be shared with postgres doc.

* Architecture page: Storage is pg specific I think (slightly different) but other sections can be partial with distributed

  * Implemented standards => partials
  * Consistency model => Opensearch and RabbitMQ consistency model can be partials
  * Specialized instances => partials 

Some pages between distributed and postgres docs can be very similar, with the only difference being the server appellation `Distributed James Server` versus `Postgresql James Server`. For this, could use attributes in partials => https://docs.antora.org/antora/latest/page/page-attributes/#custom-attribute

Could setup default attributes in partials to be the ones from distributed, and only overriding them for postgres doc.

Make sure as well that distributed doc is still the same after refactoring.

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/2335
