### ISSUE TITLE
[Antora] [PGSQL] Add Configuration section to postgresql doc

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#5191]
Add the Configuration section to the postgresql doc, similar to distributed here: https://james.staged.apache.org/james-distributed-app/3.8.1/configure/index.html

Refactor the distributed configuration section with the followings:

* Configuration => links are different, but rest same. partials with attributes?

  * Protocols => partials
  * Storage dependencies:
   => blobstore.properties => except cassandra parts, can partial the rest
   => opensearch, rabbitmq, redis, tika.properties => partials
  * Core components => partials
  * Extensions => partials

Make sure the distributed doc is still the same after refactoring.

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/2320

**Comment by vttranlina** [comment]
updated pr: https://github.com/apache/james-project/pull/2324
