### ISSUE TITLE
[Antora] [PGSQL] Add Operate section to postgresql doc

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#5192]
Add the Operate section to the postgresql doc, similar to distributed here: https://james.staged.apache.org/james-distributed-app/3.8.1/operate/index.html

Refactor the distributed Operate section with the followings:

   + Operator guide => can partial except `Solving cassandra inconsistencies`, `Setting Cassandra user permissions`, `Cassandra table level configuration` and `Updating Cassandra schema version` sections
   + Performance checklist => can partial except `Database setup` and `Cassandra` section
   + Logging => partials
   + webadmin => partials except some cassandra specific sections and be careful of healthcheck too, some components differ
   + Metrics => partials
   + Migrating existing data => partials
   + Command Line Interface => partials
   + Security checklist => partials

Of course the cassandra sections in distributed doc should be replaced by postgres exclusive doc for pg doc.

Make sure the distributed doc is still the same after refactoring.

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/2326
