### ISSUE TITLE
[Antora] [PGSQL] Add Extending server behavior section to postgresql doc

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#5193]
Add the Extending server behavior  section to the postgresql doc, similar to distributed here: https://james.staged.apache.org/james-distributed-app/3.8.1/extending/index.html

Refactor the distributed Extending server behavior section. The all section is likely good for partials.

Make sure the distributed doc is still the same after refactoring.

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/2334
