### ISSUE TITLE
[Antora] [PGSQL] Add Performance benchmarks section to postgresql doc

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#5194]
Add the Performance benchmarks section to the postgresql doc, similar to distributed here: https://james.staged.apache.org/james-distributed-app/3.8.1/benchmark/index.html

* Performance benchmark => partials

  * Database benchmarks => need to be pg specific
  * James benchmark => partials

Of course the cassandra sections in distributed doc should be replaced by postgres exclusive doc for pg doc.

Make sure the distributed doc is still the same after refactoring.

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/2336
