### ISSUE TITLE
[PGSQL] Rebase postgresql branch on master

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5214]
We should stay on track with master branch (after alot of update dependencies/lib)
And for Antora document epic

**Comment by vttranlina** [comment]
The pr green
https://github.com/apache/james-project/pull/2322
 (but test only postgres modules)
We can consider force push it to `postgres` branch.

Here is my step when do it (branch `[vttran/rebasePostgresQuickTest](vttranlina:rebasePostgresQuickTest)` ) :
- Checkout last commit in current `postgres` branch (commit: `3f274e85e8 JAMES-2586 Change boolean rlsEnabled to enum RowLevelSecurity` )
- Then rebase latest `master` & resolve conflict 
- Add new commit for fix compile & test
```
5ec09d1c80 (HEAD rebasePostgresQuickTest) Disable test: JamesWithNonCompatibleElasticSearchServerTest
2716fd6af5 JAMES-2586 Fixup PostgresPushSubscriptionSetMethodTest - add ClockMQExtension
51b02bc180 [ENHANCEMENT] Better reactify Identity methods - update for Postgres
595c316d56 JAMES-2586 Fix BlobStoreConfigurationTest
36b70fe6dc JAMES-2586 Fix sequential issue with updating flags in the reactive pipeline - Update: disabled for cassandra weakWrite
ce74fd618c JAMES-2586 [PGSQL] Fix checkstyle & adapt code after rebase master
```

**Comment by Arsnael** [comment]
Reviewed. Even if I think some commits are not purely postgres related, I'm still in favor.

+1

**Comment by vttranlina** [comment]
The CI tests passed successfully across all modules. 
Link: https://github.com/apache/james-project/pull/2312 
This boosts our confidence in the code.

**Comment by Arsnael** [comment]
I did just push the rebase on postgresql based on other PR work though :) Don't hesitate making a PR with the extra commits then
