### ISSUE TITLE
[MU] SMIMECheckSignature integration tests and evolution

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5228]
## What

Write integration tests for SMIMECheckSignature within `server/mailet/integration-testing/src/test/java/org/apache/james/mailets/crypto`

Also I would like to get for each email processed the signature status as a header:

```
X-SMIME-Status: Good signature
X-SMIME-Status: Bad signature
X-SMIME-Status: Not signed
```

Adding the `X-SMIME-Status` would likely require code modifications within `SMIMECheckSignature`.

## Why

MU governement asks for signature display in the webmail.

**Comment by chibenwa** [comment]
CF https://github.com/linagora/tmail-flutter/issues/3023

**Comment by chibenwa** [comment]
CF https://ci.linagora.com/linagora/lgs/twp/mail-gov-mauritius/-/issues/30

**Comment by chibenwa** [comment]
Dont forget to push a draft PR before the weekend nheee

**Comment by hungphan227** [comment]
draft pr https://github.com/apache/james-project/pull/2366
