### ISSUE TITLE
[MU] Configure SMimeCheckSignature with PEM files

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5237]
# Why?

Working with Java keystores is hard, badly documented and the forma is generally not ubiquitous.

Using PEM files is more classic in the Linux world, more readable and more tooling exists.

# How?

Add a factory method in KeyStoreHolder to build it from PEM files and adapt SMimeCheckSignature accordingly.

I shall be able to load the identity materials with `PemUtils` CF LegacyJavaEncryptionFactory and then create a correct keystore around that CF `KeystoreCreator`

**Comment by hungphan227** [comment]
draft pr https://github.com/apache/james-project/pull/2372
