### ISSUE TITLE
X-SMIME-Status header should always be removed as part of email chain

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#5239]
cf https://github.com/linagora/tmail-flutter/issues/3023#issuecomment-2268594567 and rest of the ticket for context

In mailetcontainer.xml remove the `X-SMIME-Status` header as part of the email processing chain in all our deployments.

Document it as well.

**Comment by quantranhong1999** [comment]
Or can we add an option in `SMIMECheckSignature` mailet to strip the `X-SMIME-Status` header before processing (verify and add the header again)? Maybe it is simpler than modifying the conf everywhere.

**Comment by Arsnael** [comment]
No I think @chibenwa wants to take it out of the mail processing even the mailet is not present, to avoid tampering with the front, cf flutter ticket. Cause if the front detects there is this header present in the mail, it would show a status for smime. However if we don't do smime verification in the back it's meaningless

**Comment by chibenwa** [comment]
Leaving the header means security issue, yes

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/2371

**Comment by quantranhong1999** [comment]
we still need to adapt to customer env values IMO

**Comment by chibenwa** [comment]
Yes and tmaik back defaukt conf and lany other places

**Comment by quantranhong1999** [comment]
> Yes and tmaik back defaukt conf and lany other places

Any update on this @hungphan227 ?

**Comment by hungphan227** [comment]
> > Yes and tmaik back defaukt conf and lany other places
> 
> Any update on this [@hungphan227](https://github.com/hungphan227) ?

https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/emaily-staging-apps/-/merge_requests/46

**Comment by chibenwa** [comment]
And all the other places (tmail back, lng prod, twp prod & staging, cnb prod & staging)

**Comment by Arsnael** [comment]
He does not have access to most of those though. Will take a look when I have time for less priority tasks like this.

**Comment by Arsnael** [comment]
* sandbox: https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/sandbox-emaily-apps/-/merge_requests/22
* postgres rls and non-rls: https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/postgresql-staging/-/merge_requests/9/diffs
* tmail-backend: https://github.com/linagora/tmail-backend/pull/1160
* tmail-backend postgresql branch: https://github.com/linagora/tmail-backend/pull/1161
* apache james postgresql branch: https://github.com/apache/james-project/pull/2382
* cnb staging : https://ci.linagora.com/linagora/lrs/saas/deployments/cnb/cnb-stg-apps/-/merge_requests/76
* cnb prod: https://ci.linagora.com/linagora/lrs/saas/deployments/cnb/cnb-prd-apps/-/merge_requests/100
* tmail-backend chart 5.0 release: https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/merge_requests/64

Deployed and running on:
- tenant-upn
- sandbox
- postgres-rls and non-rls
- LNG prod

The mailetcontainer.xml file for TWP deployments (staging and prod) is taken from the tmail-backend chart 5.0 release template directly, thus the change above.

I let ops (cc @ducnm0711 ) helping on reviewing, merging and redeploying those changes for cnb staging and prod and twp staging and prod

**Comment by chibenwa** [comment]
Thanks for this patient and exhaustive job!

**Comment by Arsnael** [comment]
Missed MU: https://ci.linagora.com/linagora/lrs/saas/infrastructures/gov-mauritius/-/merge_requests/12/diffs
