### ISSUE TITLE
[MU] SMIMECheckSignature could not handle signed mail with Content-Type: application/x-pkcs7-mime

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#5240]
Currently SMIMECheckSignature could not handle signed mail with Content-Type: application/x-pkcs7-mime; smime-type=signed-data;
It does not recognized the mail as a signed mail. Fix this.

**Comment by chibenwa** [comment]
Apparently thats a legacy mime type...

Support should be still achivable.

https://forums.oracle.com/ords/apexds/post/application-x-pkcs7-mime-with-bouncy-castle-9957

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/2374
