### ISSUE TITLE
SMIME verify: use Filesystem to load crypto materials

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5242]
## Why?

 - filesystem shall be used when loading file ressources - this offers a consistent API
 - Enforces access controls on files (IE within james root)
 - Brings features like reading conf, classpath...

## What 

Use `Filesystem` class to load files in `SMIMECheckSignature` fallback to current method in case of error.

CF DKIMSign

**Comment by Arsnael** [comment]
The team is not fully grasping why this is needed, even after reading the why section. Can you help detailing a bit mroe on that part @chibenwa ?

**Comment by chibenwa** [comment]
In james filesystem in the entity to read files on the disk especially fir configuration. We need to be consistant.
This alone is a valid reason.
Pleasecomply.

**Comment by chibenwa** [comment]
(I won t rewrite word by word what is written above: consistent api for the sysadmin, central access tu filesystem, etc)

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/2388
