### ISSUE TITLE
[PROD] [CUSTOMER] Have several health checks in one rest calls

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5244]
# Why ?

K8S allows only a single liveness probe

But as an admin I would like to combine several healthchecks (IMAP checks, Cassandra checks) behind a liveness probe which today cannot be achieved.

# How?

Be able to pass an optional query parameter to `/healtchcheck` specifying which checks to execute

curl 127.0.0.1:8000/healthcheck?checks=RabbitMQJmapEventBusDeadLetterQueueHealthCheck+OpenSearch%20Backend

Would execute and aggregate only those 2 checks

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/2399

**Comment by vttranlina** [comment]
> curl 127.0.0.1:8000/healthcheck?checks=RabbitMQJmapEventBusDeadLetterQueueHealthCheck+OpenSearch%20Backend

I think we can use a standard of http request
when `check` is a array
the syntax should be
`check=RabbitMQJmapEventBusDeadLetterQueueHealthCheck&check=OpenSearch%20Backend`

**Comment by chibenwa** [comment]
> I think we can use a standard of http request

Indeed!
