### ISSUE TITLE
JAMES-4050  % * in mailbox names

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5247]
https://issues.apache.org/jira/projects/JAMES/issues/JAMES-4050

`*` and `%` in mailbox names get a special meaning in IMAP as they are used as wildcards in IMAP LIST commands.

RFC-3501 do mention side effects of this (extra results might be present in LIST replies for those mailboxes as wildcard WILL be extended) but apparently do not prohibit them.

WHile migrating users from OpenExchange, I did encouter several failures for mailboxe names with those very characters.

I deduce from this that ASF James interpretation of % and * being forbidden in mailbox names is likely too strict and might benefit from being relaxed.

I propose to remove the check by default but propose a JVM option to re-enable it if need be. We would need to add IMAP LIST tests for this.

**Comment by Arsnael** [comment]
+ document the jvm option

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/2391

**Comment by chibenwa** [comment]
Please PR this for existing deployments: 

 - [x] CNB cf https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/tree/release/4.0.0-cnb
   => https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/merge_requests/71

 - [x] TWP prod and staging + team staging env cf https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/tree/release/5.0
   => https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/merge_requests/72

 - [x] Just in case https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/tree/main
   => https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/merge_requests/73

 - [x] MU deployment
   => https://ci.linagora.com/linagora/lrs/saas/infrastructures/gov-mauritius/-/merge_requests/19 (added to MU deployment too)

- [x] Make the option default for TMail apps (distributed, memory, postgres)
  - [x] https://github.com/linagora/tmail-backend/pull/1173
  - [x] https://github.com/linagora/tmail-backend/pull/1174
 - [X] LNG deployment

**Comment by Arsnael** [comment]
Maybe let's try to have an intermediary tag for hotfix on tmail-backend dockerhub?

**Comment by quantranhong1999** [comment]
> Maybe let's try to have an intermediary tag for hotfix on tmail-backend dockerhub?

Tagged 0.10.4-rc1 with the fix.
[0.10.4-rc1](https://github.com/linagora/tmail-backend/releases/tag/0.10.4-rc1)

**Comment by Arsnael** [comment]
Ah with the rc actually good thinking, we can go gradually up until final release :)

**Comment by Arsnael** [comment]
Are we good to close this?

**Comment by quantranhong1999** [comment]
> Are we good to close this?

Yes we can.
