### ISSUE TITLE
Healthcheck: have a query param to return 503 code if degraded

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5249]
## Why

k8s consider a pod not healthy when receiving the response code >= 400.

James healthcheck response code:

```
200: All checks have answered with a Healthy or Degraded status. James services can still be used.
503: At least one check have answered with a Unhealthy status
```

`degraded` with 200 code won't trigger k8s pod restart.

We should have an option to restart the k8s pod when `degraded` performance e.g. [IMAP healthcheck](https://github.com/linagora/james-project/issues/5245).

## How

We could add a flag as a query parameter to consider degraded as failed. EG

`GET 127.0.0.1:8000/healthcheck/checks/ImapCheck?strict`

Would return 503 response code if unhealthy and degraded

While

`GET 127.0.0.1:8000/healthcheck/checks/ImapCheck`

Would return 503 when unhealthy and 200 for degraded.

We would need to implement `GET 127.0.0.1:8000/healthcheck?strict` too.

cf https://github.com/linagora/james-project/issues/5245#issuecomment-2301254550

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/2404
