### ISSUE TITLE
[SearchSnippet] SearchSnippet/get method

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#5254]
Implement a new JMAP method as defined in https://jmap.io/spec-mail.html#search-snippets

Add a SearchSnippet object as defined per the RFC and implement the SearchSnippetGetMethod, that is similar to EmailQueryMethod, except that it would call the search with the highlight instead of normal search function.

Notes: Change in SearchSnippet internal jmap doc Not implemented to Implemented

DoD: Integration tests

**Comment by vttranlina** [comment]
I understand this ticket is implemented according to the jmap spec, but I have a related concern.


The **SearchSnippet** object has only property:
- emailId
- subject
- preview

I think it is not enough for FE, 
Now, the request body when we "Search email" (tmail-web):

single jmap request:
- "Email/query" : for get id
- "Email/get"  (backReference query): for get property:   "id", "blobId", "subject", "from", "to", "cc", "bcc",
                    "keywords", "size", "receivedAt", "sentAt", "preview",
                    "hasAttachment", "replyTo", "mailboxIds",
                    "header:X-MEETING-UID:asText"

If the frontend uses `SearchSnippet/get`, the `subject` and `preview` will be retrieved from `SearchSnippet/get`, while the other property will be obtained from `Email/get.`

Is it no problem?

CC: @hoangdat

**Comment by Arsnael** [comment]
I get the concern but I don't think we should go out bonds of the RFC spec either.

Not all properties that the front is using for email/get during a search is being shown on the screen btw, that could probably be optimized

**Comment by quantranhong1999** [comment]
Notes: Change in SearchSnippet internal jmap doc Not implemented to Implemented

**Comment by hoangdat** [comment]
Hi, from my understanding, FE can combine
```
Email/query
Email/get
SearchSnippet/get
```
And combine the response of get and searchsnippet to show to FE. No problem.

**Comment by chibenwa** [comment]
The preview in SearchSnipet is not the preview of the message (as in email/get), but a subset of the relevant part of the body.

Overall agrees.

**Comment by dab246** [comment]
> Hi, from my understanding, FE can combine
> 
> ```
> Email/query
> Email/get
> SearchSnippet/get
> ```
> 
> And combine the response of get and searchsnippet to show to FE. No problem.

IMO, It will take us more time to combine it. Is there a better solution? I see `SearchSnippet/get` is taking a list of email ids `emailIds`. So does its response return the list of results in the order of the email ids passed in?

**Comment by Arsnael** [comment]
> IMO, It will take us more time to combine it. Is there a better solution? I see `SearchSnippet/get` is taking a list of email ids `emailIds`. So does its response return the list of results in the order of the email ids passed in?

The RFC says that it might not be responded in the same order as given in the request, I am unsure how complex it would be but I guess we could try?

**Comment by chibenwa** [comment]
> The RFC says that it might not be responded in the same order as given in the request, I am unsure how complex it would be but I guess we could try?

Like between email/query + email/get. Front should ensure the odering displayed is the one of email/query

**Comment by vttranlina** [comment]
WIP https://github.com/apache/james-project/pull/2442

**Comment by vttranlina** [comment]
I forgot this ticket isn't a priority in this sprint, so I'll pause it for now.

**Comment by vttranlina** [comment]
Split tasks

- https://github.com/linagora/james-project/issues/5305
- https://github.com/linagora/james-project/issues/5306

And this ticket will focus on implement SearchSnippet/get  for distributed
