### ISSUE TITLE
Redis: support SSL connection

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5266]
We should support SSL connection mode for Redis.

cf https://github.com/redis/lettuce/wiki/SSL-Connections

**Comment by chibenwa** [comment]
With an option disabled by default to trust all SSH certs...

**Comment by chibenwa** [comment]
Please detail configuration changes required.

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/2418
