### ISSUE TITLE
Safer X-User

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5267]
## Why?

As of today, James relies on Apisix for OIDC enforcement and propagates the calls to james, identifying the user through the mean of `X-User` header.

This means that any access to the JMAP port onto James means full compromission (integrity and confidentiallity) of the underlying data.

While of course an attacker shall not breach onto a private network, having a seat-belt for this definitly can save the day! 

Having a shared secret to prove identity of the caller could achieve this (caller would need either man-in-the-middle / compromise either APisix or James which would anyway in itself compromise the email data). 

Such a shared secret would greatly reduce the attack surface...

## How?

Have a configurable shared secret for X-User in jmap.properties:

```
authentication.strategy.rfc8621.xUser.secret=abcdefghijkl
```

If configured, XUserAuthenticationSStrategy would enforce the incoming request to have the following header:

```
X-User-Secret: abcdefghijkl
```

And reject non compliant request with 401

We would need to modify our Apisix plugin to add the shared secret optionnally there too.

If omitted all requests are accepted (today behaviour)

## Dod

 - [x] James code modified
 - [x] Apisix code plugin modified
 - [ ] imap.linagora.com updated
 - [ ] CNB updated
 - [ ] Twake workplace updated
 - [x] MU updated

**Comment by chibenwa** [comment]
Safer version: have the secret being a JWT with as a scope the user and an expiration.

James would only need public key. Apisix shall hold the privateKey.

Costs is a bit higher as James shall verify the signature.

We could keep that as a possible enhancement?

**Comment by quantranhong1999** [comment]
I propose a new `XUserWithSecretAuthenticationStrategy` to avoid breaking changes.

**Comment by chibenwa** [comment]
> I propose a new XUserWithSecretAuthenticationStrategy to avoid breaking changes.

+1 good idea.

And @Deprecate the older one...

**Comment by chibenwa** [comment]
(Moved in Todo as I really want this....)

**Comment by vttranlina** [comment]
- [x] James code modified + Apisix code plugin modified : https://github.com/apache/james-project/pull/2450/files
- [x] MU updated: https://ci.linagora.com/linagora/lrs/saas/infrastructures/gov-mauritius/-/merge_requests/45/diffs
- [x] Apisix helm chart pr: https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-apisix/-/merge_requests/9/diffs
- [x] Tmail helm chart pr: https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/merge_requests/92

**Comment by chibenwa** [comment]
Remark from GCS sara: we shall make the shared secret a list.

2 reasons: 
 - Allow 1 secret per application (thus revoking access per app)
 - easier secret rotation
 
 We can implement this as a coma separated list.
 
 @vttranlina can you give it a shot?

**Comment by chibenwa** [comment]
(Thus back in todo collumn)

**Comment by Arsnael** [comment]
How about a new task for having this as an evolution instead?

**Comment by vttranlina** [comment]
I don't fully understand it, could you provide more details?

Just support x-user-secret as a list and use `.contains` for that list?

**Comment by Arsnael** [comment]
> Just support x-user-secret as a list and use .contains for that list?

pretty much yes

**Comment by Arsnael** [comment]
=> cf task https://github.com/linagora/james-project/issues/5299

**Comment by vttranlina** [comment]
Deployed on MU server
