### ISSUE TITLE
[S3 SSEC] S3 multitenancy: ssec chaos testing

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#5280]
Do some micro benchmarks regarding key derivation algorithm.

Try first with the initial algorithm, and try others? go wild!

- domain
- domain + blobId
- blobId
- ..?

DoD: benchmarks done determining the best algorithm in terms of perf / security

**Comment by chibenwa** [comment]
I'll be discussing key derivation best practices with @guimard this week...

**Comment by Arsnael** [comment]
Could do that before ssec key derivation implem actually...

Shall we do proper perf tests on sandbox with implementations?

**Comment by chibenwa** [comment]
No let's not waste time let's go with:

 - one master key for all
 - one master key + domain + a cache.
 
 I'd close this ticket IMO...
