### ISSUE TITLE
Support redis-sentinel with auth password 

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5284]
## Why?
Currently, when using Redis Sentinel, we only support password authentication for master-replica nodes. This is done by specifying the master password in the Redis URL, such as:
eg: 
`redisURL=redis-sentinel://masterSecret1@redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379?sentinelMasterId=mymaster`

In this example, `masterSecret1` is the password for the master node, not the Sentinel nodes.

In case we want to more security,  Redis itself supports password authentication for Sentinel nodes as described here:
https://redis.io/docs/latest/operate/oss_and_stack/management/sentinel/#sentinel-and-redis-authentication

But the Lettuce Redis library does not support configuring the Sentinel password via the Redis URL. This issue is tracked here:
 https://github.com/redis/lettuce/issues/1232

To enable password authentication for Sentinel nodes, we need to adapt the James codebase to support this functionality.

## How?
- Add a new configuration property in redis.properties. Eg: `redis.sentinel.password`
- Refactor james code, with init RedisURI looks like:

```java
RedisURI redisURI = RedisURI.create("redis-sentinel://password@localhost:26379/0#mymaster");
redisURI.getSentinels().forEach(it -> it.setPassword("my-sentinel-password"));
```

**Comment by chibenwa** [comment]
Can we please suggest configuration changes for such a proposal?

**Comment by vttranlina** [comment]
> Can we please suggest configuration changes for such a proposal?

- in [redis conf file ](https://github.com/apache/james-project/blob/542a99339ba375be28309e4e26a00f467a88e228/server/mailet/rate-limiter-redis/docker-compose-sample/config-template/sentinel/sentinel.conf.template)
Add new line
`requirepass ${SentinelPass}`
It is similar for all sentinel node

-  In [jamess redis.properties](https://github.com/apache/james-project/blob/542a99339ba375be28309e4e26a00f467a88e228/server/mailet/rate-limiter-redis/docker-compose-sample/redis.properties) 
add new line `redis.sentinel.password= ${SentinelPass}`

**Comment by vttranlina** [comment]
pr: https://github.com/apache/james-project/pull/2420
