### ISSUE TITLE
SMTP XOAUTH2 support continuation

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5288]
## Why?

XOATH2 fails with curl when using `CURLOPT_XOAUTH2_BEARER`

## The Spec

curl submit the token in a second call

```
[connection begins]
C: auth xoauth2                                                         
S: 334
C: dXNl...                                                                
S: 235 2.7.0 Authentication successful
```

## Definition of done

 - [x] Unit tests in SMTP test suite
 - [x] Fix backported to customer code base
 - [ ] Build and ship a new release to the customer

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/2428

**Comment by chibenwa** [comment]
https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/customers/james-gcs-sara/-/merge_requests/16

**Comment by chibenwa** [comment]
Waiting an OSSA ticket before doing the release for GCS

**Comment by Arsnael** [comment]
As I saw in my mails, it seems this has been delivered to the customer already.

@chibenwa Can we merge the PR and close this ticket then?

**Comment by chibenwa** [comment]
Yes!
