### ISSUE TITLE
 JAMES-3945 IMAP & JMAP right management for sub addressing

### ISSUE THREAD

**Issue by florentos17** [linagora/james-project#5289]
refs:
- [wikipédia for Sub-addressing](https://en.wikipedia.org/wiki/Email_address#Sub-addressing)
- [RFC5233 for subaddress extension](https://rfc-editor.org/rfc/rfc5233)
- [the jira ticket](https://issues.apache.org/jira/browse/JAMES-3945)

the first part of the work is done, now subaddressing works on the backend side, CF [the first github issue](https://github.com/linagora/james-project/issues/4884) and [the associated PR](https://github.com/apache/james-project/pull/2405)

right positioning using IMAP, eg setting the `p` right for a specific folder for either no one or anyone, is also done, CF [this PR](https://github.com/apache/james-project/pull/2419)

**remains to be done: right positioning using JMAP**. speaking to @chibenwa, we agreed to wait for front-end support before carrying on with that.

**Comment by tddang-linagora** [comment]
>we agreed to wait for front-end support before carrying on with that.

@chibenwa In what aspect do you need front end support, so that an back end feature can be implemented after? Isn't it the other way around?

**Comment by chibenwa** [comment]
> @chibenwa In what aspect do you need front end support, so that an back end feature can be implemented after? Isn't it the other way around?

Indeed there's a misunderstanding here.

I wish the backend do not deliver features that never gets exposed by the frontend but indeed adding backend support would be a prerequisite to frontend support.
