### ISSUE TITLE
[MU] Allow use of custom schema for LDAP mailet / matcher

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5292]
Given attibute with value

`cn=active,ou=twakeAccountStatus,ou=nomenclature,o=gov,c=mu`

Only match the cn

so here `active`

**Comment by chibenwa** [comment]
(Emergency...)

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/2434

**Comment by chibenwa** [comment]
Thsanks a lot Quan!
