### ISSUE TITLE
[Tika] add a circuit breaker configuration for attachments that take too long to be extracted

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#5294]
Some attachments can take too long for tika to extract the content from (some mroe than 10 minutes for example).

We need to implement a circuit breaker mechanism to allow dropping the extraction of attachments that are too slow to process. A default value of 15s shall be defined.

When the circuit breaker kicks in we should log content type and file extension of the slow attachment.

 Extra conf on tika.properties could look like this:

- `tika.circuit.breaker.enabed` => true or false, defaults to true?
- `tika.circuit.breaker.timeout` =>  the timeout before the circuit breaker kicks in, defaults to 15s

DoD: Unit and integration tests

**Comment by quantranhong1999** [comment]
Maybe only `tika.circuit.breaker.timeout` would be more simple. 
If none specified => disable circuit breaker.
If specified => enable with timeout.

**Comment by Arsnael** [comment]
Isn't it more of a timeout btw? A circuit breaker is more about closing the connection if there is too many failures in cascade, until the component recovers.

Here we just want to cut the connection of a request if it takes longer than 15s => timeout?

**Comment by chibenwa** [comment]
`tika.read.timeout.ms` for the configured property.

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/2437
