### ISSUE TITLE
[MU] Ability to list inactive users

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5298]
## Why ?

As an administrator I wish to list inactive users of my email service.

We can distinguish two kind of inactive users:

 - User never logged in but receives emails
 - User never logged in and never received email
 
 ## How ?
 
 We could easily determine the status of users by looking at their mailbox list:
 
  - If the user has no mailbox, then the user is fully inactive
  - If the user has only an INBOX, then the user never logged in but receives emails
  
 ## What ?

We can easily add filters in the `/users` webadmin endpoint to support this.

```
curl -XGET /users?hasNoMailboxes
curl -XGET /users?hasNotAllSystemMailboxes
```

----------

Ideally it could be great to allow easily add further users filters by defining a little extension for it:

(for one I can see more crazier ideas of filters potentially on extensions... for 2 I do not like a hard dependencies onto mailbox component from the users route. all this call for additional indirection.)

```
// foreach user indicate if if shall be included in the respose
interface UserFilter extends Function<Username, Publisher<Boolean>>  
class HasNoMailboxesUserFilter implements UserFilter { ... } 
class HasNotAllSystemMailboxesUserFilter implements UserFilter { ... }
```

And inject a map into usersroutes.

Finally` MailboxesRoutesModule` can declare the injections for those (mailbox related) filters:

```
MapBinder<String, UserFilter> mapBinder = MapBinder.newMapBinder(binder(), String.class, UserFilter.class);
mapBinder.addBinding("hasNoMailboxes").to(HasNoMailboxesUserFilter.class);
mapBinder.addBinding("hasNotAllSystemMailboxes").to(HasNotAllSystemMailboxesUserFilter.class);
```

This extension would be available only for people using james as a toolkit (guice overides / combines). User defined userFilter loading is for now out of scope.

## Definition of done

 - [ ] Documented (docs/modules/servers/partials/operate/webadmin.adoc + src/site/markdown/server/manage-webadmin.md)
 - [ ] Tested server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/UserRoutesTest.java

**Comment by hungphan227** [comment]
pr https://github.com/apache/james-project/pull/2474
