### ISSUE TITLE
Metrics for websocket

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5301]
- Count of connections?
 - request per minutes?
 
 See reactor-netty metrics if any as well
 
 ## Definition of done
 
 Graphs are added to the linagora.com JMAP board on https://grafana.lin-saas.com/d/bdsxdmschfvuob/jmap?orgId=1

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/2479

> See reactor-netty metrics if any as well

Mostly [HTTP metrics](https://projectreactor.io/docs/netty/1.1.19/reference/index.html#_metrics_4), no related WebSocket metric.

**Comment by chibenwa** [comment]
I'd be happy if we could expose in a Gauge:

 - jmap.reactor.netty.http.server.connections.active
 - jmap.reactor.netty.http.server.connections.total
 - jmap.reactor.netty.http.server.data.received
 - jmap.reactor.netty.http.server.data.sent

It would be valuable debug informations...

**Comment by quantranhong1999** [comment]
> It would be valuable debug informations...

https://github.com/apache/james-project/pull/2483

**Comment by quantranhong1999** [comment]
> Definition of done
Graphs are added to the linagora.com JMAP board on https://grafana.lin-saas.com/d/bdsxdmschfvuob/jmap?orgId=1

The code has not been released yet so I propose we add a note e.g. in https://github.com/linagora/james-project-private/issues/894 to quickly add the Grafana graphs later.

**Comment by Arsnael** [comment]
I think you can still add the boards now?

Not gonna show anything until the release but when we do release it should kick in. At least we sure of not forgetting it later?

**Comment by quantranhong1999** [comment]
> I think you can still add the boards now?

I tried but there are no Prometheus metrics to add to the Grafana graph yet. Please correct me if I am wrong.

**Comment by Arsnael** [comment]
You are correct, fair enough :)
