### ISSUE TITLE
James + grafana: choose host drop down menu on grafana

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5302]
On the TMail board, for per-host graphs

I have a drop down menu allowing to choose the host

**Comment by Arsnael** [comment]
With the help of Duc, the metrics have been put back up.

Reason was OVH did a force upgrade of the cluster 2 days ago, which messed up with some of the pods managing metrics

**Comment by Arsnael** [comment]
I set up a quick example here to understand how to do it https://grafana.lin-saas.com/d/edsxe5hxrpzpcd/backend?orgId=1&var-host=openpaas-tmail

But for linagora.com it's not really relevant as we only have one tmail container anyways running.

I guess the goal is more for CNB and MU gov? And TWP?

**Comment by chibenwa** [comment]
> I guess the goal is more for CNB and MU gov? And TWP?

Yes!
