### ISSUE TITLE
SPOOL queue poisonning

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5304]
# WHat

Create a bad payload and post it to the spool mail queue directly via rabbit

![image](https://github.com/user-attachments/assets/1d455435-4d84-46f6-9216-cdecfb73ad19)

Then it would trigger an exception:

![image](https://github.com/user-attachments/assets/7e294eb9-d2ef-479e-8fed-a66f800bcfb9)

The message is then unhandled and unacked

Until the timeout is reach to which point customers dies

![image](https://github.com/user-attachments/assets/702b9492-f4f4-4c6a-bc1c-4229aa37d839)

unacked message are put back to the queue and delivered again

And message get delivered in loop

![image](https://github.com/user-attachments/assets/1f56b357-0395-481e-9cfa-45a3b1e694f4)

# solution

Upon error JamesMailSpooler should nack(REJECT) the mail queue item.

**Comment by Arsnael** [comment]
=> https://github.com/apache/james-project/pull/2463
