### ISSUE TITLE
[MU] Mailet to mail to all users

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5307]
# Why?

One customer want a mail alias for writing to everybody hosted on the platform (information on the mail service)

# Example...

```
<mailet matcher="RecipientIs=all@govmu.org" class="MailToAllUsers" >
    <batchSize>100</batchSize>
</mailet>
```

Will replace existing recipients with all users (usersrepositroy.listUsers) as recipient of the email.

This can be contributed into `server-mailets`

# Performance notes

Note that this can cause significant processing as APPENDING emails for one recipient can be a longish operation. Adding a batchSize parameter can be a good idea:

 - We treat the first batch of recipients directly says first 100
 - Then uses mailetcontext().send(...) to send to all remaining recipients, by groups of 100
 
 That way we may prevent emails with excessive recipient count and also paralelize the delivery
 
 # Needed when
 
 ASAP for the code. Deployment with next release is ok.
 
 # Definition of done
 
  - [x] James ticket 
  - [x] PR with unit tests

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/2469

**Comment by Arsnael** [comment]
Can't just be a group ML with all users part of it? Or they just don't want to bother maintaining such a group list?
