### ISSUE TITLE
remove logback jackson from james

### ISSUE THREAD

**Issue by florentos17** [linagora/james-project#5309]
# What ?
remove `logback-jackson` usages from james project apps

# Why ?
because:
- it is unmaintained
- not activated by default
- alternative: mount the jar files into `/root/libs` folder of james
- logging in JSON is a LINAGORA specific operational choice.

**Comment by chibenwa** [comment]
Please link a JIRA ticket on ASF James bug tracker

**Comment by florentos17** [comment]
[here it is](https://issues.apache.org/jira/browse/JAMES-4083)
