### ISSUE TITLE
[PGSQL]  update postgresql branch to the latest master

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5310]
We should stay on track with master branch.

The latest we did it is `Jun 25` https://github.com/linagora/james-project/issues/5214

## How?
- My candidate: https://github.com/vttranlina/james-project/tree/postgresqlRebaseMaster
- The CI tests passed successfully across all modules.: https://github.com/apache/james-project/pull/2467
- Checkout current `postgresql` to `postgresql_backup` branch 
- checkout `vttranlina::postgresqlRebaseMaster` , drop commit CI test (https://github.com/apache/james-project/pull/2467/commits/50f8b1ddf1d344f811b2785a6dd3af9af6d43f8d), and checkout to `postgresql`

**Comment by Arsnael** [comment]
Pushed the work to postgresql branch. Did a preliminary backup on postgresql-backup branch

Let's monitor the build => https://ci-builds.apache.org/job/james/job/ApacheJames/job/postgresql/158/

**Comment by vttranlina** [comment]
Green
