### ISSUE TITLE
[CNB] Mailet for folding long lines

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5311]
# Why?

Some email clients (Outlook!) can generate some arbitrary long lines. For instance a loooong discussions with many `References` can have a `References` line exceeding 1000 characters.

```
References: <CAOU6bwKrkZbpUxbnz88UofkXyyBv9Y8cdPwyHXTpD9R-_UEMhg@mail.gmail.com> <PR0P264MB335651D4B1A9A2A24AFAB535D28C2@PR0P264MB3356.FRAP264.PROD.OUTLOOK.COM>
 <PR0P264MB33563D04B559EC154855E36AD28B2@PR0P264MB3356.FRAP264.PROD.OUTLOOK.COM> <MWHPR0801MB36911622D86EA054D329D81FE78B2@MWHPR0801MB3691.namprd08.prod.outlook.com> <SN4PR0801MB3696195E7746201412671F71E7972@SN4PR0801MB3696.namprd08.prod.outlook.com> <PR0P264MB3356634284CAB379147BC77AD2972@PR0P264MB3356.FRAP264.PROD.OUTLOOK.COM> <SN4PR0801MB369668222A6726E917EB5761E7922@SN4PR0801MB3696.namprd08.prod.outlook.com> <PR0P264MB3356362A5FC890D0E53567F5D2922@PR0P264MB3356.FRAP264.PROD.OUTLOOK.COM> <PR0P264MB33563B96B1CC3774F1BF23FBD2932@PR0P264MB3356.FRAP264.PROD.OUTLOOK.COM> <SN4PR0801MB36961E26D369149C13C84E2AE79B2@SN4PR0801MB3696.namprd08.prod.outlook.com> <CYXPR08MB90174A13CF388A1E7EB48D0DF99B2@CYXPR08MB9017.namprd08.prod.outlook.com> <PA4PR07MB7101C5F735ACD27149593A1C89602@PA4PR07MB7101.eurprd07.prod.outlook.com> <CYXPR08MB90173
 4D5BD04714BD6A
		04551F9602@CYXPR08MB9017.namprd08.prod.outlook.com> <PA4PR07MB710195E419888BBE1988427989612@PA4PR07MB7101.eurprd07.prod.outlook.com>  <042d01db09ec$beedd0f0$3cc972d0$@avocat.fr>
```

The issue is that RFC5322 mandates not exceeding 999 characters per lines so postfix is configured by default to fold such long lines!

```
Oct 24 18:43:53 cnb-mail-01 postfix/smtp[308449]: 13B9740A61: breaking line > 998 bytes with <CR><LF>SPACE
```

We do protect the references header as per our DKIM signing:

```
DKIM-Signature: a=rsa-sha256; b=wRnnh7MWRU2Rly2nVeoKaao+UOlG87Cs0MRD614YE3TokZsaGVqMZQVYgqWQ+9XzBqzF0tp7Zt+907TEBSTIHAcShikJuiv0Sl5fjrgzpaJrkPtYe51MmPfkSY6USXmdOsdXhZBhVdBJ5M+r4LaZL0LYYKJZVn1re4khGsalvXo=; s=s2; d=avocat.fr; v=1; bh=2AjlhSVg7EzuioM7CZqg3hz0OtP3/dOlGrqo3PYe9eg=; h=from : reply-to : subject : date : to : cc : resent-date : resent-from : resent-sender : resent-to : resent-cc : in-reply-to : references : list-id : list-help : list-unsubscribe : list-subscribe : list-post : list-owner : list-archive;
```

And doing such folding **after** the signature indeed breaks the DKIM signature.

Some domains do not interprete well our `p=quarantine` policy and just reject the mails:

```
Diagnostic-Code: smtp; 550 5.7.0 Email quarantined per DMARC policy
```

Thus we would need to fold headers correctly prior to forwarding the mails to Postfix.

# How?

Write a `FoldLongLines` mailet defaulting to 998 chars (like postfix)

It would fold headers that exceed this length.

# Definition of done

 - [ ] Unit tests. 
 - [ ] Documentation
 - [ ] JIRA ticket

# Priority

This is a hight priority topic that shall be included i the next twake mail release.

**Comment by hungphan227** [comment]
The meaning of "Folding" is moving the exceeded part to the next line like this:

To: alice@domain,
 cedric@domain

Is that correct?

**Comment by quantranhong1999** [comment]
> The meaning of "Folding" is moving the exceeded part to the next line like this

I understand the same way.

**Comment by hungphan227** [comment]
If anyone knows lib that support "folding", let me know.

**Comment by hungphan227** [comment]
fould potential one https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/WordUtils.html

**Comment by chibenwa** [comment]
> If anyone knows lib that support "folding", let me know.

mime4j ?

**Comment by hungphan227** [comment]
the only thing I found in mime4j is this:

![Image](https://github.com/user-attachments/assets/baf2b764-e10e-4c02-8923-47e316e6bfdc)

But it seems not fit the requirement

**Comment by Arsnael** [comment]
I think it does?

**Comment by hungphan227** [comment]
The limit of Mime4j is 76. Should we set the limit to 76 instead of 998?

**Comment by chibenwa** [comment]
Or we could modify mime4j to add an extra line length parameter.

We will not be the only ones with such a need...

**Comment by hungphan227** [comment]
@Arsnael could you give me permission to create PR in mime4j repo?

**Comment by chibenwa** [comment]
> @Arsnael could you give me permission to create PR in mime4j repo?

Explained live: needs to FORK!

**Comment by hungphan227** [comment]
Mime4J PR https://github.com/apache/james-mime4j/pull/110

**Comment by hungphan227** [comment]
Probably I have to wait for the new release of mime4j before continuing on james

**Comment by chibenwa** [comment]
> Probably I have to wait for the new release of mime4j before continuing on james

Duplicate temporarily mime4j code so that we do not have to wait, with a TODO in the code.

**Comment by hungphan227** [comment]
PR https://github.com/apache/james-project/pull/2490
