### ISSUE TITLE
JMAP right management for subaddressing

### ISSUE THREAD

**Issue by florentos17** [linagora/james-project#5312]
# Why
in the context of subaddressing, which now works on the backend side, we need to implement right management to be able to set the `p` (`posting`) right for the identifier `anyone` on a specific mailbox, and thus allow subaddressing on that mailbox. this is already possible with IMAP.

# What 
we would now want to implement such right management using JMAP: need to add a new `p` right, and implement tests with the identifier `anyone`

refs:
- [wikipédia for Sub-addressing](https://en.wikipedia.org/wiki/Email_address#Sub-addressing)
- [the corresponding linagora ticket](https://github.com/linagora/james-project/issues/5289)
- [the jira ticket for subaddressing in james](https://issues.apache.org/jira/browse/JAMES-3945)

**Comment by florentos17** [comment]
my bad, i wanted to open a new apache/james issue, not a linagora/james one...

**Comment by quantranhong1999** [comment]
<img width="330" alt="image" src="https://github.com/user-attachments/assets/95afc6cd-6353-4ab3-802a-4d77a6aeb63b">

You can use `Transfer issue` at the bottom right corner.
