### ISSUE TITLE
Investigate why ID command makes newer outlook versions fail

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5313]
## Why?

As a user I cannot login onto newer versions of Outlook

![image](https://github.com/user-attachments/assets/f925fd85-75dd-4bae-8183-83f1e88443dc)

It turns out a korean server scans our server (`CAPABILITY` + `ID`)

![image](https://github.com/user-attachments/assets/da0131f7-222c-4b35-abd7-2712c0e26fc9)

I see no client interactions coming from @dieptran88 

## The quickfix

Displabling the `ID` command seems to fix the issue.

```
<imapservers>
	<imapserver enabled="true">
	        <!-- ... -->
                <disabledCaps>ID</disabledCaps>
        </imapserver>
</imapservers>
```

 - [x] imap.linagora.com
 - [ ] WIP CNB staging
 - [ ] CNB prod (with @PatrickPereiraLinagora go)
 - [x] MU

## The long term fix

I suspect our syntax upon ID command might not be valid. Eg shall we return always an untagged ID response?

I wishes @vttranlina attempts to try several alternative syntaxes for the ID command on preprod and if need be on imap.linagora.com to see if we just do not return a valid answer for the ID command and it does actually crash the connection....

![image](https://github.com/user-attachments/assets/32dae316-68f0-404e-93f7-b46beb627c19)

This is a high priority topic. Please @vttranlina and @dieptran88 pair on the topic tomorrow at the office.

**Comment by vttranlina** [comment]
>  ![image](https://github.com/user-attachments/assets/726e8306-6e45-49b1-b144-7ba49585be53)

Can you give link this document?


- I tested the ID command via telnet, but the response did not match the example in the picture.
not sure it is a reason or not.

```

a1 ID ("name" "MyMailClient" "version" "1.0" "vendor" "MyCompany" "support-url" "https://support.microsoft.com/outlook")
* ID ()
a1 OK ID completed.
```

- Microsoft has two apps named "Outlook": Outlook (classic) functions well, while Outlook (new) has issues.
![image](https://github.com/user-attachments/assets/18cfcf53-3daa-4c18-b3ad-1e69c18eabe4)
When I use `Outlook (new)` and set debug breakpoints at `ImapProcessor#processReactive`, there are no requests to the tmail server.... So can't verify which IMAP command issue

**Comment by quantranhong1999** [comment]
> When I use Outlook (new) and set debug breakpoints at ImapProcessor#processReactive, there are no requests to the tmail server.... So can't verify which IMAP command issue

Maybe you can try Wireshark to see how Outlook called the IMAP commands?

**Comment by vttranlina** [comment]
> > When I use Outlook (new) and set debug breakpoints at ImapProcessor#processReactive, there are no requests to the tmail server.... So can't verify which IMAP command issue
> 
> Maybe you can try Wireshark to see how Outlook called the IMAP commands?

I just tried, but there was no "TCP" request to the James server. (that yes with Outlook (classic version))

I feel/guess it query somewhere on public (internet) before handshake directly to Local james server.

**Comment by Arsnael** [comment]
> I feel/guess it query somewhere on public (internet) before handshake directly to Local james server.

The korean server then I would guess?

**Comment by chibenwa** [comment]
Can we blindly try

```
a1 ID ("name" "MyMailClient" "version" "1.0" "vendor" "MyCompany" "support-url" "https://support.microsoft.com/outlook")
* ID (PUT THINGS HERE)
a1 OK ID completed.
```

?

**Comment by Arsnael** [comment]
I honestly think it's more on Microsoft side.

https://support.microsoft.com/en-us/office/getting-started-with-the-new-outlook-for-windows-656bb8d9-5a60-49b2-a98b-ba7822bc7627

Table of supported features, new outlook for 3rd party accounts support gets Yes***... The `***` being => `With limited capabilities`

https://techcommunity.microsoft.com/t5/microsoft-365-insider-blog/starting-to-support-third-party-accounts-in-new-outlook-for/ba-p/4219307

=> originally published in april 2024... quote:

`The initial release of this preview only supported first-party accounts from Microsoft, whether they be work, school, or personal. But Outlook is for everyone, whatever accounts they use - just like on our mobile and Mac apps. Today, we will begin to roll out support for Gmail accounts to those using the preview of the new Outlook for Windows. Soon, we will also add support for Yahoo and iCloud, as well as the ability to connect your mailbox through IMAP. It’s our intention that every person be able to access all of their emails – in one spot – on any Windows 10 or Windows 11 device.`

Maybe they just don't support "yet" 3rd party accounts from self hosted mail servers like ours? 

I read that forum post in diagonal as well https://answers.microsoft.com/en-us/outlook_com/forum/all/imap-support-for-new-outlook-for-windows/469fd2ef-9d44-42f3-800c-dda6d69e3c9c?page=4 but seems other people complain that their 3rd party imap account does not seem to work with the new outlook.

**Comment by vttranlina** [comment]
I tested `Microsoft Outlook` on MacOS, it works well 
I tend to think "Outlook (new)" is unstable.

I see Benoit tick "fixed" at `imap.linagora.com` environment. 
Both me and @dieptran88 login success, but it has another issue. Inbox is empty 
That was reported https://answers.microsoft.com/en-us/outlook_com/forum/all/outlook-new-does-not-display-new-mails/3f6f136f-aa1a-4cac-bcea-d9654659216a

**Comment by quantranhong1999** [comment]
> I feel/guess it query somewhere on public (internet) before handshake directly to Local james server.
The korean server then I would guess?

It seems that the server is a kind of MS service discovery server placed in Korea:

<img width="849" alt="image" src="https://github.com/user-attachments/assets/4270721b-f57d-4924-a10c-c56e51d14dad">

**Comment by chibenwa** [comment]
Can we just test the full untagged ID reply and see how it behaves? Please?

**Comment by vttranlina** [comment]
PR to modify the ID Command extension to support return response fields: https://github.com/apache/james-project/pull/2478.

I can't debug the `Outlook (new)` locally, so I'm unsure if this PR will resolve the issue. This email client requires SMTPS, making it impossible to test on preprod/sandbox.

**Comment by chibenwa** [comment]
> PR to modify the ID Command extension to support return response fields: https://github.com/apache/james-project/pull/2478.

Do you confirm this improves Microsoft Outlook behaviour?

**Comment by Arsnael** [comment]
> PR to modify the ID Command extension to support return response fields: [apache#2478](https://github.com/apache/james-project/pull/2478).
> 
> I can't debug the `Outlook (new)` locally, so I'm unsure if this PR will resolve the issue. This email client requires SMTPS, making it impossible to test on preprod/sandbox.

I just built up an image based on 0.11.0 tag and cherry-picked your commits on your PR and also @chibenwa commits on https://github.com/apache/james-project/pull/2475

` rcordier/tmail-backend:distributed-id-imap-cmd`

Deployed it on linagora.com, with the proper config. Now when I connect with openssl to imap.linagora.com:

```
* OK JAMES IMAP4rev1 Server 11ece749db11 is ready.
a1 ID ("name" "MyMailClient" "version" "1.0" "vendor" "MyCompany" "support-url" "https://support.microsoft.com/outlook")
* ID ("name" "Twake Mail" "version" "0.11.0" "vendor" "Linagora" "support-url" "https://linagora.com/en/our-contacts")
a1 OK ID completed.
```

Can we try again with new outlook to see?

**Comment by chibenwa** [comment]
> Can we try again with new outlook to see?

Ask @dieptran88 !

**Comment by quantranhong1999** [comment]
I can use Outlook new to login and access my mails now

![Image](https://github.com/user-attachments/assets/5e6273b3-1ee2-4811-b56d-f7a6850dcca2)

**Comment by vttranlina** [comment]
The issue is resolved; await deployment in another ticket.
