### ISSUE TITLE
[CNB] Invalid EHLO argument received: [IPV6:2a01:cb06:b841:bf5d:38ff:861a:1646:ab77]

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5317]
In SmtpServerTest, 

```
    @Test
    public void test() throws Exception {
        smtpConfiguration.setAuthorizedAddresses("128.0.0.1/8");
        smtpConfiguration.setAuthorizingAnnounce();
        init(smtpConfiguration);

        SMTPClient smtpProtocol = new SMTPClient();
        InetSocketAddress bindedAddress = testSystem.getBindedAddress();
        smtpProtocol.connect(bindedAddress.getAddress().getHostAddress(), bindedAddress.getPort());

        smtpProtocol.sendCommand("ehlo", "[IPV6:2a01:cb06:b841:bf5d:38ff:861a:1646:ab77]");
        assertThat(smtpProtocol.getReplyString()).contains("250");
    }
```

fails...

Please fix it...

(spotted on custoer production, prevent mail delivery)

**Comment by chibenwa** [comment]
Also did get `"Invalid EHLO argument received: cabinet-maitre-.domain. Must be a domain name or an IP address."`

Understand what's going on? Remove trailing `.` ?

**Comment by quantranhong1999** [comment]
> Also did get "Invalid EHLO argument received: cabinet-maitre-.domain. Must be a domain name or an IP address."
Understand what's going on? Remove trailing . ?

Actually, it was `EHLO cabinet-maitre-.domain`.

It seems not a valid hostname as `-` should not be the start or end characters:
<img width="1163" alt="image" src="https://github.com/user-attachments/assets/e583f4ad-0d46-462f-94ba-76b9f7b4c60c">

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/2492
