### ISSUE TITLE
IDLE: what to do when no mailbox is selected?

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5321]
![image](https://github.com/user-attachments/assets/a260e3e6-9be4-483e-b92c-bf468d9f8009)

Returning BAD is for instance something done by DOVECOT

-> Confirm this behaviour with another 3rd party mail server...

-> Confirm this do NOT break outlook....

And add a little test about it within ImapServerTest...

**Comment by vttranlina** [comment]
> Confirm this behaviour with another 3rd party mail server...

I tried to use terminal to connection to Gmail IMAP server

![image](https://github.com/user-attachments/assets/cd1c1859-0402-42b3-9b53-f2858baf0721)
It did not declined `IDLE` command when not selected mailbox. 
But it doesn't respond to the client when there is a new event (new message, create new mailbox)

// I failed with verify with fastmail/outlook imap mail server. (Can't not AUTHENTICATE PLAIN success with my account, don't know why, tried to enable IMAP, try to use App Password ...vv)

> Confirm this do NOT break outlook

I tried to use Outlook Classic to debug my Tmail server, 
It sent IDLE command after SELECT mailbox.  (No any case Authenticated state)
Here is logs Command steps:
```
process: LoginRequest{userid=Username{localPart=minister, domainPart=Optional[Domain : domain.tld]}}
process: AbstractImapRequest{tag=A1064, command=CAPABILITY}
process: ListRequest{baseReferenceName=, mailboxPattern=*, selectOptions=[], returnOptions=[], statusDataItem=null}
process: SelectRequest{mailboxName=INBOX, condstore=false, lastKnownUidValidity=UidValidity{UNKNOWN}, knownModSeq=null, uidSet=null, knownUidSet=null, knownSequenceSet=null}
process: FetchRequest{useUids=false, idSet=[IdRange ( 1->1 )], fetch=FetchData{items=[UID], setSeen=false, bodyElements=[], changedSince=-1, vanished=false}}
process: FetchRequest{useUids=true, idSet=[IdRange ( 1->1 )], fetch=FetchData{items=[UID, INTERNAL_DATE, SIZE, BODY_STRUCTURE], setSeen=false, bodyElements=[], changedSince=-1, vanished=false}}
process: SelectRequest{mailboxName=INBOX, condstore=false, lastKnownUidValidity=UidValidity{UNKNOWN}, knownModSeq=null, uidSet=null, knownUidSet=null, knownSequenceSet=null}
process: FetchRequest{useUids=true, idSet=[IdRange ( 1->1 )], fetch=FetchData{items=[FLAGS, UID, INTERNAL_DATE, SIZE, ENVELOPE, BODY_STRUCTURE], setSeen=false, bodyElements=[BodyFetchElement{name=BODY[HEADER.FIELDS (REFERENCES THREAD-TOPIC FROM SENDER REPLY-TO AUTO-SUBMITTED BOUNCES-TO LIST-ARCHIVE LIST-HELP LIST-ID LIST-OWNER LIST-POST LIST-SUBSCRIBE LIST-UNSUBSCRIBE PRECEDENCE RESENT-FROM RETURN-PATH)], sectionType=HEADER_FIELDS, fieldNames=[REFERENCES, THREAD-TOPIC, FROM, SENDER, REPLY-TO, AUTO-SUBMITTED, BOUNCES-TO, LIST-ARCHIVE, LIST-HELP, LIST-ID, LIST-OWNER, LIST-POST, LIST-SUBSCRIBE, LIST-UNSUBSCRIBE, PRECEDENCE, RESENT-FROM, RETURN-PATH]}, BodyFetchElement{name=BODY[TEXT], sectionType=TEXT}], changedSince=-1, vanished=false}}
process: SelectRequest{mailboxName=INBOX, condstore=false, lastKnownUidValidity=UidValidity{UNKNOWN}, knownModSeq=null, uidSet=null, knownUidSet=null, knownSequenceSet=null}
process: AbstractImapRequest{tag=i1101, command=IDLE}
```

Maybe this issue come from Outlook (New) version, 

-> Should we do the same with that we done with ID/PARTIAL (build custom image, and observe it in prod)? Or another idea to confirm it?

**Comment by vttranlina** [comment]
> Returning BAD is for instance something done by DOVECOT

Just change 
`ImapCommand IDLE_COMMAND = ImapCommand.authenticatedStateCommand("IDLE");`
to 
`ImapCommand IDLE_COMMAND = ImapCommand.selectedStateCommand("IDLE");`
https://github.com/apache/james-project/blob/master/protocols/imap/src/main/java/org/apache/james/imap/api/ImapConstants.java#L189

Then new response will be:
```
* OK JAMES IMAP4rev1 Server MacBook-Pro.local is ready.
a1 login minister@domain.tld secret
a1 OK LOGIN completed.
A2 IDLE
A2 NO IDLE failed. Command not valid in this state.
```

**Comment by chibenwa** [comment]
No as stated in https://github.com/linagora/james-project/issues/5320 we can keep the current behaviour but should simply test it in `ImapServerTest`

**Comment by vttranlina** [comment]
Pr to add test in ImapServerTest
https://github.com/apache/james-project/pull/2498
