### ISSUE TITLE
IMAP LIST does not return correct mailbox when mailboxName has namespace pattern

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5328]
While debugging James IMAP with Thunderbird, I noticed that it attempted to send the LIST command to James after the NAMESPACE command. The command looks like this:
`LIST (SUBSCRIBED) "" "#user.*" RETURN (SPECIAL-USE)`

It always returns an empty mailbox list, differing from the command's result: 
`LIST (SUBSCRIBED) "#user" "*" RETURN (SPECIAL-USE)` 

RFC related https://datatracker.ietf.org/doc/html/rfc3501#section-6.3.8
```
An empty ("" string) reference name argument indicates that the
      mailbox name is interpreted as by SELECT.  
```

How to resolve it?
Update logic of [PathConverter::mailboxQuery](https://github.com/apache/james-project/blob/master/protocols/imap/src/main/java/org/apache/james/imap/main/PathConverter.java#L171)

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/2506

**Comment by vttranlina** [comment]
> [apache#2506](https://github.com/apache/james-project/pull/2506)

I tried to manually test that pr, but it does not work as expected.

![image](https://github.com/user-attachments/assets/7afb3b00-e9f2-4014-9286-b746421279f6)

Am I missing something?

**Comment by chibenwa** [comment]
Nope Likely it's buggy.
