### ISSUE TITLE
[JOOQ] Fix pagination issue with jooq driver

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#5329]
The pagination bug identified on the reactor pipeline with JOOQ, adding the need to use `.collectList() + flatMapIterables()` for workaround it isn't clean and needs to be addressed before being able to propose to the community the merge of Postgresql branch into master.

Investigate and find a way either:
- avoiding the bug (without the current workaround)
- fixing the bug in JOOQ's code

**Comment by vttranlina** [comment]
The hanging issue is not only come of jooq,
But also come from r2dbc-postgresql 
https://github.com/pgjdbc/r2dbc-postgresql/issues/650

**Comment by chibenwa** [comment]
Still the case with code you pasted?

Maybe we could retry with R2DBC latest vrsion,
Screenshot test behaviour,
And ping r2dbc on the above ticket to tell them it is still happening with those evidences.

**Comment by vttranlina** [comment]
> Still the case with code you pasted?

yes

> Maybe we could retry with R2DBC latest vrsion,

I attempted the latest r2dbc-postgresql version, but it still failed. I have also updated the status in the r2dbc-postgresql issue repository.
