### ISSUE TITLE
[Postgres] Implement PostgresMailboxCounterCorrector

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#5333]

**Comment by chibenwa** [comment]
![image](https://github.com/user-attachments/assets/28ea2f78-6add-46e5-bf34-ab36a62f3e57)

:-1: that 

PG implem do not use a projection like cassandra but queries the source of truth.

As such it won't ever be outdated.

We just need to plug the default corrector in the guice bindings, that will be ok.
