### ISSUE TITLE
[MU] Can't recompute current quota

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5339]
Quota recompute was needed CF https://github.com/Yash18-hub/CISD-GES/issues/38

but failed

```
# curl 127.0.0.1:8000/users | jq .
{
  "statusCode": 400,
  "type": "InvalidArgument",
  "message": "Invalid arguments supplied in the user request",
  "details": "Domain parts ASCII chars must be a-z A-Z 0-9 - or _"
}
```

(similar error happens when fixin quota)

Expectations: filter out invalid users within ReadOnlyLdapUsersRepository

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/2518
