### ISSUE TITLE
[PGSQL] Postgres app performance test 

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5342]
performance test pr: 
- https://github.com/apache/james-project/pull/2514

Docker image:
tungtv202/tmail-backend-postgresql:20241125

**Comment by vttranlina** [comment]
@Arsnael 
Look like long time we don't touch to postgres testing server, 
Now the app can't start, because queue specification for `postgres` vhost incorrect with new code. 
For case Tmail require `quorum`, but queue exists is `classic` what should I do?
 remove `postgres` vhost and recreate them is ok? or remove queue by queue

**Comment by Arsnael** [comment]
It's a testing env and also been off for a moment you can safely remove the postgres vhost and recreate it, then tmail will recreate the queues

**Comment by vttranlina** [comment]
postgresql-staging update config pr:
- https://ci.linagora.com/linagora/lrs/saas/deployments/tmail/postgresql-staging/-/merge_requests/11/diffs

Test result: https://github.com/apache/james-project/pull/2514#issuecomment-2499627018

**Comment by vttranlina** [comment]
For the Jooq pagination issue, I believe the performance test with IMAP is enough. 
If JMAP is necessary, please let me know. 

// Currently, we cannot perform testing with JMAP due to a WebSocket handshake error in James Gatling. I'm investigate it
The error is same with 
- https://github.com/linagora/james-project/issues/5341
