### ISSUE TITLE
[PGSQL] Optimize when query `thread` table with `hash_mime_message_id` 

### ISSUE THREAD

**Issue by vttranlina** [linagora/james-project#5345]
The performance test reveals that the query on the `thread` table is take time:
```sql
select
  thread_id,
  hash_base_subject
from thread
where (
  username = $1
  and hash_mime_message_id in (
    $2, $3
  )
)
```
![image](https://github.com/user-attachments/assets/04a2b8ed-88f6-47ad-865d-4e3ed51583f1)

Detail: https://github.com/vttranlina/vttranlina.github.io/blob/main/gatling_20241126/before/pg_stat_statements_before.csv

It seems that `DSL.primaryKey(USERNAME, HASH_MIME_MESSAGE_ID, MESSAGE_ID)` is not effective for the `PostgresThreadDAO#findThreads` method. I suggest creating an additional index for `hash_mime_message_id` and verifying its impact.

**Comment by vttranlina** [comment]
pr https://github.com/apache/james-project/pull/2528

**Comment by chibenwa** [comment]
Reopened: I want to clearly see benefits on several metrics, not just the ones that arranges you.

**Comment by vttranlina** [comment]
> Reopened: I want to clearly see benefits on several metrics, not just the ones that arranges you.

Which metrics we need to focus?
- `postgres_execution` is metrics for all query when gatling. Not only for `thread` table -> It don't make sense

IMO, The `pg_stat_statement` is the suitable for this case.

**Comment by chibenwa** [comment]
You can't merge something with a twice worst mean time! It's non sense.

**Comment by chibenwa** [comment]
-> You'd need to explain the variation to me and you'd have to prove it is unrelated to your change.
 -> Ideally performing a new measurement not showing that discrepency would be better.

**Comment by vttranlina** [comment]
ok, I will re-run the gatling test before/after

**Comment by chibenwa** [comment]
And look at other metrics like S3 runs...

**Comment by vttranlina** [comment]
> You can't merge something with a twice worst mean time! It's non sense.

I'm not sure where you got "mean time." If it’s from Gatling, ignore this comment. 
However, if it's from `pg_stat_statements`, a decrease in `mean_exec_time` from `2.1` to `1.4` is an improvement.

**Comment by chibenwa** [comment]
Gatling.

**Comment by vttranlina** [comment]
reverted code 
https://github.com/apache/james-project/pull/2537
