### ISSUE TITLE
[MU] Limit count of recipients per mail.

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5348]
Screwed: I missed a piece of code for JMAP

https://github.com/apache/james-project/pull/2529

Will deploy it as an external JAR the time it get merged upstream.

**Comment by chibenwa** [comment]
Deployed on MU

**Comment by Arsnael** [comment]
> Deployed on MU

No PR on https://ci.linagora.com/linagora/lrs/saas/infrastructures/gov-mauritius to keep track of that change?

**Comment by vttranlina** [comment]
> Screwed: I missed a piece of code for JMAP

You mean we also need to validate the recipient size in the `EmailCreationRequest` at the `EmailSet` method, right?

**Comment by chibenwa** [comment]
No we already have a SMTP hook for this.

We missed a piece of code for bouncing in IMAP

(async feedback for this edge case is enough - let's keep it simple.)
