### ISSUE TITLE
[GCS] INBOX deletion should be forbidden

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5349]
CF RFC-3501

```
It is an error to attempt to delete INBOX or a
      mailbox name that does not exist.
```

Test this and ensures this is the case (MPT tests for IMAP)

Ensure this to in JMAP.

```
      Renaming INBOX is permitted, and has special behavior.  It moves
      all messages in INBOX to a new mailbox with the given name,
      leaving INBOX empty.  If the server implementation supports
      inferior hierarchical names of INBOX, these are unaffected by a
      rename of INBOX.
```

Also ensure this is tested. (MPT test)

Those behaviours shall also be true in JMAP.

**Comment by Arsnael** [comment]
GCS really? I see nothing related to that topic in the last mails

**Comment by chibenwa** [comment]
Cause you are not on smartsla

**Comment by hungphan227** [comment]
Currently deleting INBOX is possible in IMAP
James PR for forbiding INBOX deletion: https://github.com/apache/james-project/pull/2541

Renaming INBOX is currently forbidded. Will create another pr to update

**Comment by chibenwa** [comment]
Ok. Do not forget JMAP in your tests!

**Comment by hungphan227** [comment]
> Ok. Do not forget JMAP in your tests!

Regarding delete, we already have destroyShouldNotRemoveSystemMailboxes in MailboxSetMethodContract

**Comment by hungphan227** [comment]
I have one concern about renaming INBOX: Usually INBOX contains a lot of messages. I guess it would take a long time to move all msg from INBOX to another. Therefore, renaming INBOX would require users, clients to **wait for a very long time** until it complete --> affect user experience very badly

**Comment by hungphan227** [comment]
More precisely, currently IMAP support renaming INBOX but JMAP does not.

The way IMAP does renaming INBOX is renaming INBOX to the new name first and then create an empty INBOX which is a risky way in @Arsnael 's opinion.

**Comment by chibenwa** [comment]
> The way IMAP does renaming INBOX is renaming INBOX to the new name first and then create an empty INBOX which is a risky way in @Arsnael 's opinion.

From an IMAP point of view this sounds OK

We *could* be trying to see how Tmail frontend reacts to this. (cache...) and open a ticket if needed?

**Comment by hungphan227** [comment]
PR for rename inbox: https://github.com/apache/james-project/pull/2549
Will test frontend on staging
