### ISSUE TITLE
[Postgres] Mailbox ACL concurrency issue

### ISSUE THREAD

**Issue by hungphan227** [linagora/james-project#5350]
Currently, to handle mailbox ACL update request, James (Postgres version) fetch acl from db, update it and save it back to db. However, Mailbox ACL could be updated by multiple sources at the same time and it causes concurrency issue.

For instance, initially Bob has an empty mailbox acl for mailbox A. When James receive request X (replace acl by new one: "ilprstw"), it fetch empty acl from db, replace it by new one then save back to db. At the same time, James receive request Y (add "p" to current acl), it fetch empty acl from db, add p then save back to db. The final result would be the acl with only "p", not the expected "ilprstw".

**Comment by vttranlina** [comment]
No any description?

**Comment by hungphan227** [comment]
Currently my solution is event sourcing (used by cassandra mailboxacl)

https://github.com/apache/james-project/pull/2535

**Comment by chibenwa** [comment]
Not fan at all

How about optimistic transactions (update if) with a version number to increment?

**Comment by hungphan227** [comment]
> Not fan at all
> 
> How about optimistic transactions (update if) with a version number to increment?

Great idea. However, our postgres code does not support transaction. I think the best way to write transaction is using sql procedure/function

**Comment by chibenwa** [comment]
We do not have `UPDATE ... IF ... ;` ?

**Comment by hungphan227** [comment]
How did I find out this issue? --> run mailboxGetShouldListBaseMailbox in PostgresTeamMailboxesTest repeatedly until fail

**Comment by hungphan227** [comment]
> We do not have `UPDATE ... IF ... ;` ?

Actually we can use UPDATE ... WHERE ... instead. To summarize the solution:

- create column MAILBOX_ACL_VERSION in MAILBOX table
- when updating MAILBOX_ACL, do the following:
          + fetch MAILBOX_ACL and MAILBOX_ACL_VERSION from db
          + update mailbox acl object in James
          + save new mailbox acl to db by running sql command:
          update MAILBOX set MAILBOX_ACL = ? and MAILBOX_ACL_VERSION = MAILBOX_ACL_VERSION +1 where MAILBOX_ID = ? and MAILBOX_ACL_VERSION = ?
          + based on the afftected row count returned, we would know that the sql command succeed or fail.

Nice. Tks.

**Comment by chibenwa** [comment]
+1 `UPDATE ... WHERE ... RETURNING ...`

**Comment by hungphan227** [comment]
new PR https://github.com/apache/james-project/pull/2551
