### ISSUE TITLE
JAMES-3763 Generics for BlobIdProvider

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5356]
Following JAMES-3763 the deduplicating blob store buffered everything on files, on the bounded elastic scheduler.

EVEN WHEN WORKING WITH `byte[]`.

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/2540

**Comment by chibenwa** [comment]
Reopened to run tests with provisionning

Cc @vttranlina

**Comment by vttranlina** [comment]
Provisionning result https://github.com/apache/james-project/pull/2544#issuecomment-2516133675

**Comment by chibenwa** [comment]
> Provisionning result https://github.com/apache/james-project/pull/2544#issuecomment-2516133675

It's partial right?

We would need `before` `after` and `after with threading enhancement`...

Also include stat for IMAP APPEND command as a all if you can...

**Comment by vttranlina** [comment]
Result added: https://github.com/apache/james-project/pull/2544#issuecomment-2516133675
