### ISSUE TITLE
Rogue log org.apache.james.jmap.mail.Rights

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5358]
???

Investigate why https://github.com/apache/james-project/pull/2509 do not work...

**Comment by Arsnael** [comment]
@chibenwa Are you talking about tmail.linagora.com or an other enviornment?

After having a look with @hungphan227 , the image for example on tmail.linagora.com deployed is `linagora/tmail-backend:distributed-1.0.0-rc2`

And after verification, this image does not have included yet the work merged in https://github.com/apache/james-project/pull/2509

Here I can see two options if you want this on tmail.linagora.com:
- we can deploy `linagora/tmail-backend:distributed-1.0.1-rc1` tagged by @vttranlina a few days ago with the motto "eat your own dog food"
- we can play it more safe and rebuild an image based on `linagora/tmail-backend:distributed-1.0.0-rc2` with extra commit from https://github.com/apache/james-project/pull/2509

If it's related to an other environment, please specify which.

**Comment by chibenwa** [comment]
> @chibenwa Are you talking about tmail.linagora.com or an other enviornment?

MU

**Comment by chibenwa** [comment]
Maybe simply not-yet updated image...

**Comment by chibenwa** [comment]
Indeed old image
