### ISSUE TITLE
[PERF] Email move should send only one JMAP push notification

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5365]
Key idea: on the EventBus, I shall be able to publish a list of events.

This will be serialized and transported by rabbit as a list of event. (We can have a configuration parameter to turn on/off this parameter to ease rolling migration). Deserialization will need to handle both list and single events.

It will be executed as a list of events by listeners, with a default implementation to handle the current single event (without breaking change)

MailboxChangeListener will handle the email move in a single pass: process both `Added` and `Expunged` in a single pass and return a single `StateChange`.

See https://github.com/linagora/tmail-flutter/issues/3331

**Comment by quantranhong1999** [comment]
https://github.com/apache/james-project/pull/2567
