### ISSUE TITLE
[MU] S3: configure connectionAcquisitionTimeout

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/james-project#5368]
## Why
During high load to the S3, acquiring the connection from the S3 connection pool could be timeout.

![Image](https://github.com/user-attachments/assets/1a8c0668-aa41-4c3d-8c53-c19cc5f9e471)

Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.

## How

Make acquire timeout configurable?
![Image](https://github.com/user-attachments/assets/c6cd1805-fcfc-4e29-b168-ee8dbccdde39)

**Comment by quantranhong1999** [comment]
(increase `objectstorage.s3.http.concurrency` solves the issue too - added to MU)

**Comment by chibenwa** [comment]
Yes it is deployed
