### ISSUE TITLE
s/onMatcherException/onMatchException/g

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5370]
Exception handling was not applied

 - [X] Fix James CF https://github.com/apache/james-project/pull/2563
 - Twake mail not affected
 - [X] Fix MU
 - [X] CNB prod https://ci.linagora.com/linagora/lrs/saas/deployments/cnb/cnb-prd-apps/-/merge_requests/136
 - [x] CNB preprod AGC (archived, no fight for it)
 - [X] CNBpreprod OVH https://ci.linagora.com/linagora/lrs/saas/deployments/cnb/cnb-stg-ovh-apps/-/merge_requests/19
 - [x] linagora.com
 - [x] TWP preprod
 - [x] TWP prod

**Comment by Arsnael** [comment]
tmail-backend helm chart => https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-backend/-/merge_requests/121

**Comment by chibenwa** [comment]
Also need on twp preprod no?

**Comment by Arsnael** [comment]
Yes yes went to lunch break in the middle of it sorry :)

TWP dev: https://ci.linagora.com/linagora/lrs/saas/deployments/twake/twake-workplace-apps/-/merge_requests/247
TWP staging: https://ci.linagora.com/linagora/lrs/saas/deployments/twake/twake-workplace-apps/-/merge_requests/248

**Comment by Arsnael** [comment]
Merged and delpoyed for dev and staging

**Comment by Arsnael** [comment]
PR on james not merged yet?
