### ISSUE TITLE
Wrong part selected as the message body in JMAP, ok in IMAP

### ISSUE THREAD

**Issue by ddolcimascolo** [linagora/james-project#544]
Hello team,

The attached email displays its attachment (a plain text file) as the email body and preview instead of the actual body. Looks good in IMAP.
Also the attachment does not appear, probably because the part is detected as the body.

Thanks,
David

[Re: [Internet] Re: [Internet] Rendez-vous Linagora <> GN.eml.txt](https://github.com/linagora/james-project/files/682518/Re.Internet.Re.Internet.Rendez-vous.Linagora.GN.eml.txt)

Second email, not exactly the same behavior but probably linked (twice the same inline image in the body, no HTML body at all in Inbox):

[Inline twice.eml.txt](https://github.com/linagora/james-project/files/682803/Inline.twice.eml.txt)

**Comment by rouazana** [comment]
That's the result of our best effort policy to find text part when not always available.
We can try to fix the issue for this particular mail (great that we have non regression tests), but we should try do find a more suitable solution, maybe by reading for source code of TBider for example as suggested by matthieu. Even if TBird is known to be not really rfc-compliant on this...

**Comment by rouazana** [comment]
fixed, see #594
