### ISSUE TITLE
Cannot move a Folder with sub-folder to another folder

### ISSUE THREAD

**Issue by StephaneColson** [linagora/james-project#557]
* Create a folder "A"
* Create a sub-folder of "A" named "B" (then you have "A/B" in the treeview)
* Have another folder "C"
* Try to move "A" folder to "C" folder
* ```Modification of folder Sub failed```  in the toaster message
* Error in console
```
angular.js:11706 Error: Failed to update mailbox 89ee0530-d7ec-11e6-bcda-2d74340cbaa3, the reason is: [object Object]
    at jmap-client.min.js:1
    at angular.js:13318
    at n.$eval (angular.js:14570)
    at n.$digest (angular.js:14386)
    at n.$apply (angular.js:14675)
    at l (angular.js:9725)
    at F (angular.js:9915)
    at XMLHttpRequest.C.onload (angular.js:9856)
angular.js:11706 Error: Failed to update mailbox 89ee0530-d7ec-11e6-bcda-2d74340cbaa3, the reason is: [object Object]
    at jmap-client.min.js:1
    at angular.js:13318
    at n.$eval (angular.js:14570)
    at n.$digest (angular.js:14386)
    at n.$apply (angular.js:14675)
    at l (angular.js:9725)
    at F (angular.js:9915)
    at XMLHttpRequest.C.onload (angular.js:9856)
```
* `[["mailboxesSet",{"created":{},"updated":[],"destroyed":[],"notCreated":{},"notUpdated":{"3b64f310-d800-11e6-a8c3-2d74340cbaa3":{"type":"invalidArguments","description":"Cannot update a parent mailbox.","properties":null}},"notDestroyed":{}},"#0"]]`
* No errors in James logs
* The folder is not moved {color:red}NOK{color}

**Comment by chibenwa** [comment]
As off JMAP RFC-8621 implementation, we improved the loop detection mechanism and no longer reject renames to mailboxes having childs.
