### ISSUE TITLE
Filter "With attachments" not working with OpenPaaS Inbox

### ISSUE THREAD

**Issue by StephaneColson** [linagora/james-project#564]
Apparently, the feature to filter emails with attachments only is not yet implemented.
See https://ci.open-paas.org/jira/browse/INBOX-301

**Comment by ddolcimascolo** [comment]
When implementing this ticket, please make sure that:
* `hasAtachment: true` as a filter also filters mails with only inline attachments
* In `getMessages` calls, messages are given `hasAttachment: true` only if they have at least one non-inline attachment. This one's currently not true.

Thanks :)

**Comment by rouazana** [comment]
also done
