### ISSUE TITLE
Mailer-Deamon messages should not be indexed

### ISSUE THREAD

**Issue by ddolcimascolo** [linagora/james-project#569]
See https://ci.open-paas.org/jira/browse/INBOX-389?focusedCommentId=22546&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22546 for details

**Comment by chibenwa** [comment]
404

**Comment by ddolcimascolo** [comment]
4 years 🤩

What's up Benoît?

**Comment by chibenwa** [comment]
> What's up Benoît?

-> https://meet.jit.si/beerroom if you want <3
