### ISSUE TITLE
Bogus "everything empty" email

### ISSUE THREAD

**Issue by MichaelBailly** [linagora/james-project#586]
Since we started getting emails in OP, I often see bogus emails. You can detect those ones bc they seem to come from 
```
Accueil Exterieur Paris<@>
```

which is obviously wrong, and is presented so because, I guess "Accueil" is the first name in alphabetical order. Here is the content of the JMAP response, if of any interest:

![bogus2](https://cloud.githubusercontent.com/assets/1465817/22252603/0e4d167e-e24f-11e6-93f1-6ed75a2086ac.png)

**Comment by rouazana** [comment]
I think it is a Inbox bug, misintrepreting the from: null we send it.

**Comment by MichaelBailly** [comment]
It's definitely a James (or postfix -> James) bug if I receive an email without from, to, cc, bcc...
The Accueil Exterieur Paris thing is a way I give you to catch those bogus emails with your eyes when using Inbox.

Please note that in the historical system (Postfix/Cyrus/Thunderbird I don't have any "full empty" mail.

**Comment by rouazana** [comment]
ok, so please attach the .eml

**Comment by rouazana** [comment]
(:heart: the Accueil Exterieur Paris feature)

**Comment by MichaelBailly** [comment]
What .eml ?

**Comment by rouazana** [comment]
The original mail which has a From but which seems to not be parsed correctly

**Comment by MichaelBailly** [comment]
Where do I find it ? As stated in the bug report, it's not in the historical system.

**Comment by rouazana** [comment]
I mean the original bogus mail.

**Comment by MichaelBailly** [comment]
How do I find the original bogus mail ?

**Comment by MichaelBailly** [comment]
ok, I plugged in IMAP. Here is a bogus message.
[message.eml.txt](https://github.com/linagora/james-project/files/727114/message.eml.txt)

**Comment by rouazana** [comment]
thank you. so this mail has no from, what do you expect from us?

**Comment by MichaelBailly** [comment]
I expect you to understand why we have bogus messages in op.linagora, that we don't have in extranet.linagora.

**Comment by rouazana** [comment]
Fixed by #598
