### ISSUE TITLE
The SPFHandler provided in conf/smtpserver.xml fails initialization

### ISSUE THREAD

**Issue by pleira** [linagora/james-project#605]
Uncommenting the SPFHandler element provided in conf/smtpserver.xml fails in beta5 (and in the current snapshot):
```
Caused by: org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'org.apache.james.smtpserver.fastfail.SPFHandler': 
Injection of autowired dependencies failed; 
nested exception is org.springframework.beans.factory.BeanCreationException: 
Could not autowire method: public void 
org.apache.james.smtpserver.fastfail.SPFHandler.setDNSService(org.apache.james.jspf.core.DNSService); 
nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: 
No qualifying bean of type [org.apache.james.jspf.core.DNSService] found for dependency: 
expected at least 1 bean which qualifies as autowire candidate for this dependency.
```

When I introduced some jars needed for SPF, dnsjava-2.1.1.jar and dnsjnio-1.0.3.jar, still did not work.
The @Inject setDNSService method in SPFHandler requires a DNSService implementation, but injection of DNSServiceXBillImpl does not succeed.

**Comment by chibenwa** [comment]
Good catch. We need to add a binding for this, in scope Singleton.

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project/pull/606 should solve the issue. Thanks for report.
