### ISSUE TITLE
Set the Content-Length header in the attachment download endpoint

### ISSUE THREAD

**Issue by MichaelBailly** [linagora/james-project#628]
I noticed that the usser-agent doesn't display the progression % when downloading a mail attachment.

I *suspect* that this is bc the server download endpoint does not set the Content-Length header... I didn't check it.

Can you check if you set this header, and set it if it's missing ?

For the record: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13

**Comment by rouazana** [comment]
done see #634
