### ISSUE TITLE
This mail don't get preview....

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#732]
Is it because of base64 encoding?

[vietnam>757.txt](https://github.com/linagora/james-project/files/892047/vietnam.757.txt)

![screenshot from 2017-04-04 11-28-07](https://cloud.githubusercontent.com/assets/6928740/24641466/47e5c57c-192a-11e7-9331-a285da71b4b4.png)

**Comment by chibenwa** [comment]
Other example: 

[vietnam>751.txt](https://github.com/linagora/james-project/files/892056/vietnam.751.txt)

In both case I suspect HMTL parsing to fail.

**Comment by quynhn** [comment]
I tried 2 integration tests with both of those example files and preview string are still OK

**Comment by chibenwa** [comment]
I guess I already merged changes then ;-)

**Comment by quynhn** [comment]
It had issue with TikaTextExtrator when it does not remove white spaces but Jsoup did it.
This one will be fixed automatically when we do this one [https://issues.apache.org/jira/browse/JAMES-2018](url)
But now, I would like to reopen this one
