### ISSUE TITLE
[Hacktoberfest] Implement a HasMimeType matcher

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#992]
Hello dear HocktoberFester, and thanks for considering helping us!

The goal of this issue is to contribute to https://github.com/apache/james-project (yes, an **Apache project!**) but for technical reasons, we could not open tickets on that repository...

You can gather a bit more information on what is James and why it's an awesome project [on our website](http://james.apache.org/).

-------------------------------------------------------

**Here are the more specific task details:**

Link to JIRA: https://issues.apache.org/jira/browse/JAMES-2157

We would like to be able to write delivery logic based on the Mime Content-Type of a message.

Thus, you should create in *mailet-standard* a *HasMimeType* matcher that extends *GenericMatcher*.

You will add the corresponding tests *HasMimeTypeTest*. You can rely on the MimeMessageBuilder helper class to generate test data.

Don't hesitate to ask for help on the Gitter chat : https://gitter.im/apache/james-project

------------------------------------------------------------------------

![giphy](https://user-images.githubusercontent.com/6928740/30963301-2cd87a62-a477-11e7-8dca-dcd3dc43b681.gif)

**Comment by cunhazera** [comment]
@chibenwa what exactly must be compared?

**Comment by chibenwa** [comment]
Hi @cunhazera 

Every Mime message, as defined by https://tools.ietf.org/html/rfc2045#section-5 has a Content-Type header indicating, well, the content type of the message (or the message part).

If I look at the raw email in my inbox (using IE thunderbird) I have something like this:

```
Return-Path: <server-dev-return-64125-btellier=linagora.com@james.apache.org>
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
From: matthieu@apache.org
To: server-dev@james.apache.org
Date: Thu, 28 Sep 2017 07:58:33 -0000
Message-Id: <bb7aed0067e84458909161bc88ab164a@git.apache.org>
Subject: [9/9] james-project git commit: Merge remote-tracking branch

Merge remote-tracking branch 'linagora/pr/986'


Project: http://git-wip-us.apache.org/repos/asf/james-project/repo
Commit: http://git-wip-us.apache.org/repos/asf/james-project/commit/8c460636
Tree: http://git-wip-us.apache.org/repos/asf/james-project/tree/8c460636
Diff: http://git-wip-us.apache.org/repos/asf/james-project/diff/8c460636

----------------------------------------------------------------------
 mailbox/cassandra/pom.xml                       |   1 -
 mailbox/elasticsearch/pom.xml                   |   1 -
 mailbox/store/pom.xml                           |   1 -
 .../transport/mailets/StripAttachmentTest.java  |  33 ++--
 .../src/test/resources/logback-test.xml         |  15 ++
 server/protocols/jmap/pom.xml                   |   1 -
 .../apache/james/utils/SMTPMessageSender.java   |  11 +-
 24 files changed, 905 insertions(+), 218 deletions(-)
----------------------------------------------------------------------
---------------------------------------------------------------------
To unsubscribe, e-mail: server-dev-unsubscribe@james.apache.org
For additional commands, e-mail: server-dev-help@james.apache.org
```

You will notice the:

```
Content-Type: text/plain; charset="us-ascii"
```

I would like to have a matcher that allow me selecting emails in James that match a given content type.

Something like:

```
<mailet matcher="HasContentType=text/plain" class="...">
   ...
</mailet>
```

For matching text/plain emails.

(Note that this can be achieved through javax.mail API or Apache James MIME4J API.)

Does thi answers your question?

**Comment by cunhazera** [comment]
Ok.

How can I build and run the project locally?

**Comment by chibenwa** [comment]
Hi.

If I remember well, the README contains what is needed.

Build: **mvn clean install** (possibly with skipTests)
Run: We have docker containers.

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/73 by @vVv-AA solves this.

**Comment by chibenwa** [comment]
Issue merged
