### ISSUE TITLE
[Hacktoberfest] Administer Sieve quotas via CLI

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#994]
Hello dear HocktoberFester, and thanks for considering helping us!

The goal of this issue is to contribute to https://github.com/apache/james-project (yes, an **Apache project!**) but for technical reasons, we could not open tickets on that repository...

You can gather a bit more information on what is James and why it's an awesome project [on our website](http://james.apache.org/).

-------------------------------------------------------

**Here are the more specific task details:**

Link to JIRA: https://issues.apache.org/jira/browse/JAMES-2151

James allows users to store Sieve scripts. As defined in ManageSieve RFC such storage should be limited by quotas. Hence, James allow administration of such quotas via the Command Line Client. But miss this administration aspect through *webadmin*.

In *webadmin-data* project, crete a *SieveQuota* route class directly calling *SieveRepository* to create, read and delete such quotas. Globally, and per user. You will write relevant unit tests.

You can have a look to the existing *GlobalQuotaRoutes* and related tests in *GlobalQuotaRoutesTest*.

Here is the proposed API:

```
GET /sieve/quota
150000
(Expressed in bytes)

PUT /sieve/quota
160000

DELETE /sieve/quota


GET /sieve/quota/:user
150000
(Expressed in bytes)

PUT /sieve/quota/:user
160000

DELETE /sieve/quota/:user
```
Don't hesitate to ask for help on the Gitter chat : https://gitter.im/apache/james-project

------------------------------------------------------------------------

![giphy](https://user-images.githubusercontent.com/6928740/30963301-2cd87a62-a477-11e7-8dca-dcd3dc43b681.gif)

**Comment by sebast26** [comment]
I would like to start working on that. All I need for now is clear instructions on how to compile/test this project.

**Comment by sebast26** [comment]
Ok. Thanks to @aduprat I am now able to start working on that.

**Comment by chibenwa** [comment]
This issue had been solved.
