### ISSUE TITLE
[Hacktoberfest] JPA-SMTP guice project needs a docker file

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#995]
Hello dear HocktoberFester, and thanks for considering helping us!

The goal of this issue is to contribute to https://github.com/apache/james-project (yes, an **Apache project!**) but for technical reasons, we could not open tickets on that repository...

You can gather a bit more information on what is James and why it's an awesome project [on our website](http://james.apache.org/).

-------------------------------------------------------

**Here are the more specific task details:**

JIRA issue: https://issues.apache.org/jira/browse/JAMES-2153

James supports two packaging (IOC framework): *guice* and *spring*. Guice allows defining specific products shipping only some components of the James server. As part of this solution, we implemented a simple SMTP (only) server using JPA in the *jpa-smtp* project.

However, this project currently misses a DockerFile.

You will create such a DockerFile in /dockerfiles/run/guice/jpa-smtp along with a relevant default configuration. You can, of course, get a look to surrounding guice dockerfiles.

Don't hesitate to ask for help on the Gitter chat : https://gitter.im/apache/james-project

------------------------------------------------------------------------

![giphy](https://user-images.githubusercontent.com/6928740/30963301-2cd87a62-a477-11e7-8dca-dcd3dc43b681.gif)

**Comment by logandonley** [comment]
@chibenwa I can pickup this issue.

**Comment by chibenwa** [comment]
Cool @logandonley  , might you need any help, don't hesitate. And welcome aboard!

**Comment by chibenwa** [comment]
Solved in https://github.com/linagora/james-project/pull/1826

Thanks to @matzepan !!
