### ISSUE TITLE
[Hacktoberfest] Implement a JPA Sieve Repository

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#996]
Hello dear HocktoberFester, and thanks for considering helping us!

The goal of this issue is to contribute to https://github.com/apache/james-project (yes, an **Apache project!**) but for technical reasons, we could not open tickets on that repository...

You can gather a bit more information on what is James and why it's an awesome project [on our website](http://james.apache.org/).

-------------------------------------------------------

**Here are the more specific task details:**

JIRA issue: https://issues.apache.org/jira/browse/JAMES-2155

James exposes the *SieveRepository* interface for storing Sieve scripts. 

Nowadays, Sieve scripts can only be stored on top of Files and Cassandra. Storing Sieve scripts on top of *JPA* would unlock this feature above a database.

I order to do so:

 - Write a *JPASieveRepository* in *data-jpa* project. (in the sieve package.) You can look at other classes to get hints. Like JPAUsersRepository or JPADomainList.
 - To write a *JPASieveRepositoryTest* class and check your work simply extend the *AbstractSieveRepositoryTest* class. 

Don't hesitate to ask for help on the Gitter chat : https://gitter.im/apache/james-project

------------------------------------------------------------------------

![giphy](https://user-images.githubusercontent.com/6928740/30963301-2cd87a62-a477-11e7-8dca-dcd3dc43b681.gif)

**Comment by suryaprakashraja** [comment]
Hi @chibenwa, If this is not yet taken I would like to start working on this enhancement.

**Comment by aduprat** [comment]
Hi @suryaprakashraja ,

Yes, it's available, feel free to ask questions on our gitter:
https://gitter.im/apache/james-project

**Comment by nstdio** [comment]
Hi guys,

It seems @suryaprakashraja is not active, I can handle this.

**Comment by sebast26** [comment]
@chibenwa Hi @nstdio I started to work on that. Please check Gitter. Could you please take some other task?

**Comment by nstdio** [comment]
@sebast26 Yes, sure. Thanks for information.

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project/pull/1719 solved the issue.

Many thanks to @sebast26 and all other people working on this issue
