### ISSUE TITLE
[Hacktoberfest] JPA should support MOVE

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#997]
Hello dear HocktoberFester, and thanks for considering helping us!

The goal of this issue is to contribute to https://github.com/apache/james-project (yes, an **Apache project!**) but for technical reasons, we could not open tickets on that repository...

You can gather a bit more information on what is James and why it's an awesome project [on our website](http://james.apache.org/).

-------------------------------------------------------

**Here are the more specific task details:**

Jira issue: https://issues.apache.org/jira/browse/JAMES-2154

Nowadays JPA mailbox do not support using move command. It throws a Unsupported operation in JPAMessageMapper move method.

Your goal is to implement this method and allow a direct move of the email.

Then, to enable testing your code, you can add the MOVE capability to the JPAMapperProvider supported Capabilities.

Don't hesitate to ask for help on the Gitter chat : https://gitter.im/apache/james-project

------------------------------------------------------------------------

![giphy](https://user-images.githubusercontent.com/6928740/30963301-2cd87a62-a477-11e7-8dca-dcd3dc43b681.gif)

**Comment by sebast26** [comment]
Hi @chibenwa, if this task is still open I would like to take it.

**Comment by chibenwa** [comment]
Yes, sure, feel free ;-)

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project/pull/1850 solved this

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project/pull/1859 enabled related MPT tests
