### ISSUE TITLE
[Hactoberfest] Reindex API through WebAdmin

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#998]
Hello dear HocktoberFester, and thanks for considering helping us!

The goal of this issue is to contribute to https://github.com/apache/james-project (yes, an **Apache project!**) but for technical reasons, we could not open tickets on that repository...

You can gather a bit more information on what is James and why it's an awesome project [on our website](http://james.apache.org/).

-------------------------------------------------------

**Here are the more specific task details:**

Jira issue: https://issues.apache.org/jira/browse/JAMES-2152

James allows to index and search for specific emails in a *MessageSearchIndex*. However some implementations stores data in a separated data store (eg Lucene or ElasticSearch), which brings data consistencies issues. The way to solve these issues is to re-index data from the *mailbox*.

Such process is currently triggered from the *Command Line Client*, but is not available yet using *webadmin. The goal of this task is to enable it.

To do so, in *webadmin-mailbox* create a *ReindexRoutes* class. You will implement the following proposed endpoints using the *Reindexer*:

```
PUT /reindex
PUT /reindex/:namespace/:user/:mailboxName
```

You will, through a simple locking strategy, ensure that James is not performing two re-indexation at the same time.

You will implement tests for your routes in *ReindexRoutesTest*. You can get a look at surrounding tests.

Don't hesitate to ask for help on the Gitter chat : https://gitter.im/apache/james-project

------------------------------------------------------------------------

![giphy](https://user-images.githubusercontent.com/6928740/30963301-2cd87a62-a477-11e7-8dca-dcd3dc43b681.gif)

**Comment by arunavdev89** [comment]
I will look into it.

**Comment by chibenwa** [comment]
@arunavdev89  Sure, feel free.

You need maven to build the project. The project is easy to import in IntelliJ, and my coworkers are running eclipse.

**Comment by jreijn** [comment]
If this issue is still open I would love to take a look at it.

**Comment by chibenwa** [comment]
Hi @jreijn ! First thanks for will to contribute to the James project!

Sorry, we are currently working on it.

A set of pull requests are solving this exact problem:

https://github.com/linagora/james-project/pull/1799 did wrap reIndexing in a task

https://github.com/linagora/james-project/pull/1803 Removed no more needed event tracking

Because we reindex a list of UID for a given mailbox, if:

 -  A new message arrive it will be handled by the normal indexing process
 -  A concurrently deleted message will be filtered out as it can not be retrieved from storage
 -  And we will read the latest applied flag value

Note that global event tracking is still needed for mailbox path renames.

https://github.com/linagora/james-project/pull/1804 added API support for per-user and per-message reIndexing

All of these pull requests are already merged.

https://github.com/linagora/james-project/pull/1805 Adds the base WebAdmin APIs

https://github.com/linagora/james-project/pull/1808 Adds support for reIndexing using the messageId.

We started working on this topic @linagora due to a strong need in production.

I will be creating another ticket targetting webAdmin, that would be useful for us.

**Comment by chibenwa** [comment]
@jreijn you might be interested by this issue https://github.com/linagora/james-project/issues/1809

We are thinking about proposing additional Hacktoberfest tickets but this would need to be discussed a bit ibternally.

**Comment by chibenwa** [comment]
Solved in https://issues.apache.org/jira/browse/JAMES-2555 by #1805  and #1808
