### ISSUE TITLE
[Hacktober] JPA Attachment Mapper

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#999]
Hello dear HocktoberFester, and thanks for considering helping us!

The goal of this issue is to contribute to https://github.com/apache/james-project (yes, an **Apache project!**) but for technical reasons, we could not open tickets on that repository...

You can gather a bit more information on what is James and why it's an awesome project [on our website](http://james.apache.org/).

-------------------------------------------------------

Link to the issue: https://issues.apache.org/jira/browse/JAMES-2156

Attachments can be stored separately in the mailbox. This allows protocols and user defined interfaces to directly interact with attachments.

Nowadays, the JPA mailbox does not support such storage. Your goal is to add it. This is a first step to get JPA support for JMAP.

To do so :
 - Implement the *AttachmentMapper* interface in *mailbox-jpa* *mail* package.
 - You can easily check your implementation by writing a *JPAAttachmentMapperTest*. To do so, extend the *AttachmentMapperTest* and allow Attachment mapper creation in *JPAMapperProvider* (createAttachmentMapper method as well as add Attachment to supported capabilities).
 - You need to store attachment ids on JPA messages. Add the related properties in *AbstractJPAMailboxMessage*. Then implement *MessageWithAttachmentMapperTest* in *JPAMessageWithAttachmentMapperTest* to check your work. 
 - *JPAMailboxSessionMapperFactory* should then implement *AttachmentMapperFactory*
 - Add the Attachment Message capability as part of *JPAMailboxManager*

Don't hesitate to ask for help on the Gitter chat : https://gitter.im/apache/james-project

------------------------------------------------------------------------

![giphy](https://user-images.githubusercontent.com/6928740/30963301-2cd87a62-a477-11e7-8dca-dcd3dc43b681.gif)

**Comment by P3trur0** [comment]
@chibenwa may I take a look at this #999?

**Comment by chibenwa** [comment]
Yes please, feel free, @P3trur0

**Comment by P3trur0** [comment]
Thank you, I am working on this.

**Comment by P3trur0** [comment]
This should be solved by #1077. Please review it properly since I am not sure if my implementation suits your needs properly!
Thank you!

**Comment by sebast26** [comment]
@chibenwa what is the status of this issue? Do you plan to merge #1077 ? I would like to do some work on that issue, please tell me how we can proceed...

**Comment by chibenwa** [comment]
Hi @sebast26  

Thank you very much for your involvement on this issue.

This pull request currently has merge conflict with master. Could you rebase it, so that we can get some builds on it?
